### ISSUE TITLE
Routing from shop views

### ISSUE THREAD

**Issue by CyberiaResurrection** [aimeos/aimeos-laravel#10]
It's distinctly possible I've missed something, but why are the links **in the shop views themselves** seemingly hardcoded to (eg) /shop/list instead of the result of url('shop/list') - directly off the webserver root versus off the base url of the laravel install?

For example, from the rendered view source for shop/list,
`
        <section class="aimeos catalog-filter">
	<nav>
		<h1>Filter</h1>
		<form method="GET" action="/shop/list">
<section class="catalog-filter-search">`

This breaks on my install, which is not directly installed into the web server root, and 404s with "The requested URL /shop/list was not found on this server."

The following didn't work:
* php artisan aimeos:cache
* Setting a baseurl manually in config/app.php, then composer dump-autoload, then php artisan aimeos:cache
* Nuking website install dir from orbit, re-cloning from project repo, reinstalling laravel, reinstalling packages, re-doing aimeos install from scratch

**Comment by aimeos** [comment]
If I've understood you correctly, your document root is your application base directory instead of its ./public subdirectory, so your URLs are like ```http://localhost/myapp/public/index.php/shop/list```.

In this case, your problem isn't related to Aimeos because it uses the Laravel URL generator to create all URLs. Laravel expects the document root to be the ./public directory of your application by default due to security reasons (remember your .env file with your passwords is then publicly readable without further actions).

There seems to be a way to force Laravel to use another root directory:
http://stackoverflow.com/questions/25750604/laravel-artisan-gives-wrong-base-url
The question is related to the artisan CLI interface and Laravel 4.2 but the method is available in 5.x too and should also work in the HTTP environment.

**Comment by CyberiaResurrection** [comment]
Thanks heaps for your help so far despite how thick I've been.

I haven't set any vhosts or anything, as I'm still developing.
The base is `http://localhost/myapp/public` - all the urls hang off that.  

The only thing that is having problems is aimeos.  Everything else in my laravel project picks up its target route (eg `auth/register`) and bolts that onto the end of the base url (`http://localhost/myapp/public/auth/register`)

I would expect shop/list to be `http://localhost/myapp/public/shop/list` , which I can browse to without a problem.  It's just clicking Go from that view tries to go to `http://localhost/shop/list` , no matter what I set as the base url in config/app.php

**Comment by aimeos** [comment]
I would expect that too but I've found out that the Laravel URL generator behaves differently depending on what method you are using (```to()``` vs. ```route()```). I've created an issue for Laravel: https://github.com/laravel/framework/issues/9829

**Comment by aimeos** [comment]
To make things short: The answer of the Laravel maintainer was "placing applications in subdirectories is not supported" ...

**Comment by CyberiaResurrection** [comment]
Damn.  Thanks for chasing this up.

**Comment by CyberiaResurrection** [comment]
I'm not so sure it's a Laravel framework issue, now.

I stuck a `dd(route('aimeos_shop_list'))` call in my home controller's index method, and it returned `http://localhost/myapp/public/shop/list` as both you and I are expecting.

Doing a `dd($adminUrl)` call in Aimeos\Shop\Controller\AdminController.php immediately after line 61 gave `'"http://localhost/myapp/public/admin/shop/admin?site=%7Bsite%7D&lang=%7Blang%7D&tab=%7Btab%7D"'`

Third time (hopefully) being half a charm, I tried a dd($params) call in Aimeos\Shop\Controller\CatalogController.php just after line 60 (in listAction(), just after the app( 'Aimeos\Shop\Base\Page' )->getSections( 'catalog-list' ) and probably too much to just copy and paste here.

Highlights
aiheader['catalog/filter'] had a src of `/shop/count`
aiheader['catalog/list'] had a href of `/shop/list` - what I've tripped over previously.

That should be enough to establish the general pattern that, in that outpout from getSections, _every single_ target url was of form /(foo), hanging directly off webserver root.

**Comment by aimeos** [comment]
Yes, it seems to work if an absolute URL should be generated (the ```route()``` helper does this by default). In all relative URLs the sub-directories are still missing.

**Comment by CyberiaResurrection** [comment]
I'm not actually sure if the issue is in aimeos-laravel, or aimeos-core.  Unless I'm even more wrong than usual, aimeos-core is where the getBody() implementations that return the non-subdir-sensitive links all seem to reside.  

Would a Laravel-compatible test case expressing what I'm looking for be of any help?

**Comment by aimeos** [comment]
If the following returns a correct URL in your application, we should have a deeper look into it:
```dd(route('aimeos_shop_list', [], false))```

If the URL is wrong than Laravel has a bug creating relative URLs from routes.

FYI: All URLs generated in the Aimeos core are created by the Laravel view helper: https://github.com/aimeos/ai-laravel/blob/master/lib/custom/src/MW/View/Helper/Url/Laravel5.php

**Comment by CyberiaResurrection** [comment]
Put that dd call in my home controller's index method, and it came back with
`"/shop/list"`

Which is not a correct URL for my setup.  I'll have a look at the view helper.

**Comment by CyberiaResurrection** [comment]
When I changed
`return $this->_builder->route( $target, $params + $this->_fixed, $values['absoluteUri'] );`
to 
`return $this->_builder->route( $target, $params + $this->_fixed, true );` 
in line 56 of the view helper, the route not found problem that I've been having goes away.

**Comment by aimeos** [comment]
Yes, that's what I meant: Laravel builds absolute URLs correctly but generated relative URLs are wrong for your setup. The root problem is in this method: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/UrlGenerator.php#L289

**Comment by CyberiaResurrection** [comment]
Oh fun.  Hand-patching will get very old, very quick.

**Comment by aimeos** [comment]
The easiest way to get around this in your development environment is to use the integrated web server available since PHP 5.4. In your Laravel application directory type into a shell:
```php -S 127.0.0.1:8000 -t public```

Then, your Laravel application will be available at the URL ```http://127.0.0.1:8000/``` and you won't have problems with URLs while developing :-)

**Comment by CyberiaResurrection** [comment]
Thanks again for your help - this is simply smoething I'll have to work around

**Comment by aimeos** [comment]
You can try to fix it and open a pull request in the Laravel repository but it's not sure that it will be accepted.
