### ISSUE TITLE
Frontend page not loading

### ISSUE THREAD

**Issue by ramsaiphp** [aimeos/aimeos-laravel#101]
After setting up everything my frontend page is not loading
![image](https://cloud.githubusercontent.com/assets/5070829/22967530/d5fa8848-f38c-11e6-8460-0c74097a5ec3.png)
I followed all the steps in documentation, but now i am not able to see the frontend.

**Comment by aimeos** [comment]
The correct URL is `http://127.0.0.1:8000/index.php/list` not ".../lists"
