### ISSUE TITLE
Mongodb integration

### ISSUE THREAD

**Issue by solonik1** [aimeos/aimeos-laravel#102]
Is there the possibility to use mongodb? If no, is it planned to integrate?

**Comment by aimeos** [comment]
There's no plan to integrate MongoDB soon. As MongoDB is a document-oriented database it's different to the SQL databases supported by Aimeos and PDO. The best way would be to use it as high speed storage for the product index just like ElasticSearch.

If you want to help integrating MongoDB, it would speed up things dramatically :-)
