### ISSUE TITLE
Disable sub parts for specific pages

### ISSUE THREAD

**Issue by ujackson** [aimeos/aimeos-laravel#103]
How can I disable sub parts for specific pages. For example, I would like to only display the search input from the filter and disable categories and attributes on the homepage but enable them on the list page.
Alternatively, can I reuse individual sub parts from "aimeos_nav" without displaying everything on a page.

**Comment by aimeos** [comment]
The easiest way is to hide the subparts you don't need on the homepage with CSS. Besides the unused HTML sent with each page request, there's no downside going this way. Instead, the same `catalog/filter` cache entry can be retrieved for both pages.

If you want a leaner solution in terms of page weight than you have to setup your own page sections and insert the configuration you need in the action of your controller for the home page, e.g.:
```
$config = app( '\Aimeos\Shop\Base\Context' )->get()->getConfig();
$config->set( 'client/html/catalog/filter/standard/subparts', ['search'] );
$params = app( 'Aimeos\Shop\Base\Page' )->getSections( 'home' );
return View::make('hometmpl', $params);
```
in your `config/shop.php` you have to add the "home" section:
```
	'page' => array(
		// ...
		'home' => array( 'catalog/filter' ),
	),
```

**Comment by ujackson** [comment]
Thanks for your reply. I have tried the second option but it's not working.  How does 
$config->set( 'client/html/catalog/filter/standard/subparts', ['search'] ); work?
 Don't I need to pass it along with $params to the view or does it use sessions to update the configuration.

**Comment by aimeos** [comment]
`app( '\Aimeos\Shop\Base\Context' )->get()->getConfig()` returns the same shared object as used by the `app( 'Aimeos\Shop\Base\Page' )->getSections( 'home' );` method. So if you set a new configuration before calling the method, it's used while generating the component output. Here's the code:

app/Http/Controllers/HomeController.php:
```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $config = app( '\Aimeos\Shop\Base\Context' )->get()->getConfig();
        $config->set( 'client/html/catalog/filter/standard/subparts', ['search'] );
        $params = app( 'Aimeos\Shop\Base\Page' )->getSections( 'home' );

        return View::make('home', $params);
    }
}
```

config/shop.php:
```
	'page' => array(
		// ...
		'home' => array( 'catalog/filter' ),
	),
```

resources/view/home.blade.php:
```
@extends('layouts.app')

@section('content')
    <?= $aibody['catalog/filter'] ?>

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Dashboard</div>

                    <div class="panel-body">
                        You are logged in!
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
```

Then, after login you will see the search subpart of the catalog filter when opening `http://127.0.0.1:8000/home`

**Comment by ujackson** [comment]
It's working now... many thanks for your help.
