### ISSUE TITLE
Can not remove page components

### ISSUE THREAD

**Issue by peteracs** [aimeos/aimeos-laravel#104]
I am trying to deal with this section: https://aimeos.org/docs/Laravel/Adapt_pages#Remove_components

For example if I want to remove the 'catalog/session' component from the 'account-index' configuration, I would just simply remove it from the array in my shop.php configuration.

`'page' => array(
    'account-index' => array('account/history','account/favorite','account/watch','basket/mini'),
),`

However in your ShopServiceProvider class you use array_replace_recursive, so even though I removed the 'catalog/session' from the shop.php configuration, it's still there because of the recursive replacement with default.php and shop.php. Could you please take a look?

**Comment by aimeos** [comment]
Yes, that's a problem. This commit fixes it: 78bf9f0
Which version do you use?
