### ISSUE TITLE
Catalog list promotion subpart not displaying

### ISSUE THREAD

**Issue by ujackson** [aimeos/aimeos-laravel#105]
Hello,
I did the following in my controller:
  $config = app( '\Aimeos\Shop\Base\Context' )->get()->getConfig();
        $config->set( 'client/html/catalog/lists/standard/subparts', ['promo'] );
        $params = app( 'Aimeos\Shop\Base\Page' )->getSections( 'home' );

In my view: <?= $aibody['catalog/lists'] ?>

I added to config/shop.php and set client/html/catalog/list/promo/size = 3

I also added the products in admin and changed the ListType in Catalog from Standard to Promotion.

Is this the correct way to do it as it doesn't display the "Top seller" promotion products on my page.

**Comment by aimeos** [comment]
Does your `config/shop.php` contains `catalog/lists` for the `page/home` configuration?
The size parameter must be `client/html/catalog/lists/promo/size` (lists vs. list)

**Comment by ujackson** [comment]
Yes it does:
'home' => array( 'catalog/lists', 'basket/mini', 'catalog/filter' ),
The size parameter is also correct, It was a typo: client/html/catalog/lists/promo/size

**Comment by aimeos** [comment]
Does `$aibody['catalog/lists']` contains anything at all?

**Comment by ujackson** [comment]
Yes it displays all the products in lists. it's not displaying the added promotion products and size limit as intended.

**Comment by aimeos** [comment]
You probably forgot to set the default category ID:
https://aimeos.org/docs/Configuration/Core/client/html/catalog/lists/catid-default

Otherwise, the catalog/lists component displays the same results as for an empty text search. But still don't know why the "items" subpart is displayed.

**Comment by ujackson** [comment]
Ok, if I set this: client/html/catalog/lists/catid-default = 1 in config/shop.php, it only displays the products with category 1. How can I set that in my controller before passing it to view as I only want to display the promo products on the homepage and all products on the list page

**Comment by aimeos** [comment]
Like the subparts config: `$config->set( 'client/html/catalog/lists/catid-default', 1 );`

**Comment by ujackson** [comment]
I have already tried that. For some reason setting the config doesn't seem to work in the controller but it works fine in config/shop.php.

**Comment by aimeos** [comment]
This works pretty well in our tests:

HomeController:
```
        $config = app( '\Aimeos\Shop\Base\Context' )->get()->getConfig();
        $config->set( 'client/html/catalog/filter/standard/subparts', ['search'] );
        $config->set( 'client/html/catalog/lists/standard/subparts', ['promo'] );
        $config->set( 'client/html/catalog/lists/catid-default', 1 );
        $params = app( 'Aimeos\Shop\Base\Page' )->getSections( 'home' );

        return View::make('home', $params);
```

config/shop.php:
```
	'page' => array(
		'home' => array( 'catalog/filter', 'catalog/lists' ),
	),
```

home.blade.php:
```
    <?= $aibody['catalog/filter'] ?>
    <?= $aibody['catalog/lists'] ?>
```
