### ISSUE TITLE
artisan vendor:publish throws error "Call to undefined method Illuminate\Foundation\Application::share()"

### ISSUE THREAD

**Issue by InigoWD** [aimeos/aimeos-laravel#106]
Running latest Laravel. Here is my composer.json file:

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "prefer-stable": true,
    "minimum-stability": "dev",    
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "aimeos/aimeos-laravel": "~2016.10"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize",
            "php artisan vendor:publish --tag=public --force",
            "php artisan vendor:publish",
            "php artisan migrate"           
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
`

**Comment by aimeos** [comment]
You are using Laravel 5.4 and Aimeos 2016.10, but only Aimeos 2017.x support Laravel 5.4:
https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by InigoWD** [comment]
Sorry, re-read notes and now realise I need to run the Beta version, ~2017.01 for Laravel 5.4
