### ISSUE TITLE
SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size

### ISSUE THREAD

**Issue by InigoWD** [aimeos/aimeos-laravel#107]
I have followed the steps in the instructions, for Laravel 5.4, and the Beta 2017.01 version of Aimeos. When trying to run the command `php artisan aimeos:setup --option=setup/default/demo:1` I get the titular error.

I am running the standard Homestead Vagrant box.

**Comment by aimeos** [comment]
Please have a look at https://github.com/aimeos/aimeos-laravel/issues/99

**Comment by aimeos** [comment]
Also documented in the "Important notice" section:
https://github.com/aimeos/aimeos-laravel#important-notice
