### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zaisahil** [aimeos/aimeos-laravel#108]
Hello!

I have tried to  setup the aimeos-laravel on my localhost machine using Windows 10 x64 which Git installed with bash commands support. 

I get an error while I run update composer after cloing it from GitHub. 

**Error:**
> mkdir -p public/admin/extjs/lib/ext.ux/AdvancedSearch/resources public/admin/extjs/lib/ext.ux/Portal/resources
The syntax of the command is incorrect.
Script mkdir -p public/admin/extjs/lib/ext.ux/AdvancedSearch/resources public/admin/extjs/lib/ext.ux/Portal/resources handling the post-update-cmd event returned with error code 1

Here are the following steps I did for better clarity:

- git clone https://github.com/aimeos/aimeos-laravel.git

- composer update

I cant find clear understanding on how to install and setup the aimeos-laravel. 

Any help will be highly appreciated. Please note that I am just a beginner developer so step by step guidance will be highly appreciated. 

Thank you.

**Comment by aimeos** [comment]
You only need to clone the repository if you want to contribute to Aimeos.

If you want to install and use it, please set up your Laravel application and then follow the manual:
https://github.com/aimeos/aimeos-laravel#table-of-content
