### ISSUE TITLE
Demo Import Failed

### ISSUE THREAD

**Issue by gichia300** [aimeos/aimeos-laravel#109]
I get the following error when i try to import the demo 

Wayne@Wayne MINGW64 /c/MAMP/htdocs/silicon_bids
$ php artisan migrate
Migrated: 2015_03_06_000000_aimeos_users_table
Migrated: 2015_08_10_000000_aimeos_users_label

Wayne@Wayne MINGW64 /c/MAMP/htdocs/silicon_bids
$ php artisan aimeos:setup --option=setup/default/demo:1

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Aimeos\MW\Session\Laravel5::__construct() must be an instance of Illuminate\Session\SessionInterface, instance of Illuminate\Session\Store given, called i
  n C:\MAMP\htdocs\silicon_bids\vendor\aimeos\aimeos-laravel\src\Aimeos\Shop\Base\Context.php on line 212

**Comment by aimeos** [comment]
Seems like a version mismatch. Which Laravel/Aimeos version do you use?

Did you check if your Laravel and Aimeos version fit together?
https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by gichia300** [comment]
$ php artisan --version
Laravel Framework 5.4.15

**Comment by aimeos** [comment]
Did you then used "aimeos-laravel": "~2017.01" in your composer.json?

**Comment by gichia300** [comment]
I used the default 
"aimeos/aimeos-laravel": "~2016.10"

**Comment by aimeos** [comment]
Laravel 5.4 and Aimeos 2016.10 doesn't fit together. Use 2017.01 instead.
