### ISSUE TITLE
Number of binds (25) doesn't match the number of markers

### ISSUE THREAD

**Issue by ceceps** [aimeos/aimeos-laravel#11]
I working on Laravel 5.1, I had folow installation after composer update, and fil service provider as suggest then I type command like this in console as below:
php artisan  vendor:publish
php artisan migrate 
php artisan aimeos:setup --option=setup/default/demo:1

Got Errors like this
Number of binds (25) doesn't match the number of markers in "mshop/customer/manager/address/laravel/item//insert"

**Comment by ceceps** [comment]
My Mistake that error appeare when I install usgin aimeos/aimeos-laravel: dev-master, but when I am using aimeos/aimeos-laravel: 1.1.1 it look success, and don't forget dependencies packages to other aimeos

**Comment by aimeos** [comment]
Thanks for the hint! We've fixed the problem in dev-master and it works now as expected again.
