### ISSUE TITLE
Installation error with laravel 5.4

### ISSUE THREAD

**Issue by morganmsk** [aimeos/aimeos-laravel#110]
`user@dev:~/projects/sm.dev$ php artisan vendor:publish

PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::share() in /media/psf/projects/sm.dev/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/ShopServiceProvider.php on line 112
PHP Stack trace:
PHP   1. {main}() /media/psf/projects/sm.dev/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /media/psf/projects/sm.dev/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:115
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:270
PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:208
PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
PHP   7. Illuminate\Foundation\ProviderRepository->load() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:543
PHP   8. Illuminate\Foundation\Application->register() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:74
PHP   9. Aimeos\Shop\ShopServiceProvider->register() /media/psf/projects/sm.dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:568

                                                                       
  [Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share()  `

problem solution
https://laracasts.com/discuss/channels/laravel/undefined-method-illuminatefoundationapplicationshare-when-upgrading-to-laravel-54/replies/311403

**Comment by morganmsk** [comment]
here is my solution in vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/ShopServiceProvider.php
rewrite all share methods  to singleton

	```
$this->app->singleton('command.aimeos.account',function() {
			return new Command\AccountCommand();
		});

		$this->app->singleton('command.aimeos.cache',function() {
			return new Command\CacheCommand();
		});

		$this->app->singleton('command.aimeos.jobs',function() {
				return new Command\JobsCommand();
		});

		$this->app->singleton('command.aimeos.setup',function() {
			return new Command\SetupCommand();
		});
```

**Comment by aimeos** [comment]
Use `"aimeos/aimeos-laravel": "~2017.01"` instead. This version supports Laravel 5.4 out of the box

**Comment by prappo** [comment]
I got the same problem, I'm using sqlite. Any hint?

**Comment by aimeos** [comment]
Same as above: Only Aimeos 2017.x (currently ~2017.03) works with Laravel 5.4.
SQLite isn't one of the supported databases: https://aimeos.org/docs/Developers/Library/Database_support

**Comment by iamAliAsgharKhan** [comment]
@morganmsk  you solved my problem. Thanks.
