### ISSUE TITLE
Error when trying to create admin user

### ISSUE THREAD

**Issue by gichia300** [aimeos/aimeos-laravel#111]
$ php artisan aimeos:account --admin gichia300@gmail.com

 Password:
 >

  [Aimeos\MW\DB\Exception]
  Executing statement "
                        INSERT INTO "users" (

                                "name", "company", "vatid", "salutation", "title",

                                "firstname", "lastname", "address1", "address2", "address3",

                                "postal", "city", "state", "countryid", "langid", "telephone",

                                "telefax", "website", "email", "longitude", "latitude", "label",

                                "birthday", "status", "vdate", "password",

                                "updated_at", "editor", "created_at"

                        ) VALUES (

                                'gichia300@gmail.com','','','','','','','','','','','','',NULL,NULL,'','','','gichia300@gmail.com',NULL,NULL,'gichia300@gmail.com',NULL,1,NULL,'$2y$10$102GlgLff
PzP0tqt3Kn9cO4SzJpov/e9
  Hve5gOjzxMbV3QyC3mKQW','2017-03-15 01:25:30','aimeos:account','2017-03-15 01:25:30'
                        )

                " failed: An exception occurred while executing '

                        INSERT INTO "users" (

                                "name", "company", "vatid", "salutation", "title",

                                "firstname", "lastname", "address1", "address2", "address3",

                                "postal", "city", "state", "countryid", "langid", "telephone",

                                "telefax", "website", "email", "longitude", "latitude", "label",

                                "birthday", "status", "vdate", "password",

                                "updated_at", "editor", "created_at"

                        ) VALUES (

                                'gichia300@gmail.com','','','','','','','','','','','','',NULL,NULL,'','','','gichia300@gmail.com',NULL,NULL,'gichia300@gmail.com',NULL,1,NULL,'$2y$10$102GlgLff
PzP0tqt3Kn9cO4SzJpov/e9
  Hve5gOjzxMbV3QyC3mKQW','2017-03-15 01:25:30','aimeos:account','2017-03-15 01:25:30'
                        )

                ':

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'gichia300@gmail.com' for key 'users_email_unique'

**Comment by aimeos** [comment]
`Duplicate entry 'gichia300@gmail.com' for key 'users_email_unique'`

You tried to add your user twice

**Comment by gichia300** [comment]
Thanks that worked
