### ISSUE TITLE
Installed Aimeos to existing project but not sure what to do with existing register process

### ISSUE THREAD

**Issue by symfonycoda** [aimeos/aimeos-laravel#116]
Hi

Firstly, thanks for your awesome package, and the support when I have needed it in the past

I have recently added a ~2016.10 installation to a small user-based site that i had already built in Laravel 5.3. 
Everything seems successful, and comes up under /list and /admin ready to be used. 
However, the Aimeos installation has added more columns to the Users table, which means that when I try to add a user to my original site it fails:

SQLSTATE[HY000]: General error: 1364 Field 'salutation' doesn't have a default value

I understand why I am getting the error, but what would be the strategy in setting up the database to still be able to use that site that I built as well as the Aimeos shop alongside it?

Is there a way to allow each user to have their own shop? or can only the main user have access to the shop?

I read through a lot of the relevant sections of the docs and couldn't find the answers

Many thanks

@SymfonyCoda

**Comment by aimeos** [comment]
DBAL sets the default values for columns to `NULL` automatically but also uses `NOT NULL` as default. The solution would be to specify a default value for each column that matches its type:
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/schema-representation.html#portable-options

If you could create a PR for the Laravel and Symfony integration, we are happy to merge it into the core:
- https://github.com/aimeos/ai-laravel/blob/master/lib/custom/setup/default/schema/customer.php#L11
- https://github.com/aimeos/ai-fosuser/blob/master/lib/custom/setup/default/schema/customer.php#L11

**Comment by symfonycoda** [comment]
Thanks for the reply. I'm determined to give this a go, but haven't had any time the last few days. I'll get back to you if/when I get a solution

**Comment by aimeos** [comment]
We did this now so the changes are included in the 2017.04 release:
https://github.com/aimeos/ai-laravel/commit/0d5a25274e9b542acf7de549c24dfa7d238f3f4d

**Comment by symfonycoda** [comment]
You guys are awesome. thanks! 
I think there will be other users that appreciate that change too!
