### ISSUE TITLE
British Pounds

### ISSUE THREAD

**Issue by InigoWD** [aimeos/aimeos-laravel#117]
Nowhere to be found in the list of currencies. Am I missing something?

**Comment by aimeos** [comment]
The British Pound uses the currency code "GBP" and is available in the list of currencies:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/setup/default/data/currency.php#L57

It's not enabled by default in the admin interface. You can enable it in the expert mode -> Locale tab -> Currencies. Translation into the currency symbol is also available:
https://github.com/aimeos/ai-client-html/blob/master/client/i18n/currency/en.po#L433

**Comment by InigoWD** [comment]
Thanks, I see now.
