### ISSUE TITLE
Cannot Setup Aimeos with PostgreSQL

### ISSUE THREAD

**Issue by vickonovianto** [aimeos/aimeos-laravel#118]
I use Aimeos 2017.04 with PostgreSQL 9.6.2 and Laravel 5.4 with PHP 7.1.1. I use Windows 8 Pro. After I entered `php artisan vendor:publish` , I changed the file config/shop.php into : 
```
	'resource' => array(
		'db' => array(
			'adapter' => env('DB_CONNECTION', 'pgsql'),
			'host' => env('DB_HOST', 'localhost'),
			'port' => env('DB_PORT', '5432'),
			'socket' => '',
			'database' => env('DB_DATABASE', 'marketplace'),
			'username' => env('DB_USERNAME', 'postgres'),
			'password' => env('DB_PASSWORD', '***'),
			'stmt' => null,
		),
	),
	'mshop' => array(
		'index' => array(
	        'manager' => array(
	            'name' => 'PgSQL',
	            'attribute' => null,
	            'catalog' => null,
	            'price' => null,
	            'text' => array(
	                'name' => 'PgSQL',
	            ),
	        ),
	    ),
	),
```
And then I entered `php artisan aimeos:setup --option=setup/default/demo:1`, but en error occured, the error is : 
```
 [Aimeos\MW\DB\Exception]
Executing statement "SET SESSION sql_mode='ANSI'" failed: An exception occurred while executi ng 'SET SESSION sql_mode='ANSI'':
SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "sql_mode" 
```

Why is this occured? Thank you.

**Comment by aimeos** [comment]
The documentation wasn't up to date and there was a bug when creating an index in the `user_address` table. Please run `composer update` and change your configuration according to the update docs in https://aimeos.org/docs/Developers/Library/Database_support

**Comment by vickonovianto** [comment]
Thank you for the reply. Now I can connect aimeos with PostgreSQL. Thank you very much.
