### ISSUE TITLE
071 Specified key was too long; max key length is 767 bytes while importing demo

### ISSUE THREAD

**Issue by asimshazad** [aimeos/aimeos-laravel#119]
When i try to import demo data i got this error,but i have added this in AppServiceProvider
      Schema::defaultStringLength(191);

php artisan aimeos:setup --option=setup/default/demo:1
[Aimeos\MW\DB\Exception]
Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes.

I am sure there is no max length violation.Could you please look at this issue?

**Comment by asimshazad** [comment]
Fixed,there was max key issue

**Comment by evertramos** [comment]
How did you fix it?

**Comment by aimeos** [comment]
Please read the important notices: https://github.com/aimeos/aimeos-laravel#important-notice
