### ISSUE TITLE
A Guide on how to register delivery providers?

### ISSUE THREAD

**Issue by faustbrian** [aimeos/aimeos-laravel#120]
So I spent a few hours of reading the docs to know how to create delivery providers, themes and all that kinda stuff.

Now my issue is after reading https://aimeos.org/docs/Developers/Library/Service/Implement_delivery_provider is that how on earth am I supposed to register the delivery provider? I couldn't find any information on how to register it through a service provider or alike.

How would I register a new Delivery Provider that resides in `App\Services\Delivery\ProviderName`?

**Comment by aimeos** [comment]
Did you read https://aimeos.org/docs/User_Manual/Administration_Interface/Service_details?
