### ISSUE TITLE
Login, Register etc... Not showing on Shop Frontend.

### ISSUE THREAD

**Issue by ekundayo-ab** [aimeos/aimeos-laravel#121]
I've installed and done neccessary configurations for aimeos on Debian OS. 

After accessing frontend with **127.0.0.1:8000/list** it only shows Cart icon and default welcome page for laravel. 
![aimeos issue](https://cloud.githubusercontent.com/assets/20375577/25775969/aa9243b0-32a9-11e7-8069-0e8063b6bdf4.png)

**Comment by aimeos** [comment]
I see the catalog filter and list component too in your screen shot ...

**Comment by ekundayo-ab** [comment]
yes @aimeos but no Login, Register etc.

**Comment by aimeos** [comment]
You have to setup Laravel authentication: https://github.com/aimeos/aimeos-laravel#admin

**Comment by aimeos** [comment]
Is your problem solved?

**Comment by ekundayo-ab** [comment]
No. I had to forget about using aimeos thanks though.
