### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by NeonKraze** [aimeos/aimeos-laravel#122]
I for Some reason cannot get this installed correct. 
I am running Ubuntu 14.04 with nginx 1.4.6 (ubuntu) and have the latest Laravel Installation, 
When I run the basic Artisan Commands here is what I receive. 
` php artisan vendor:publish`
`Nothing to publish for tag []`
`php artisan migrate`
`Nothing to migrate`
'php artisan aimeos:setup --option=setup/default/demo:1'
'[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "aimeos" namespace.'

I am unsure on how to proceed and have tried from a default installation and have yet to accomplish this.  What would be the next steps to resolve this?

**Comment by aimeos** [comment]
You probably forgot to add the service provider:

> Next, the Aimeos provider class must be added to the providers array of the config/app.php file so the application and Laravel command task will work:

```
return array(
    'providers' => array(
        ...
        Aimeos\Shop\ShopServiceProvider::class,
    ),
);
```

**Comment by NeonKraze** [comment]
![appconfig](https://cloud.githubusercontent.com/assets/13115444/25977783/34c28818-367b-11e7-953b-38823b9458a2.png)
I have done this, here is a screen shot

**Comment by aimeos** [comment]
Can you try to put the Aimeos line at the end of the `provider` array?

**Comment by NeonKraze** [comment]
![appconfig1](https://cloud.githubusercontent.com/assets/13115444/25989940/2af78078-36bb-11e7-8f38-03e8443278ef.png)
![appconfig2](https://cloud.githubusercontent.com/assets/13115444/25989943/2c6075dc-36bb-11e7-99f6-b2ccbbe46815.png)
I placed it at the end of the `providers` array and have placed it at the end of the laravel framework service providers as well. bit confused as to why it is not registering it. 

Would it cause problems if I already used `php artisan make:auth`?

**Comment by aimeos** [comment]
No, that shouldn't be a problem. How does your composer.json look like?

**Comment by NeonKraze** [comment]
![composer](https://cloud.githubusercontent.com/assets/13115444/25991769/b9522a52-36c1-11e7-9e07-caf4902d6b9e.png)
![composer1](https://cloud.githubusercontent.com/assets/13115444/25991770/bada807c-36c1-11e7-86fe-657791b34754.png)
Here is my `composer.json`

**Comment by aimeos** [comment]
You are using Laravel 5.2 but Aimeos 2017.04 only supports Laravel 5.3 and 5.4 due to breaking changes in Laravel between 5.2 and 5.4. You can still use the Aimeos 2016.10 LTS version that works with Laravel 5.1/5.2/5.3: https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by NeonKraze** [comment]
Oh wow! I'm dumb! thanks for you help!
