### ISSUE TITLE
Laravel/Configure cronjobs

### ISSUE THREAD

**Issue by devikafr** [aimeos/aimeos-laravel#123]
Description:I am trying to setup task every hour.

I executed command : vagrant@vagrant-ubuntu-trusty-64:/var/www/html/shop$ 30 * * * * php /var/www/html/shop/artisan aimeos:jobs "customer/email/watch order/cleanup/unfinished order/service/async order/service/payment"

I got this result: 30: command not found

Please help. Thanks

**Comment by devikafr** [comment]
Thanks a lot. This is a new thing for me to learn (Unix crontab). Your guidance very much appriciated.

**Comment by aimeos** [comment]
You are welcome!
