### ISSUE TITLE
Site for code "default" not found

### ISSUE THREAD

**Issue by ashok-picinfotec** [aimeos/aimeos-laravel#124]
Whoops, looks like something went wrong.
1/1 Exception in Standard.php line 126: Site for code "default" not found 

Issues found, plz help me how to solve it.

Thanks

**Comment by aimeos** [comment]
When does this occur? Did you execute
```
php artisan aimeos:setup --option=setup/default/demo:1
```
like described in the docs?

**Comment by ashok-picinfotec** [comment]
Yes,
executed php artisan aimeos:setup --option=setup/default/demo:1 command

**Comment by aimeos** [comment]
Can you please post the complate error message?

**Comment by ashok-picinfotec** [comment]
Please find front end and backend error,

![backend](https://cloud.githubusercontent.com/assets/28763922/26277510/e96cdc80-3da8-11e7-96cc-6638c5a4df7a.png)
![frontend](https://cloud.githubusercontent.com/assets/28763922/26277511/e96f34e4-3da8-11e7-99c7-a14350be8b91.png)

**Comment by ashok-picinfotec** [comment]
also find my composer.json detail


{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "prefer-stable": true,
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "aimeos/aimeos-laravel": "~2017.04"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize",
            "php artisan vendor:publish --tag=public --force",
            "php artisan vendor:publish",
            "php artisan migrate"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by aimeos** [comment]
What's the status value in the mshop_locale_site and mshop_locale tables?

**Comment by ashok-picinfotec** [comment]
re-install :

when i run migration command the following error occured,



  [Aimeos\MW\DB\Exception]
  Executing statement "ALTER TABLE users ADD `label` VARCHAR(255) DEFAULT '' NOT NULL, ADD salutation VARCHAR(8) DEFAULT '' NOT NULL, ADD company VARCHAR(100) DEFAULT '' NOT NULL, ADD vatid
   VARCHAR(32) DEFAULT '' NOT NULL, ADD title VARCHAR(64) DEFAULT '' NOT NULL, ADD firstname VARCHAR(64) DEFAULT '' NOT NULL, ADD lastname VARCHAR(64) DEFAULT '' NOT NULL, ADD address1 VARC
  HAR(200) DEFAULT '' NOT NULL, ADD address2 VARCHAR(200) DEFAULT '' NOT NULL, ADD address3 VARCHAR(200) DEFAULT '' NOT NULL, ADD postal VARCHAR(16) DEFAULT '' NOT NULL, ADD city VARCHAR(20
  0) DEFAULT '' NOT NULL, ADD state VARCHAR(200) DEFAULT '' NOT NULL, ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT NULL, ADD telephone VARCHAR(32) DEFAULT '' NOT NULL,
  ADD telefax VARCHAR(32) DEFAULT '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude NUMERIC(8, 6) DEFAULT NULL, ADD latitude NUMERIC(8, 6) DEFAULT NULL, ADD birthday
  DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD status SMALLINT DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name
  name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at upd
  ated_at DATETIME NOT NULL" failed: An exception occurred while executing 'ALTER TABLE users ADD `label` VARCHAR(255) DEFAULT '' NOT NULL, ADD salutation VARCHAR(8) DEFAULT '' NOT NULL, AD
  D company VARCHAR(100) DEFAULT '' NOT NULL, ADD vatid VARCHAR(32) DEFAULT '' NOT NULL, ADD title VARCHAR(64) DEFAULT '' NOT NULL, ADD firstname VARCHAR(64) DEFAULT '' NOT NULL, ADD lastna
  me VARCHAR(64) DEFAULT '' NOT NULL, ADD address1 VARCHAR(200) DEFAULT '' NOT NULL, ADD address2 VARCHAR(200) DEFAULT '' NOT NULL, ADD address3 VARCHAR(200) DEFAULT '' NOT NULL, ADD postal
   VARCHAR(16) DEFAULT '' NOT NULL, ADD city VARCHAR(200) DEFAULT '' NOT NULL, ADD state VARCHAR(200) DEFAULT '' NOT NULL, ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT
  NULL, ADD telephone VARCHAR(32) DEFAULT '' NOT NULL, ADD telefax VARCHAR(32) DEFAULT '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude NUMERIC(8, 6) DEFAULT NULL, A
  DD latitude NUMERIC(8, 6) DEFAULT NULL, ADD birthday DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD status SMALLINT DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, C
  HANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE created_a
  t created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL':
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by aimeos** [comment]
Please read the important notices: https://github.com/aimeos/aimeos-laravel#important-notice
