### ISSUE TITLE
composer update failed

### ISSUE THREAD

**Issue by kanfur** [aimeos/aimeos-laravel#125]
$ composer update
Loading composer repositorUpdating dependencies (including require-dev)            Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package aimeos/aimeos-laravel No version set (parsed as 1.0.   0) is satisfiable by aimeos/aimeos-laravel[No version set (parsed as 1.0.0)] but    these conflict with your requirements or minimum-stability.
  Problem 2
    - aimeos/aimeos-laravel 2017.04.1 requires aimeos/aimeos-core ~2017.04 -> sa   tisfiable by aimeos/aimeos-core[2017.04.x-dev].
    - aimeos/aimeos-laravel 2017.04.2 requires aimeos/aimeos-core ~2017.04 -> sa   tisfiable by aimeos/aimeos-core[2017.04.x-dev].
    - aimeos/aimeos-laravel 2017.04.3 requires aimeos/aimeos-core ~2017.04 -> sa   tisfiable by aimeos/aimeos-core[2017.04.x-dev].
    - aimeos/aimeos-laravel 2017.04.x-dev requires aimeos/aimeos-core ~2017.04 -   > satisfiable by aimeos/aimeos-core[2017.04.x-dev].
    - Can only install one of: aimeos/aimeos-core[dev-master, 2017.04.x-dev].
    - Installation request for aimeos/aimeos-core dev-master -> satisfiable by a   imeos/aimeos-core[dev-master].
    - Installation request for aimeos/aimeos-laravel ~2017.04 -> satisfiable by    aimeos/aimeos-laravel[2017.04.1, 2017.04.2, 2017.04.3, 2017.04.x-dev].

What can i do to solve ?

**Comment by aimeos** [comment]
Can you please post your composer.json?

**Comment by Taufikur** [comment]
i have the same problem with @kanfur 
![image](https://cloud.githubusercontent.com/assets/29013107/26754509/6fff31fa-48a6-11e7-9057-03840ac9ee7a.png)


![image](https://cloud.githubusercontent.com/assets/29013107/26754525/a8c27dee-48a6-11e7-9e0d-1b4cf60c2020.png)

![image](https://cloud.githubusercontent.com/assets/29013107/26754529/b4ed6890-48a6-11e7-9fc9-af45e00084bb.png)

and this is my composer.json
[composerJSON.txt](https://github.com/aimeos/aimeos-laravel/files/1049655/composerJSON.txt)

What can i do to solve ?

**Comment by aimeos** [comment]
Your composer.json file is the Aimeos Laravel one and not your own one. You have to install a Laravel skeleton first (https://laravel.com/docs/5.4) and then add the lines from the documentation to THAT componser.json file.

**Comment by Taufikur** [comment]
@aimeos 
thanks,
i got error again when i execute "composer update" command

![image](https://cloud.githubusercontent.com/assets/29013107/26759810/a57913cc-4933-11e7-99dc-3cadbc0df640.png)

What can i do to solve ?

**Comment by aimeos** [comment]
The "laravel/tinker" package has been removed from your installation (line 1 "Removing ...") but it's service provider is still in `./config/app.php`

**Comment by Taufikur** [comment]
i have install "laravel/tinker" again using "composer require laravel/tinker" command, but still got the same error

**Comment by aimeos** [comment]
You have two require sections in your `composer.json` and there must be only one!
