### ISSUE TITLE
Database schema class "\Aimeos\MW\Setup\DBSchema\Sqlsrv" not found

### ISSUE THREAD

**Issue by oatache** [aimeos/aimeos-laravel#126]
Hi,
I facing an error messages on installation procedure. 
(following https://github.com/aimeos/aimeos-laravel#installation-or-update)

>php artisan aimeos:setup --option=setup/default/demo
Database schema class "\Aimeos\MW\Setup\DBSchema\Sqlsrv" not found

PHP 7.0
Laravel 5.2
DB: SQL Server 2012 
OS:Windows ,IIS8.5
Microsoft driver for PHP7.0 for SQL Server in IIS : installed via WebInstallerPlatform

I found that Laravel using **sqlsrv** as db adapter,
while aimeos using **sqlserv** .

I tried to change all of database.conf, shop.conf, .env to sqlsrv or sqlserv, still not working
please suggest

**Comment by aimeos** [comment]
It's "sqlsrv" for Aimeos too, this was an error in the documentation and the class was named wrong. Can you please use

`"aimeos/aimeos-laravel": "dev-master"`

in your `composer.json` file and run `composer update` before you execute the Aimeos setup command again?

**Comment by oatache** [comment]
Hi,
just need your confirmation.

Is this going to be a compatibility issue with "aimeos/aimeos-laravel": "dev-master" ?
Document recommended me to use "aimeos/aimeos-laravel": "~2016.10" since i'm using **laravel 5.2.**

**Comment by aimeos** [comment]
In this case, you have to use
```
"aimeos/aimeos-laravel": "2016.10.x-dev"
```

**Comment by oatache** [comment]
Hi, I got error messages below after execute composer update with **"aimeos/aimeos-laravel": "2016.10.x-dev"**


C:\inetpub\wwwroot\laravel>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Warning: Ambiguous class resolution, "AimeosUsersTable" was found in both "$baseDir . '/database/migrations/2015_03_06_000000_aimeos_users_table.php"
and "C:\inetpub\wwwroot\laravel\vendor/aimeos/aimeos-laravel/src/database/migrations\2015_03_06_000000_aimeos_users_table.php", the first will be used
.
Warning: Ambiguous class resolution, "AimeosUsersLabel" was found in both "$baseDir . '/database/migrations/2015_08_10_000000_aimeos_users_label.php"
and "C:\inetpub\wwwroot\laravel\vendor/aimeos/aimeos-laravel/src/database/migrations\2015_08_10_000000_aimeos_users_label.php", the first will be used
.
> php artisan vendor:publish --tag=public --force
Copied Directory [\vendor\aimeos\aimeos-laravel\public] To [\public\packages\aimeos\shop]
Publishing complete for tag [public]!
> php artisan vendor:publish
Copied Directory [\vendor\aimeos\aimeos-laravel\src\database\migrations] To [\database\migrations]
Copied Directory [\vendor\aimeos\aimeos-laravel\src\views] To [\resources\views\vendor\shop]
Copied Directory [\vendor\aimeos\aimeos-laravel\public] To [\public\packages\aimeos\shop]
Publishing complete for tag []!
> php artisan migrate

  [InvalidArgumentException]
  Database [sqlsrv] not configured.

Script php artisan migrate handling the post-update-cmd event returned with error code

**Comment by aimeos** [comment]
The warning is not relevant but it seems you don't have configured the DB in your config/database.php correctly.

**Comment by oatache** [comment]
Hi,
My bad on a config/database.php, typo error.

Issue was resolved after update the composer.json to "aimeos/aimeos-laravel": "2016.10.x-dev" per your suggestion.

Thank you for your support !
