### ISSUE TITLE
directory of installation

### ISSUE THREAD

**Issue by Bonobomagno** [aimeos/aimeos-laravel#127]
Why the directory of the installation is a separate "ext" instead of been under "vendor"?

**Comment by aimeos** [comment]
The extensions in the `ext` folder are scanned for their manifest files. They contain a some data where to find what. This wouldn't be possible in the `vendor` folder.

**Comment by Bonobomagno** [comment]
So, i can just add it to gitignore? Non need to save/edit it? vendor:publish will generate it for me?

**Comment by aimeos** [comment]
You can handle it like the `vendor` directory. Additionally, you should add your own project specific Aimeos extension to the `ext` directory. That's the only one you should add to your repository
