### ISSUE TITLE
Instalation issue with `users_address` on column `website` - Demo:1

### ISSUE THREAD

**Issue by evertramos** [aimeos/aimeos-laravel#128]
I am reciving this error message right after running this command:

```
php artisan aimeos:setup --option=setup/default/demo:1
```

Error: 

```
[Aimeos\MW\DB\Exception]
  An exception occurred while executing '
                        INSERT INTO "users_address" (                                                                
                                "siteid", "parentid", "company", "vatid", "salutation", "title",                     
                                "firstname", "lastname", "address1", "address2", "address3",                         
                                "postal", "city", "state", "countryid", "langid", "telephone",                       
                                "email", "telefax", "website", "longitude", "latitude", "flag",                      
                                "pos", "mtime", "editor", "ctime"                                                    
                        ) VALUES (                                                                                   
                                6,'Demo company','DE999999999','mrs','','Test','User','Demo street','100','','12345','Demo city','NY','US','
  en','','demo@example.com','','',NULL,NULL,0,0,'2017-07-03 09:57:23','core:setup',1,'2017-07-03 09:57:23'
                        )                                                                                            
                ':                                                                                                   
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'website' cannot be null
```

I tried to change the column in database, but it seems the "verification" Aimeos does changes the column to `not null` again.

Found on `ext` folder, some file with this table on it, but could no get any effective changes on that.

Thanks for any help!

**Comment by aimeos** [comment]
Can you please give us some more information about your environment?
Which Aimeos version, Laravel version, MySQL version and Operating System are you using?

**Comment by evertramos** [comment]
Laravel version 5.4.23
Aimeos version: 2017.07.1 (fresh install)
OS: Windows 10 (Ubuntu Bash)
MariaDB version 15

Sorry for that...

On Laravel 5.5 it passes that point.

**Comment by aimeos** [comment]
There seems to be a mix of different versions due to the new 2017.07 release of the Aimeos core vs. the current release of the Laravel integration (2017.04). Can you please execute `composer update` (you should get 2017.04.5) and proceed with the installation like described in the docs afterwards?

If that doesn't work due to the already created database tables, please drop your database and recreate it before you execute `./artisan aimeos:setup --option=setup/default/demo:1`

**Comment by aimeos** [comment]
The new 2017.07 version is out
