### ISSUE TITLE
Does this support multi vendor feature?

### ISSUE THREAD

**Issue by Nisthar** [aimeos/aimeos-laravel#129]
Does it support multi seller feature?

**Comment by aimeos** [comment]
Yes, every Aimeos installation can host an unlimted number of shops. For market places that aggregate products from all shops, you additionally need the ai-sites extension from the Aimeos company:
https://aimeos.com/extensions/#c1331

**Comment by Nisthar** [comment]
@aimeos So, after a user register on the site the user can become a seller and sell their product. Right?

**Comment by Nisthar** [comment]
Or do i (admin) need to manually create a store for each user?

**Comment by aimeos** [comment]
You need to create a store for each user or write some code that sets up the database entries automatically if someone registers as seller.

**Comment by Nisthar** [comment]
@aimeos Thanks.
