### ISSUE TITLE
MySQL error running php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by colinbarstow** [aimeos/aimeos-laravel#132]
After running the command i receive this error:

  [Aimeos\MW\DB\Exception]
  An exception occurred while executing 'ALTER TABLE users ADD siteid INT DEFAULT NULL, ADD `label` VARCHAR(255) DEFA
  ULT '' NOT NULL, ADD salutation VARCHAR(8) DEFAULT '' NOT NULL, ADD company VARCHAR(100) DEFAULT '' NOT NULL, ADD v
  atid VARCHAR(32) DEFAULT '' NOT NULL, ADD title VARCHAR(64) DEFAULT '' NOT NULL, ADD firstname VARCHAR(64) DEFAULT
  '' NOT NULL, ADD lastname VARCHAR(64) DEFAULT '' NOT NULL, ADD address1 VARCHAR(200) DEFAULT '' NOT NULL, ADD addre
  ss2 VARCHAR(200) DEFAULT '' NOT NULL, ADD address3 VARCHAR(200) DEFAULT '' NOT NULL, ADD postal VARCHAR(16) DEFAULT
   '' NOT NULL, ADD city VARCHAR(200) DEFAULT '' NOT NULL, ADD state VARCHAR(200) DEFAULT '' NOT NULL, ADD langid VAR
  CHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT NULL, ADD telephone VARCHAR(32) DEFAULT '' NOT NULL, ADD telefa
  x VARCHAR(32) DEFAULT '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude NUMERIC(8, 6) DEFAUL
  T NULL, ADD latitude NUMERIC(8, 6) DEFAULT NULL, ADD birthday DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD s
  tatus SMALLINT DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, CHANGE id id INT AUTO_INCREMENT NOT
   NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password V
  ARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NUL
  L':
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

I've tried extending the boot function with: 

use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}

But I am having no luck

Laravel version 5.4

Do you know how to fix this issue?

**Comment by aimeos** [comment]
Please read the important notices: https://github.com/aimeos/aimeos-laravel#important-notice

**Comment by mpandar** [comment]
or change path/to/project/ext/ai-laravel/lib/custom/setup/default/schema/customer.php `$table->addColumn( 'email', 'string', array( 'length' => 255 ) );` to `$table->addColumn( 'email', 'string', array( 'length' => 191 ) );`

**Comment by santiagoapp** [comment]
@mpandar thank you! it really works!

**Comment by antonisch** [comment]
Change from config/database.php 

'mysql' => [
            ...
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            ...
        ],

and then clear config cache (php artisan config:cache)
last step cost me a few hours of wild goose hunting ...
