### ISSUE TITLE
Public directory

### ISSUE THREAD

**Issue by silenoth** [aimeos/aimeos-laravel#135]
Hello, i'm using xampp for up my server on localhost and have an error on the url on link, the url on top is typing manually

![bad_url](https://user-images.githubusercontent.com/5028565/28344200-0104af2e-6bf0-11e7-9fab-a8de8d542eba.png)

this is my .env file
`APP_URL=http://localhost/shop`

thanks, sry for my english

**Comment by aimeos** [comment]
The document root of your web server must point to .../shop/public
