### ISSUE TITLE
Pre-installed repo / boilerplate

### ISSUE THREAD

**Issue by LunarDevelopment** [aimeos/aimeos-laravel#137]
Is there already / can you make available a base Laravel project with Aimeos already present? 

It would make adoption so much easier to be able to clone and play with the package.

**Comment by aimeos** [comment]
There will be a distribution in the future but it's just as easy as this:

Create a base Laravel project: `composer create-project --prefer-dist laravel/laravel myshop`
Then, follow the steps in the docs: https://github.com/aimeos/aimeos-laravel#important-notice

You will get a ready to play installation within 5min.

**Comment by aimeos** [comment]
Our new Aimeos distribution is now available:
https://github.com/aimeos/aimeos
