### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by bahman2216** [aimeos/aimeos-laravel#138]
I got this error in my browser console every minutes!!
And redirect to login page.

Im using latest version on laravel 5.4

**Comment by bahman2216** [comment]
Im using Chrome browser latest version.
No matter witch URL, anywhere it happen internally.

`jquery.js:8630 OPTIONS http://localhost:8000/admin/default/jsonadm 401 (Unauthorized) `

Also Im using wamp with PHP 7.0.4 - MySQL 5.7.11 on windows 8.1

**Comment by aimeos** [comment]
You have to set `'always_populate_raw_post_data` to `-1` in your php.ini as described in the warning
