### ISSUE TITLE
Change datepicker

### ISSUE THREAD

**Issue by bahman2216** [aimeos/aimeos-laravel#139]
Im going to change datepicker in expert mode. After many hours I just found:

> xtype : 'fieldset',

Date type. Does it extjs datepicker or jqueryui datepicker? How can I change it? I added my custom datepicker plugin, But not work.

**Comment by aimeos** [comment]
The ExtJS based interface is hard to change, you need a lot of understanding of ExtJS. Furthermore, the ExtJS interface will be removed next year.

We recommend to adapt the JQAdm interface which is build on PHP, JQuery and Bootstrap only. That's a lot of easier to understand and change.

**Comment by bahman2216** [comment]
Does JQAdm interface cover all features? I couldn't find some features in JQAdm.

**Comment by aimeos** [comment]
The next version will also contain the panels that are usually only necessary for initial setup (delivery, payment, sites, etc.)

**Comment by bahman2216** [comment]
When you release next version?

**Comment by aimeos** [comment]
In two month

**Comment by aimeos** [comment]
The Aimeos JQAdm admin interface is now complete and can also manage all other shop domains (current dev-master branch). The expert mode now isn't necessary any more for shop owners.
