### ISSUE TITLE
error php:artisan vendor:publish

### ISSUE THREAD

**Issue by adityabudiman17** [aimeos/aimeos-laravel#14]
sorry, i have an issue about installing the aiemos, i placed the folder Aimeos/Shop/ to App/Providers and modified the providers in the app.php. but when I run the command php artisan vendor:publish it throws me an error

C:\xampp\htdocs\laravel>php artisan vendor:publish

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Aimeos\Shop\ShopServiceProvider' not found

I'm a newbie in laravel 5. please help me to install this.. thanks..

**Comment by aimeos** [comment]
Aimeos is like Laravel "composer"-based which mean you need the composer utility (getcomposer.org). Please don't copy anything manually! Start from scratch again and follow the documentation: https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by Shane230** [comment]
C:\xampp\htdocs\myshop>php artisan vendor:publish --all
PHP Fatal error:  Class 'Aimeos\Shop\ShopServiceProvider' not found in C:\xampp\htdocs\myshop\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 208


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Aimeos\Shop\ShopServiceProvider' not found

Please help on this

**Comment by aimeos** [comment]
Have you executed `composer update`
