### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by XPanel** [aimeos/aimeos-laravel#140]
hello,
when I run -> php artisan migrate
I receive this error

 [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_u
  nique`(`email`))

Server version: 10.1.25-MariaDB MariaDB Server
PHP 7.1.7

**Comment by aimeos** [comment]
Please read the important notices for Laravel 5.4:
https://github.com/aimeos/aimeos-laravel#important-notice

**Comment by XPanel** [comment]
ok, sorry.
please remove this issue
