### ISSUE TITLE
Readme contain an error

### ISSUE THREAD

**Issue by AntoineDessauges** [aimeos/aimeos-laravel#143]
Hi (not sure if i should post it like a issue but...)

I install aimeos on an homestead and i have some problem to acces the admin panel. After few hours i find a old topic who say i should have my config/shop.php without any routes define in the array but in the readme it write to put some lines (https://github.com/aimeos/aimeos-laravel/tree/2016.04#installation-or-update) (last part). I remove the line and now i can acces my admin panel. I'm not sure if i have a specific install or another things but i think i should report it.

Bye

Laravel v5.4.33

**Comment by aimeos** [comment]
The note about the routes is for Laravel **5.1** only:

> Note: For Laravel 5.1 the routes section in your config/shop.php must be changed like this because in 5.1 there's no middleware group "web" as in 5.2 and later:

**Comment by AntoineDessauges** [comment]
Total my bad. Sorry !
