### ISSUE TITLE
Error while add an attribute

### ISSUE THREAD

**Issue by gera-mtz** [aimeos/aimeos-laravel#147]
Hi guys, when I was modifying the attribute values, I started to get this error:

No item found for conditions: Array ( [attribute.code] => custom [attribute.domain] => product [attribute.type.code] => price [attribute.type.domain] => product ) 

I want to know why this error comes out and how I solve it.

Thanks

**Comment by aimeos** [comment]
There are a few attributes you must not change like the "custom", "date" and "text" attributes. They are important to provide some features, e.g. custom texts, dates and prices
