### ISSUE TITLE
index.php/admin is not redirecting to admin panel

### ISSUE THREAD

**Issue by f9tech** [aimeos/aimeos-laravel#148]
Hello,

I have followed whole documentation. I installed this script in laravel 5.2. 

When I am logging with admin credentials, it is not redirecting admin panel. Instead, it is redirecting to index.php.

Can you clear this?

**Comment by f9tech** [comment]
what does this mean?

Add "admin" group to user "admin3@keza.com" for site "default"

Shall I need to do anything?

**Comment by f9tech** [comment]
This is the setup log

It may help you.


Initializing or updating the Aimeos database tables for site "default"
Changing typeid of mshop_attribute table                              OK
Renaming catalog tree table                                           
  Checking table "mshop_catalog_tree":                                OK
Adding code column to mshop_catalog                                   OK
Renaming product warehouse table                                      OK
Adding ctime/mtime/user columns to tables                             
  Checking table "mshop_attribute" for column "mtime":                OK
  Checking table "mshop_attribute" for column "ctime":                OK
  Checking table "mshop_attribute" for column "editor":               OK
  Checking table "mshop_attribute_list" for column "mtime":           OK
  Checking table "mshop_attribute_list" for column "ctime":           OK
  Checking table "mshop_attribute_list" for column "editor":          OK
  Checking table "mshop_attribute_list_type" for column "mtime":      OK
  Checking table "mshop_attribute_list_type" for column "ctime":      OK
  Checking table "mshop_attribute_list_type" for column "editor":     OK
  Checking table "mshop_attribute_type" for column "mtime":           OK
  Checking table "mshop_attribute_type" for column "ctime":           OK
  Checking table "mshop_attribute_type" for column "editor":          OK
  Checking table "mshop_catalog" for column "mtime":                  OK
  Checking table "mshop_catalog" for column "ctime":                  OK
  Checking table "mshop_catalog" for column "editor":                 OK
  Checking table "mshop_catalog_list" for column "mtime":             OK
  Checking table "mshop_catalog_list" for column "ctime":             OK
  Checking table "mshop_catalog_list" for column "editor":            OK
  Checking table "mshop_catalog_list_type" for column "mtime":        OK
  Checking table "mshop_catalog_list_type" for column "ctime":        OK
  Checking table "mshop_catalog_list_type" for column "editor":       OK
  Checking table "mshop_customer" for column "editor":                OK
  Checking table "mshop_customer_address" for column "mtime":         OK
  Checking table "mshop_customer_address" for column "ctime":         OK
  Checking table "mshop_customer_address" for column "editor":        OK
  Checking table "mshop_customer_list" for column "mtime":            OK
  Checking table "mshop_customer_list" for column "ctime":            OK
  Checking table "mshop_customer_list" for column "editor":           OK
  Checking table "mshop_customer_list_type" for column "mtime":       OK
  Checking table "mshop_customer_list_type" for column "ctime":       OK
  Checking table "mshop_customer_list_type" for column "editor":      OK
  Checking table "mshop_locale" for column "mtime":                   OK
  Checking table "mshop_locale" for column "ctime":                   OK
  Checking table "mshop_locale" for column "editor":                  OK
  Checking table "mshop_locale_currency" for column "mtime":          OK
  Checking table "mshop_locale_currency" for column "ctime":          OK
  Checking table "mshop_locale_currency" for column "editor":         OK
  Checking table "mshop_locale_language" for column "mtime":          OK
  Checking table "mshop_locale_language" for column "ctime":          OK
  Checking table "mshop_locale_language" for column "editor":         OK
  Checking table "mshop_locale_site" for column "mtime":              OK
  Checking table "mshop_locale_site" for column "ctime":              OK
  Checking table "mshop_locale_site" for column "editor":             OK
  Checking table "mshop_media" for column "mtime":                    OK
  Checking table "mshop_media" for column "ctime":                    OK
  Checking table "mshop_media" for column "editor":                   OK
  Checking table "mshop_media_list" for column "mtime":               OK
  Checking table "mshop_media_list" for column "ctime":               OK
  Checking table "mshop_media_list" for column "editor":              OK
  Checking table "mshop_media_list_type" for column "mtime":          OK
  Checking table "mshop_media_list_type" for column "ctime":          OK
  Checking table "mshop_media_list_type" for column "editor":         OK
  Checking table "mshop_media_type" for column "mtime":               OK
  Checking table "mshop_media_type" for column "ctime":               OK
  Checking table "mshop_media_type" for column "editor":              OK
  Checking table "mshop_order" for column "ctime":                    OK
  Checking table "mshop_order" for column "editor":                   OK
  Checking table "mshop_order_base" for column "ctime":               OK
  Checking table "mshop_order_base" for column "editor":              OK
  Checking table "mshop_order_base_address" for column "ctime":       OK
  Checking table "mshop_order_base_address" for column "editor":      OK
  Checking table "mshop_order_base_product" for column "ctime":       OK
  Checking table "mshop_order_base_product" for column "editor":      OK
  Checking table "mshop_order_base_product_attr" for column "ctime":  OK
  Checking table "mshop_order_base_product_attr" for column "editor": OK
  Checking table "mshop_order_base_service" for column "ctime":       OK
  Checking table "mshop_order_base_service" for column "editor":      OK
  Checking table "mshop_order_base_service_attr" for column "ctime":  OK
  Checking table "mshop_order_base_service_attr" for column "editor": OK
  Checking table "mshop_plugin" for column "mtime":                   OK
  Checking table "mshop_plugin" for column "ctime":                   OK
  Checking table "mshop_plugin" for column "editor":                  OK
  Checking table "mshop_plugin_type" for column "mtime":              OK
  Checking table "mshop_plugin_type" for column "ctime":              OK
  Checking table "mshop_plugin_type" for column "editor":             OK
  Checking table "mshop_price" for column "mtime":                    OK
  Checking table "mshop_price" for column "ctime":                    OK
  Checking table "mshop_price" for column "editor":                   OK
  Checking table "mshop_price_type" for column "mtime":               OK
  Checking table "mshop_price_type" for column "ctime":               OK
  Checking table "mshop_price_type" for column "editor":              OK
  Checking table "mshop_product" for column "ctime":                  OK
  Checking table "mshop_product" for column "mtime":                  OK
  Checking table "mshop_product" for column "editor":                 OK
  Checking table "mshop_product_list" for column "ctime":             OK
  Checking table "mshop_product_list" for column "mtime":             OK
  Checking table "mshop_product_list" for column "editor":            OK
  Checking table "mshop_product_list_type" for column "ctime":        OK
  Checking table "mshop_product_list_type" for column "mtime":        OK
  Checking table "mshop_product_list_type" for column "editor":       OK
  Checking table "mshop_product_type" for column "ctime":             OK
  Checking table "mshop_product_type" for column "mtime":             OK
  Checking table "mshop_product_type" for column "editor":            OK
  Checking table "mshop_service" for column "ctime":                  OK
  Checking table "mshop_service" for column "mtime":                  OK
  Checking table "mshop_service" for column "editor":                 OK
  Checking table "mshop_service_list" for column "ctime":             OK
  Checking table "mshop_service_list" for column "mtime":             OK
  Checking table "mshop_service_list" for column "editor":            OK
  Checking table "mshop_service_list_type" for column "ctime":        OK
  Checking table "mshop_service_list_type" for column "mtime":        OK
  Checking table "mshop_service_list_type" for column "editor":       OK
  Checking table "mshop_service_type" for column "ctime":             OK
  Checking table "mshop_service_type" for column "mtime":             OK
  Checking table "mshop_service_type" for column "editor":            OK
  Checking table "mshop_supplier" for column "ctime":                 OK
  Checking table "mshop_supplier" for column "mtime":                 OK
  Checking table "mshop_supplier" for column "editor":                OK
  Checking table "mshop_supplier_address" for column "ctime":         OK
  Checking table "mshop_supplier_address" for column "mtime":         OK
  Checking table "mshop_supplier_address" for column "editor":        OK
  Checking table "mshop_text" for column "ctime":                     OK
  Checking table "mshop_text" for column "mtime":                     OK
  Checking table "mshop_text" for column "editor":                    OK
  Checking table "mshop_text_list" for column "ctime":                OK
  Checking table "mshop_text_list" for column "mtime":                OK
  Checking table "mshop_text_list" for column "editor":               OK
  Checking table "mshop_text_list_type" for column "ctime":           OK
  Checking table "mshop_text_list_type" for column "mtime":           OK
  Checking table "mshop_text_list_type" for column "editor":          OK
  Checking table "mshop_text_type" for column "ctime":                OK
  Checking table "mshop_text_type" for column "mtime":                OK
  Checking table "mshop_text_type" for column "editor":               OK
Renaming order tables                                                 
  Checking table "mshop_order_address":                               OK
  Checking table "mshop_order_discount":                              OK
  Checking table "mshop_order_product":                               OK
  Checking table "mshop_order_service":                               OK
  Checking table "mshop_order_service_attribute":                     OK
Adding id to order service attribute table                            
  Checking column "id":                                               OK
Adding siteid to order tables                                         
  Checking table "mshop_order_base":                                  OK
  Checking table "mshop_order":                                       OK
  Checking table "mshop_order_base_address":                          OK
  Checking table "mshop_order_base_discount":                         OK
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base_product_attr":                     OK
  Checking table "mshop_order_base_service_attr":                     OK
Renaming global tables                                                
Changeing locale sites to tree of sites                               
  Checking column "mshop_locale_site.level":                          OK
  Checking column "mshop_locale_site.nleft":                          OK
  Checking column "mshop_locale_site.nright":                         OK
Changing site ID to NOT NULL                                          
  Changing table "madmin_job":                                        OK
  Changing table "mshop_attribute":                                   OK
  Changing table "mshop_attribute_list":                              OK
  Changing table "mshop_attribute_list_type":                         OK
  Changing table "mshop_attribute_type":                              OK
  Changing table "mshop_catalog":                                     OK
  Changing table "mshop_catalog_index_attribute":                     OK
  Changing table "mshop_catalog_index_catalog":                       OK
  Changing table "mshop_catalog_index_price":                         OK
  Changing table "mshop_catalog_index_text":                          OK
  Changing table "mshop_catalog_list":                                OK
  Changing table "mshop_catalog_list_type":                           OK
  Changing table "mshop_coupon":                                      OK
  Changing table "mshop_coupon_code":                                 OK
  Changing table "mshop_customer_list":                               OK
  Changing table "mshop_customer_list_type":                          OK
  Changing table "mshop_locale":                                      OK
  Changing table "mshop_media":                                       OK
  Changing table "mshop_media_list":                                  OK
  Changing table "mshop_media_list_type":                             OK
  Changing table "mshop_media_type":                                  OK
  Changing table "mshop_plugin":                                      OK
  Changing table "mshop_plugin_type":                                 OK
  Changing table "mshop_price":                                       OK
  Changing table "mshop_price_type":                                  OK
  Changing table "mshop_product":                                     OK
  Changing table "mshop_product_list":                                OK
  Changing table "mshop_product_list_type":                           OK
  Changing table "mshop_product_stock":                               OK
  Changing table "mshop_product_stock_warehouse":                     OK
  Changing table "mshop_product_tag":                                 OK
  Changing table "mshop_product_tag_type":                            OK
  Changing table "mshop_product_type":                                OK
  Changing table "mshop_service":                                     OK
  Changing table "mshop_service_list":                                OK
  Changing table "mshop_service_list_type":                           OK
  Changing table "mshop_service_type":                                OK
  Changing table "mshop_supplier":                                    OK
  Changing table "mshop_supplier_address":                            OK
  Changing table "mshop_text":                                        OK
  Changing table "mshop_text_list":                                   OK
  Changing table "mshop_text_list_type":                              OK
  Changing table "mshop_text_type":                                   OK
Renaming catalog index tables to index                                
  Checking table "mshop_catalog_index_attribute"                      OK
  Checking table "mshop_catalog_index_catalog"                        OK
  Checking table "mshop_catalog_index_price"                          OK
  Checking table "mshop_catalog_index_text"                           OK
Changing "domain" columns                                             
  Checking table "mshop_attribute":                                   OK
  Checking table "mshop_attribute_type":                              OK
  Checking table "mshop_attribute_list_type":                         OK
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_catalog":                                     OK
  Checking table "mshop_catalog_list_type":                           OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_catalog_suggest":                             OK
  Checking table "mshop_media_type":                                  OK
  Checking table "mshop_media_list_type":                             OK
  Checking table "mshop_media":                                       OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_plugin":                                      OK
  Checking table "mshop_price":                                       OK
  Checking table "mshop_product_type":                                OK
  Checking table "mshop_product_list_type":                           OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_product_tag_type":                            OK
  Checking table "mshop_service":                                     OK
  Checking table "mshop_service_list_type":                           OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_text_type":                                   OK
  Checking table "mshop_text":                                        OK
  Checking table "mshop_text_list_type":                              OK
  Checking table "mshop_text_list":                                   OK
Renaming column "discount" to "rebate"                                
  Checking table "mshop_price"                                        OK
  Checking table "mshop_order_base"                                   OK
  Checking table "mshop_order_base_product"                           OK
  Checking table "mshop_order_base_service"                           OK
Renaming discount tables                                              
Adding mtime, ctime, editor columns to coupon tables                  
  Checking table "mshop_coupon"                                       
    Checking column "mtime":                                          OK
    Checking column "ctime":                                          OK
    Checking column "editor":                                         OK
  Checking table "mshop_coupon_code"                                  
    Checking column "mtime":                                          OK
    Checking column "ctime":                                          OK
    Checking column "editor":                                         OK
  Checking table "mshop_order_base_coupon"                            
    Checking column "ctime":                                          OK
    Checking column "editor":                                         OK
Migrating configuration keys in coupon tables                         done
Adding status column to all list tables                               
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_customer_list":                               OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_price_list":                                  OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_text_list":                                   OK
Changing typeid of mshop_media table                                  OK
Adding product ID to order base product table                         
  Checking table "mshop_order_base_product":                          OK
Adding warehouse code to order base product table                     done
Adding service ID to order base service table                         
  Checking table "mshop_order_base_service":                          OK
Migrating order address salutations                                   
  Checking table "mshop_order_base_address":                          OK
Adding tax column to order tables                                     
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base":                                  OK
Migrating order emailflag colum to order status list                  
  Deleting order index with emailflag colum                           OK
  Migrating order emailflag colum                                     OK
Fixing order email status values                                      OK
Migrating order flags to order status list                            
  Deleting order index with flag colum                                OK
  Migrating order flag colum                                          OK
Migrating order type                                                  
  Checking table "mshop_order":                                       OK
Renaming order base customercode to customerid                        
  Checking table "mshop_order_base":                                  OK
Renaming order base product amount to quantity                        
  Checking table "mshop_order_base_product":                          OK
Renaming order columns pdate,ddate,dstatus,pstatus                    
  Checking columne "ddate":                                           OK
  Checking columne "pdate":                                           OK
  Checking columne "pstatus":                                         OK
  Checking columne "dstatus":                                         OK
Renaming order domain                                                 
  Checking table "mshop_order":                                       OK
  Checking table "mshop_order_base_address":                          OK
  Checking table "mshop_order_base_service":                          OK
Renaming shipping to costs                                            
  Checking table "mshop_order_base":                                  OK
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
Renaming column "price" to "value"                                    
  Checking table "mshop_price"                                        OK
Renaming shipping to costs                                            
  Checking table "mshop_price":                                       OK
Rename "prodid" to "parentid" in table "mshop_product_stock"          
  Checking column "prodid"                                            OK
Changing code from "product" to "default" in "mshop_product_type"     OK
Changing typeid column of product table                               
  Checking table "mshop_product":                                     OK
Migrating product property domain to "product"                        OK
Changing warehouseid column in mshop_product_stock                    OK
Rename warehouse table                                                
  Drop "mshop_product_stock.fk_msprost_whid"                          OK
  Drop "mshop_product_stock.fk_msprost_stock_warehouseid"             OK
  Rename "mshop_product_stock.wareshouseid"                           OK
  Rename "mshop_product_stock_wareshouse"                             OK
Move stock tables to own domain                                       
  Checking "mshop_product_stock"                                      OK
  Checking "mshop_product_stock_type"                                 OK
Adding label and status columns for product warehouse                 
Ensure unique codes in mshop_service                                  done
Migrate product code in stock table                                   
  Remove index "unq_msprost_sid_pid_tid"                              OK
  Remove index "unq_msprost_sid_pid_wid"                              OK
  Migrate to column "productcode"                                     OK
  Remove foreign key "fk_msprost_parentid"                            OK
  Remove foreign key "fk_msprost_pid"                                 OK
  Remove column "parentid"                                            OK
Migrating subject tables                                              
  Checking table "mshop_subject_customer":                            OK
  Checking table "mshop_subject_supplier":                            OK
  Checking table "mshop_subject_common_address":                      OK
  Checking table "mshop_subject":                                     OK
Moving product tag tables to own domain                               
  Moving table "mshop_product_tag_type"                               OK
  Moving table "mshop_product_tag"                                    OK
Adding label to mshop text table                                      OK
Changing typeid of mshop_text table                                   OK
Adding parentid column to catalog and locale_site                     
  Checking parentid column in "mshop_catalog"                         OK
  Checking parentid column in "mshop_locale_site"                     OK
Creating base tables                                                  
  Using schema from locale.php                                        
    Checking table "mshop_locale_site":                               done
    Checking table "mshop_locale_language":                           done
    Checking table "mshop_locale_currency":                           done
    Checking table "mshop_locale":                                    done
  Using schema from attribute.php                                     
    Checking table "mshop_attribute_type":                            done
    Checking table "mshop_attribute":                                 done
    Checking table "mshop_attribute_list_type":                       done
    Checking table "mshop_attribute_list":                            done
  Using schema from customer.php                                      
    Checking table "mshop_customer":                                  done
    Checking table "mshop_customer_address":                          done
    Checking table "mshop_customer_list_type":                        done
    Checking table "mshop_customer_list":                             done
    Checking table "mshop_customer_group":                            done
    Checking table "users":                                           done
    Checking table "users_address":                                   done
    Checking table "users_list_type":                                 done
    Checking table "users_list":                                      done
  Using schema from media.php                                         
    Checking table "mshop_media_type":                                done
    Checking table "mshop_media":                                     done
    Checking table "mshop_media_list_type":                           done
    Checking table "mshop_media_list":                                done
  Using schema from order.php                                         
    Checking table "mshop_order_base":                                done
    Checking table "mshop_order_base_address":                        done
    Checking table "mshop_order_base_product":                        done
    Checking table "mshop_order_base_product_attr":                   done
    Checking table "mshop_order_base_service":                        done
    Checking table "mshop_order_base_service_attr":                   done
    Checking table "mshop_order_base_coupon":                         done
    Checking table "mshop_order":                                     done
    Checking table "mshop_order_status":                              done
  Using schema from plugin.php                                        
    Checking table "mshop_plugin_type":                               done
    Checking table "mshop_plugin":                                    done
  Using schema from price.php                                         
    Checking table "mshop_price_type":                                done
    Checking table "mshop_price":                                     done
    Checking table "mshop_price_list_type":                           done
    Checking table "mshop_price_list":                                done
  Using schema from product.php                                       
    Checking table "mshop_product_type":                              done
    Checking table "mshop_product":                                   done
    Checking table "mshop_product_list_type":                         done
    Checking table "mshop_product_list":                              done
    Checking table "mshop_product_property_type":                     done
    Checking table "mshop_product_property":                          done
  Using schema from stock.php                                         
    Checking table "mshop_stock_type":                                done
    Checking table "mshop_stock":                                     done
  Using schema from service.php                                       
    Checking table "mshop_service_type":                              done
    Checking table "mshop_service":                                   done
    Checking table "mshop_service_list_type":                         done
    Checking table "mshop_service_list":                              done
  Using schema from supplier.php                                      
    Checking table "mshop_supplier":                                  done
    Checking table "mshop_supplier_address":                          done
    Checking table "mshop_supplier_list_type":                        done
    Checking table "mshop_supplier_list":                             done
  Using schema from text.php                                          
    Checking table "mshop_text_type":                                 done
    Checking table "mshop_text":                                      done
    Checking table "mshop_text_list_type":                            done
    Checking table "mshop_text_list":                                 done
  Using schema from coupon.php                                        
    Checking table "mshop_coupon":                                    done
    Checking table "mshop_coupon_code":                               done
  Using schema from catalog.php                                       
    Checking table "mshop_catalog":                                   done
    Checking table "mshop_catalog_list_type":                         done
    Checking table "mshop_catalog_list":                              done
  Using schema from tag.php                                           
    Checking table "mshop_tag_type":                                  done
    Checking table "mshop_tag":                                       done
  Using schema from index.php                                         
    Checking table "mshop_index_attribute":                           done
    Checking table "mshop_index_catalog":                             done
    Checking table "mshop_index_price":                               done
    Checking table "mshop_index_text":                                done
Move list types to separate table                                     
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_attribute_option_list":                       OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
Add locale data for languages and currencies                          
  Adding data for MShop locale languages                              188/188
  Adding data for MShop locale currencies                             156/156
Renaming in "madmin_job" column "user" to "editor".                   
  Checking column "user":                                             OK
Converting "madmin_job" to InnoDB".                                   OK
Creating admin tables                                                 
  Using schema from cache.php                                         
    Checking table "madmin_cache":                                    done
    Checking table "madmin_cache_tag":                                done
  Using schema from log.php                                           
    Checking table "madmin_log":                                      done
  Using schema from job.php                                           
    Checking table "madmin_job":                                      done
  Using schema from queue.php                                         
    Checking table "madmin_queue":                                    done
Adding data for MShop locale domain                                   
  Adding data for MShop locale sites                                  done
  Adding data for MShop locales                                       done
Adding locale data if not yet present                                 OK
Setting locale to "default"                                           OK
Migrating catalog suggest tables                                      
  Checking table "mshop_catalog_suggest":                             OK
Changing typeid to not allow NULL values                              
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_text_list":                                   OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_media_list":                                  OK
Adding time columns to order table                                    done
Renaming plugin domain                                                
  Checking table "mshop_plugin":                                      OK
Adding label column to mshop_plugin table                             OK
Migrating "Complete" to "BasketLimits" plugin                         
  Migrating "minorder"                                                OK
  Migrating "minproducts"                                             OK
  Migrating "Complete"                                                OK
Migrating configuration of "Complete" plugin                          OK
Migrating configuration of "ProductLimit" plugin                      OK
Adding typeid column to price table                                   
  Checking column "typeid":                                           OK
Add domain values to "mshop_product_stock_type" table                 OK
Migrating product text and media tables to list                       
  Checking table "mshop_product_package":                             OK
  Checking table "mshop_product_package_text":                        OK
  Checking table "mshop_product_package_price":                       OK
  Checking table "mshop_product_package_stock":                       OK
Migrate suppliercode in mshop_product                                 OK
Changing typeid column in mshop_product_tag table                     
  Checking table "mshop_product_tag":                                 OK
Migrating product text and media tables to list                       
  Checking table "mshop_product_text":                                OK
  Checking table "mshop_product_media":                               OK
Migrating service price table to list                                 
  Checking table "mshop_service_price":                               OK
Renaming service domain                                               
  Checking table "mshop_service":                                     OK
Renaming service configuration                                        OK
Migrating service text table                                          
  Checking table "mshop_service_text":                                OK
Add stock type domain values                                          done
Creating platform specific schema                                     
  Using tables from index-mysql.sql                                   
    Checking index "mshop_index_text.idx_msindte_p_s_lt_la_ty_do_va": OK
    Checking index "mshop_index_text.idx_msindte_value":              OK
  Using tables from order-mysql.sql                                   
    Checking index "mshop_order_base_product_attr.idx_msordbaprat_si_cd_va": OK
    Checking index "mshop_order_base_service_attr.idx_msordbaseat_si_cd_va": OK
  Using tables from text-mysql.sql                                    
    Checking index "mshop_text.idx_mstex_sid_dom_cont":               OK
Setting label and status values                                       
  Checking table "mshop_attribute_type":                              OK
  Checking table "mshop_attribute_list_type":                         OK
  Checking table "mshop_catalog_list_type":                           OK
  Checking table "mshop_media_list_type":                             OK
  Checking table "mshop_media_type":                                  OK
  Checking table "mshop_plugin_type":                                 OK
  Checking table "mshop_product_list_type":                           OK
  Checking table "mshop_product_tag_type":                            n/a
  Checking table "mshop_product_type":                                OK
  Checking table "mshop_service_list_type":                           OK
  Checking table "mshop_service_type":                                OK
  Checking table "mshop_text_list_type":                              OK
  Checking table "mshop_text_type":                                   OK
Adding MShop type data for site "default"                             
  Checking "attribute/type" type data                                 OK
  Checking "attribute/lists/type" type data                           OK
  Checking "catalog/lists/type" type data                             OK
  Checking "customer/lists/type" type data                            OK
  Checking "media/type" type data                                     OK
  Checking "media/lists/type" type data                               OK
  Checking "plugin/type" type data                                    OK
  Checking "price/type" type data                                     OK
  Checking "price/lists/type" type data                               OK
  Checking "product/type" type data                                   OK
  Checking "product/lists/type" type data                             OK
  Checking "product/property/type" type data                          OK
  Checking "stock/type" type data                                     OK
  Checking "service/type" type data                                   OK
  Checking "service/lists/type" type data                             OK
  Checking "supplier/lists/type" type data                            OK
  Checking "tag/type" type data                                       OK
  Checking "text/type" type data                                      OK
  Checking "text/lists/type" type data                                OK
Adding default code data for site "default"                           
  Checking "customer/group" codes                                     OK
Processing product demo data                                          added
Processing catalog demo data                                          added
Processing coupon demo data                                           added
Processing customer demo data                                         added
Processing service demo data                                          added
Processing supplier demo data                                         added
Rebuilding index for demo data                                        done
Adding default attribute data for site "default"                      OK
Adding default plugin data                                            
  Adding data for MShop plugins                                       OK
Rename "refid" to "parentid" in table "users_address"                 
  Checking column "refid"                                             OK

**Comment by f9tech** [comment]
mshop_customer_list_type table is empty

**Comment by aimeos** [comment]
Which Aimeos version are you using?

**Comment by f9tech** [comment]
I think I have used latest version

This is what I have kept in composer.json

"aimeos/aimeos-laravel": "~2017.07",

**Comment by aimeos** [comment]
For Laravel 5.2 you need Aimeos ~2016.10 because 2017.x doesn't work due to changes in Laravel 5.4 and 5.5
