### ISSUE TITLE
front-end price exception

### ISSUE THREAD

**Issue by kamranmalikte** [aimeos/aimeos-laravel#149]
I added new product also add price but it not shown
![screen shot 2017-09-08 at 1 11 26 pm](https://user-images.githubusercontent.com/27995556/30202307-63d614c4-9497-11e7-9785-95f2f2f64332.png)
 

When i add to basket it says price item not available 

![screen shot 2017-09-08 at 1 13 45 pm](https://user-images.githubusercontent.com/27995556/30202350-976917e6-9497-11e7-9eca-e158f9e46828.png)

Here is price item 

![screen shot 2017-09-08 at 1 15 23 pm](https://user-images.githubusercontent.com/27995556/30202422-d6f4cb76-9497-11e7-9772-bc323d33e37a.png)

**Comment by aimeos** [comment]
Your default currency is EUR but your product only contains prices for USD. To see your USD prices, change the currency by either making USD default in the locale list panel or adding a currency selector on your page.

**Comment by kamranmalikte** [comment]
So , How to make USD default in Locale list Panel  here in no option
![screen shot 2017-09-08 at 2 04 56 pm](https://user-images.githubusercontent.com/27995556/30204391-c008368a-949e-11e7-9b8f-e3f82f55278d.png)

**Comment by aimeos** [comment]
Just change positions and make EN/USD first (position 0)

**Comment by kamranmalikte** [comment]
ok but it is not realy good technique

**Comment by aimeos** [comment]
Why not?
Alternative: Add the locale selector to the frontend so customer can change languages/currencies:
https://aimeos.org/docs/Laravel/Add_locale_selector
