### ISSUE TITLE
Error while setting up the package

### ISSUE THREAD

**Issue by ZengineAlex** [aimeos/aimeos-laravel#15]
After I run the setup command in he command line, this error appears:

[MW_DB_Exception]                                                                                       
  Executing statement "CREATE TABLE "madmin_cache" (                                                      
  	-- Unique id of the cache entry                                                                        
  	"id" VARCHAR(255) NOT NULL,                                                                            
  	-- site id                                                                                             
  	"siteid" INTEGER NULL,                                                                                 
  	-- Expiration time stamp                                                                               
  	"expire" DATETIME,                                                                                     
  	-- Cached value                                                                                        
  	"value" MEDIUMTEXT NOT NULL,                                                                           
  CONSTRAINT "pk_macac_id_siteid"                                                                         
  	PRIMARY KEY ("id", "siteid")                                                                           
  ) ENGINE=InnoDB CHARACTER SET = utf8;                                                                   
  " failed: SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be N  
  OT NULL; if you need NULL in a key, use UNIQUE instead     

Do you have an idea if is a problem with the migration itself or with my SQL version?

**Comment by aimeos** [comment]
Which MySQL version do you use? Maybe we need to declare the "siteid" column as NOT NULL

**Comment by ZengineAlex** [comment]
I'm using MySql Workbench for my Ubuntu System with SQL Version 5.7.9

**Comment by aimeos** [comment]
Seems to be that MySQL 5.7 is more picky than previous versions. We will change the siteid column definition.

**Comment by ZengineAlex** [comment]
Great, thanks a lot! :)

**Comment by aimeos** [comment]
The problem should be fixed now. We've changed the index from "primary" to "unique" and the fix is part of the Laravel 1.2.2 / Core 2015.10.4 releases of today

**Comment by ZengineAlex** [comment]
Now it's working fine! Thanks once again !
