### ISSUE TITLE
language manage

### ISSUE THREAD

**Issue by Bonobomagno** [aimeos/aimeos-laravel#151]
What did you use for managing language?
I see i18n, but this isn't the laravel standard. So i cant use some nice traslator manager made for laravel.
It's not a big deal for only admin ui, but the actual traslation is not fine in my languague..
At least, there is a quick way to traslate it?

**Comment by Bonobomagno** [comment]
Ok, thank. I think i will traslate on transifex.
an other question:
What about multilanguage model?
Ok, you use doctrine, but how to have a multilanguage description of the products!?
But more usefull for me, how to increase the enabled language on the "text" voice?
I cant find italian for eg.

**Comment by aimeos** [comment]
You can add texts in as many languages in the admin interface for each product as you need. Make sure you've enabled the languages you need in the **Locale -> Languages** panel.

To add a language selector in the frontend, follow this guide:
https://aimeos.org/docs/Laravel/Add_locale_selector

**Comment by Bonobomagno** [comment]
Ok, and what you use for localize the right language? standard laravel?
Becouse i need to change the url for seo purpose, and use arcanedev/localization. So i need the same lang on both the the traslation method.

**Comment by aimeos** [comment]
What is the right language?
Do you want to localize e.g. "detail" to "dettaglio"?
