### ISSUE TITLE
Session ends continuously

### ISSUE THREAD

**Issue by JCarlosR** [aimeos/aimeos-laravel#153]
I have installed the aimeos package in a new laravel project (5.5.4).

I have created an admin user and the login works, but the session expires continuously.

Why it happens? Is it an known bug? :(

![image](https://user-images.githubusercontent.com/3101238/30396506-79b9a4b2-988f-11e7-94bd-83edc0aab5eb.png)

Thank you in advance.

**Comment by aimeos** [comment]
This is a Laravel message and I think you can extend the session timeout somewhere in the Laravel configuration

**Comment by JCarlosR** [comment]
@aimeos Thank you.

Well, I have the lifetime by default in `config/session.php`:

```
'lifetime' => 120,
'expire_on_close' => false,
```

Each session should have a lifetime of 120 minutes, but it expires in a few seconds.

**Comment by aimeos** [comment]
You are the first one reporting that behavior when using Laravel 5.5. Aimeos doesn't care about session handing because this is completely done by Laravel. As Laravel 5.4 have never shown such a behavior it might be either a bug in the 5.5 session handling or your browser looses the session cookie for some unknown reason. Maybe you should ask in one of the Laravel forums if other had seen that problem too.

**Comment by JCarlosR** [comment]
@aimeos Ok, I understand.

Just a last question:
![image](https://user-images.githubusercontent.com/3101238/30398809-5373f5ac-9897-11e7-9e5b-3bba9ca35eae.png)

How I can change these labels?
I am using the spanish language but some words are not translated.

Thank you for your time.

**Comment by aimeos** [comment]
Please register with your GitHub account at Transifex (https://www.transifex.com/aimeos/public/) and translate the missing label. We will integrate your translations into the next version in two weeks.

**Comment by JCarlosR** [comment]
@aimeos Ok. I have translated some important labels.

There is a way to use the updated labels? Even if I have to updated it manually in my project.

**Comment by aimeos** [comment]
We've updated the translations in the dev-master branch. If you change to

`"aimeos/aimeos-laravel": "dev-master"`

you will get your new translations after running `composer update`
