### ISSUE TITLE
JQadmin Categories are not deleted

### ISSUE THREAD

**Issue by gera-mtz** [aimeos/aimeos-laravel#154]
Hi guys, when I want to delete a category and the dialog box confirming its deletion appears, where I confirm it, it does nothing more to disappear the confirmation dialog box. Even if I update the page in that part, the category is still found. 

Aimeos version: 2017.07.2
Laravel version: 5.4
PHP version: 7.1.7
Environment: Windows 10

**Comment by aimeos** [comment]
Can you post the output of `composer show`?

**Comment by gera-mtz** [comment]
![composer show 1](https://user-images.githubusercontent.com/2713929/30442006-b93d0c80-9940-11e7-9cd4-537138e3974a.png)
![composer show 2](https://user-images.githubusercontent.com/2713929/30442007-b9411a96-9940-11e7-98a7-1a7e4aa19884.png)

**Comment by aimeos** [comment]
Please execute `composer update` to get the latest versions of `ai-admin-jqadm` and `ai-admin-jsonadm`

**Comment by gera-mtz** [comment]
![composer show 2](https://user-images.githubusercontent.com/2713929/30442237-71f68dc8-9941-11e7-83de-e2ec8ec106b0.png)
![composer show 1](https://user-images.githubusercontent.com/2713929/30442238-71f8f6bc-9941-11e7-9a23-999268636115.png)

**Comment by gera-mtz** [comment]
Yes I worked. Thanks
