### ISSUE TITLE
change delivery status in jqadm

### ISSUE THREAD

**Issue by gera-mtz** [aimeos/aimeos-laravel#156]
Hi mr aimeos...

The problem I have is when I change the shipping status for an order in the "jqadm". The change of the sending of the order does not show in the profile of the client after having saved the changes.

**Comment by gera-mtz** [comment]
the curious thing about this, is that in the "extadm" it works changing the sending state

**Comment by aimeos** [comment]
Maybe you've changed only the delivery status of a single ordered product. The delivery status of the whole order must be changed in the "Invoice" tab (select the "Delivery" column to show these values)

**Comment by gera-mtz** [comment]
ok yes it is there where you can change the value but even when you have made the change, but the change is not yet shown in the "profile" of "myaccount"

**Comment by gera-mtz** [comment]
yes, it works, but for the date, i need to show datepicker because the client will not know how to write the date correctly

**Comment by aimeos** [comment]
You need to set the delivery date and status. The delivery date field is a HTML5 date picker, so it depends on the browser you are using if it's shown or only a text field is displayed.

**Comment by gera-mtz** [comment]
I use firefox 56.0b12, there are parts inside the jqadmin where the datepicker works (product -> add -> basic / -> start date / end date) and others where it does not work (in this case)

**Comment by aimeos** [comment]
Support for date/time seems to be at least partially disabled by default until Firefox 56:
https://caniuse.com/input-datetime

Can you post a screenshot where the date picker doesn't work?

**Comment by gera-mtz** [comment]
in this part, does work...
![screenshot-2017-9-19 aimeos administration interface](https://user-images.githubusercontent.com/2713929/30596334-6d73c294-9d19-11e7-9b09-62520f723d50.png)

...and here, not
![screenshot-2017-9-19 aimeos administration interface 2](https://user-images.githubusercontent.com/2713929/30596649-5f95fe7a-9d1a-11e7-8f0f-b9ea84ed1ee9.png)

**Comment by gera-mtz** [comment]
how to integrate the "js datepicker" into that field of the purchase order?

**Comment by aimeos** [comment]
Simply replace `type="datetime-local"` in <input> fields with `type="text"` and add `date` as CSS class like here:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/product/item-default.php#L238

If you replace the HTML5 date picker with the JS date picker in the templates in a pull request, we will happily merge it :-)

**Comment by gera-mtz** [comment]
I have a error while change the datetime picker por this:

![error 1 datetime](https://user-images.githubusercontent.com/2713929/30619242-14e4c07e-9d64-11e7-939a-1a7bdeb82687.png)

**Comment by gera-mtz** [comment]
and so, i doesn't works in this parts:

![screenshot-2017-9-19 aimeos administration interface 1](https://user-images.githubusercontent.com/2713929/30619438-06471c78-9d65-11e7-8537-194aac617603.png)

**Comment by aimeos** [comment]
The date format doesn't match. Forgot to mention the required `data-format` attribute:
```
data-format="<?= $this->translate( 'admin', 'yy-mm-dd' ); ?>"
``

**Comment by gera-mtz** [comment]
yes the "dateformat" part worked, but the part of adding an invoice has not yet

![](https://user-images.githubusercontent.com/2713929/30619438-06471c78-9d65-11e7-8537-194aac617603.png)

**Comment by aimeos** [comment]
DOM nodes that are cloned must be handled differently because the cloned JS enhanced fields don't work any more after cloning.

We implemented a different approach now:
All date/time fields are of type "datetime-local" now and if browsers don't support them, the JQuery date picker is used instead. This requires the Modernizr JS library to work which has been added to the Laravel Aimeos JQAdm Blade template (https://github.com/aimeos/aimeos-laravel/blob/83cb369009f7a79123f5a6f1a85408562e14093c/src/views/jqadm/index.blade.php#L31). Make sure you remove the old template if it exists and run `artisan view:publish` afterwards.

**Comment by gera-mtz** [comment]
ok, let me check

**Comment by gera-mtz** [comment]
I already tried the changes made and I still have the same thing. I had to create another blank project to see if you made changes, and it's still the same but with the difference that the field "bought" does work in my case.

**Comment by aimeos** [comment]
Which ones do not work?

Yes, please create a test installation from scratch using dev-master. I guess you still have the old Blade template in your current one.
