### ISSUE TITLE
Demo install fails with error: max key length is 767 bytes 

### ISSUE THREAD

**Issue by moksamedia** [aimeos/aimeos-laravel#158]
Hello. I'm trying to install the demo app, but my install ( php artisan aimeos:setup --option= setup/default/demo:1) keeps failing with this error: 

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes 

Apparently 767 bytes is the max key length in InnoDB, which is the engine MAMP is using on my Mac.

I'm on Laravel Framework 5.4.36 and "aimeos/aimeos-laravel": "~2017.07"

Any ideas how to resolve this?

**Comment by moksamedia** [comment]
Switched to MyIASM and got the same error.

` [Aimeos\MW\DB\Exception]                                                                                                                                                                                                                                          
  An exception occurred while executing 'ALTER TABLE users ADD siteid INT DEFAULT NULL, ADD `label` VARCHAR(255) DEFAULT '' NOT NULL, ADD salutation VARCHAR(8) DEFAULT '' NOT NULL, ADD company VARCHAR(100) DEFAULT '' NOT NULL, ADD vatid VARCHAR(32) DEFAULT '  
  ' NOT NULL, ADD title VARCHAR(64) DEFAULT '' NOT NULL, ADD firstname VARCHAR(64) DEFAULT '' NOT NULL, ADD lastname VARCHAR(64) DEFAULT '' NOT NULL, ADD address1 VARCHAR(200) DEFAULT '' NOT NULL, ADD address2 VARCHAR(200) DEFAULT '' NOT NULL, ADD address3 V  
  ARCHAR(200) DEFAULT '' NOT NULL, ADD postal VARCHAR(16) DEFAULT '' NOT NULL, ADD city VARCHAR(200) DEFAULT '' NOT NULL, ADD state VARCHAR(200) DEFAULT '' NOT NULL, ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT NULL, ADD telephone VARCHA  
  R(32) DEFAULT '' NOT NULL, ADD telefax VARCHAR(32) DEFAULT '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude NUMERIC(8, 6) DEFAULT NULL, ADD latitude NUMERIC(8, 6) DEFAULT NULL, ADD birthday DATE DEFAULT NULL, ADD vdate DATE DEFAULT   
  NULL, ADD status SMALLINT DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT  
   NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL':                                                                                                                                                           
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes         `

**Comment by aimeos** [comment]
Please read the important notices to solve this:
https://github.com/aimeos/aimeos-laravel#important-notice
