### ISSUE TITLE
enable email for send the invoice

### ISSUE THREAD

**Issue by gera-mtz** [aimeos/aimeos-laravel#159]
how to enable the function to send the invoice to email to customer after buying a product?

**Comment by aimeos** [comment]
There's a confirmation e-mail you can send if the payment status changes (job: order/email/payment). You only have to set up a cronjob that is executed regularly. For more details, please have a look at this article: https://aimeos.org/docs/Laravel/Configure_cronjobs

**Comment by gera-mtz** [comment]
just to confirm... All I have to do is just this?...

`php artisan aimeos:job order/email/payment default`

and with that send the mails?

**Comment by aimeos** [comment]
Yes, that should do the job
