### ISSUE TITLE
php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by pratik007kumarDev** [aimeos/aimeos-laravel#16]
on this comment 
$ php artisan aimeos:setup --option=setup/default/demo:1

  [MW_DB_Exception]
  SQLSTATE[HY000] [1049] Unknown database 'laravel'
following is displaying what to do pls help me

**Comment by aimeos** [comment]
Either you don't have a database "laravel" created or your settings in your .env file are not correct

**Comment by pratik007kumarDev** [comment]
i create a database "store" in my local machine 
can you help me correct my .env 
my local 
database is "store"
user id "root"
pass in  ''     -nothing

**Comment by pratik007kumarDev** [comment]
i confider .env file and it working 
thanks for helping
