### ISSUE TITLE
Not publishing migration files

### ISSUE THREAD

**Issue by darkadaptation** [aimeos/aimeos-laravel#161]
On a production site using Laravel 5.4, I can't get the migrations copied to the database/migrations folder.
I've followed every single step, added the Provider, cleared the cache, and then typed the correct command: `php artisan migrate`

Then it returns: `nothing to migrate`

There are the only files that are copied after using the `php artisan vendor:publish` command

```
Copied Directory [/vendor/aimeos/aimeos-laravel/src/views] To [/resources/views/vendor/shop]
Copied Directory [/vendor/aimeos/aimeos-laravel/public] To [/public/packages/aimeos/shop]
```

On a fresh Laravel installation (5.4 and 5.5), everything works as intended, but not on a copy of the production site which is using an updated version of Laravel 5.4.

Any thoughts ?

**Comment by aimeos** [comment]
The Aimeos package2017.07 and later don't need migrations any more. The database schema will be kept up to date by running `./artisan aimeos:setup`.

**Comment by darkadaptation** [comment]
Thanks for the answer. The documentation should probably be updated, this is not mentioned anywhere.
