### ISSUE TITLE
Production app integration

### ISSUE THREAD

**Issue by roasted-toast** [aimeos/aimeos-laravel#162]
I have finally successfully installed your package into a Laravel 5.5 application which was already using a fully functional backend with user account/subscription management, invoicing etc...

I am now wondering if it's possible to make a seamless integration in such an environment if we want to use aimeos as our shopping system?
If for example we would like to use a single backend, a single account management for both app and shop usage etc...

Is this even possible or am I wasting my time trying to figure out if it is?

Thanks

**Comment by aimeos** [comment]
You can add a common navigation in this blade template:
https://github.com/aimeos/aimeos-laravel/blob/master/src/views/jqadm/index.blade.php

If you have the same navigation in the other backends, the editors can switch between them without noticing that they are in a different part.

**Comment by darkadaptation** [comment]
Nice, thanks. And what about the invoicing ?
Can we merge the systems so we have a single invoicing for both the app and the shop?

**Comment by aimeos** [comment]
What does this mean? Can you explain in more detail?

**Comment by darkadaptation** [comment]
Our app invoices numbers are generated in a specific way, I just want to make sure the Shop's invoice numbers follow the incrementing scheme.

**Comment by aimeos** [comment]
The Aimeos order IDs are generated using a auto increment column in the `mshop_order` table. You can use any other table as long as it can store the same data (column names can be different):

https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/setup/default/schema/order.php#L253

You also need to overwrite the foreign key constraint in the `mshop_order_status` table to point to your new table.
