### ISSUE TITLE
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.siteid' in 'field list' 

### ISSUE THREAD

**Issue by VCheque** [aimeos/aimeos-laravel#164]
Hello

I'm trying to set up the admin account using this command "php artisan aimeos:account <email> --admin" at terminal and i'm having that error:

 [Aimeos\MW\DB\Exception]                                                                    
  An exception occurred while executing '                                                     
  					SELECT lvu."id" AS "customer.id", lvu."siteid" AS "customer.siteid",                   
  						lvu."label" AS "customer.label", lvu."name" AS "customer.code",                       
  						lvu."company" AS "customer.company", lvu."vatid" AS "customer.vatid",                 
  						lvu."salutation" AS "customer.salutation", lvu."title" AS "customer.title",           
  						lvu."firstname" AS "customer.firstname", lvu."lastname" AS "customer.lastname",       
  						lvu."address1" AS "customer.address1", lvu."address2" AS "customer.address2",         
  						lvu."address3" AS "customer.address3", lvu."postal" AS "customer.postal",             
  						lvu."city" AS "customer.city", lvu."state" AS "customer.state",                       
  						lvu."countryid" AS "customer.countryid", lvu."langid" AS "customer.languageid",       
  						lvu."telephone" AS "customer.telephone",lvu."telefax" AS "customer.telefax",          
  						lvu."email" AS "customer.email", lvu."website" AS "customer.website",                 
  						lvu."longitude" AS "customer.longitude", lvu."latitude" AS "customer.latitude",       
  						lvu."birthday" AS "customer.birthday", lvu."status" AS "customer.status",             
  						lvu."vdate" AS "customer.dateverified", lvu."password" AS "customer.password",        
  						lvu."created_at" AS "customer.ctime", lvu."updated_at" AS "customer.mtime",           
  						lvu."editor" AS "customer.editor"                                                     
  					FROM "users" AS lvu                                                                    
  					                                                                                       
  					WHERE ( ( lvu."name" = 'admin@admin.com' ) )                                           
  					GROUP BY lvu."id", lvu."siteid", lvu."label", lvu."name", lvu."company", lvu."vatid",  
  						lvu."salutation", lvu."title", lvu."firstname", lvu."lastname",                       
  						lvu."address1", lvu."address2", lvu."address3", lvu."postal",                         
  						lvu."city", lvu."state", lvu."countryid", lvu."langid",                               
  						lvu."telephone", lvu."telefax", lvu."email", lvu."website",                           
  						lvu."longitude", lvu."latitude", lvu."birthday", lvu."status",                        
  						lvu."vdate", lvu."password", lvu."created_at", lvu."updated_at",                      
  						lvu."editor"                                                                          
  					                                                                                       
  					LIMIT 100 OFFSET 0                                                                     
  				':                                                                                      
                                                                                              
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.siteid' in 'field list' 

Thanks for the help

PS:  sorry about the mistakes, english isnt my first language

**Comment by aimeos** [comment]
You haven't executed this command first:
```./artisan aimeos:setup --option=setup/default/demo:1```

**Comment by VCheque** [comment]
It works. Thanks

I didn't see this command in the tutorial which I'm following...

**Comment by aimeos** [comment]
In the official documentation it's in the installation section after the box for adding the Laravel service provider: https://github.com/aimeos/aimeos-laravel#installation-or-update
