### ISSUE TITLE
Unable to access localhost:8000/index.php/list

### ISSUE THREAD

**Issue by alihamza1214** [aimeos/aimeos-laravel#165]
I am getting this error :
![screenshot 344](https://user-images.githubusercontent.com/17277823/31379778-ba1767bc-adc8-11e7-8089-c7c2812efa45.png)

Declaration of Aimeos\MShop\Catalog\Manager\Base::__construct(Aimeos\MShop\Context\Item\Iface $context, array $searchConfig) must be compatible with Aimeos\MShop\Common\Manager\Factory\Iface::__construct(Aimeos\MShop\Context\Item\Iface $context)

**Comment by aimeos** [comment]
Can you copy&paste the output of `composer show`?

**Comment by alihamza1214** [comment]
aimeos/ai-admin-extadm                2017.07.2  Aimeos ai-admin-extadm extension
aimeos/ai-admin-jqadm                 2017.07.12 Aimeos ai-admin-jqadm extension
aimeos/ai-admin-jsonadm               2017.07.3  Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html                 2017.07.9  Aimeos ai-client-html extension
aimeos/ai-client-jsonapi              2017.07.2  Aimeos JSON API extension
aimeos/ai-controller-frontend         2017.07.3  Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs             2017.07.2  Aimeos ai-controller-jobs extension
aimeos/ai-gettext                     2017.07.2  Aimeos Gettext extension
aimeos/ai-laravel                     2017.07.4  Laravel adapter for Aimeos web shops and e-commerce solutions
aimeos/ai-swiftmailer                 2017.07.2  SwiftMailer adapter for Aimeos web shops and e-commerce solutions
aimeos/aimeos-core                    2017.07.5  Full-featured e-commerce components for high performance online s...
aimeos/aimeos-laravel                 2017.07.4  Full-featured Laravel web shop package and e-commerce solution fo...
composer/installers                   v1.4.0     A multi-framework Composer library installer
dnoegel/php-xdg-base-dir              0.1        implementation of xdg base directory specification for php
doctrine/annotations                  v1.5.0     Docblock Annotations Parser
doctrine/cache                        v1.7.1     Caching library offering an object-oriented API for many cache ba...
doctrine/collections                  v1.5.0     Collections Abstraction library
doctrine/common                       v2.8.1     Common Library for Doctrine projects
doctrine/dbal                         v2.6.2     Database Abstraction Layer
doctrine/inflector                    v1.2.0     Common String Manipulations with regard to casing and singular/pl...
doctrine/instantiator                 1.1.0      A small, lightweight utility to instantiate objects in PHP withou...
doctrine/lexer                        v1.0.1     Base library for a lexer that can be used in Top-Down, Recursive ...
egulias/email-validator               2.1.2      A library for validating emails against several RFCs
erusev/parsedown                      1.6.3      Parser for Markdown.
fideloper/proxy                       3.3.4      Set trusted proxies for Laravel
filp/whoops                           2.1.10     php error handling for cool kids
fzaninotto/faker                      v1.7.1     Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v1.2.2     This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
laravel/framework                     v5.5.14    The Laravel Framework.
laravel/tinker                        v1.0.2     Powerful REPL for the Laravel framework.
league/flysystem                      1.0.41     Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       0.9.9      Mockery is a simple yet flexible PHP mock object framework for us...
monolog/monolog                       1.23.0     Sends your logs to files, sockets, inboxes, databases and various...
mtdowling/cron-expression             v1.2.0     CRON for PHP: Calculate the next or previous run date and determi...
myclabs/deep-copy                     1.6.1      Create deep copies (clones) of your objects
nesbot/carbon                         1.22.1     A simple API extension for DateTime.
nikic/php-parser                      v3.1.1     A PHP parser written in PHP
paragonie/random_compat               v2.0.11    PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.1      Component for reading phar.io manifest information from a PHP Arc...
phar-io/version                       1.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common       1.0.1      Common reflection classes used by phpdocumentor to reflect the co...
phpdocumentor/reflection-docblock     4.1.1      With this component, a library can provide support for annotation...
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      v1.7.2     Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             5.2.2      Library that provides collection, processing, and rendering funct...
phpunit/php-file-iterator             1.4.2      FilterIterator implementation that filters files based on a list ...
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     1.0.9      Utility class for timing
phpunit/php-token-stream              2.0.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       6.4.1      The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          4.0.4      Mock Object library for PHPUnit
psr/container                         1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1      Common interface for HTTP messages
psr/log                               1.0.2      Common interface for logging libraries
psr/simple-cache                      1.0.0      Common interfaces for simple caching
psy/psysh                             v0.8.11    An interactive shell for modern PHP.
ramsey/uuid                           3.7.1      Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122...
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator                  2.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                        2.0.1      Diff implementation
sebastian/environment                 3.1.0      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0      Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0      Snapshotting of global state
sebastian/object-enumerator           3.0.3      Traverses array structures and object graphs to enumerate all ref...
sebastian/object-reflector            1.1.1      Allows reflection of object attributes, including inherited and n...
sebastian/recursion-context           3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0      Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1      Library that helps with managing the version number of Git-hosted...
swiftmailer/swiftmailer               v6.0.2     Swiftmailer, free feature-rich PHP mailer
symfony/console                       v3.3.10    Symfony Console Component
symfony/css-selector                  v3.3.10    Symfony CssSelector Component
symfony/debug                         v3.3.10    Symfony Debug Component
symfony/event-dispatcher              v3.3.10    Symfony EventDispatcher Component
symfony/finder                        v3.3.10    Symfony Finder Component
symfony/http-foundation               v3.3.10    Symfony HttpFoundation Component
symfony/http-kernel                   v3.3.10    Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.5.0     Symfony polyfill for the Mbstring extension
symfony/process                       v3.3.10    Symfony Process Component
symfony/psr-http-message-bridge       v1.0.0     PSR HTTP message bridge
symfony/routing                       v3.3.10    Symfony Routing Component
symfony/translation                   v3.3.10    Symfony Translation Component
symfony/var-dumper                    v3.3.10    Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.0      A small library for converting tokenized PHP source code into XML...
tijsverkoyen/css-to-inline-styles     2.2.0      CssToInlineStyles is a class that enables you to convert HTML-pag...
vlucas/phpdotenv                      v2.4.0     Loads environment variables from `.env` to `getenv()`, `$_ENV` an...
webmozart/assert                      1.2.0      Assertions to validate method input/output with nice error messages.
zendframework/zend-diactoros          1.6.0      PSR HTTP Message implementations

**Comment by alihamza1214** [comment]
`aimeos/ai-admin-extadm                2017.07.2  Aimeos ai-admin-extadm extension
aimeos/ai-admin-jqadm                 2017.07.12 Aimeos ai-admin-jqadm extension
aimeos/ai-admin-jsonadm               2017.07.3  Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html                 2017.07.9  Aimeos ai-client-html extension
aimeos/ai-client-jsonapi              2017.07.2  Aimeos JSON API extension
aimeos/ai-controller-frontend         2017.07.3  Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs             2017.07.2  Aimeos ai-controller-jobs extension
aimeos/ai-gettext                     2017.07.2  Aimeos Gettext extension
aimeos/ai-laravel                     2017.07.4  Laravel adapter for Aimeos web shops and e-commerce solutions
aimeos/ai-swiftmailer                 2017.07.2  SwiftMailer adapter for Aimeos web shops and e-commerce solutions
aimeos/aimeos-core                    2017.07.5  Full-featured e-commerce components for high performance online s...
aimeos/aimeos-laravel                 2017.07.4  Full-featured Laravel web shop package and e-commerce solution fo...
composer/installers                   v1.4.0     A multi-framework Composer library installer
dnoegel/php-xdg-base-dir              0.1        implementation of xdg base directory specification for php
doctrine/annotations                  v1.5.0     Docblock Annotations Parser
doctrine/cache                        v1.7.1     Caching library offering an object-oriented API for many cache ba...
doctrine/collections                  v1.5.0     Collections Abstraction library
doctrine/common                       v2.8.1     Common Library for Doctrine projects
doctrine/dbal                         v2.6.2     Database Abstraction Layer
doctrine/inflector                    v1.2.0     Common String Manipulations with regard to casing and singular/pl...
doctrine/instantiator                 1.1.0      A small, lightweight utility to instantiate objects in PHP withou...
doctrine/lexer                        v1.0.1     Base library for a lexer that can be used in Top-Down, Recursive ...
egulias/email-validator               2.1.2      A library for validating emails against several RFCs
erusev/parsedown                      1.6.3      Parser for Markdown.
fideloper/proxy                       3.3.4      Set trusted proxies for Laravel
filp/whoops                           2.1.10     php error handling for cool kids
fzaninotto/faker                      v1.7.1     Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v1.2.2     This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
laravel/framework                     v5.5.14    The Laravel Framework.
laravel/tinker                        v1.0.2     Powerful REPL for the Laravel framework.
league/flysystem                      1.0.41     Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       0.9.9      Mockery is a simple yet flexible PHP mock object framework for us...
monolog/monolog                       1.23.0     Sends your logs to files, sockets, inboxes, databases and various...
mtdowling/cron-expression             v1.2.0     CRON for PHP: Calculate the next or previous run date and determi...
myclabs/deep-copy                     1.6.1      Create deep copies (clones) of your objects
nesbot/carbon                         1.22.1     A simple API extension for DateTime.
nikic/php-parser                      v3.1.1     A PHP parser written in PHP
paragonie/random_compat               v2.0.11    PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.1      Component for reading phar.io manifest information from a PHP Arc...
phar-io/version                       1.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common       1.0.1      Common reflection classes used by phpdocumentor to reflect the co...
phpdocumentor/reflection-docblock     4.1.1      With this component, a library can provide support for annotation...
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      v1.7.2     Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             5.2.2      Library that provides collection, processing, and rendering funct...
phpunit/php-file-iterator             1.4.2      FilterIterator implementation that filters files based on a list ...
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     1.0.9      Utility class for timing
phpunit/php-token-stream              2.0.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       6.4.1      The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          4.0.4      Mock Object library for PHPUnit
psr/container                         1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1      Common interface for HTTP messages
psr/log                               1.0.2      Common interface for logging libraries
psr/simple-cache                      1.0.0      Common interfaces for simple caching
psy/psysh                             v0.8.11    An interactive shell for modern PHP.
ramsey/uuid                           3.7.1      Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122...
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator                  2.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                        2.0.1      Diff implementation
sebastian/environment                 3.1.0      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.0      Provides the functionality to export PHP variables for visualization
sebastian/global-state                2.0.0      Snapshotting of global state
sebastian/object-enumerator           3.0.3      Traverses array structures and object graphs to enumerate all ref...
sebastian/object-reflector            1.1.1      Allows reflection of object attributes, including inherited and n...
sebastian/recursion-context           3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0      Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1      Library that helps with managing the version number of Git-hosted...
swiftmailer/swiftmailer               v6.0.2     Swiftmailer, free feature-rich PHP mailer
symfony/console                       v3.3.10    Symfony Console Component
symfony/css-selector                  v3.3.10    Symfony CssSelector Component
symfony/debug                         v3.3.10    Symfony Debug Component
symfony/event-dispatcher              v3.3.10    Symfony EventDispatcher Component
symfony/finder                        v3.3.10    Symfony Finder Component
symfony/http-foundation               v3.3.10    Symfony HttpFoundation Component
symfony/http-kernel                   v3.3.10    Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.5.0     Symfony polyfill for the Mbstring extension
symfony/process                       v3.3.10    Symfony Process Component
symfony/psr-http-message-bridge       v1.0.0     PSR HTTP message bridge
symfony/routing                       v3.3.10    Symfony Routing Component
symfony/translation                   v3.3.10    Symfony Translation Component
symfony/var-dumper                    v3.3.10    Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.0      A small library for converting tokenized PHP source code into XML...
tijsverkoyen/css-to-inline-styles     2.2.0      CssToInlineStyles is a class that enables you to convert HTML-pag...
vlucas/phpdotenv                      v2.4.0     Loads environment variables from `.env` to `getenv()`, `$_ENV` an...
webmozart/assert                      1.2.0      Assertions to validate method input/output with nice error messages.
zendframework/zend-diactoros          1.6.0      PSR HTTP Message implementations`

**Comment by aimeos** [comment]
PHP 7 is buggy until 7.0.4 so please update your PHP version. Then it will work as expected.
