### ISSUE TITLE
Undefined offset: 2

### ISSUE THREAD

**Issue by colinbarstow** [aimeos/aimeos-laravel#166]
Hey guys,

Just running this straight out the box, Laravel 5.5 and when i go to view a product, i get this "Undefined offset: 2" error.

It points to this:

<?php foreach( $productItem->getRefItems( 'product', 'default', 'default' ) as $prodid => $product ) : ?>
                            <?php if( $productItems[$prodid] ) { $product = $productItems[$prodid]; } ?>

I don't want to start messing around with things, if it's something really obvious. 

Cheers, Colin

**Comment by aimeos** [comment]
Thanks for the hint! The problem has been fixed in the latest version. Please execute `composer update` to get the new release
