### ISSUE TITLE
finding products with Persian name does not work properly in catalog suggest search filter?

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#167]
i use aimeos laravel 2017.7 version
my locale is `fa` and i add products with label, names, description and ... in Persian characters,
for example the name of one of my product is "رژ لب جامد لنسور سری 3D شماره D06", but when i search "جامد لنسور" find it but when i search "رژ لب" nothing will be found, and even when i paste the name of whole product in filter search input nothing will be found,
my database character set is ` utf8 -- UTF-8 Unicode`, and my database collation is `utf8_persian_ci`,
how can i fix this issue?

**Comment by aimeos** [comment]
Aimeos uses the MySQL full text search and the result is totally depending on how MySQL tokenizes the text. Maybe you can tweak the MySQL configuration a bit to improve the results.

Alternatively, you can change the text index manager to "Standard" instead of "MySQL":
https://github.com/aimeos/aimeos-laravel/blob/master/src/default.php#L348
But be aware that this won't use any index when searching products and will be extremely slow if you have more then a few hundred products.

**Comment by aimeos** [comment]
Changing the text manager alone doesn't work. Please use these settings in `config/shop.php`:
```
	'mshop' => [
		'index' => array(
			'manager' => array(
				'name' => 'Standard',
				'attribute' => array(
					'name' => 'Standard',
				),
				'catalog' => array(
					'name' => 'Standard',
				),
				'price' => array(
					'name' => 'Standard',
				),
				'text' => array(
					'name' => 'Standard',
				),
			),
		),
	],
```
But be aware that this is slow!

**Comment by parsester** [comment]
this way is slow, even i set this settings but it does not work,
What should I do in the database؟

**Comment by aimeos** [comment]
Hard to say, we have to experience with MySQL and Persian. The MySQL implementation uses full text search in boolean mode (https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/MySQL.php#L40) while the standard implementation uses string POSITION (https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php#L39).

You can try using "utf8mb4" as encoding in the database and for the connection:
- https://github.com/aimeos/aimeos/blob/master/config/database.php#L50
- https://github.com/aimeos/aimeos/blob/master/config/shop.php#L39

If you can create a SQL statement that finds your texts in the database, we can solve the issue.

**Comment by parsester** [comment]
@aimeos 

`SELECT
*
FROM
mshop_product
WHERE
mshop_product.label LIKE '%ویسکوز%'`
or
`SELECT
*
FROM
mshop_text
WHERE
mshop_text.label LIKE '%ویسکوز%';`

in above, i create a SQL statement that get my request to search a product that have a persian label,
with this SQL statement i get my products  successfully

**Comment by aimeos** [comment]
Does this also work?
`SELECT * FROM mshop_index_text WHERE POSITION( 'ویسکوز' IN value ) > 0`

**Comment by parsester** [comment]
**Yes, this SQL statement also works**
and returns to me, 2 records from table `mshop_index_text` with type name and long and domain product

**Comment by aimeos** [comment]
OK, than the text search must also work if you use the "Standard" implementation of the index text manager in your `config/shop.php` configuration file:
```
	'mshop' => array(
		'index' => array(
			'manager' => array(
				'name' => 'MySQL',
				'attribute' => array(
					'name' => 'MySQL',
				),
				'catalog' => array(
					'name' => 'MySQL',
				),
				'price' => array(
					'name' => 'MySQL',
				),
				'text' => array(
					'name' => 'Standard',
				),
			),
		),
	),
```
