### ISSUE TITLE
Views not published

### ISSUE THREAD

**Issue by roasted-toast** [aimeos/aimeos-laravel#169]
I'm probably missing something but the views are not being published anymore on a Laravel 5.4 project.

`
	/**
	 * Bootstrap the application events.
	 *
	 * @return void
	 */
	public function boot()
	{
		$ds = DIRECTORY_SEPARATOR;
		$basedir = dirname( dirname( __DIR__ ) ) . $ds;
		$this->loadRoutesFrom( $basedir . 'routes.php' );
		$this->loadViewsFrom( $basedir . 'views', 'shop' );
		$this->publishes( [ $basedir . 'config/shop.php' => config_path( 'shop.php' ) ], 'config' );
		$this->publishes( [ dirname( $basedir ) . $ds . 'public' => public_path( 'packages/aimeos/shop' ) ], 'public' );
	}
`

Views are loaded but not published with the `php artisan vendor:publish` function. Is this being done somewhere else?

**Comment by roasted-toast** [comment]
Adding:
`
$this->publishes(array(
$basedir.'views' => base_path('resources/views/vendor/shop'),
), 'views');
`
To the `boot` function in `vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/ShopServiceProvider.php` solves the problem.

**Comment by aimeos** [comment]
Views don't have to be published since at least Laravel 5.3. Instead, the views from the package are used directly. You can still copy template files to the `resources/views/vendor/shop` directory if you want to overwrite them but you shouldn't do that by default and only for those where you need to replace the original files! Otherwise, you won't get updated files for e.g. the admin interface and you will wonder why things are not working as expected.

**Comment by roasted-toast** [comment]
Yep, i needed to replace some things.

Another question, how can i give back end permissions to an existing user ?
Using the `php artisan aimeos:account` tool works for a new account and the user can sign in and get to the back end, but when I try to insert `aimeos:account` inside `editor` column for the existing user, I get redirected to the "login" after trying to reach the aimeos admin interface.

**Comment by aimeos** [comment]
In the customer panel of the admin interface you can assign groups to users. The "Editor", "Administrator" and "Super user" groups allow admin interface access

**Comment by roasted-toast** [comment]
Any informations on what's being done behind the scene?
May be useful for future purposes.

**Comment by aimeos** [comment]
Groups are linked through the `users_list` table with the entries in teh `mshop_customer_groups` table. Inside the JQAdm controller actions, permissions are checked using the Laravel authorization infrastructure and you've added the code for checking permissions in `app/Providers/AuthServiceProvider.php`

**Comment by roasted-toast** [comment]
I don't know if I should open a new issue or not but how can I use different columns names?

The Laravel app I'm working has a thousand of active users and it uses `first_name` and `last_name` columns inside the `users` table but aimeos uses `firstname` and `lastname`.

Records are displayed with empty cells:

![selection_004](https://user-images.githubusercontent.com/10560326/31607275-02ab03a6-b26c-11e7-99ea-8d04d9a9dc0b.png)

**Comment by aimeos** [comment]
You can change the SQL statements for the different column names. Please create a new topic at https://aimeos.org/help/laravel-package-f18/
