### ISSUE TITLE
Error while artian clear compiled 

### ISSUE THREAD

**Issue by ZengineAlex** [aimeos/aimeos-laravel#17]
Hey guys,

I have a new problem/question:

I'm trying to run the shop on a shared hosting server and after I run composer update, I get an error relating to the php artisan clear-compiled command:

' file_input_contents(/.../bootstrap/cache/services.json): failed to open stream: No such file or directory'

Do you have any idea why this error appears/why the file is not existing? Have I maybe done something wrong or forgotten something during the setup ?

Kind regards,

ZengineAlex

**Comment by aimeos** [comment]
Maybe the directory belongs to the web server and you can't write into it?
If that doesn't help, please ask in the Laravel forums what else could be the reason.

**Comment by ZengineAlex** [comment]
Yeah, it was a Laravel Issue. Fixes now!

**Comment by aimeos** [comment]
What was the problem?
