### ISSUE TITLE
Customizing Theme

### ISSUE THREAD

**Issue by mobiblunt** [aimeos/aimeos-laravel#170]
I have been trying to customize the default theme on the application. the documentation guide is outdated and refers to older versions of the project. most structures have been updated and even file locations have changed. I need to know the most recent method of customizing the theme. what is the most efficient method to use my use templates and also on-board other developers to maintain this project as it doesn't follow normal Laravel conventions i am familiar with.

**Comment by aimeos** [comment]
Have you read https://aimeos.org/docs/Developers#Frontend
For CSS and Javascript, you can use the Laravel way to integrate your own files. For the templates you need to create an Aimeos extension (https://aimeos.org/docs/Developers/Create_an_extension) using the extension builder and place your modified templates into the same folder structure of your extension.  If you want to use Blade templates, you have to configure them: https://aimeos.org/docs/Laravel/Use_Blade_templates

**Comment by mobiblunt** [comment]
Thank you. This explained previously unclear facts to me.

**Comment by sabrine-mg** [comment]
hi , i need to change the template i had create my own extension but i didn't know when and how include it so plz i need some help.

**Comment by aimeos** [comment]
Add your extension to the ./<app>/ext/ directory
