### ISSUE TITLE
Display Products For A Category FrontEnd

### ISSUE THREAD

**Issue by worla** [aimeos/aimeos-laravel#171]
Hi, i have setup a new installation of Aimeos( https://github.com/aimeos/aimeos-laravel ). I have logged in to the backend and have added 5 categories and products to each of the categories created. I want to at the frontend display the products for each category when i click on the five different links i have created. 

Fairly new to Laravel, i can create a basic CRUD application. 

Your help is very much appreciated.
Thank you.

**Comment by aimeos** [comment]
Does the category tree and the list view at the /list page not what you want? You can rearrange/remove parts and style the page completely

**Comment by worla** [comment]
Okay, great, I have seen what you are talking about, but how do i change the page completely?

**Comment by aimeos** [comment]
Have you read the articles how to adapt the theme and the frontend?
https://aimeos.org/docs/Laravel#Themes

**Comment by worla** [comment]
hi, thanks for the help, i am reading and learning a lot. where can i find the subclients under aimeos_nav to show only the CATEGORIES and not the ATTRIBUTES. And also style the categories to look like in the website in this link ( http://www.betts.com.au/ ). 

![capture](https://user-images.githubusercontent.com/8648008/32052700-fd7fd914-ba50-11e7-82bf-2424ab0f0980.PNG)

I am sure others will find this useful as well.

Thank you.

**Comment by aimeos** [comment]
https://aimeos.org/docs/Configuration/Core/client/html/Adapt_catalog_filter
