### ISSUE TITLE
Change Currency to IDR Indonesia.

### ISSUE THREAD

**Issue by fahreza007** [aimeos/aimeos-laravel#172]
I change currency to IDR indonesia, But price not appear in list just "price:default". I try change to rusian ruble working. what wrong? please help. Thank you.
![aimeos](https://user-images.githubusercontent.com/11717937/31861087-bb395de4-b750-11e7-83ce-af84db9ed367.png)

**Comment by aimeos** [comment]
Your products have no prices for IDR currency. Can you please check that?

**Comment by fahreza007** [comment]
1. This details price 
![aimeos 2 detail price](https://user-images.githubusercontent.com/11717937/31871300-662dfd04-b7dd-11e7-80ba-55d326849ddc.png)
2. Locale Setting
![aimeos locale setting](https://user-images.githubusercontent.com/11717937/31871315-805f2054-b7dd-11e7-8ce4-bce6812b72f1.png)
![aimeos price](https://user-images.githubusercontent.com/11717937/31871331-9a36d68e-b7dd-11e7-8c3f-461e0851945b.jpg)
3. Inspect from google chrome front-end list
![aimeos 3](https://user-images.githubusercontent.com/11717937/31871345-b113e87e-b7dd-11e7-9b5b-57203fbe79f7.png)
4. Just price not appear. 
User : PHP Version 5.6.30
Laravel 5.2
Aimeos version 2016.10

Please help thank you

**Comment by aimeos** [comment]
Prices are displayed and hidden via CSS. Maybe some CSS styling from your own CSS interferes?

**Comment by fahreza007** [comment]
This package New Install, and no one adding css or edit css. Just new installation so i add new currency IDR and language Indonesian to change currency for my country.

**Comment by aimeos** [comment]
Aimeos 2016.10 LTS is superseded by 2017.10 LTS. 2016.10 is supported by the Aimeos company only if you have a support contract. As Laravel 5.2 isn't supported either any more, you should first upgrade to Laravel 5.5 and Aimeos 2017.10 if possible

**Comment by fahreza007** [comment]
I try use : 
Laravel 5.4
PHP 7.1
Aimeos 2017.10
But the problem same like before, The price not appear.
Please help me.

**Comment by fahreza007** [comment]
This Problem Done. 
Sorry Brother this is My fault.
Thank you for help. 
success for you
