### ISSUE TITLE
enable or config catalog stage image

### ISSUE THREAD

**Issue by jgmartinez** [aimeos/aimeos-laravel#173]
when I enter a category, an image appears above the bread crumb. I found it as "catalog-stage-image". How can I change or modify the image in the administration part? or I can only by code? There will also be a way to enable it in the index (catalog / list)?

**Comment by aimeos** [comment]
In the catalog panel, you can add an image to each category. This is shown above the product list for this category. For search results (and the default list view is a search result), this doesn't work. Instead, you have to configure a default category that should be displayed using:
https://aimeos.org/docs/Configuration/Core/client/html/catalog/lists/catid-default

**Comment by jgmartinez** [comment]
I speak of the index page if there is way to put the "catalog image"?
