### ISSUE TITLE
reduce the number of products listed in the index

### ISSUE THREAD

**Issue by jgmartinez** [aimeos/aimeos-laravel#174]
in the index, the total of products to be shown are 48 products, and I want to reduce it to at least 24 products, how can I reduce the number of products shown on the main page?

**Comment by aimeos** [comment]
Use this config setting: https://aimeos.org/docs/Configuration/Core/client/html/catalog/lists/size

For questions about how to adapt Aimeos, please use the forum: https://aimeos.org/help

**Comment by jgmartinez** [comment]
thanks
