### ISSUE TITLE
Composer Update error

### ISSUE THREAD

**Issue by worla** [aimeos/aimeos-laravel#175]
Hi, I am trying to install aimeos, anytime i try `composer update`. this is what shows up. I tried looking up the error but i cant find anything related to it. 

 Which provider or tag's files would you like to publish?:
  [0 ] Publish files from all providers and tags listed below
  [1 ] Provider: Aimeos\Shop\ShopServiceProvider
  [2 ] Provider: Fideloper\Proxy\TrustedProxyServiceProvider
  [3 ] Provider: Illuminate\Mail\MailServiceProvider
  [4 ] Provider: Illuminate\Notifications\NotificationServiceProvider
  [5 ] Provider: Illuminate\Pagination\PaginationServiceProvider
  [6 ] Tag: config
  [7 ] Tag: laravel-mail
  [8 ] Tag: laravel-notifications
  [9 ] Tag: laravel-pagination
  [10] Tag: public
 >

  [Symfony\Component\Console\Exception\RuntimeException]
  Aborted

Script php artisan vendor:publish handling the post-update-cmd event returned with error code 1

**Comment by aimeos** [comment]
Platform, Laravel version, Aimeos version?

**Comment by worla** [comment]
hello, i found the solution.

i deleted this part of this code and run it manually 
`"php artisan vendor:publish",` 

`"prefer-stable": true,
    "minimum-stability": "dev",
    "require": {
        "aimeos/aimeos-laravel": "~2017.10",
        ...
    },
    "scripts": {
        ...
        "post-update-cmd": [
            "php artisan vendor:publish --tag=public --force",
            "php artisan vendor:publish",
            "php artisan migrate",
            ...
        ]
    }`

Thanks for the help, but i am getting another error ( `A non-recoverable error occured`  ) after i have added more categories to the already existing home category

Windows 10,
Laravel Framework 5.5.19,
aimeos "2017.10.5"

**Comment by aimeos** [comment]
Did you add something to the target field that is not a route name?

**Comment by worla** [comment]
The error was because i added the a **Target URL**  whiles adding a new category.
Thanks for the help. i really appreciate it.
