### ISSUE TITLE
exception in product searchItems for get search product stocklevel

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#177]
according to [Developers/Library/Managing items](https://aimeos.org/docs/Developers/Library/Managing_items#Conditions)
i tried to search products that have stocklevel more than 0 
my search items code is:
`$manager = \Aimeos\MShop\Factory::createManager( $context, 'product' );`
    `$search = $manager->createSearch();`
    `$expr = array(`
        `$search->compare( '==', 'product.type.code', 'selection' ),`
        `$search->compare( '>', 'product.stock.stocklevel', 0 ),`
        `$search->compare( '>', 'product.stock.warehouse.code', 'default' ),`
    `);`
    `$search->setConditions( $search->combine( '&&', $expr  ) );`
    `$items = $manager->searchItems( $search );`

but  i encountered a `Aimeos \ MW \ Common \ Exception` that say
 `Aimeos \ MW \ Common \ Exception`
`Invalid name "product.stock.stocklevel"`

What is wrong?

![2017-11-12_0-12-45](https://user-images.githubusercontent.com/16049244/32693317-4090618e-c73e-11e7-86d3-20e741532249.png)

**Comment by aimeos** [comment]
The stock levels have been moved to its own domain in 2017.x
Please use "stock.stocklevel" as search key instead

**Comment by parsester** [comment]
forgive but I did not understand,
1- I want to search for products that have stocklevel more than from a specific number?
How to make these two tables join together?

I have a second question
2- how i can get searchItems result with photos, prices and stocklevel and title in locale language?
 i want to get products  found with photos, prices and stocklevel and titles in locale language)
what should I do?

**Comment by aimeos** [comment]
Sorry, the documentation contained an old example with stock levels. We've fixed that.
For questions regarding using Aimeos, you should create a new topic per question in the Aimeos forum:
https://aimeos.org/help/

**Comment by parsester** [comment]
ok thanks,
in old example in documentation when we find for product with stock level more that a number, we must use
$expr = array(`
        `$search->compare( '==', 'product.type.code', 'selection' ),`
        `$search->compare( '>', 'product.stock.stocklevel', 0 ),`
        `$search->compare( '>', 'product.stock.warehouse.code', 'default' ),`
    `);`
    `$search->setConditions( $search->combine( '&&', $expr  ) );`

How do i know that in the new documentation How do I do this?

**Comment by aimeos** [comment]
Please have a look here: https://aimeos.org/help/post4946.html#p4946
