### ISSUE TITLE
Register new Users and Admins

### ISSUE THREAD

**Issue by ZengineAlex** [aimeos/aimeos-laravel#18]
Hello, I've got once again a question ;)

I've looked in the documentation but didn't find anything about what is needed to register a new User or an Admin.

How is an Admin stored in the DB? Does he have an own Model?

**Comment by aimeos** [comment]
Laravel offers user registration and login methods:
http://laravel.com/docs/5.1/authentication

But it has no means to distinguish between admin and regular users. Aimeos fills the gap in the current dev-master branch and you can find more details about this in the forum:
https://aimeos.org/help/laravel-package-f18/adapting-existing-routes-t536.html#p2125

**Comment by ZengineAlex** [comment]
Ah great, thanks! All clear for me now ! :)
