### ISSUE TITLE
Admin Redirect to Home Page

### ISSUE THREAD

**Issue by worla** [aimeos/aimeos-laravel#180]
Hi, i just downloaded aimeos and after adding  `php artisan make:auth`  and `php artisan aimeos:account --admin myemail@email.com`, I am unable to to go the http://127.0.0.1:8000/index.php/admin page after logging in. I redirects me to the home page. 

This is the second time I am installing it, the old one works perfectly.

**Comment by aimeos** [comment]
If the first one works, it's hard to say what's different in the second.
I would recommend to try again from the start.

**Comment by worla** [comment]
I did the first installation three weeks ago, i made some changes, i was wondering if something might have been added between that time and now that is causing this problem

**Comment by aimeos** [comment]
If you use 2017.10, only bugfixes have been applied

**Comment by worla** [comment]
okay, thank you very much
