### ISSUE TITLE
translate( 'client/code') not working?

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#183]
when i use translate('client/code') in my own generated extension (myextension-client-html) instead of referring to the path ('ext/myextension-client-html/client/i18n/code/fa.po') referring and use the default path ('ext/ai-client-html/client/i18n/code/fa.po')
consider that the commant translate('client') works right and reffering and use my extension path
Why is this?
what should I do in order to when i use translate('client/code') refer to my extension path?

**Comment by aimeos** [comment]
Two things:
- Generate a binary Gettext file using `msgfmt` from your `fa.po` file in the same directory
- Add `client/i18n/code` to the `i18n` section of your `manifest.php`:
```
'i18n' => array(
	'client/code' => 'client/i18n/code',
	// ...
)
