### ISSUE TITLE
error php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by bandrea96** [aimeos/aimeos-laravel#186]
After:

php artisan aimeos:setup --option=setup/default/demo:1

It gives me the following error:

In Simple.php line 97:

  An exception occurred while executing 'ALTER TABLE users ADD siteid INT DEFAULT NULL, ADD `label` VARCHAR(255) DEFAULT '' NOT NULL, ADD salutation VARCHAR(8) DEFAU
  LT '' NOT NULL, ADD company VARCHAR(100) DEFAULT '' NOT NULL, ADD vatid VARCHAR(32) DEFAULT '' NOT NULL, ADD title VARCHAR(64) DEFAULT '' NOT NULL, ADD firstname V
  ARCHAR(64) DEFAULT '' NOT NULL, ADD lastname VARCHAR(64) DEFAULT '' NOT NULL, ADD address1 VARCHAR(200) DEFAULT '' NOT NULL, ADD address2 VARCHAR(200) DEFAULT '' N
  OT NULL, ADD address3 VARCHAR(200) DEFAULT '' NOT NULL, ADD postal VARCHAR(16) DEFAULT '' NOT NULL, ADD city VARCHAR(200) DEFAULT '' NOT NULL, ADD state VARCHAR(20
  0) DEFAULT '' NOT NULL, ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT NULL, ADD telephone VARCHAR(32) DEFAULT '' NOT NULL, ADD telefax VARCHAR(
  32) DEFAULT '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude NUMERIC(8, 6) DEFAULT NULL, ADD latitude NUMERIC(8, 6) DEFAULT NULL, ADD birth
  day DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD status SMALLINT DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, CHANGE id id INT AUTO_INCR
  EMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE created_at
   created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL':

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by bandrea96** [comment]
Ok I have found that was a problem about mysql.
It would be nice  if it was written in the installation doc.

**Comment by aimeos** [comment]
Here it is: https://github.com/aimeos/aimeos-laravel#important-notice

**Comment by swapnilbarhate** [comment]
I am having the same issue you discussed.
I have followed all the steps mentioned in the documentation, still not able to solve this issue.
when i was tried this package with new project then it works fine, but when i was tried on my actual project this issue comes.. don't know how to solve, please help me.
