### ISSUE TITLE
XML Import

### ISSUE THREAD

**Issue by oktayaydogan** [aimeos/aimeos-laravel#188]
Sample: http://www.icgiyimruzgari.com.tr/xml/?R=161&K=7f18&Imgs=1&AltUrun=1&TamLink&Dislink

**Comment by aimeos** [comment]
What's your question?

**Comment by oktayaydogan** [comment]
Hello there,

I need to pull the products from other sites with the example xml. Is there a way to transfer them to the system?

**Comment by aimeos** [comment]
You have to implement you own job controller like this one:
https://github.com/aimeos/ai-controller-jobs/tree/master/controller/jobs/src/Controller/Jobs/Product/Import/Csv
