### ISSUE TITLE
Page Expired 

### ISSUE THREAD

**Issue by worla** [aimeos/aimeos-laravel#189]
Hi @aimeos , I have a local installation, while trying to use the backend and while placing an order. I get this error "The page has expired due to inactivity. 

Please refresh and try again"

![inactivity](https://user-images.githubusercontent.com/8648008/34164705-24941384-e4d2-11e7-95a7-a2c5fc53afcc.png)

**Comment by aimeos** [comment]
That page appears in Laravel 5.5, either if the session has timed out or (more likely in your case) the CSRF tokens doesn't match any more.

**Comment by worla** [comment]
Please is there any solution to this problem?

**Comment by aimeos** [comment]
Please ask in the Laravel forums because this seems deeply rooted in Laravel itself.

**Comment by worla** [comment]
Thank you.
