### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by marvoh** [aimeos/aimeos-laravel#19]
After installation, I try to run the frontend and Admin's but get the following errors respectively:

FatalErrorException in View.php line 35: Class 'Input' not found

FatalErrorException in AdminController.php line 31: Class 'Input' not found 

What could be the issue?

**Comment by swpierce** [comment]
I have the same issue. I posted in the forums but no response yet. Maybe after the holidays! :)

**Comment by marvoh** [comment]
The solution is to replace all \Input with \Request


After that got other admin errors and decided to abandon using this altogether


Sent from Outlook Mobile






On Fri, Dec 25, 2015 at 6:14 AM -0800, "swpierce" <notifications@github.com> wrote:












I have the same issue. I posted in the forums but no response yet. Maybe after the holidays! :)

**Comment by swpierce** [comment]
I've been using 1.1 for a while. It's very nice. I really like it. Upgrading to 1.2 has given me issues though. Also, don't use MySQL 5.7 as that causes different issues.

**Comment by aimeos** [comment]
Laravel up to 5.1.x and up to MySQL 5.6.x works great,  Laravel 5.2 and MySQL 5.7 doesn't yet

**Comment by wygigs** [comment]
Any idea when Laravel 5.2 will be supported?

**Comment by aimeos** [comment]
The problem was that the "Input" facade isn't available as ```\Input``` any more and only the namespaced version works in Laravel 5.2. All other facades don't need to be namespaced but we changed this for all occurrences now. The Laravel 5.2 tests run fine: https://travis-ci.org/aimeos/aimeos-laravel/builds/99097565

The changes are available in dev-master and in the Aimeos Laravel 1.2 branch (1.2.x-dev). A new version will be released this week.

**Comment by ChadTaljaardt** [comment]
Is this fully working on Laravel 5.2 yet?

**Comment by aimeos** [comment]
Yes, Laravel 5.2 is fully supported with the Aimeos Laravel 1.2.4 package.

Only MySQL 5.7 support isn't supported in this version and therefore, it won't work in the latest Homestead Vagrant box (it works if you use dev-master of the Aimeos core). This will be in the next major Aimeos Laravel release available this month.

**Comment by Christudasan** [comment]
Is this support for laravel 5.5

**Comment by aimeos** [comment]
Laravel 5.5 is fully supported by Aimeos 2017.10

**Comment by Christudasan** [comment]
Can you send me the link please

**Comment by aimeos** [comment]
https://packagist.org/packages/aimeos/aimeos-laravel

**Comment by aimeos** [comment]
You need composer: https://getcomposer.org/
Please learn using it first if you haven't used it yet. For Laravel you need it too
