### ISSUE TITLE
don't save cart items when user log out?

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#192]
the customer adds a product to cart and after that logged out, but when customer logged in again the products was not in cart and numbers of products in the cart is 0?

Why is this happening?
Should we keep the cart for a customer account and do not delete it, should we do it?

**Comment by aimeos** [comment]
The cart is session based and Laravel seems to clear the session. If you want permanent carts for customers, you can overwrite the get/setSession() methods in the order base manager:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Order/Manager/Base/Base.php#L50
