### ISSUE TITLE
Using aimeos with conekta

### ISSUE THREAD

**Issue by gera-mtz** [aimeos/aimeos-laravel#194]
Conekta (https://www.conekta.com/en) is a REST API payment for charges with credit card (e.g. paypal). How to integrate coneckta with aimeos as a payment option?

**Comment by aimeos** [comment]
The best option is to implement an Omnipay driver:
https://omnipay.thephpleague.com/
https://github.com/thephpleague/omnipay

**Comment by gera-mtz** [comment]
The problem with omnipay is the approvation for my API because it is not in the list of approved API's and I do not know how long it takes

**Comment by aimeos** [comment]
You can also implement an Aimeos payment service provider directly:
https://aimeos.org/docs/Developers/Library/Service

**Comment by gera-mtz** [comment]
OK, I'll check that and publish how it went, thanks
