### ISSUE TITLE
request /admin 404

### ISSUE THREAD

**Issue by BrianBi** [aimeos/aimeos-laravel#195]
I installed, request /list is 200 ok
but i request /admin or /login 404
5.5:
App\Providers\AuthServiceProvider
public function boot()
    {
        $this->registerPolicies();

        // 
        Gate::define('admin', function($user, $class, $roles) {
            return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );
        });
    }

please help me!thanks!

**Comment by BrianBi** [comment]
fexed this! please close

**Comment by sgwcollins** [comment]
How did you fix this?
