### ISSUE TITLE
extent of common manager does not work?

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#198]
hi,
I've completed the steps outlined in this guide([Extend managers items](https://aimeos.org/docs/Developers/Library/Extend_managers_items)) to extent Aimeos\MShop\Common\Item\Address manager but it does not work for me,
I did the same for another manager (Aimeos\MShop\Order\Manager\Base\Address) and worked but for common manager it does not work,
my configuration in mshop.php in my extention lib/custom/config folder is:

'common' => [
        'item' => [
            'address' => [
                'name' => 'MyStandard'
            ]
        ],
        'manager' => [
            'address' => [
                'name' => 'MyStandard'
            ]
        ]
    ],

The project does not refer to my file/class,

What should I do to do this?

**Comment by aimeos** [comment]
Items and base classes cannot be extended in this way because PHP/OOP doesn't allow this. You can only extend e.g. the standard customer address manager and overwrite the createItemBase() method to create your new address item class.

**Comment by parsester** [comment]
but i extent the Order and my mshop.php config is:

'order' => [
        'item' => [
            'base' => [
                'address' => [
                    'name' => 'MyStandard'
                ]
            ]
        ],
        'manager' => [
            'base' => [
                'address' => [
                    'name' => 'MyStandard'
                ]
            ]
        ],
    ],

i extend this class and it work for me, why i can not extent common controllers?
they are similar, 
i want to add 2 new fields (province_id and city_id) in toArray function of my adresses?

**Comment by aimeos** [comment]
The order item base address config is unnecessary because it's not used at all.
For the order base address manager this works because it's no abstract class like the common address base manager class. You have to overwrite the customer address manager class and it's item, then it will work.

**Comment by parsester** [comment]
@aimeos 
please read my description
in Aimeos\Client\Html\Checkout\Standard\Address setViewParams function we retrieve
`$paymentAddressItem = $orderAddressManager->createItem()->copyFrom( $item->getPaymentAddress() );`

in Aimeos\MShop\Customer\Item getPaymentAddress function we return \Aimeos\MShop\Common\Item\Address\Iface that are in custruction of customer item class

so for that i access to my added fields of customer.address i should be add function getMyField and setMyField in Common\Item\Address and then add those in toArray and fromArray of that.


@aimeos 
please read my description
in Aimeos\Client\Html\Checkout\Standard\Address setViewParams function we retrieve
`$paymentAddressItem = $orderAddressManager->createItem()->copyFrom( $item->getPaymentAddress() );`

in Aimeos\MShop\Customer\Item getPaymentAddress function we return \Aimeos\MShop\Common\Item\Address\Iface that are in custruction of customer item class

so for that i access to my added fields of customer.address i should be add function getMyField and setMyField in Common\Item\Address and then add those in toArray and fromArray of that.

as you can see in below, when i return dd( $item->getPaymentAddress() ) in setViewParams of Aimeos\Client\Html\Checkout\Standard\Address class, i can not access my custom fields in this function, because getPaymentAddress return Common\Item\Address item and i must add getMyField and setMyField in common address item

alse my custom field of customer address are also there in my order.base.order


```
Standard {#494 ▼
  -values: array:33 [▼
    "customer.id" => "4"
    "customer.siteid" => "1"
    "customer.label" => "-------@gmail.com"
    "customer.code" => "--------"
    "customer.company" => ""
    "customer.vatid" => ""
    "customer.salutation" => "mr"
    "customer.title" => ""
    "customer.firstname" => "----"
    "customer.lastname" => "-----"
    "customer.address1" => "------"
    "customer.address2" => "------"
    "customer.address3" => ""
    "customer.postal" => "1"
    "customer.city" => "------"
    "customer.state" => ""
    "customer.province_id" => "8" // my custom fields of customer address
    "customer.city_id" => "12" // my custom fields of customer address
    "customer.countryid" => "TR"
    "customer.languageid" => "-----"
    "customer.telephone" => "------"
    "customer.telefax" => ""
    "customer.email" => "------@gmail.com"
    "customer.website" => ""
    "customer.longitude" => null
    "customer.latitude" => null
    "customer.birthday" => null
    "customer.status" => "1"
    "customer.dateverified" => null
    "customer.password" => "$2y$10$I/7u/8Gbo.oV7rhs.B1qN.S.f8UdwAKsNGdFbDOVAU5jVXCnQr82W"
    "customer.ctime" => "2018-01-04 16:14:43"
    "customer.mtime" => "2018-01-06 15:56:14"
    "customer.editor" => "-----"
  ]
  -helper: Bcrypt {#492 ▶}
  -salt: "mshop"
  -addresses: []
  -billingaddress: Standard {#493 ▼
    -prefix: "customer.address."
    -values: array:1 [▶]
    -data: array:12 [▼
      "customer.address.siteid" => "1"
      "customer.address.salutation" => "mr"
      "customer.address.firstname" => "-----"
      "customer.address.lastname" => "-----"
      "customer.address.address1" => "-----"
      "customer.address.address2" => "------"
      "customer.address.postal" => "1"
      "customer.address.city" => "------"
      "customer.address.countryid" => "TR"
      "customer.address.languageid" => "----"
      "customer.address.telephone" => "-------"
      "customer.address.email" => "------@gmail.com"
    ]
    -bdata: array:3 [▶]
    -modified: false
    -prefix: "customer.address."
    -prefix: "customer.address."
  }
  -sortedAddr: true
  -data: array:33 [▶]
  -refItems: []
  -listItems: []
  -sortedLists: null
  -bdata: array:33 [▶]
  -prefix: "customer."
  -modified: false
}

```

**Comment by parsester** [comment]
@aimeos 
please read my description
in Aimeos\Client\Html\Checkout\Standard\Address setViewParams function we retrieve
`$paymentAddressItem = $orderAddressManager->createItem()->copyFrom( $item->getPaymentAddress() );`

in Aimeos\MShop\Customer\Item getPaymentAddress function we return \Aimeos\MShop\Common\Item\Address\Iface that are in custruction of customer item class

so for that i access to my added fields of customer.address i should be add function getMyField and setMyField in Common\Item\Address and then add those in toArray and fromArray of that.

as you can see in below, when i return dd( $item->getPaymentAddress() ) in setViewParams of Aimeos\Client\Html\Checkout\Standard\Address class, i can not access my custom fields in this function, because getPaymentAddress return Common\Item\Address item and i must add getMyField and setMyField in common address item

alse my custom field of customer address are also there in my order.base.order

how can i access my fields in customer address getPaymentAddress function?

```
Standard {#494 ▼
  -values: array:33 [▼
    "customer.id" => "4"
    "customer.siteid" => "1"
    "customer.label" => "-------@gmail.com"
    "customer.code" => "--------"
    "customer.company" => ""
    "customer.vatid" => ""
    "customer.salutation" => "mr"
    "customer.title" => ""
    "customer.firstname" => "----"
    "customer.lastname" => "-----"
    "customer.address1" => "------"
    "customer.address2" => "------"
    "customer.address3" => ""
    "customer.postal" => "1"
    "customer.city" => "------"
    "customer.state" => ""
    "customer.province_id" => "8" // my custom fields of customer address
    "customer.city_id" => "12" // my custom fields of customer address
    "customer.countryid" => "TR"
    "customer.languageid" => "-----"
    "customer.telephone" => "------"
    "customer.telefax" => ""
    "customer.email" => "------@gmail.com"
    "customer.website" => ""
    "customer.longitude" => null
    "customer.latitude" => null
    "customer.birthday" => null
    "customer.status" => "1"
    "customer.dateverified" => null
    "customer.password" => "$2y$10$I/7u/8Gbo.oV7rhs.B1qN.S.f8UdwAKsNGdFbDOVAU5jVXCnQr82W"
    "customer.ctime" => "2018-01-04 16:14:43"
    "customer.mtime" => "2018-01-06 15:56:14"
    "customer.editor" => "-----"
  ]
  -helper: Bcrypt {#492 ▶}
  -salt: "mshop"
  -addresses: []
  -billingaddress: Standard {#493 ▼
    -prefix: "customer.address."
    -values: array:1 [▶]
    -data: array:12 [▼
      "customer.address.siteid" => "1"
      "customer.address.salutation" => "mr"
      "customer.address.firstname" => "-----"
      "customer.address.lastname" => "-----"
      "customer.address.address1" => "-----"
      "customer.address.address2" => "------"
      "customer.address.postal" => "1"
      "customer.address.city" => "------"
      "customer.address.countryid" => "TR"
      "customer.address.languageid" => "----"
      "customer.address.telephone" => "-------"
      "customer.address.email" => "------@gmail.com"
    ]
    -bdata: array:3 [▶]
    -modified: false
    -prefix: "customer.address."
    -prefix: "customer.address."
  }
  -sortedAddr: true
  -data: array:33 [▶]
  -refItems: []
  -listItems: []
  -sortedLists: null
  -bdata: array:33 [▶]
  -prefix: "customer."
  -modified: false
}

**Comment by aimeos** [comment]
No, you should do that in your own customer address item that extends from `\Aimeos\MShop\Customer\Item\Address\Standard`:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Customer/Item/Address/Standard.php

`\Aimeos\MShop\Common\Item\Address\Iface` is only the base interface for type checking but not the object that is passed to the constructor: https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Customer/Item/Address/Iface.php#L19

**Comment by parsester** [comment]
@aimeos 
ok, that's right, but that does not work,
i have Item, and Manager in my own extension lib and add those in my own extension config file but the project does not use my class and do not refer to my file at all
the project just use my own myext/lib/custom/src/MShop/Customer/Manager/MyStandard but don't use:
myext/lib/custom/src/MShop/Customer/Item/MyStandard
myext/lib/custom/src/MShop/Customer/Item/Address/MyStandard
myext/lib/custom/src/MShop/Customer/Manager/Address/MyStandard

for Order extend everything all right but for customer i encounter the problem I mentioned above

here is my config file:
```
return [
    'customer' => [
        'item' => [
            'name' => 'MyStandard',
            'address' => [
                'name' => 'MyStandard'
            ]
        ],
        'manager' => [
            'name' => 'MyStandard',
            'address' => [
                'name' => 'MyStandard'
            ]
        ]  
    ],
    'order' => [
        'item' => [
            'base' => [
                'address' => [
                    'name' => 'MyStandard'
                ]
            ]
        ],
        'manager' => [
            'base' => [
                'address' => [
                    'name' => 'MyStandard'
                ]
            ]
        ],
    ],
];
```

**Comment by aimeos** [comment]
To use your item classes e.g. the customer item class, you have to implement this in your customer manager class:
```
	protected function createItemBase( array $values = [], array $listItems = [], array $refItems = [], array $addresses = [] )
	{
		if( !isset( $this->addressManager ) ) {
			$this->addressManager = $this->getObject()->getSubManager( 'address' );
		}
		$helper = $this->getPasswordHelper();
		$address = $this->addressManager->createItem();
		return new \Aimeos\MShop\Customer\Item\MyStandard( $address, $values, $listItems, $refItems, $this->salt, $helper, $addresses );
	}
```
Same for your customer address item. Using your own customer address manager implementation should work with that configuration but like said, you have to implement there createItemBase() too.
