### ISSUE TITLE
Disable language in settings causes 404

### ISSUE THREAD

**Issue by qvotaxon** [aimeos/aimeos-laravel#199]
When disabling a language in the jqadm backend, I'm getting redirected to a 404 page. The problem is that when a user disables a language by selecting the "status" option and setting it to disabled, and then clicks the save button, the user is redirected to the following url /admin/default/jqadm/get/locale/language/en (when choosing English of course). Though the correct URL is /admin/default/jqadm/get/locale/language/EN. The capitalized locale abbreviation in the end is not correctly set when pressing the save button.

I'm using version aimeos/aimeos-laravel - 2017.10.

**Comment by aimeos** [comment]
Thank you for your bug report! The problem has been fixed and new releases are available for dev-master, 2018.01 and 2017.10. Could you please run `composer update` and check if the problem is gone now?

**Comment by qvotaxon** [comment]
The issue is resolved. Thanks you very much for the quick work!
