### ISSUE TITLE
Can't open the URL

### ISSUE THREAD

**Issue by Polinicles** [aimeos/aimeos-laravel#2]
Hi!

I've followed all your instructions until:
http://aimeos.org/docs/Laravel/Test_installation

But when I try to get the URL: http:/localhost/index.php/list (or "/admin") doesn't work!
The root directory is set correctly so...

Best Regards

**Comment by aimeos** [comment]
Is the ./public directory of your Laravel application the  document root of your VHost?

If you are using PHP 5.4 and above you can execute the following command in the root directory of your Laravel application for testing by using the integrated PHP web server:

```php -S 127.0.0.1:8000 -t public```

The you should be able to open ```http://localhost:8000/index.php/list``` or ```http://localhost:8000/index.php/admin``` (the port 8000 is important in this case)

**Comment by Polinicles** [comment]
Thank you for your answer. I tried with the integrated PHP web server and now it works!

**Comment by aimeos** [comment]
Great! :-)
