### ISSUE TITLE
Upload to Cpanel

### ISSUE THREAD

**Issue by fahreza007** [aimeos/aimeos-laravel#200]
Why my project laravel aimeos if i upload to cpanel the routes not work?
if i open http://cobacoba.test123.org/list the page just show "404 Not Found The resource requested could not be found on this server!"
But in my localhost there is no problem, everything work.
i use aimeos 2017
laravel 5.4
![aimeos](https://user-images.githubusercontent.com/11717937/35080840-c0cf09a2-fc42-11e7-9f16-54f493e6a7ca.png)

can help me?
thank you

**Comment by aimeos** [comment]
Don't know. We have no experience with CPanel

**Comment by 1SA1** [comment]
copy and paste this in you .htacess file
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
