### ISSUE TITLE
add exceptions in process method for a new payment option

### ISSUE THREAD

**Issue by astagerardomartinez** [aimeos/aimeos-laravel#202]
In my payment method creation, i use an API REST for send info and receives the confirm of tha pay. How can I send a custom error message (text only) along with the status change (such as "\Aimeos\MShop\Order\Item\Base::PAY_UNFINISHED") within the process method?

**Comment by aimeos** [comment]
If you want to display something to the user, you should thrown an `\Aimeos\MShop\Service\Exception`. To be able to translate it, use
```
$i18n = $this->getContext()->getI18n();
throw new \Aimeos\MShop\Service\Exception( sprintf( $i18n->dt( 'Status %1$s', $status ) ) );
```
