### ISSUE TITLE
array beconfig add options in type select

### ISSUE THREAD

**Issue by astagerardomartinez** [aimeos/aimeos-laravel#203]
Using the guide "Define config" (https://aimeos.org/docs/Developers/Library/Service/Define_configuration), to add a configuration of type "select", I need to add the different values of type "option" for this field. How can I add them?

**Comment by astagerardomartinez** [comment]
What I just understand is that I can add the values inside the "default" key, how should I add them? Array  type?

**Comment by aimeos** [comment]
Yes, add them as a PHP array with key/value pairs

**Comment by astagerardomartinez** [comment]
Can you give me an example?

**Comment by aimeos** [comment]
```
'default' => [
    'key1' => 'Label 1',
    'key2' => 'Label 2',
    'key3' => 'Label 3',
],
```
or if you need to add the options dynamically:
`$this->feconfig['<yourcode>']['default'] = [...];`

'key1', 'key2' or 'key3' is then passed back and stored.

**Comment by astagerardomartinez** [comment]
Thank you very much! By way of finishing the "issue", a recommendation. I would like that example to put it inside the aimeos developers page to give a better guide on how to use them.

**Comment by aimeos** [comment]
Done: https://aimeos.org/docs/Developers/Library/Service/Define_configuration#Define_the_configuration
