### ISSUE TITLE
called client/html/checkout/standard/address/states for a new service provider

### ISSUE THREAD

**Issue by astagerardomartinez** [aimeos/aimeos-laravel#204]
For a new payment provider, I call the elements of "getAddress(\Aimeos\MShop\Order\Item\Base\Address\Base::TYPE_PAYMENT)" but the "order.base.address.state" only returns the id of the state, how can I extract the array "client/html/checkout/standard/address/states" to get the name from "\Aimeos\MShop\Service\Provider\Payment\newProvider.php"?

**Comment by aimeos** [comment]
Use `$context->getConfig()->get( 'client/html/checkout/standard/address/states', [] );` to retrieve configuration values. It's not perfect because you are accessing data from a layer above the one that contains your code.

**Comment by astagerardomartinez** [comment]
Thanks :)
