### ISSUE TITLE
error php artisan aimeos:setup

### ISSUE THREAD

**Issue by swapnilbarhate** [aimeos/aimeos-laravel#206]
After executing "php artisan aimeos:setup" command it will throws an error called,

An exception occurred while executing 'ALTER TABLE users ADD siteid INT DEF
 AULT NULL, ADD `label` VARCHAR(255) DEFAULT '' NOT NULL, ADD salutation VAR
 CHAR(8) DEFAULT '' NOT NULL, ADD company VARCHAR(100) DEFAULT '' NOT NULL,
 ADD vatid VARCHAR(32) DEFAULT '' NOT NULL, ADD title VARCHAR(64) DEFAULT ''
  NOT NULL, ADD firstname VARCHAR(64) DEFAULT '' NOT NULL, ADD lastname VARC
 HAR(64) DEFAULT '' NOT NULL, ADD address1 VARCHAR(200) DEFAULT '' NOT NULL,
  ADD address2 VARCHAR(200) DEFAULT '' NOT NULL, ADD address3 VARCHAR(200) D
 EFAULT '' NOT NULL, ADD postal VARCHAR(16) DEFAULT '' NOT NULL, ADD city VA
 RCHAR(200) DEFAULT '' NOT NULL, ADD state VARCHAR(200) DEFAULT '' NOT NULL,
  ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT NULL, AD
 D telephone VARCHAR(32) DEFAULT '' NOT NULL, ADD telefax VARCHAR(32) DEFAUL
 T '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude
 NUMERIC(8, 6) DEFAULT NULL, ADD latitude NUMERIC(8, 6) DEFAULT NULL, ADD bi
 rthday DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD status SMALLINT
 DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, CHANGE id
 id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHA
 NGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255
 ) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_
 at updated_at DATETIME NOT NULL':

 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
 oo long; max key length is 767 bytes

when i was tried this package with new project its working fine, But with some existing project it's throws the exception, please help me to solve this issue.

**Comment by aimeos** [comment]
Please read the important notice for new MySQL versions:
https://github.com/aimeos/aimeos-laravel#important-notice
