### ISSUE TITLE
Can order more items then available when using options

### ISSUE THREAD

**Issue by gdgroot** [aimeos/aimeos-laravel#207]
Hi,

While checking out the package i noticed that i could order more items then available .
I found that this was possible due to adding different options to the item.

I tested it with the demo selection article located at : detail/4/Demo_selection_article/1
It had 3 items in stock.
When selecting an option for it i could order three more and there were two extra options available.
When finishing the order it was reflected in the admin sections as -6 in stock.

**Comment by aimeos** [comment]
Thank you for your bug report! You are right, the stock level was checked incorrectly if the same article was added with different option. This has been fixed and new versions released.

Can you please execute "composer update" and confirm that the problem has been solved?

**Comment by gdgroot** [comment]
Yes it has been fixed. 

Cheers!
