### ISSUE TITLE
http://localhost:8000/index.php/adminredirects to nothing

### ISSUE THREAD

**Issue by matthewton** [aimeos/aimeos-laravel#208]
I just configured the aimeos according to the readme file. 
it seems the frontend is OK, but the backend http://127.0.0.1:8000/index.php/admin will redirect me to http://127.0.0.1:8000/index.php/login, and it gives page not found!
I searched the documents, but still have no idea where the route is configured!

**Comment by aimeos** [comment]
Did you created the Laravel auth infrastructure by executing `php artisan make:auth`?

**Comment by matthewton** [comment]
No, I thought aimeos has configured the login somewhere unknown!
Now I got it. thanks!  suggest you make this step clear in the readme.md...

**Comment by aimeos** [comment]
OK, we made this more explicit now: https://github.com/aimeos/aimeos-laravel#admin
