### ISSUE TITLE
  SQLSTATE[42000]: Syntax error or access violation while migration

### ISSUE THREAD

**Issue by hengsoheak** [aimeos/aimeos-laravel#209]
I'm using this environment

MAC OSX
MAPP 5.6.35
I got below error 

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes                                                                                                                 
<img width="1621" alt="screen shot 2018-02-21 at 9 36 45 am" src="https://user-images.githubusercontent.com/812528/36460413-c5f46f72-16ea-11e8-8a11-3fdf07999e5f.png">

**Comment by aimeos** [comment]
Please read the important notices: https://github.com/aimeos/aimeos-laravel#important-notice
