### ISSUE TITLE
blank page after install and setup

### ISSUE THREAD

**Issue by Dontorpedo** [aimeos/aimeos-laravel#21]
Hello,

I run Laravel / Aimeos on a shared hoster with composer, after working trough all the installation steps provided in the documentation and adapting the welcome.blade.php file.

only the bootstrap files are loading, the @yields aimeos parts seems not to work, how can i solve this?

thank you!

**Comment by aimeos** [comment]
What version do you use?

Can you please have a look into the "storage/log/laravel.log" and your Apache error log file? There you might find more information why your environment has this problems.

**Comment by Dontorpedo** [comment]
Hi,

I use Laravel 5.1.11, PHP Version 5.6

in the apache error log is no laravel related entry.. also in laravel.log no problems..

**Comment by aimeos** [comment]
Do you have an URL where we can check the installation?

**Comment by Dontorpedo** [comment]
http://market.creadiv.at/

**Comment by aimeos** [comment]
Looks awful because the CSS files are not found but in principle it works :-)
http://market.creadiv.at/list

**Comment by Dontorpedo** [comment]
oh, maybe i misunderstood something, thought it will be something like your demopage.. with working pages and categories.. and i also cant login.. i sorry, iam a newbe to laravel/aimeos

**Comment by aimeos** [comment]
Yes (but without the start page) if you set it up exactly like described in the installation steps (https://aimeos.org/docs/Laravel#Installation, in principle the same as in the GibHub Readme).

Authentication must be set up in Laravel: https://laravel.com/docs/5.1/authentication

**Comment by Dontorpedo** [comment]
ok, i think i found the error:

file_exists(): open_basedir restriction in effect. File(/.../vendor/aimeos/aimeos-core/ext/.gitignore/manifest.php) is not within the allowed path(s): (/../data/web/e36889/phpsession:/data/web/e36889/phptmp:/tmp:/usr/bin)


what does it mean? do you know how i can solve it?

**Comment by aimeos** [comment]
All files and directories of your Laravel application must be within the paths that are configured with open_basedir. The document root of your VHost needs to point to the ```./public``` directory of your Laravel application

**Comment by Zabanya** [comment]
Had this problem too, I wanted so that index.php are gone while all .js / .css / .jpg still pointing to public/.

**Comment by Mathias88** [comment]
Laravel 4

# Group Writable (Group, User Writable)
$ sudo chmod -R gu+w app/storage

# World-writable (Group, User, Other Writable)
$ sudo chmod -R guo+w app/storage

Laravel 5

# Group Writable (Group, User Writable)
$ sudo chmod -R gu+w storage

# World-writable (Group, User, Other Writable)
$ sudo chmod -R guo+w storage

**Comment by arthurtarasov** [comment]
> oh, maybe i misunderstood something, thought it will be something like your demopage.. with working pages and categories.. and i also cant login.. sorry, iam a newbie to laravel/aimeos

After reading the installation instructions, this is exactly what I thought too. I spent a few hours trying to figure out why nothing shows up even though everything seemed to work.

I think it is worth mentioning in the instructions that the demo comes with an empty front page.

**Comment by aimeos** [comment]
A hint has been added to the readme and the documentation:
https://aimeos.org/docs/Laravel/Test_installation
