### ISSUE TITLE
i want to redirect application url's. can someone help me with file location of this URL Changes?

### ISSUE THREAD

**Issue by vignesh-subash** [aimeos/aimeos-laravel#211]
**For hosting purpose** 
I want to redirect the Front End URL **http:localhost:8000/index.php/list** to **http:localhost:8000**
**http://localhost:8000/index.php/admin** to **http://localhost:8000/admin**

**Comment by aimeos** [comment]
You can overwrite the named "/list" route in your `./routes/web.php` to
```
	Route::match( array( 'GET', 'POST' ), '/', array(
		'as' => 'aimeos_shop_list',
		'uses' => 'Aimeos\Shop\Controller\CatalogController@listAction'
	));
```

The later one is available automatically due to the .htaccess file in the public folder (Apache only).
