### ISSUE TITLE
media uploads not working for XLS, XLSX, CSV, ZIP etc.

### ISSUE THREAD

**Issue by michalfeher** [aimeos/aimeos-laravel#212]
When I try to attach new media to product (type download) and select the file with one of these extension, the uploaded file is stored without extension. this is the case also in DB.

![image](https://user-images.githubusercontent.com/7691204/37146926-84ffce4e-22c5-11e8-82a7-7b2f07f32a10.png)

![image](https://user-images.githubusercontent.com/7691204/37146902-67da72ec-22c5-11e8-9b8b-4c9c6af1e695.png)

If I manually add an extension to the uploaded file, then it opens the file correctly.

This works for image extensions like jpg, png and also for PDF.

**Comment by aimeos** [comment]
The problem is that this is a fixed list: https://github.com/aimeos/aimeos-core/blob/master/controller/common/src/Controller/Common/Media/Standard.php#L222

We will make it configurable

**Comment by aimeos** [comment]
It's configurable now and these are the extensions known by default:
https://github.com/aimeos/aimeos-core/blob/master/controller/common/config/controller.php
