### ISSUE TITLE
Pincode with every product for list only particular product related to that Pincode

### ISSUE THREAD

**Issue by anshul977** [aimeos/aimeos-laravel#213]
Hi Team,

I want to know is there any plugin or any code to check the availability of every product for a particular pin code. 
I want to list the product to the user from they belongs.

**Comment by aimeos** [comment]
Do you want to limit products to certain customer groups?

**Comment by anshul977** [comment]
No dear, I want to all the product But that product according to pin code availability.

Suppose Customer is registered after that customer will enter his postel code. I will list those products which can deliver to that postel code.

**Comment by aimeos** [comment]
You could attach the postal codes to the product as attributes or as properties. Then you can add a few lines of code that filters the products according to the postal code of th customer adddress.

**Comment by anshul977** [comment]
1. Can tell me where to add that code. Because i am using your jsonapi not customizing any thing?
2. Can you give me the API URL to register the user ?
3. When i am adding a user from the Aimeos backend it is going in user table not customer table. Is it working like this?

**Comment by aimeos** [comment]
1.) In the admin interface, you can add new attributes with the postal code (create a new attribute type "postal" first"). Then, add the appropriate postal codes to the products in the product panel. You get the available postal attributes using the "attribute" endpoint (https://aimeos.org/docs/Developers/Client/JSONAPI/Retrieve_metadata). They will be indexed and you can filter by the attribute IDs (https://aimeos.org/docs/Developers/Client/JSONAPI/Retrieve_product_catalog#Attributes_for_faceted_search).

2.) Use the "customer" endpoint for this (https://aimeos.org/docs/Developers/Client/JSONAPI/Retrieve_metadata)

3.) Yes, in Laravel context the "users" table is used for customer accounts

**Comment by anshul977** [comment]
Thanks team for the above reply.

I am facing one more issue. 

Suppose my URL is http://33.22.66.11/laravel/public

But in the http://33.22.66.11/laravel/public/admin all the sub url start from  http://33.22.66.11/admin

I am not able to open any page and not able to do any activity

Can you tell me where to change this URL ?

**Comment by aimeos** [comment]
Laravel requires the `./public/ ` directory to be the document root of you virtual host. Otherwise, it doesn't work under all circumstances.

**Comment by anshul977** [comment]
As you guide me to add the attribute for solve my filter problem. But i am facing one problem. I created a attribute and added that in characteristics of the product. It is showing in admin but changes does not reflect in the mshop_index_attribute. Can guide me some more ?

**Comment by aimeos** [comment]
Is it added to the mshop_index_attribute table if you run `php artisan aimeos:jobs index/rebuild`?

**Comment by anshul977** [comment]
I am not running any thing. I installed the aimeos on my localhost and upload it on the server and after that doing the attribute things.

**Comment by anshul977** [comment]
OK fine. But confirm me one thing. My attributes added after run ```php artisan aimeos:jobs index/rebuild```. In future, I have to run this command every time to add the attributes ?

**Comment by aimeos** [comment]
Did you add the product attribute via the JSON admin API?

**Comment by anshul977** [comment]
No, I am adding the attributes via Aimeos Admin panel.

**Comment by anshul977** [comment]
When i am creating a product with image. It is loading continuously. But Product didn't add. If I added a product without image it is working fine.

After add the product i am trying to add the image but getting the error message-: 
```Call to undefined function Aimeos\MW\Media\Image\imagecreatefromstring()```

**Comment by aimeos** [comment]
Which Aimeos version are you using?

**Comment by anshul977** [comment]
I am using the latest version of Aimeos and downloaded using the composer.

**Comment by aimeos** [comment]
Please post the output of `composer show`

**Comment by anshul977** [comment]
D:\xampp\htdocs\myshop>composer show
aimeos/ai-admin-extadm                2017.10.1  Aimeos ai-admin-extadm ...
aimeos/ai-admin-jqadm                 2017.10.20 Aimeos ai-admin-jqadm e...
aimeos/ai-admin-jsonadm               2017.10.5  Aimeos ai-admin-jsonadm...
aimeos/ai-client-html                 2017.10.9  Aimeos ai-client-html e...
aimeos/ai-client-jsonapi              2017.10.3  Aimeos JSON API extension
aimeos/ai-controller-frontend         2017.10.5  Aimeos ai-controller-fr...
aimeos/ai-controller-jobs             2017.10.4  Aimeos ai-controller-jo...
aimeos/ai-gettext                     2017.10.1  Aimeos Gettext extension
aimeos/ai-laravel                     2017.10.1  Laravel adapter for Aim...
aimeos/ai-swiftmailer                 2017.10.5  SwiftMailer adapter for...
aimeos/aimeos-core                    2017.10.14 Full-featured e-commerc...
aimeos/aimeos-laravel                 2017.10.4  Full-featured Laravel w...
composer/installers                   v1.5.0     A multi-framework Compo...
dnoegel/php-xdg-base-dir              0.1        implementation of xdg b...
doctrine/annotations                  v1.6.0     Docblock Annotations Pa...
doctrine/cache                        v1.7.1     Caching library offerin...
doctrine/collections                  v1.5.0     Collections Abstraction...
doctrine/common                       v2.8.1     Common Library for Doct...
doctrine/dbal                         v2.6.3     Database Abstraction Layer
doctrine/inflector                    v1.3.0     Common String Manipulat...
doctrine/instantiator                 1.1.0      A small, lightweight ut...
doctrine/lexer                        v1.0.1     Base library for a lexe...
dragonmantank/cron-expression         v2.0.0     CRON for PHP: Calculate...
egulias/email-validator               2.1.3      A library for validatin...
erusev/parsedown                      1.6.4      Parser for Markdown.
fideloper/proxy                       4.0.0      Set trusted proxies for...
filp/whoops                           2.1.14     php error handling for ...
fzaninotto/faker                      v1.7.1     Faker is a PHP library ...
hamcrest/hamcrest-php                 v2.0.0     This is the PHP port of...
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
laravel/framework                     v5.6.6     The Laravel Framework.
laravel/tinker                        v1.0.3     Powerful REPL for the L...
league/flysystem                      1.0.42     Filesystem abstraction:...
mockery/mockery                       1.0        Mockery is a simple yet...
monolog/monolog                       1.23.0     Sends your logs to file...
myclabs/deep-copy                     1.7.0      Create deep copies (clo...
nesbot/carbon                         1.22.1     A simple API extension ...
nikic/php-parser                      v3.1.4     A PHP parser written in...
nunomaduro/collision                  v1.1.22    Cli error handling for ...
paragonie/random_compat               v2.0.11    PHP 5.x polyfill for ra...
phar-io/manifest                      1.0.1      Component for reading p...
phar-io/version                       1.0.1      Library for handling ve...
phpdocumentor/reflection-common       1.0.1      Common reflection class...
phpdocumentor/reflection-docblock     4.3.0      With this component, a ...
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      1.7.5      Highly opinionated mock...
phpunit/php-code-coverage             6.0.1      Library that provides c...
phpunit/php-file-iterator             1.4.5      FilterIterator implemen...
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     2.0.0      Utility class for timing
phpunit/php-token-stream              3.0.0      Wrapper around PHP's to...
phpunit/phpunit                       7.0.2      The PHP Unit Testing fr...
phpunit/phpunit-mock-objects          6.0.1      Mock Object library for...
psr/container                         1.0.0      Common Container Interf...
psr/http-message                      1.0.1      Common interface for HT...
psr/log                               1.0.2      Common interface for lo...
psr/simple-cache                      1.0.0      Common interfaces for s...
psy/psysh                             v0.8.17    An interactive shell fo...
ramsey/uuid                           3.7.3      Formerly rhumsaa/uuid. ...
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function...
sebastian/comparator                  2.1.3      Provides the functional...
sebastian/diff                        3.0.0      Diff implementation
sebastian/environment                 3.1.0      Provides functionality ...
sebastian/exporter                    3.1.0      Provides the functional...
sebastian/global-state                2.0.0      Snapshotting of global ...
sebastian/object-enumerator           3.0.3      Traverses array structu...
sebastian/object-reflector            1.1.1      Allows reflection of ob...
sebastian/recursion-context           3.0.0      Provides functionality ...
sebastian/resource-operations         1.0.0      Provides a list of PHP ...
sebastian/version                     2.0.1      Library that helps with...
swiftmailer/swiftmailer               v6.0.2     Swiftmailer, free featu...
symfony/console                       v4.0.4     Symfony Console Component
symfony/css-selector                  v4.0.4     Symfony CssSelector Com...
symfony/debug                         v4.0.4     Symfony Debug Component
symfony/event-dispatcher              v4.0.4     Symfony EventDispatcher...
symfony/finder                        v4.0.4     Symfony Finder Component
symfony/http-foundation               v4.0.4     Symfony HttpFoundation ...
symfony/http-kernel                   v4.0.4     Symfony HttpKernel Comp...
symfony/polyfill-mbstring             v1.7.0     Symfony polyfill for th...
symfony/polyfill-php72                v1.7.0     Symfony polyfill backpo...
symfony/process                       v4.0.4     Symfony Process Component
symfony/psr-http-message-bridge       v1.0.2     PSR HTTP message bridge
symfony/routing                       v4.0.4     Symfony Routing Component
symfony/thanks                        v1.0.6     Give thanks (in the for...
symfony/translation                   v3.4.4     Symfony Translation Com...
symfony/var-dumper                    v4.0.4     Symfony mechanism for e...
theseer/tokenizer                     1.1.0      A small library for con...
tijsverkoyen/css-to-inline-styles     2.2.1      CssToInlineStyles is a ...
vlucas/phpdotenv                      v2.4.0     Loads environment varia...
webmozart/assert                      1.3.0      Assertions to validate ...
zendframework/zend-diactoros          1.7.1      PSR HTTP Message implem...

**Comment by aimeos** [comment]
Seems like the php-gd extension isn't installed on your server because `imagecreatefromstring()` function isn't found

**Comment by anshul977** [comment]
Yes, I got this why this is not working. Thanks for helping. I will send message. If anything will be needed

**Comment by anshul977** [comment]
Can i get the attribute list according to the attribute type. Because this will easier to filter the data and compare the attribute lable with my value.?
Currently I am using this API to list the attributes
http://localhost/jsonapi/attribute

**Comment by aimeos** [comment]
I will close the issue because it gets confusing due to the many different topics. Please ask questions regarding usage in the Aimeos forum: https://aimeos.org/help/
