### ISSUE TITLE
Invalid size provided for UploadedFile; must be an int

### ISSUE THREAD

**Issue by kyriecarlos** [aimeos/aimeos-laravel#214]
I'm having issue on updating the image of product. Whenever i add multiple photo to the item this error shows.
![screencapture-localhost-9090-admin-default-jqadm-save-product-2018-03-15-01_03_03](https://user-images.githubusercontent.com/1561090/37418221-b3f94b90-27ec-11e8-86d2-c8652598f6f6.png)

**Comment by aimeos** [comment]
Which Aimeos version are you using?

**Comment by aimeos** [comment]
@kyriecarlos Can you post a screenshot with the "Files: image" section opened when the error occurs?

**Comment by aimeos** [comment]
@kyriecarlos @quyentv88 Please post the output of `composer show` too

**Comment by G-Horvath** [comment]
I think there be an error in the file names what you try to upload... try to use correct filenames without special characters. (Demo: Article 3.jpg!!! ??)

**Comment by mrnaghibi** [comment]
Increase upload_max_filesize in php.ini
;Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 16M
