### ISSUE TITLE
Question: How to get user group on frontend?

### ISSUE THREAD

**Issue by MurKit** [aimeos/aimeos-laravel#215]
I know I should use something like this `{{ Auth::user()->isAdmin }}`

So I created this method in User.php
```
public function isAdmin()
    {
        return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $this->id, "admin" );
    }
```

Of course it doesn't work. How to do it properly?

**Comment by aimeos** [comment]
Can you try checkUserGroup() instead which needs the Laravel user object? Also pass `["admin", "super"] ` as parameter because you are most probably a super user
