### ISSUE TITLE
How to use a sub in the layout template

### ISSUE THREAD

**Issue by randaleWatson** [aimeos/aimeos-laravel#216]
Good day I am having the hardest time trying to use the search component by itself. I am using ver 2017.10. What I am trying to do is extract the products search feature and use it by itself in my navigation section (navbar) in my app.blade.php file of with out having to  use the the 'aimeos_nav' section. Since the category and attributes filter lives there as well. I have been able to mimic this by hiding the other two section and using css the show and re position sub elements for the two hidden sections but I don't think this is the right thing to do. I have enjoyed working with your ecommerce framework.

**Comment by aimeos** [comment]
If you can wait till next Tuesday, the new stable 2018.04 release will contain additional components for tree, search and attribute facets too.

**Comment by randaleWatson** [comment]
That sounds awesome. Will wait for that
