### ISSUE TITLE
Problem with routes auth

### ISSUE THREAD

**Issue by Mathias88** [aimeos/aimeos-laravel#22]
Hi,

I have this error when I access routes authorization (auth/login, auth/register. etc.)

NotFoundHttpException in RouteCollection.php line 161:

Thanks!

**Comment by GuiAfonso** [comment]
I found the same error, i thing is because the new Authentication Scaffolding for Laravel 5.2

**Comment by aimeos** [comment]
You have to set up authentication first:
https://laravel.com/docs/5.2/authentication#authentication-quickstart

**Comment by GuiAfonso** [comment]
@aimeos i already set up authentication, the problem is when i access the /login works but auth/login, auth/register or auth/logout give me the above error. Try this, go to /list and click in login link, will open auth/login page with the above error.

**Comment by aimeos** [comment]
Make sure that these routes are present in your "./app/Http/routes.php":
```
Route::group(['middleware' => ['web']], function () {

	// Authentication routes...
	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');

	// Registration routes...
	Route::get('auth/register', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');

});
```

**Comment by GuiAfonso** [comment]
@aimeos Now its working, but sometimes go to /login other to auth/login, i don't know if it is a problem. I think the best thing to do is follow the authentication setup for laravel 5.1 instead of 5.2

**Comment by Mathias88** [comment]
In the route.php I have this:

Route::group(['middleware' => 'web'], function () {
    Route::auth();
});

What I have to replace?

**Comment by aimeos** [comment]
@GuiAfonso @Mathias88 
Can you please change your "./resources/views/vendor/shop/admin/index.blade.php" file and replace the line with the "form" tag with this one:

```<form class="login" method="POST" action="{{ URL::action('Auth\AuthController@login') }}" >```

**Comment by GuiAfonso** [comment]
@aimeos i do that, but keep going to login sometimes and auth/login sometimes, i think the problem is when you do the `php artisan make:auth` in laravel 5.2 he create a app.blade.php in ./resources/views/layouts and the default login and register files from laravel extends that class, but in your tutorial you create a app.blade.php in ./resources/views that your classes extends.

**Comment by aimeos** [comment]
@GuiAfonso It seems that in Laravel 5.2 login has changed to "/login" path (formerly "/auth/login"). If you've added the routes I've posted above, this may conflict. Can you please remove those route lines again and add
```
Route::group(['middleware' => 'web'], function () {
    Route::auth();
});
```
like @Mathias88 posted? The new "action" parameter in the "form" tag posted above should now use either "/login" or "/auth/login" depending on the Laravel version. At least in my case it works.

**Comment by GuiAfonso** [comment]
@aimeos i remove those "route" lines and add the new "action" parameter in the "form" tag and i get the  NotFoundHttpException in RouteCollection.php line 161: 

My routes.php file is like that

```
Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/home', 'HomeController@index');
});
```

The error is not because `Route::get('/')` inside the `Route::group`, i already test.

**Comment by aimeos** [comment]
Are you using Laravel 5.1 or 5.2? The Route::Auth() is new in 5.2.
Can you post the stack trace of the exception?

**Comment by GuiAfonso** [comment]
I'm using Laravel 5.2, the error is:

```
in RouteCollection.php line 161
at RouteCollection->match(object(Request)) in Router.php line 802
at Router->findRoute(object(Request)) in Router.php line 670
at Router->dispatchToRoute(object(Request)) in Router.php line 654
at Router->dispatch(object(Request)) in Kernel.php line 246
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Kernel.php line 132
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 54
at require_once('/Users/guilhermino/Desktop/ecommerce/public/index.php') in server.php line 21
```

**Comment by aimeos** [comment]
Unfortunately, the stack trace isn't very helpful. I would try to restart with a clean installation and see if ```php artisan make:auth``` adds the correct route lines ("/login") before installing the Aimeos package (use dev-master to get the latest code for testing).

**Comment by GuiAfonso** [comment]
@aimeos Thanks, i will try to restart. I think the error is because the /auth/login url in app.blade.php in ./resources/views, because the application only recognize the /login not /auth/login.

Last thing, i couldn't finish the tutorial, because after `php artisan make:auth` the `php artisan aimeos:account <email> --admin` don't work, return this error: `-bash: admin@email.com: No such file or directory`

**Comment by aimeos** [comment]
You are right, the login/register/logout URLs in the example app.blade.php are static too and should be replaced by the generated URL.

**Comment by aimeos** [comment]
I've updated the example template. Can you try with the new one again?
https://github.com/aimeos/aimeos-laravel#setup

**Comment by GuiAfonso** [comment]
@aimeos now is working well, but in Admin Setup, the `aimeos:account <email> --admin` keep not working. When you have some time record a youtube video of setup, it will be very helpful.

**Comment by GuiAfonso** [comment]
@aimeos Now in Laravel 5.1 i get the follow error:

```
ErrorException in UrlGenerator.php line 590:
Action App\Http\Controllers\Auth\AuthController@login not defined. (View: /Users/guilhermino/Desktop/cover/resources/views/app.blade.php) (View: /Users/guilhermino/Desktop/cover/resources/views/app.blade.php) (View: /Users/guilhermino/Desktop/cover/resources/views/app.blade.php)
```

I think is because in tutorial we only setup the authentication in Admin Setup.

**Comment by aimeos** [comment]
OK, found some methods that are available in 5.1 and 5.2. If you update and replace the app.blade.php again, it should work now with both versions.

**Comment by aimeos** [comment]
A new version fixing the routes for 5.2 has been released

**Comment by xyraclius** [comment]
i have same problem, but in laravel 5.3

> NotFoundHttpException in RouteCollection.php line 161:
    in RouteCollection.php line 161
    at RouteCollection->match(object(Request)) in Router.php line 766
    at Router->findRoute(object(Request)) in Router.php line 621
    at Router->dispatchToRoute(object(Request)) in Router.php line 607
    at Router->dispatch(object(Request)) in Kernel.php line 268
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
    at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
    at Pipeline->then(object(Closure)) in Kernel.php line 150
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
    at Kernel->handle(object(Request)) in index.php line 53
    at require_once('C:\xampp\htdocs\laravel\public\index.php') in server.php line 21


how to solve this?

**Comment by aimeos** [comment]
Did you set up Laravel authentication?
- https://github.com/aimeos/aimeos-laravel#admin
- https://laravel.com/docs/5.3/authentication

**Comment by developerpratika** [comment]
Sir 
it tryed 
both links

    https://github.com/aimeos/aimeos-laravel#admin
    https://laravel.com/docs/5.3/authentication

i am getting same issue

**Comment by aimeos** [comment]
An new version 2017.01.2 has been released that fixes the problem and works according to the documentation.

**Comment by KristinaYordanova** [comment]
Restart local php environment - xampp, mamp or whatever you are using and it will work.

**Comment by brian-lamb-software-engineer** [comment]
Hmm, Its still not clear to me, if i use `Auth::routes();` why i still only have 
```
|        | POST     | /login                           |                  | App\Http\Controllers\Auth\LoginController@login                        | web,guest    |
|        | GET|HEAD | /login                           | login            | App\Http\Controllers\Auth\LoginController@showLoginForm                | web,guest    |
|        | POST     | /logout                          | logout           | App\Http\Controllers\Auth\LoginController@logout                       | web    
```

Do I have to manually add the register, reset routes?  Is this documented anywhere?  I thought because I used `Auth::routes()` i was good.

**Comment by aimeos** [comment]
You need to execute `php artisan make:auth` (since Laravel 5.2):
https://laravel.com/docs/5.5/authentication#included-routing
