### ISSUE TITLE
Call to undefined method Aimeos\Shop\ShopServiceProvider::loadRoutesFrom()

### ISSUE THREAD

**Issue by jsartisan** [aimeos/aimeos-laravel#222]
I am using 2017.07 version which is calling loadRoutesFrom() from boot() method.
But loadRoutesFrom() is not present in ServiceProvider of the Laravel ( 5.3 ) i am using.

Any solution to this ?

**Comment by aimeos** [comment]
Please upgrade to 2017.10 first as 2017.07 isn't supported any more.

**Comment by jsartisan** [comment]
@aimeos Let me try it.

**Comment by jsartisan** [comment]
@aimeos same issue.

![screen shot 2018-05-02 at 2 10 51 pm](https://user-images.githubusercontent.com/6636360/39513665-b4e207e4-4e12-11e8-9aee-e3cad52b65d6.png)

**Comment by jsartisan** [comment]
ServiceProvider of laravel does not have the loadRoutesFrom() method :/

**Comment by jsartisan** [comment]
@aimeos any solution for this ?

**Comment by aimeos** [comment]
According to the Laravel 5.3 documentation, the ServiceProvider class should have a `loadRoutesFrom()` method: https://laravel.com/docs/5.3/packages#routing

https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/ShopServiceProvider.php#L37
