### ISSUE TITLE
Repeated/Redundant Queries

### ISSUE THREAD

**Issue by zbmowrey** [aimeos/aimeos-laravel#224]
Zend ZRay is showing a bunch of repeated, identical queries. Haven't added any products or really done anything with the system aside from install the demo data to browse. 

**Environment:** 
Aimeos ~2018.04 (latest from composer)
Laravel 5.6.21 
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1...
Demo data populated per the how-to for install 

**Description**
page: /admin/default/jqadm/search/product?lang=en

**This query occurs identically 16 times:**
`
 SELECT mlocsi."id" AS "locale.site.id", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime", mlocsi."ctime" AS "locale.site.ctime" FROM "mshop_locale_site" AS mlocsi WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' ) GROUP BY mlocsi."id", mlocsi."code", mlocsi."label", mlocsi."config", mlocsi."status", mlocsi."editor", mlocsi."mtime", mlocsi."ctime" ORDER BY mlocsi."id" ASC LIMIT 100 OFFSET 0 
`

**As does this one, 17 times:**
`
 SELECT lvu."id" AS "customer.id", lvu."siteid" AS "customer.siteid", lvu."label" AS "customer.label", lvu."name" AS "customer.code", lvu."company" AS "customer.company", lvu."vatid" AS "customer.vatid", lvu."salutation" AS "customer.salutation", lvu."title" AS "customer.title", lvu."firstname" AS "customer.firstname", lvu."lastname" AS "customer.lastname", lvu."address1" AS "customer.address1", lvu."address2" AS "customer.address2", lvu."address3" AS "customer.address3", lvu."postal" AS "customer.postal", lvu."city" AS "customer.city", lvu."state" AS "customer.state", lvu."countryid" AS "customer.countryid", lvu."langid" AS "customer.languageid", lvu."telephone" AS "customer.telephone",lvu."telefax" AS "customer.telefax", lvu."email" AS "customer.email", lvu."website" AS "customer.website", lvu."longitude" AS "customer.longitude", lvu."latitude" AS "customer.latitude", lvu."birthday" AS "customer.birthday", lvu."status" AS "customer.status", lvu."vdate" AS "customer.dateverified", lvu."password" AS "customer.password", lvu."created_at" AS "customer.ctime", lvu."updated_at" AS "customer.mtime", lvu."editor" AS "customer.editor" FROM "users" AS lvu WHERE ( ( lvu."id" = 3 AND 1 = 1 ) ) GROUP BY lvu."id", lvu."siteid", lvu."label", lvu."name", lvu."company", lvu."vatid", lvu."salutation", lvu."title", lvu."firstname", lvu."lastname", lvu."address1", lvu."address2", lvu."address3", lvu."postal", lvu."city", lvu."state", lvu."countryid", lvu."langid", lvu."telephone", lvu."telefax", lvu."email", lvu."website", lvu."longitude", lvu."latitude", lvu."birthday", lvu."status", lvu."vdate", lvu."password", lvu."created_at", lvu."updated_at", lvu."editor" LIMIT 100 OFFSET 0 
`

**and this one, 16 times:**
`
 SELECT mlocla."id" AS "locale.language.id", mlocla."label" AS "locale.language.label", mlocla."siteid" AS "locale.language.siteid", mlocla."status" AS "locale.language.status", mlocla."mtime" AS "locale.language.mtime", mlocla."editor" AS "locale.language.editor", mlocla."ctime" AS "locale.language.ctime" FROM "mshop_locale_language" AS mlocla WHERE mlocla."status" = 1 GROUP BY mlocla."id", mlocla."label", mlocla."siteid", mlocla."status", mlocla."mtime", mlocla."editor", mlocla."ctime" ORDER BY mlocla."id" ASC LIMIT 100 OFFSET 0 
`

I'm sure there's a valid reason for pulling the data (eager loading, etc), but a single page load on the products page with the default set of demo products is running 124 queries. Just got me curious as to the economy of this approach. 

I've attached the full ZRay export for convenience. 

[Aimeos-ZRay.txt](https://github.com/aimeos/aimeos-laravel/files/1997896/Aimeos-ZRay.txt)

**Comment by aimeos** [comment]
No, there's no valid reason for this. Seems that Laravel executes those queries whenever authentication has to be checked mainly because of that code you insert in the AuthServiceProvider.php:

```
    Gate::define('admin', function($user, $class, $roles) {
        if( isset( $user->superuser ) && $user->superuser ) {
            return true;
        }
        return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );
    });
```

Do you have a better idea how to avoid calling `app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );` every time?

**Comment by zbmowrey** [comment]
Beautiful code isn't an every day thing for me. :) Every way I can think to solve this riddle is ugly; for example, the checkGroup function could grab the result and populate on the first check, then store the result in an array by key indicating the $user->id, $roles in place; future checks would see that this has already been done and return the value directly rather than run another DB query.

**Comment by bhulsman** [comment]
Maybe you can solve the issue using https://github.com/spatie/laravel-blink: "The cache only spans the length of a single request."

**Comment by aimeos** [comment]
We solved this by caching the result as @zbmowrey suggested. Blink does the same but involves an additional dependency
