### ISSUE TITLE
Multisite issue with app('Aimeos\Shop\Base\Page')

### ISSUE THREAD

**Issue by JapSeyz** [aimeos/aimeos-laravel#225]
Simply trying this: dd(app('Aimeos\Shop\Base\Page')->getSections('catalog-list')); in the HomeController on a fresh installation with multiple stores, throws the URI error.

Missing required parameters for [Route: aimeos_shop_basket] [URI: {site}/basket].

Can I make it default to using the active site?

**Comment by JapSeyz** [comment]
Same happens if I try to follow this example:

https://aimeos.org/docs/Laravel/Create_new_pages

**Comment by aimeos** [comment]
For multisite setups, you have to adapt the routing:
https://aimeos.org/docs/Laravel/Configure_multiple_shops

If you want the route to use the default site if no value for site is given, you may try to make it optional:
`['prefix' => '{site?}']`

**Comment by JapSeyz** [comment]
Ah okay, thank you.
