### ISSUE TITLE
Admin for multiple sites

### ISSUE THREAD

**Issue by JapSeyz** [aimeos/aimeos-laravel#226]
Running the command: `php artisan aimeos:account email@domain.com --admin` works wonderfully for the default site.

If you then setup an additional site, for example `php artisan aimeos:setup sg`

You can't access that sites admin page, even though you're an admin. And if you run  `php artisan aimeos:account email@domain.com --admin sg` you lose access to the default site, and gains access to SG.

Can I add the site, instead of replacing it, for the admin account?

**Comment by JapSeyz** [comment]
Ah okay, what's the difference between moderator, admin and super?

I'm thinking super is just global admin, but moderator and admin are both applied to single sites only, so where do they differ?

**Comment by aimeos** [comment]
Admins have full access to all panels, editors only to some of them. You can adapt the panels both have access to by overwriting the configuration and you can even add more groups with different rights:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/config/admin/jqadm/resource.php
