### ISSUE TITLE
php artisan aimeos:setup - No such file or directory

### ISSUE THREAD

**Issue by frafra85** [aimeos/aimeos-laravel#228]
i have correctly change charset and collection how is reported in "important Notice" of documentation but i have this error when i lunch **php artisan aimeos:setup**

` Aimeos\MW\DB\Exception  : An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

  at /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Manager/DBAL.php:99
     95|                        return array_pop( $this->connections[$name] );
     96| 
     97|                }
     98|                catch( \Exception $e ) {
  >  99|                        throw new \Aimeos\MW\DB\Exception( $e->getMessage(), $e->getCode() );
    100|                }
    101|        }
    102| 
    103| 

  Exception trace:

  1   Aimeos\MW\DB\Manager\DBAL::acquire("db")
      /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php:66

  2   Aimeos\MW\Setup\Manager\Multiple::__construct(Object(Aimeos\MW\DB\Manager\DBAL), [], Object(Aimeos\MShop\Context\Item\Standard))
      /Applications/MAMP/htdocs/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/SetupCommand.php:64

  Please use the argument -v to see more details.
`

Could you help me please ?

this is my **composer.json**

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "aimeos/aimeos-laravel": "^2018.04",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

This is my **php -v**:

PHP 7.2.3 (cli) (built: Mar  8 2018 10:29:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies

**Comment by aimeos** [comment]
Seems like you haven't installed PDO Mysql driver

**Comment by frafra85** [comment]
i have other laravel installation without any problem.. what can i check ?

**Comment by aimeos** [comment]
`php -m` for
```
PDO
pdo_mysql
```

**Comment by frafra85** [comment]
`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`

**Comment by aimeos** [comment]
What's your MySQL setup in your `.env` file?

**Comment by Quix0r** [comment]
For documenting and showing @frafra85 it, my `.env` looks like this (and this is not an aimeos-related issue):
````
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=33060
DB_DATABASE=aimeos_shop
DB_USERNAME=homestead
DB_PASSWORD=secret
````

**Comment by aimeos** [comment]
Sometimes, the values from .env are not passed to Aimeos in `./config/shop.php` (heavy load might be such a scenario). Then, it's better to add the parameters for database setup directly in `./config/shop.php`
