### ISSUE TITLE
the section of myaccount /client not charge plz answare me

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/aimeos-laravel#229]

**Comment by aimeos** [comment]
No details, no answer ...

**Comment by sabrine-mg** [comment]
hi when i installled aimeos every is right the shopping delivery payment and summary but the client part does it have no account no bascket
![c2](https://user-images.githubusercontent.com/38504508/41218127-e73b74c6-6d0e-11e8-9bcb-58f2ebd950a2.PNG)
![c3](https://user-images.githubusercontent.com/38504508/41218128-e758cf80-6d0e-11e8-8b77-73d7a1b1c767.PNG)

**Comment by sabrine-mg** [comment]
this what i'm talking about the client access part
this image from demo 
![c4](https://user-images.githubusercontent.com/38504508/41218343-9af2aa3e-6d0f-11e8-8c88-6d46d2a7138d.PNG)
in my project there is no login no register and no myaccount

**Comment by aimeos** [comment]
You have to add that links yourself in the app.blade.php file. Only the additional language/currency selector is from Aimeos: https://aimeos.org/docs/Laravel/Add_locale_selector

**Comment by sabrine-mg** [comment]
should i save the default name like this * <?= $aiheader['locale/select'] ?>* or what because after using these line in the corrected files there is something wrong 
![c5](https://user-images.githubusercontent.com/38504508/41221480-18006e7c-6d19-11e8-90da-aaf8be6c7443.PNG)

**Comment by aimeos** [comment]
https://aimeos.org/docs/Laravel/Add_locale_selector#Configuration
