### ISSUE TITLE
Problem with login to admin interface

### ISSUE THREAD

**Issue by abufalbo** [aimeos/aimeos-laravel#230]
Hi, 
I know that a similar problem is described here but I have not found a solution for me.
The installation was without any problems. 
I executed command `php artisan make:auth` and I created admin user and modified `App\Providers\AuthServiceProvider` according to instruction. 
But my login screen is still defaul Laravel login screen, and after login I'm redirected to /home route: 

![aimeos](https://user-images.githubusercontent.com/27345104/41207033-61cecaae-6d0e-11e8-8cd8-034da93dc029.png)

My environment:
```
php7.1.9
laravel 5.6.24
aimeos-laravel 2018.04.3
```
(I also tried older version of Aimeos - LTS version 2017.10 and also older Laravel 5.5 and result was the same) 

Thanks.

**Comment by aimeos** [comment]
Did you created your account using `php artisan aimeos:account --admin admin@admin.com`?
Instead of `--admin` you can also use `--super` or `--editor` for different access levels.

**Comment by abufalbo** [comment]
Thanks for your response. I already noticed line `if( isset( $user->superuser ) && $user->superuser ) {` and I understoodd that I need a superuser.
