### ISSUE TITLE
Cannnot login to admin with admin user

### ISSUE THREAD

**Issue by davidporos92** [aimeos/aimeos-laravel#232]
Hy,

I've installed a fresh site and created an admin user with `php artisan aimeos:account --admin <email>`. I assume that an admin user can use the administration area of the site. So I have tried to acces itt, and then get redirected to the `/home` route.

I looked at the code and noticed that in the `Aimeos\Shop\Base\Support` class `checkUserGroup` function you are comparing the user site id and the actual site id with type comparison but while the `$user->siteid` is numeric the `$siteid` is a string so this comparsion will never be true.

If you would fix this, than not only superusers will be able to use the administration are. :)

Best regards,
David.

**Comment by aimeos** [comment]
This has been fixed today with https://github.com/aimeos/aimeos-laravel/commit/bde63eb21bf09844b21f428ae68c90a906d5c6fa and will be part of the next release :-)
