### ISSUE TITLE
Documentation suggest Laravel 5.6 is not supported

### ISSUE THREAD

**Issue by Quix0r** [aimeos/aimeos-laravel#233]
The [documentation page](https://aimeos.org/docs/Laravel/Supported_versions) suggest that Laravel 5.5 is the latest version being usable. Since 2018.04 stable release this is no longer the case as it supports 5.6 as well.

I suggest updating the documentation ASAP to encourage people to use your shop system with newest Laravel version.

**Comment by aimeos** [comment]
Thanks, the docs have been updated

**Comment by Quix0r** [comment]
Also you need to update [installation steps](https://aimeos.org/docs/Laravel/Install_Aimeos) as 5.6 needs key generation: `php artisan key:generate`.

**Comment by Quix0r** [comment]
And administrative interface page, too. No mentioning of 5.6 there.

**Comment by aimeos** [comment]
Isn't `php artisan key:generate` automatically executed when you install the framework distribution?
`composer create-project --prefer-dist laravel/laravel myapp`

Where is 5.6 missing in the admin interface page?

**Comment by aimeos** [comment]
Thanks for the hint. Done now

**Comment by Quix0r** [comment]
Welcome. :-)
