### ISSUE TITLE
Upgrade blade templates

### ISSUE THREAD

**Issue by Quix0r** [aimeos/aimeos-laravel#235]
I have spotted the following things in latest release:

- usage of `{{ csrf_field() }}` which can be replaced with `@csrf` which is shorter
- usage of <?= route('bla'); ?> this is discouraged and should be replaced with {{ route('bla') }}
- usage of route-based `url()` calls, e.g. `url('/logout')`, this doesn't make sure that the URL will always work, using `route('logout')` will maybe result in same URL but it makes sure that the route (see `php artisan route:list`, column `name`, *not* `uri`) does really exist

So far these have been the first issues I have spotted.

**Comment by aimeos** [comment]
Same here. If you can create a PR with your changes, we will merge them into dev-master.

**Comment by Quix0r** [comment]
Sorry, low at hand (now at work) and at home I have family and lot's of own projects. 😢

**Comment by aimeos** [comment]
`url()` is used for login/logout because otherwise the unit tests fail

**Comment by Quix0r** [comment]
That was only an example. :-)
