### ISSUE TITLE
Error php artisan migrate

### ISSUE THREAD

**Issue by astagerardomartinez** [aimeos/aimeos-laravel#237]
In a new project of aimeos (2018.04 with laravel 5.6, php 7.2.6 and mysql 8.0.11), after configuring the composer.json and the database.php, at the moment of executing in a terminal the "composer update", in the part of "php artisan migrate" this happens to me:
![imagen](https://user-images.githubusercontent.com/29209485/42098023-512cbf92-7b7f-11e8-8d12-f4fa8b944692.png)

**Comment by aimeos** [comment]
Your database server has closed the connection. This happens in `artisan migrate`, which create the `users` tables for some reason. Maybe your connection timeout is too low. If you can't find the reason, please ask in the Laravel or MySQL forum what can be the cause
