### ISSUE TITLE
[2018.04] Mails not delivered under homestead/vagrant, yet laravel does send mails

### ISSUE THREAD

**Issue by Quix0r** [aimeos/aimeos-laravel#238]
I have setup aimeos-shop under homestead and have it successfully running on nginx, yet no mail is being sent, except the default Laravel pages, like "reset password" and so.

I have this error message in logfile:
`Error while trying to send payment e-mail for order ID "1" and status "4": Cannot send message without a sender address`

My `.env` file:
````
APP_NAME=Aimeos-Shop
APP_ENV=local
APP_KEY=base64:xxxxxxxxxxxx
APP_DEBUG=true
APP_URL=https://aimeos-shop.local

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=33060
DB_DATABASE=aimeos_shop
DB_USERNAME=homestead
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=sendmail
MAIL_HOST=127.0.0.1
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=noreply@aimeos-shop.local
MAIL_FROM_NAME="Shop"

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
````
And I changed one setting in `config/mail.php`:
`'sendmail' => '/usr/sbin/sendmail -t',`

So this means the above mail settings work (Laravel's default reset-password feature sends out mail) but Aimeos seem to ignore it.

I also find it strange that this message pops up as it comes from `AbstractSmtpTransport` but I was never using it (tried `mail` as `MAIL_DRIVER` before).

**Comment by Quix0r** [comment]
And I have setup all 3 cron jobs.

**Comment by aimeos** [comment]
The sender name/email isn't used from the .env file in your version. That will be the case in the next one released in the next days but up to now, you have to add these lines in your `./config/shop` file yourself:
https://github.com/aimeos/aimeos-laravel/blob/master/src/config/shop.php#L52

For sending e-mails, Aimeos uses the SwiftMailer instance provided by Laravel:
`app( 'mailer' )->getSwiftMailer()`

**Comment by Quix0r** [comment]
Thank you. I have changed it now. I'm testing it now.

I also had to set client->html->common->content->baseurl to `env('APP_URL')` to have it respect the setting from `.env`. Maybe worth changing the shop.php file?

**Comment by Quix0r** [comment]
I have the following "wrapper" scripts (Mittwald accepts parameter lists until 96 characters):

_minutely.sh_:
````
#!/bin/sh

./artisan $@ aimeos:jobs "order/export/csv order/email/delivery order/email/payment order/service/delivery subscription/export/csv customer/email/account" || exit 255
````

_hourly.sh_:
````
#!/bin/sh

./artisan $@ aimeos:jobs "customer/email/watch order/cleanup/unfinished order/service/async order/service/payment" || exit 255
````

_daily.sh_:
````
#!/bin/sh

./artisan $@ aimeos:jobs "admin/cache admin/log order/cleanup/unpaid product/import/csv product/bought index/rebuild index/optimize product/export/sitemap subscription/process/begin subscription/process/renew subscription/process/end" || exit 255

# @TODO Defect jobs:
./artisan $@ aimeos:jobs "catalog/import/csv"
````
The last one imports the whole `.env` file as products. Maybe another bug that needs tracking in other ticket. However, still no mail goes out. Under which circumstances when will mails be sent? When I order some items, I guess?

**Comment by aimeos** [comment]
Do you get the e-mails now after you've removed the importer from the `artisan aimeos:jobs` command?

**Comment by Quix0r** [comment]
Yes, still no mail goes out.

**Comment by Quix0r** [comment]
Thank you, will test it when time permits.

**Comment by Quix0r** [comment]
Jupp,  **when** permits. Please show patience ... Currently (I'm home now) my employer has an other more pressing project for me.

OT: Are you based in Germany? Is it possible to buy "premium" or business support? Maybe I can convince them.

**Comment by aimeos** [comment]
You can buy business support from the Aimeos company (based in Hamburg): https://aimeos.com/support/

**Comment by aimeos** [comment]
2018.4 is long gone and unsupported since the release of 2018.10 LTS. We close this isse now :)
