### ISSUE TITLE
Attributes issues

### ISSUE THREAD

**Issue by sabrine-mg** [aimeos/aimeos-laravel#241]
**Environment**
1. Version (e.g. 2017.10)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sabrine-mg** [comment]
when i remove the default attributes of demo in admin dashboard the adding of a new project will be impossible and this is the issue shown 
![attribute](https://user-images.githubusercontent.com/38504508/43007426-27b4a372-8bed-11e8-924f-28fa594e7274.PNG)

**Comment by aimeos** [comment]
You must not remove the attribute of type "price" and code "custom"

**Comment by sabrine-mg** [comment]
but i don't have any attribute i remove all of them
![attribute2](https://user-images.githubusercontent.com/38504508/43008742-aa0f3230-8bf0-11e8-958f-2fc8f1919e3f.PNG)
my adding attributre section look like this i'm just remove the demo attribute and add this one plz help me

**Comment by aimeos** [comment]
Create one with type "price" and code "custom". Then it will work again.
