### ISSUE TITLE
Laravel migrations being not executed while running installation instruction

### ISSUE THREAD

**Issue by anantaramdas** [aimeos/aimeos-laravel#242]
**Environment**
1. Version 2018.07
2. Operating system (Windows)

**Describe the bug**
Laravel migrations being not executed while running installation instruction

**To Reproduce**
1. Follow the instruction in Setup section
2. Open site
3. See error:
```
An exception occurred while executing ' SELECT mlocsi."id" AS "locale.site.id", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime", mlocsi."ctime" AS "locale.site.ctime" FROM "mshop_locale_site" AS mlocsi WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' ) GROUP BY mlocsi."id", mlocsi."code", mlocsi."label", mlocsi."config", mlocsi."status", mlocsi."editor", mlocsi."mtime", mlocsi."ctime" ORDER BY mlocsi."id" ASC LIMIT 100 OFFSET 0 ': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myshop.mshop_locale_site' doesn't exist
```

**Expected behavior**
See shop

**Additional context**
I see that routes are woking however the migrations are not placed in right directory. I searched for them in package itself and idid not found. Maybe instruction is missing some additional step to follow?

**Comment by anantaramdas** [comment]
Okay what is missing is you should run 
```php artisan aimeos:setup```
before
```php artisan aimeos:setup --option=setup/default/demo:1```
Then everything working as expected

**Comment by aimeos** [comment]
`php artisan aimeos:setup --option=setup/default/demo:1` does the same as `php artisan aimeos:setup` but adds also the demo data. Did `php artisan aimeos:setup --option=setup/default/demo:1` failed for some reason?

**Comment by gaurav-chaudhari** [comment]
Thank You...

**Comment by anish1988** [comment]
Thnak you @anantaramdas  It also works for me
