### ISSUE TITLE
Changes in installation-instructions

### ISSUE THREAD

**Issue by xitara** [aimeos/aimeos-laravel#244]
Hi,
I think, this code

`"@php artisan vendor:publish --tag=public --force",
"@php artisan migrate",`

is better than

`"php artisan vendor:publish --tag=public --force",
"php artisan migrate",`

'cause I'm using php7.0 as standard and when I call composer with php7.2 the scripts in composer.json will use the same php-version. now your scripts use the php-standard-version on the system

**Comment by aimeos** [comment]
Yes, you are right. Can you create a pull request that updated the README.md file?

**Comment by aimeos** [comment]
Fixed
