### ISSUE TITLE
 Aimeos\MW\DB\Exception

### ISSUE THREAD

**Issue by MubarakSULAYMAN** [aimeos/aimeos-laravel#245]
I am trying to install aimeos for the first time using Laravel 5.6.* with xampp-win32-7.2.5 and got this error...

C:\xampp\htdocs\laravel_projects\sitedemo>php artisan aimeos:setup --option=setup/default/demo:1
Initializing or updating the Aimeos database tables for site "default"
Changing typeid of mshop_attribute table                              OK
Adding code column to mshop_catalog                                   OK
Renaming product warehouse table                                      OK
Adding ctime/mtime/user columns to tables
  Checking table "mshop_attribute" for column "mtime":                OK
  Checking table "mshop_attribute" for column "ctime":                OK
  Checking table "mshop_attribute" for column "editor":               OK
  Checking table "mshop_attribute_list" for column "mtime":           OK
  Checking table "mshop_attribute_list" for column "ctime":           OK
  Checking table "mshop_attribute_list" for column "editor":          OK
  Checking table "mshop_attribute_list_type" for column "mtime":      OK
  Checking table "mshop_attribute_list_type" for column "ctime":      OK
  Checking table "mshop_attribute_list_type" for column "editor":     OK
  Checking table "mshop_attribute_type" for column "mtime":           OK
  Checking table "mshop_attribute_type" for column "ctime":           OK
  Checking table "mshop_attribute_type" for column "editor":          OK
  Checking table "mshop_customer" for column "editor":                OK
  Checking table "mshop_customer_address" for column "mtime":         OK
  Checking table "mshop_customer_address" for column "ctime":         OK
  Checking table "mshop_customer_address" for column "editor":        OK
  Checking table "mshop_customer_list" for column "mtime":            OK
  Checking table "mshop_customer_list" for column "ctime":            OK
  Checking table "mshop_customer_list" for column "editor":           OK
  Checking table "mshop_customer_list_type" for column "mtime":       OK
  Checking table "mshop_customer_list_type" for column "ctime":       OK
  Checking table "mshop_customer_list_type" for column "editor":      OK
  Checking table "mshop_locale" for column "mtime":                   OK
  Checking table "mshop_locale" for column "ctime":                   OK
  Checking table "mshop_locale" for column "editor":                  OK
  Checking table "mshop_locale_currency" for column "mtime":          OK
  Checking table "mshop_locale_currency" for column "ctime":          OK
  Checking table "mshop_locale_currency" for column "editor":         OK
  Checking table "mshop_locale_language" for column "mtime":          OK
  Checking table "mshop_locale_language" for column "ctime":          OK
  Checking table "mshop_locale_language" for column "editor":         OK
  Checking table "mshop_locale_site" for column "mtime":              OK
  Checking table "mshop_locale_site" for column "ctime":              OK
  Checking table "mshop_locale_site" for column "editor":             OK
Renaming catalog index tables to index
  Checking table "mshop_catalog_index_attribute"                      OK
  Checking table "mshop_catalog_index_catalog"                        OK
  Checking table "mshop_catalog_index_price"                          OK
  Checking table "mshop_catalog_index_text"                           OK
Changing "domain" columns
  Checking table "mshop_attribute":                                   OK
  Checking table "mshop_attribute_type":                              OK
  Checking table "mshop_attribute_list_type":                         OK
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_catalog":                                     OK
  Checking table "mshop_catalog_list_type":                           OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_catalog_suggest":                             OK
  Checking table "mshop_media_type":                                  OK
  Checking table "mshop_media_list_type":                             OK
  Checking table "mshop_media":                                       OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_plugin":                                      OK
  Checking table "mshop_price":                                       OK
  Checking table "mshop_product_type":                                OK
  Checking table "mshop_product_list_type":                           OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_product_tag_type":                            OK
  Checking table "mshop_service":                                     OK
  Checking table "mshop_service_list_type":                           OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_text_type":                                   OK
  Checking table "mshop_text":                                        OK
  Checking table "mshop_text_list_type":                              OK
  Checking table "mshop_text_list":                                   OK
Adding mtime, ctime, editor columns to coupon tables
  Checking table "mshop_coupon"
  Checking table "mshop_coupon_code"
  Checking table "mshop_order_base_coupon"
Migrating configuration keys in coupon tables                         OK
Adding status column to all list tables
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_customer_list":                               OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_price_list":                                  OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_text_list":                                   OK
Changing typeid of mshop_media table                                  OK
Adding id to order service attribute table
  Checking column "id":                                               OK
Adding siteid to order tables
  Checking table "mshop_order_base":                                  OK
  Checking table "mshop_order":                                       OK
  Checking table "mshop_order_base_address":                          OK
  Checking table "mshop_order_base_discount":                         OK
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base_product_attr":                     OK
  Checking table "mshop_order_base_service_attr":                     OK
Adding product ID to order base product table
  Checking table "mshop_order_base_product":                          OK
Adding warehouse code to order base product table                     OK
Adding service ID to order base service table
  Checking table "mshop_order_base_service":                          OK
Migrating order address salutations
  Checking table "mshop_order_base_address":                          OK
Adding tax column to order tables
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base":                                  OK
Migrating order emailflag colum to order status list
Fixing order email status values                                      OK
Migrating order flags to order status list
Migrating order type
  Checking table "mshop_order":                                       OK
Renaming order base customercode to customerid
  Checking table "mshop_order_base":                                  OK
Renaming order base product amount to quantity
  Checking table "mshop_order_base_product":                          OK
Renaming order columns pdate,ddate,dstatus,pstatus
  Checking columne "ddate":                                           OK
  Checking columne "pdate":                                           OK
  Checking columne "pstatus":                                         OK
  Checking columne "dstatus":                                         OK
Renaming order domain
  Checking table "mshop_order":                                       OK
  Checking table "mshop_order_base_address":                          OK
  Checking table "mshop_order_base_service":                          OK
Renaming shipping to costs
  Checking table "mshop_order_base":                                  OK
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
Renaming column "discount" to "rebate"
  Checking table "mshop_price"                                        OK
  Checking table "mshop_order_base"                                   OK
  Checking table "mshop_order_base_product"                           OK
  Checking table "mshop_order_base_service"                           OK
Renaming column "price" to "value"
  Checking table "mshop_price"                                        OK
Renaming shipping to costs
  Checking table "mshop_price":                                       OK
Rename "prodid" to "parentid" in table "mshop_product_stock"
  Checking column "prodid"                                            OK
Changing code from "product" to "default" in "mshop_product_type"     OK
Changing typeid column of product table
  Checking table "mshop_product":                                     OK
Migrating product property domain to "product"                        OK
Changing warehouseid column in mshop_product_stock                    OK
Rename warehouse table
  Drop "mshop_product_stock.fk_msprost_whid"                          OK
  Drop "mshop_product_stock.fk_msprost_stock_warehouseid"             OK
  Rename "mshop_product_stock.wareshouseid"                           OK
  Rename "mshop_product_stock_wareshouse"                             OK
Move stock tables to own domain
  Checking "mshop_product_stock"                                      OK
  Checking "mshop_product_stock_type"                                 OK
Adding label and status columns for product warehouse
Ensure unique codes in mshop_service                                  OK
Migrate product code in stock table
Moving product tag tables to own domain
  Moving table "mshop_product_tag_type"                               OK
  Moving table "mshop_product_tag"                                    OK
Adding label to mshop text table                                      OK
Changing typeid of mshop_text table                                   OK
Adding parentid column to catalog and locale_site
  Checking parentid column in "mshop_catalog"                         OK
  Checking parentid column in "mshop_locale_site"                     OK
Remove left over Laravel user address records                         OK
Remove left over Laravel user list records                            OK
Creating base tables
  Using schema from locale.php
    Checking table "mshop_locale_site":                               done
    Checking table "mshop_locale_language":                           done
    Checking table "mshop_locale_currency":                           done
    Checking table "mshop_locale":                                    done
  Using schema from attribute.php
    Checking table "mshop_attribute_type":                            done
    Checking table "mshop_attribute":                                 done
    Checking table "mshop_attribute_list_type":                       done
    Checking table "mshop_attribute_list":                            done
    Checking table "mshop_attribute_property_type":                   done
    Checking table "mshop_attribute_property":                        done
  Using schema from customer.php
    Checking table "mshop_customer":                                  done
    Checking table "mshop_customer_address":                          done
    Checking table "mshop_customer_list_type":                        done
    Checking table "mshop_customer_list":                             done
    Checking table "mshop_customer_group":                            done
    Checking table "mshop_customer_property_type":                    done
    Checking table "mshop_customer_property":                         done
    Checking table "users":
   Aimeos\MW\DB\Exception  : An exception occurred while executing 'ALTER TABLE users ADD superuser SMALLINT DEFAULT 0 NOT NULL, ADD siteid INT DEFAULT NULL, ADD `label` VARCHAR(255) DEFAULT '' NOT NULL, ADD name VARCHAR(255) NOT NULL, ADD salutation VARCHAR(8) DEFAULT '' NOT NULL, ADD company VARCHAR(100) DEFAULT '' NOT NULL, ADD vatid VARCHAR(32) DEFAULT '' NOT NULL, ADD title VARCHAR(64) DEFAULT '' NOT NULL, ADD lastname VARCHAR(64) DEFAULT '' NOT NULL, ADD address1 VARCHAR(200) DEFAULT '' NOT NULL, ADD address2 VARCHAR(200) DEFAULT '' NOT NULL, ADD address3 VARCHAR(200) DEFAULT '' NOT NULL, ADD postal VARCHAR(16) DEFAULT '' NOT NULL, ADD city VARCHAR(200) DEFAULT '' NOT NULL, ADD state VARCHAR(200) DEFAULT '' NOT NULL, ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid CHAR(2) DEFAULT NULL, ADD telephone VARCHAR(32) DEFAULT '' NOT NULL, ADD telefax VARCHAR(32) DEFAULT '' NOT NULL, ADD website VARCHAR(255) DEFAULT '' NOT NULL, ADD longitude NUMERIC(8, 6) DEFAULT NULL, ADD latitude NUMERIC(8, 6) DEFAULT NULL, ADD birthday DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD status SMALLINT DEFAULT 1 NOT NULL, ADD editor VARCHAR(255) DEFAULT '' NOT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT '' NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

  at C:\xampp\htdocs\laravel_projects\sitedemo\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:97
     93|                {
     94|                        try {
     95|                                $result = $this->reconnect( $e )->exec();
     96|                        } catch( \Doctrine\DBAL\DBALException $e ) {
  >  97|                                throw new \Aimeos\MW\DB\Exception( $e->getMessage(), $e->getCode() );
     98|                        }
     99|                }
    100|
    101|                return new \Aimeos\MW\DB\Result\DBAL( $result );

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      C:\xampp\htdocs\laravel_projects\sitedemo\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\Task\Base.php:127

  2   Aimeos\MW\Setup\Task\Base::executeList("db-customer")
      C:\xampp\htdocs\laravel_projects\sitedemo\vendor\aimeos\aimeos-core\lib\mshoplib\setup\TablesCreateMShop.php:194

  Please use the argument -v to see more details.

I have tried many solutions I saw online but all seems futile. Even other related solutions to "same issue" are not working for me. Kindly help out...

**Comment by MubarakSULAYMAN** [comment]
Sure, I followed it in sequence. Even restarted the whole project and had same issue.

**Comment by aimeos** [comment]
Cause error message you've gotten is the same as in the docs:
`Specified key was too long; max key length is 767 bytes`

This is related to the `utf8mb4` charset and collation Laravel is using if you use MySQL 5.6 or earlier. You must change the configuration in `config/database.php` **before** you create the tables:
```
'mysql' => [
    // ...
    'charset' => 'utf8',
    'collation' => 'utf8_unicode_ci',
    // ...
]
```

**Comment by aimeos** [comment]
You still have `utf8mb4` in your "mysql" config:
```
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
```

**Comment by MubarakSULAYMAN** [comment]
Still the same or is there anything I am to do outside the project folder?

**Comment by MubarakSULAYMAN** [comment]
I just realized I have to empty and drop my database table after those suggested changes. Did that and everything is now working well, thank you for your support.
