### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Sivar-Developer** [aimeos/aimeos-laravel#248]
![192 168 10 10_list](https://user-images.githubusercontent.com/36133259/48499152-d85c0a00-e848-11e8-891e-c6a018751c62.png)

**Comment by aimeos** [comment]
Vagrant isn't the best option to test Aimeos because it's file system layer is damn slow. As Aimeos consists of a lot of files to load, this can be the reason why you run into the PHP execution time limit. Try it on your local machine or in a docker container and it will be blazing fast.

**Comment by Sivar-Developer** [comment]
Thanks, actually I notice that vagrant is really slow , and because am windows user I can't even switch NFS, so I will try docker and I will see the results.
