### ISSUE TITLE
Email Address Changes in the Users Table during Address Step of Checkout

### ISSUE THREAD

**Issue by aievangelist** [aimeos/aimeos-laravel#254]
**Environment**
1. Version (2018.10)
2. Operating system (Ubuntu)

**Describe the bug**
The user is allowed to change his email address on the address step of the checkout process. This changes the email column of the users table which is used by Laravel to log the user in. The user cannot login with his old email/password as it has been changed in the database. This is a serious drawback/concern as users are unable to login. 

**To Reproduce**
1. Login with a user and go through the standard checkout steps.
2. On the address step, update the email address and complete the order.
3. Log off and try to login again
4. User will not be able to login with the old credentials.
5. User is able to login by giving the email address provided on the checkout page

**Expected behavior**
The users should not be allowed to make this change. Perhaps the new email should be stored in the user_addresses table?

**Screenshots**

![image](https://user-images.githubusercontent.com/39655137/51872248-938d3d00-237a-11e9-91f0-ad5d9f004a85.png)

**Comment by aievangelist** [comment]
I thought about that but wouldn't it make it impossible for new users (who
haven't signed up yet) to create an account during checkout?

**Comment by aimeos** [comment]
You should only remove the e-mail input field in the form that changes the existing billing address, not in that for a new one
