### ISSUE TITLE
new user choose a password on checkout

### ISSUE THREAD

**Issue by PopkornKevin** [aimeos/aimeos-laravel#255]
What is the best way to make a new user choose a password when going through the checkout process and selecting "create a new account"? 

I couldn't find the info and right now a password is generated but the user is not informed or sent a password notice / change link.

**Comment by aimeos** [comment]
You have to execute `php artisan aimeos:jobs customer/email/account` via a cronjob to send the e-mail for the new user account including the password to the customer:
https://aimeos.org/docs/Laravel/Configure_cronjobs#Every_minute

**Comment by PopkornKevin** [comment]
Aha great, it works now. I must have overlooked that line or seen it somewhere without that job since the cronjob every minute was there on our server but did not include that customer/email/account job.
