### ISSUE TITLE
Cant Install DB Error

### ISSUE THREAD

**Issue by virgiltu** [aimeos/aimeos-laravel#256]
**Environment**
1. Version LV 5.7
2. Operating system Windows 

**Describe the bug**
```
 Checking table "mshop_customer_list":                             done
    Checking table "mshop_customer_group":                            done
    Checking table "mshop_customer_property_type":                    done
    Checking table "mshop_customer_property":                         done
    Checking table "users":                                           done
    Checking table "users_address":
   Aimeos\MW\DB\Exception  : SQLSTATE[HY000]: General error: 1005 Can't create table 'eshop.#sql-3a04_6' (errno: 150)

  at C:\Users\VRSystem\Desktop\laravel\eShop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:91
    87|
    88|                 try {
    89|                         $result = $this->exec();
    90|                 } catch( \PDOException $e ) {
  > 91|                         throw new \Aimeos\MW\DB\Exception( $e->getMessage(), $e->getCode() );
    92|                 }
    93|
    94|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    95|         }

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      C:\Users\VRSystem\Desktop\laravel\eShop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\Task\Base.php:153

  2   Aimeos\MW\Setup\Task\Base::executeList("db-customer")
      C:\Users\VRSystem\Desktop\laravel\eShop\vendor\aimeos\aimeos-core\lib\mshoplib\setup\TablesCreateMShop.php:197

  Please use the argument -v to see more details.
```

**To Reproduce**
Try to install when running 
php artisan aimeos:setup

**Comment by virgiltu** [comment]
A bit more information. I found that when running the install and getting to migrate at step two the system comes up with nothing to migrate. Any ideas? 


php artisan vendor:publish --all
php artisan migrate

**Comment by aimeos** [comment]
Which version of the Aimeos Laravel package are you using?

**Comment by virgiltu** [comment]
I am running Laravel Framework 5.7.24 and for Aimeos I tried both Beta and Stable. 
Here are the steps I took. 

1. Installed a new Laravel app called eShop.
2. Set env parameters
3. Set the parameters per the Install of Aimeos
// I noticed that when I ran composer update the migration did only migrated the user and password tables that laravel already had. 
4. Set the providers
5. Ran php artisan vendor:publish --all     // everything got published 
6. Ran php artisan migrate    / At this point I get   "Nothing to migrate"  After looking the the code it looks like here is where the user_list_type table should be created among other ones.

**Comment by aimeos** [comment]
The Laravel migration is only used for the `users` table but `php artisan aimeos:setup` creates the rest of the Aimeos tables. The Aimeos setup tasks are more flexible than the DBAL migration when upgrading with your own extensions is required.

You have to add use the steps in exactly that order:
https://github.com/aimeos/aimeos-laravel#installation
Also don't forget any line in the composer.json file.

Last question: What database server and version are you using?

**Comment by virgiltu** [comment]
I am honestly not sure what the issue was. I just changed my computer and did the same exact steps and it works. I guess it was one of those days when nothing worked. The system works great :) Thank you for all the help.
