### ISSUE TITLE
Change ID from user foreign key

### ISSUE THREAD

**Issue by christophe-44-27** [aimeos/aimeos-laravel#259]
Hello,

I'm trying to use this package, but when i want to setup the project, i get this mysql error about problem with the fact that Aimeos try to change the foreign key related to the table users.

Is there a solution to abort this without "removing the foreign key" and create it again then ?

Regards,
Christophe

**Comment by aimeos** [comment]
Can you post the error message as it's printed on the command line?
Which Laravel and Aimeos version do you use?

**Comment by christophe-44-27** [comment]
Sure, i'm using the version 5.7 of Laravel, and  "aimeos/aimeos-laravel": "~2018.07" of Aiemos. (Not the 2018.10)

Here one of the erros :  Aimeos\MW\DB\Exception  : SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'commission_quotations_user_id_foreign' of table 'cosplayschool.commission_quotations' (The problem is repeated on all the table where user_id is used as FK).

**Comment by aimeos** [comment]
This should be fixed in 2018.10 AFAIK

**Comment by christophe-44-27** [comment]
I've juste changed the version to 2018.10 and i always the same error.

        "aimeos/aimeos-laravel": "~2018.10"
    },

![image](https://user-images.githubusercontent.com/7846034/54529991-dff70100-4957-11e9-93b4-5a9819ce9433.png)

**Comment by aimeos** [comment]
Can you please post the output of `SHOW CREATE TABLE users`?
Seems you've added a foreign key constraint that conflicts with Aimeos.

**Comment by christophe-44-27** [comment]
Sure, here it is : 

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `stripe_customer_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `is_teacher` tinyint(1) NOT NULL DEFAULT '0',
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `blocked` tinyint(1) NOT NULL DEFAULT '0',
  `public_pseudonym` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `facebook_page` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `twitter_page` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instagram_page` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `youtube_page` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `profile_picture` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_picture` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `stripe_id` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `card_brand` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_last_four` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trial_ends_at` timestamp NULL DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

**Comment by aimeos** [comment]
The problem had been fixed in the current master branch and we backported it to 2018.10 now. Can you please test in your installation by adding `"aimeos/ai-laravel": "2018.10.x-dev"` to the `require` section of your `composer.json` file, run `composer update` and then execute the setup tasks again?

**Comment by christophe-44-27** [comment]
I've tried to test it, but the class ShopServiceProvider is missing.

λ php artisan aimeos:setup --option=setup/default/demo:1

In ProviderRepository.php line 208:

  Class 'Aimeos\Shop\ShopServiceProvider' not found

Did i have to keep it into the "providers" section, in app.php ?

**Comment by aimeos** [comment]
Did you remove the `"aimeos/aimeos-laravel"` line?
You have to add the `"aimeos/ai-laravel"` line, not replacing it:
```
"aimeos/aimeos-laravel": "2018.10",
"aimeos/ai-laravel": "2018.10.x-dev"
```

**Comment by christophe-44-27** [comment]
Perfect, it's working, thanks a lot :) Do you will add the fix in the main branch of aimeos or did i have to keep the x-dev ?

**Comment by aimeos** [comment]
We tagged a new version now so you can remove the `ai-laravel` line again

**Comment by nhakhtn** [comment]
you should go to table `users` then change the type of table from MyISAM to InnoDB, then it will be solved!
