### ISSUE TITLE
Consultation on the database

### ISSUE THREAD

**Issue by Mathias88** [aimeos/aimeos-laravel#26]
Hi,
I have a question, do you not think that the product table of the database has too many columns?

Thanks!

**Comment by aimeos** [comment]
The mshop_product table contains only 12 columns and five are used by all tables:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/setup/default/schema/mysql/product.sql#L52

It contains no texts, prices, attributes and other related data. These are associated via the mshop_product_list tables.

Why do you think there are too many columns and which ones do you have in mind?

**Comment by Mathias88** [comment]
I'm sorry, I did not want to refer to the table "products". I wanted to refer to the "users" table.
In the tables "users" and "users_address" there are columns that are repeated. Which is the reason?

**Comment by aimeos** [comment]
That's a compromise for the different frameworks and applications Aimeos can be used with. Depending on the environment some user tables already store addresses, others don't. To streamline things, the billing address is therefore always stored in the user table. The user address table is necessary for delivery addresses. There can be multiple which can't be handled by the user table.

In the beginning, billing and delivery addresses were stored in one address table but this led to problems in some applications when the billing address was expected to be part of the user table.
