### ISSUE TITLE
Composer installation error

### ISSUE THREAD

**Issue by yosirn** [aimeos/aimeos-laravel#260]
I'm using Php 7.2 on ubuntu try to  install aimeos and aimeos distrubution, however the installation could'nt be completed composer throws this error:
 ```
 [RuntimeException]                                                                                                                 
  Could not scan for classes inside "ext/ai-controller-jobs//controller/common/src" which does not appear to be a file nor a folder 

```

**Comment by aimeos** [comment]
Sounds like composer couldn't download the package or didn't extract it properly. Can you redo the installation from scratch?
