### ISSUE TITLE
Doesn't shows the Images

### ISSUE THREAD

**Issue by Kingsum007** [aimeos/aimeos-laravel#261]
**Environment**
1. Version (e.g. 2017.10)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Kingsum007** [comment]
Hi this is my app hosted on shared hosting but doesn't shows the images and also doesn't accepts the Admin Email.
www.marifatteam.com

**Comment by aimeos** [comment]
Maybe not all files have been uploaded to the server?

**Comment by Kingsum007** [comment]
I have Uploaded as a zip after the extraction process I configured the .env
database credentials and then I saved a product but the product details are
in Database but not showing

**Comment by Kingsum007** [comment]
I got the problem so When I Upload the Product Images it creates public folder again and saves  the files onto public folder not in public_html/preview and public_html/files folders  can you help me to save files in the mentioned directories.

**Comment by Kingsum007** [comment]
now my domain is sheekposhan.com

**Comment by aimeos** [comment]
Did you fixed it? The `public` folder is the folder of the document root for Laravel

**Comment by Kingsum007** [comment]
I found the  solution thanks sorry that I haven't closed the thread
