### ISSUE TITLE
 Class 'Aimeos\Shop\ShopServiceProvider' not found

### ISSUE THREAD

**Issue by paluni44** [aimeos/aimeos-laravel#263]
I was trying to start, but 
Class 'Aimeos\Shop\ShopServiceProvider' not found

 
**Environment**
1. Version (e.g. 2017.10)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aimeos** [comment]
Which Laravel and Aimeos version do you use?
