### ISSUE TITLE
Problem in iis aimeos laravel

### ISSUE THREAD

**Issue by j0k3rcr2** [aimeos/aimeos-laravel#265]
**Environment**
1. php 7.2, iis 10, laravel 5.7, "aimeos/aimeos-laravel": "^2019.01",
2. Windows 10 PRO

**Describe the bug**

hello to all, install the packet of aimeos laravel but I have a problem, at the moment of consulting the catalogs it does not show them on my server mounted on iis. But if I raise the server from php artisan serve if you show them to me. Does anyone know what I'm doing wrong?

regards

**To Reproduce**
1. Go to https://github.com/aimeos/aimeos-laravel and follow the steps
2. Mount the project in iis 
3. Access localhost/admin as admin
4. Go to section Catalog
5. The catalogs are not displayed
6. See error

![1](https://user-images.githubusercontent.com/4907317/55662463-9f5d0b80-57d0-11e9-9239-7fd4c5e09653.png)
![2](https://user-images.githubusercontent.com/4907317/55662469-ab48cd80-57d0-11e9-9a71-815c9631237f.png)

**Comment by aimeos** [comment]
Seems like the JSON REST API class fails. Can you please check that in the network and console tab of the browser console?

**Comment by j0k3rcr2** [comment]
Of course, I attached the two images in the first does not work the catalogs in the second if it works.

Thank you
![dontworks](https://user-images.githubusercontent.com/4907317/55670484-37dfa400-5842-11e9-9174-9fd5f0c2c933.png)

![works](https://user-images.githubusercontent.com/4907317/55670486-3ca45800-5842-11e9-9497-5acb8b29da5f.png)

**Comment by aimeos** [comment]
In the list of IIS connections, the catalog XHR request isn't sent at all. Does the `Console` tab in the browser console shows a error?

**Comment by j0k3rcr2** [comment]
no, no mistake. Do you need more info?

regards 
![dontwork](https://user-images.githubusercontent.com/4907317/55670639-4c24a080-5844-11e9-9d8d-4f3660715294.png)

![works](https://user-images.githubusercontent.com/4907317/55670642-5ba3e980-5844-11e9-8e19-1fa746eda230.png)

**Comment by aimeos** [comment]
Can you post the response of the `jsonadm` XHR request?

**Comment by j0k3rcr2** [comment]
Of course
![Captura de pantalla (49)](https://user-images.githubusercontent.com/4907317/55670807-fc46d900-5845-11e9-8a4f-e6f148c88ec8.png)


![Captura de pantalla (50)](https://user-images.githubusercontent.com/4907317/55670810-0072f680-5846-11e9-8afc-0d118c8d5b56.png)

**Comment by aimeos** [comment]
Here's the problem: Your IIS doesn't seem to allow HTTP OPTION requests required for REST APIs

**Comment by j0k3rcr2** [comment]
Thank you very much, I was very helpful, try to configure the iis to allow the HTTP OPTIONS method, then I miss the error in the set_cookies, finally end up changing iis by nginx and is working without any problem.

Again, thank you very much.

Greetings.
