### ISSUE TITLE
aimeos/aimeos-laravel 2019.04.1 requires aimeos/aimeos-core 2019.04.*

### ISSUE THREAD

**Issue by yaser-alazem** [aimeos/aimeos-laravel#266]
I think this is a dependency package for `aimeos-laravel` 
`composer require aimeos/aimeos-core ` should solve the issue.

Also this package through an error like I have here : 
`Problem 1
    - aimeos/aimeos-core 2019.04.x-dev requires ext-curl * -> the requested PHP extension curl is missing from your system.`

Which doesn't make sense for me because I already have `curl` installed for php

composer.json : 

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "aimeos/aimeos-laravel": "~2019.04"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=public --force",
            "@php artisan migrate"
        ]
    }
}
`

**OS**: Ubuntu 18.04 

Any suggestions ?

**Comment by aimeos** [comment]
You've installed curl but not the php-curl extension

**Comment by yaser-alazem** [comment]
> You've installed curl but not the php-curl 

This was my fault, thanks for the hint .
