### ISSUE TITLE
Admin doesn't serve with multiple database

### ISSUE THREAD

**Issue by dhara15101991** [aimeos/aimeos-laravel#267]
Hello All,

First, thank you in advance!!

I have running a laravel Skelton application. I want to install the shop module on my running application but both databases should be using different with same laravel install.

I have configured config/shop.php "resources" with new database connection string but though admin is taking default laravel database.

Can you guide us on how and what we need to configure and achieve both functionality?

**Comment by aimeos** [comment]
Laravel can't use a `users` table in a different database AFAIK. You have add another `db-customer` database resource that points to your Laravel database.

**Comment by dhara15101991** [comment]
I have tried to use your provided solution but could not resolve the issue. 

Here I have attached a config/shop.php file for your reference : 

```
<?php

return [
	'resource' => [
		'db' => [
			'adapter' => config('database.connections.eshop.driver', 'mysql'),
			'host' => config('database.connections.eshop.host', '127.0.0.1'),
			'port' => config('database.connections.eshop.port', '3306'),
			'socket' => config('database.connections.eshop.unix_socket', ''),
			'database' => config('database.connections.eshop.database', 'forge'),
			'username' => config('database.connections.eshop.username', 'forge'),
			'password' => config('database.connections.eshop.password', ''),
			'stmt' => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
			'limit' => 3, // maximum number of concurrent database connections
			'defaultTableOptions' => [
					'charset' => config('database.connections.eshop.charset'),
					'collate' => config('database.connections.eshop.collation'),
			],
		],
            'db-customer' => [
			'adapter' => config('database.connections.mysql.driver', 'mysql'),
			'host' => config('database.connections.mysql.host', '127.0.0.1'),
			'port' => config('database.connections.mysql.port', '3306'),
			'socket' => config('database.connections.mysql.unix_socket', ''),
			'database' => config('database.connections.mysql.database', 'forge'),
			'username' => config('database.connections.mysql.username', 'forge'),
			'password' => config('database.connections.mysql.password', ''),
			'stmt' => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
			'limit' => 3, // maximum number of concurrent database connections
			'defaultTableOptions' => [
					'charset' => config('database.connections.mysql.charset'),
					'collate' => config('database.connections.mysql.collation'),
			],
		],
	],
];

```

Below are attach a code for config/database.php

```
<?php

return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
        ],
        'eshop' => [
            'driver' => 'mysql',
            'host' => env('DB_ESHOP_HOST', '127.0.0.1'),
            'port' => env('DB_ESHOP_PORT', '3306'),
            'database' => env('DB_ESHOP_DATABASE', 'forge'),
            'username' => env('DB_ESHOP_USERNAME', 'forge'),
            'password' => env('DB_ESHOP_PASSWORD', ''),
            'unix_socket' => env('DB_ESHOP_SOCKET', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
        ],
    ],
];
```

Now, If I try to login from frontend - It takes laravel default application database but I could not redirect to admin of aimeos.

Can you guide us on how to resolve this issue?

Once again, Thanks in advance!!

**Comment by aimeos** [comment]
We had this behavior once (not redirecting to the admin interface) after changing the configuration but after dropping and recreating the database with the new configuration, everything works fine.

**Comment by dhara15101991** [comment]
I have tried by dropping the database and recreating aimeos:setup command but still it takes default application instead of aimeos database.

**Comment by aimeos** [comment]
This is a perfectly valid setup and used by others too.

Your configuration seems to be OK if your credentials in the `.env` file are set right. You can check if you add the database credentials directly to your `./config/database.php` file.

One more thing: If APCu is enabled, the old credentials may be stored in the APCu cache. You have to clear the cache or restart the web server resp. the PHP-FPM service.

**Comment by dhara15101991** [comment]
Thanks for your quick response!!

This works now. I have faced one issue while managing two database and each has a users table. 

When I have tried to set up the admin interface using below command :

`php artisan aimeos:account <email> --admin`

facing a MySQL column not found (superuser) issue in the skelton application default database.

After investigating more deeper, I found that provided email will search from aimeos database users table and update on Skelton application default database.

So should we need to take "superuser" column in the skelton application default database?

**Comment by aimeos** [comment]
Maybe you didn't run `./artisan aimeos:setup` to add the new columns to the `users` table after you've fixed the connection settings?

**Comment by meghatops** [comment]
We have followed below setup : 

1. `git clone` or `git pull` depending on whether it&#39;s already deployed or not

2. Change permission for storage and bootstrap folder by following command

`sudo chmod -R 0777 storage/`

`sudo chmod -R 0777 bootstrap/`

3. Create .env file from .env.example

4. Generate a key by following command 

`php artisan key:generate`

5. Update database connection details in .env file for both database

6. Add vendor folder by following command

`composer install --no-interaction --no-dev`

7. Publish vendor by using following command

`php artisan vendor:publish`

8. Create a database schema by following command

`php artisan migrate`

9. Update config/shop.php file as describe above comment 

10. Run follwing command to setup eshop database(aimeos)

`php artisan aimeos:setup` 

11. Clear cache of aimeos

`php artisan aimeos:cache`

Let me know, If we have missed any step. 

As I have mentioned in above, users table is auto generate on both database.  So we are facing MySQL column not found (superuser column) when we execute following command : 

`php artisan aimeos:account <email> --admin`

**Comment by aimeos** [comment]
Then, your configuration for the "db-customer" resource is missing, wrong or isn't used. The Aimeos database must not contain the `users` table, only the default Laravel database where columns like `superuser` will be added.

**Comment by dhara15101991** [comment]
Yes but it creates `users` table in Aimeos database. Please see attached screenshot. It creates `users` table to Aimeos database although default laravel database has a `users` table. 

![database-migration](https://user-images.githubusercontent.com/14217908/57068668-0a2a3580-6cf0-11e9-8a03-d57f53607035.png)
![phpmyadmin](https://user-images.githubusercontent.com/14217908/57068904-aeac7780-6cf0-11e9-86fe-40565ee4b836.png)

**Comment by aimeos** [comment]
Please add your database settings in the `resource/db-customer` section of your `./config/shop.php` directly. There have been cases where the variables from the .env file haven't been passed correctly by Laravel. Then, delete the `users*` tables from your Aimeos database and run `./artisan aimeos:setup` again.

**Comment by dhara15101991** [comment]
Hello, @aimeos 

I tried your steps. but it creates users table when I run `./artisan aimeos:setup` this command.

**Comment by aimeos** [comment]
Can you please paste your `./config/shop.php` file (without the passwords)

**Comment by dhara15101991** [comment]
`<?php

return [
    'routes'     => [
        // 'admin' => ['prefix' => 'admin', 'middleware' => ['web']],
        'jqadm' => ['prefix' => 'admin/{site}/jqadm', 'middleware' => ['web', 'auth']],
    // 'jsonadm' => ['prefix' => 'admin/{site}/jsonadm', 'middleware' => ['web', 'auth']],
    // for shop-only applications, remove 'prefix' => 'shop' from 'default' route group
    // for multi-channel setups add 'domain' => '{site}' to each route group and use the domains as locale site codes
    // 'jsonapi' => ['prefix' => 'jsonapi', 'middleware' => ['web', 'api']],
    // 'account' => ['prefix' => 'myaccount', 'middleware' => ['web', 'auth']],
    // 'default' => ['prefix' => 'shop', 'middleware' => ['web']],
    // 'update' => [],
    ],
    'page'       => [
        // Docs: https://aimeos.org/docs/Laravel/Adapt_pages
        // Hint: catalog/filter is also available as single 'catalog/tree', 'catalog/search', 'catalog/attribute'
        'account-index'    => ['account/profile', 'account/subscription', 'account/history',
            'account/favorite', 'account/watch', 'basket/mini', 'catalog/session'],
        'basket-index'     => ['basket/standard', 'basket/related'],
        'catalog-count'    => ['catalog/count'],
        'catalog-detail'   => ['basket/mini', 'catalog/stage', 'catalog/detail',
            'catalog/session'],
        'catalog-list'     => ['basket/mini', 'catalog/filter', 'catalog/lists'],
        'catalog-stock'    => ['catalog/stock'],
        'catalog-suggest'  => ['catalog/suggest'],
        'catalog-tree'     => ['basket/mini', 'catalog/filter', 'catalog/stage',
            'catalog/lists'],
        'checkout-confirm' => ['checkout/confirm'],
        'checkout-index'   => ['checkout/standard'],
        'checkout-update'  => ['checkout/update'],
    ],
    'resource'   => [
        'db'       => [
            'adapter'             => config('database.connections.eshop.driver',
                                            'mysql'),
            'host'                => config('database.connections.eshop.host',
                                            '127.0.0.1'),
            'port'                => config('database.connections.eshop.port',
                                            '3306'),
            'socket'              => config('database.connections.eshop.unix_socket',
                                            ''),
            'database'            => config('database.connections.eshop.database',
                                            'forge'),
            'username'            => config('database.connections.eshop.username',
                                            'forge'),
            'password'            => config('database.connections.eshop.password',
                                            ''),
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3, // maximum number of concurrent database connections
            'defaultTableOptions' => [
                'charset' => config('database.connections.eshop.charset'),
                'collate' => config('database.connections.eshop.collation'),
            ],
        ],
        'db-eshop' => [
            'adapter'             => 'mysql',
            'host'                => '127.0.0.1',
            'port'                => '3306',
            'socket'              => '',
            'database'            => 'test_eshop',
            'username'            => 'root',
            'password'            => '',
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3, // maximum number of concurrent database connections
            'defaultTableOptions' => [
                'charset' => 'utf8',
                'collate' => 'utf8_unicode_ci',
            ],
        ],
        /*'db-eshop' => [
            'adapter'             => config('database.connections.eshop.driver',
                                            'mysql'),
            'host'                => config('database.connections.eshop.host',
                                            '127.0.0.1'),
            'port'                => config('database.connections.eshop.port',
                                            '3306'),
            'socket'              => config('database.connections.eshop.unix_socket',
                                            ''),
            'database'            => config('database.connections.eshop.database',
                                            'forge'),
            'username'            => config('database.connections.eshop.username',
                                            'forge'),
            'password'            => config('database.connections.eshop.password',
                                            ''),
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3, // maximum number of concurrent database connections
            'defaultTableOptions' => [
                'charset' => config('database.connections.eshop.charset'),
                'collate' => config('database.connections.eshop.collation'),
            ],
        ],*/
    ],
    'admin'      => [],
    'client'     => [
        'html' => [
            'basket' => [
                'cache' => [
                // 'enable' => false, // Disable basket content caching for development
                ],
            ],
            'common' => [
                'content'  => array(
                    'baseurl' => env('ESHOP_DOMAIN_NAME',
                                     'http://eshop.mydomain.lan/'),
                ),
                'template' => [
                    'baseurl' => public_path('packages/aimeos/shop/themes/elegance'),
                ],
            ],
            'email'  => array(
                'from-email' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
                'from-name'  => env('MAIL_FROM_NAME', 'Example'),
            ),
        ],
    ],
    'controller' => [
    ],
    'i18n'       => [
    ],
    'madmin'     => [
        'cache' => [
            'manager' => [
            // 'name' => 'None', // Disable caching for development
            ],
        ],
        'log'   => [
            'manager' => [
                'standard' => [
                // 'loglevel' => 7, // Enable debug logging into madmin_log table
                ],
            ],
        ],
    ],
    'mshop'      => [
    ],
    'command'    => [
    ],
    'frontend'   => [
    ],
    'backend'    => [
    ],
];`

**Comment by dhara15101991** [comment]
```
<?php

return [
    'routes'     => [
        'jqadm' => ['prefix' => 'admin/{site}/jqadm', 'middleware' => ['web', 'auth']],

    ],
    'page'       => [
        'account-index'    => ['account/profile', 'account/subscription', 'account/history',
            'account/favorite', 'account/watch', 'basket/mini', 'catalog/session'],
        'basket-index'     => ['basket/standard', 'basket/related'],
        'catalog-count'    => ['catalog/count'],
        'catalog-detail'   => ['basket/mini', 'catalog/stage', 'catalog/detail',
            'catalog/session'],
        'catalog-list'     => ['basket/mini', 'catalog/filter', 'catalog/lists'],
        'catalog-stock'    => ['catalog/stock'],
        'catalog-suggest'  => ['catalog/suggest'],
        'catalog-tree'     => ['basket/mini', 'catalog/filter', 'catalog/stage',
            'catalog/lists'],
        'checkout-confirm' => ['checkout/confirm'],
        'checkout-index'   => ['checkout/standard'],
        'checkout-update'  => ['checkout/update'],
    ],
    'resource'   => [
        'db'       => [
            'adapter'             => config('database.connections.eshop.driver',
                                            'mysql'),
            'host'                => config('database.connections.eshop.host',
                                            '127.0.0.1'),
            'port'                => config('database.connections.eshop.port',
                                            '3306'),
            'socket'              => config('database.connections.eshop.unix_socket',
                                            ''),
            'database'            => config('database.connections.eshop.database',
                                            'forge'),
            'username'            => config('database.connections.eshop.username',
                                            'forge'),
            'password'            => config('database.connections.eshop.password',
                                            ''),
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3,
            'defaultTableOptions' => [
                'charset' => config('database.connections.eshop.charset'),
                'collate' => config('database.connections.eshop.collation'),
            ],
        ],
        'db-eshop' => [
            'adapter'             => 'mysql',
            'host'                => '127.0.0.1',
            'port'                => '3306',
            'socket'              => '',
            'database'            => 'test_eshop',
            'username'            => 'root',
            'password'            => '',
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3,
            'defaultTableOptions' => [
                'charset' => 'utf8',
                'collate' => 'utf8_unicode_ci',
            ],
        ],
    ],
    'admin'      => [],
    'client'     => [
        'html' => [
            'basket' => [
                'cache' => [
                ],
            ],
            'common' => [
                'content'  => array(
                    'baseurl' => env('ESHOP_DOMAIN_NAME',
                                     'http://eshop.mydomain.lan/'),
                ),
                'template' => [
                    'baseurl' => public_path('packages/aimeos/shop/themes/elegance'),
                ],
            ],
            'email'  => array(
                'from-email' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
                'from-name'  => env('MAIL_FROM_NAME', 'Example'),
            ),
        ],
    ],
    'controller' => [
    ],
    'i18n'       => [
    ],
    'madmin'     => [
        'cache' => [
            'manager' => [
            ],
        ],
        'log'   => [
            'manager' => [
                'standard' => [
                ],
            ],
        ],
    ],
    'mshop'      => [
    ],
    'command'    => [
    ],
    'frontend'   => [
    ],
    'backend'    => [
    ],
];
```

**Comment by aimeos** [comment]
`db-eshop` isn't valid. It must be `db-customer` and the settings must point to your default Laravel database.

**Comment by dhara15101991** [comment]
So. instead of `db-eshop` it must be `db-customer` and the settings of this should point to default laravel database?. 

And for db(array) it must be aimeos database setting?

**Comment by aimeos** [comment]
Exactly

**Comment by dhara15101991** [comment]
See now.

`db-customer` is my default database setting and `db` is aimeos database.

```
'resource'   => [
        'db'       => [
            'adapter'             => config('database.connections.eshop.driver',
                                            'mysql'),
            'host'                => config('database.connections.eshop.host',
                                            '127.0.0.1'),
            'port'                => config('database.connections.eshop.port',
                                            '3306'),
            'socket'              => config('database.connections.eshop.unix_socket',
                                            ''),
            'database'            => config('database.connections.eshop.database',
                                            'forge'),
            'username'            => config('database.connections.eshop.username',
                                            'forge'),
            'password'            => config('database.connections.eshop.password',
                                            ''),
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3, // maximum number of concurrent database connections
            'defaultTableOptions' => [
                'charset' => config('database.connections.eshop.charset'),
                'collate' => config('database.connections.eshop.collation'),
            ],
            
        ],
        'db-customer' => [
            'adapter'             => config('database.connections.mysql.driver',
                                            'mysql'),
            'host'                => config('database.connections.mysql.host',
                                            '127.0.0.1'),
            'port'                => config('database.connections.mysql.port',
                                            '3306'),
            'socket'              => config('database.connections.mysql.unix_socket',
                                            ''),
            'database'            => config('database.connections.mysql.database',
                                            'forge'),
            'username'            => config('database.connections.mysql.username',
                                            'forge'),
            'password'            => config('database.connections.mysql.password',
                                            ''),
            'stmt'                => ["SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'"],
            'limit'               => 3, // maximum number of concurrent database connections
            'defaultTableOptions' => [
                'charset' => config('database.connections.mysql.charset'),
                'collate' => config('database.connections.mysql.collation'),
            ],
        ],
    ],
```
charset of default database is `utf8mb4`. so it gives me 
`Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

So is it compulsory for both db have `utf8_unicode_ci` and `utf8` setting?

Also when I tried to set this chartset in both db still getting an error. And yes some tables are created in the default database. Is it the correct situation?

I

**Comment by aimeos** [comment]
If your MySQL version is <5.7.8, you have to use `utf8_unicode_ci` and `utf8` in both databases due to the indexes in the users/address tables.

Now you should have a few `users_*` tables as well as `mshop_customer*` tables (won't be used).

**Comment by dhara15101991** [comment]
Hello, @aimeos

You are really awesome. Thank you so much. It works now. I am really grateful for your kind support. :)

**Comment by aimeos** [comment]
Thanks! :-)
