### ISSUE TITLE
Categories doesn't display in admin

### ISSUE THREAD

**Issue by digihomedk** [aimeos/aimeos-laravel#268]
**Environment**
1. Version 2018.10.*
2. Operating system Linux Debian (LAMP)
3. Project installed using composer create-project aimeos/aimeos shop

**Describe the bug**
After a fresh install, no categories are displayed. I can create categories, and they appear in the database, but they doesn't show up in the backend.
In the browser console, I get the following message:
/admin/default/jsonadm:1 Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

**To Reproduce**
1. Do a fresh install with composer create-project aimeos/aimeos shop
2. Go to admin backend > Categories, and add a category
3. No categories displayed when clicking the category button
4. jsonadm error appears in console

**Expected behavior**
Categories should be listed in the backend

**Screenshots**
<img width="1169" alt="Screenshot 2019-04-24 at 22 28 24" src="https://user-images.githubusercontent.com/26410816/56691598-9df07600-66e0-11e9-9158-af674cff9058.png">
<img width="1226" alt="Screenshot 2019-04-24 at 22 28 52" src="https://user-images.githubusercontent.com/26410816/56691596-9df07600-66e0-11e9-9e63-77161992a5d0.png">
<img width="1671" alt="Screenshot 2019-04-24 at 22 29 15" src="https://user-images.githubusercontent.com/26410816/56691597-9df07600-66e0-11e9-938d-97f15236991a.png">

**Comment by aimeos** [comment]
It's a problem of your web server which doesn't allow OPTIONS requests

**Comment by digihomedk** [comment]
> It's a problem of your web server which doesn't allow OPTIONS requests

Geez... I feel so stupid now... Of course... After hours of troubleshooting... It was just a matter of that... Enabling OPTIONS in apache conf did the trick. Thanks!
