### ISSUE TITLE
After successful payment callback function

### ISSUE THREAD

**Issue by dhara15101991** [aimeos/aimeos-laravel#269]
Hello @aimeos ,

Thanks for your awesome package!!

I have used aimeos on my Skelton laravel application. 

I have configured the skeleton application database and aimeos database differently but install on the same laravel installation with the different subdomain.

Once a new user successfully payment in subscription, I need to update user some information on skeleton application database. I can use any callback API or callback function to achieve 

 Can you guide me on how to achieve this  #feature?

**Comment by aimeos** [comment]
Aimeos only uses the `users` table in your default database if you've configured it to be there.
Github issues are the wrong place for getting help, only for bugs. If you have questions how to do this, please add more information what you want to do and create a topic in the Aimeos forum:
https://aimeos.org/help/laravel-package-f18/
