### ISSUE TITLE
Rewrite views

### ISSUE THREAD

**Issue by Mathias88** [aimeos/aimeos-laravel#27]
Hi,

As I can do to replace the view of list products? There is a method for get all products?

Thanks.

**Comment by aimeos** [comment]
Views cannot access data themselves. Instead, the client that belongs to the view has to add all necessary data to the view.

The "catalog list items" view already receives the list of products from its client. The list is limited to the maximum number of products that should be shown (configurable) and paged if there are more products available. If you have more than 48 products you want to display at once, simple increase the limit. Search for "catalog/list/size" in the docs (https://aimeos.org/docs/)

**Comment by Mathias88** [comment]
But how I can send items to my custom views? 
Another issue, there is a forum Aimeos?

Thank you.

**Comment by aimeos** [comment]
What is your use case? Do you want to create a new component/subpart or just replace an existing view?

Yes, there's a forum at https://aimeos.org/help/

**Comment by Mathias88** [comment]
I need to replace the views of the default template

**Comment by aimeos** [comment]
Still not totally sure what you want to do. Do you need to replace the "client/html/templates/catalog/lists/item-body-default.php" with your own one?

**Comment by Mathias88** [comment]
Yes, because my design change much with respect to default. Thanks

**Comment by aimeos** [comment]
The simplest way is to copy the existing template to the same directory in your own Aimeos extension and then adapt the HTML inside. You have access to all data which have been passed to the view using ```$this->get( '<name>', <default> );```

**Comment by Mathias88** [comment]
Thank you!
