### ISSUE TITLE
It's possible to integrate this package in an existing application?

### ISSUE THREAD

**Issue by ludo237** [aimeos/aimeos-laravel#270]
I have an application that already have users table set up, is it possible to integrate this package without altering the users table itself?

**Comment by aimeos** [comment]
You can integrate Aimeos into your existing application without problems but it has to add some columns to the `users` table. If you don't want that, you can put Aimeos into a separate database and configure the standard customer manager which will use the `mshop_customer*` tables instead. Then, you only need to add a `superuser` column to your `users` table to be able to log into the admin interface.
