### ISSUE TITLE
Class 'NumberFormatter' not found

### ISSUE THREAD

**Issue by hoangnamitc** [aimeos/aimeos-laravel#271]
Hi guys,

My problem image bellow:

![image](https://user-images.githubusercontent.com/7042462/57024047-d30b4400-6c5d-11e9-923a-a76e3f49bfb3.png)

How to fix it?
Thanks

**Comment by hoangnamitc** [comment]
I fixed it:

**Comment by aimeos** [comment]
PHP intl extension isn't installed
