### ISSUE TITLE
Write new field data to orders table on checkout

### ISSUE THREAD

**Issue by hyph3nx** [aimeos/aimeos-laravel#272]
Hi,
I want to generate a unique value for each order and write it to a field/column I have created in the order table.

Where is the specific code that writes to the order to the table so I can update it?
I want to display the unique value on the summary page.
Once assigned to the order, the unique value does not change.

Thank you.

**Comment by aimeos** [comment]
The easiest way would be to write it into the customer reference number column. Unfortunately, this is currently only available in the master branch of https://github.com/aimeos/aimeos-core:
https://github.com/aimeos/aimeos-core/commit/2b29dd01b566f5fb3d67d1cf7d00487c4a831fc7

**Comment by hyph3nx** [comment]
How do I update to that? I am using the distribution.

**Comment by aimeos** [comment]
You could change
```
"aimeos/aimeos-laravel": "~2018.10"
```
to
```
"aimeos/aimeos-laravel": "dev-master"
```
and run `composer update` and `artisan aimeos:setup` afterwards. Keep in mind, that this is an upgrade to a new major version (there may be some things to fix afterwards) and dev-master is not always stable

**Comment by hyph3nx** [comment]
Thanks, reference number is exactly what I need
