### ISSUE TITLE
Requirements for coupon code "XXX" aren't met

### ISSUE THREAD

**Issue by khalidbashirbajwa** [aimeos/aimeos-laravel#273]
**Environment**
1. Version (e.g. 2018.10)
2. Operating system (Linux)

**Describe the bug**
When I create Coupon codes from the Admin panel by following the User Manual https://aimeos.org/docs/User_Manual/Administration_Interface/Coupon_list I get a weired kind of error  "Requirements for coupon code "XXX" aren't met". This is when the coupon code has capital letters in it. However, if I create a coupon code with small letters it works.

**To Reproduce**
1. Follow the process of creating a Coupon code as in the user manual. I am using a FixedRebate provider with no decorators
2. Add a code to the Voucher (I added KHALID)
3. Try to use the code in frontend
4. An error is Requirements for coupon code "KHALID" aren't met is received
(Screenshots are attached)

**Expected behavior**
The coupon should work seamlessly. This happens when i use a coupon code with small letters like khalid. Everything works. Screenshots are attached

I was facing this problem since long and was kind of working my way around this by using coupon codes with small letters. However, now I want to enable Gift Vouchers for my shop. When I enable them and purchase one from the frontend the codes are automatically generated by the system. The generated codes are mix of numbers and capital letters. I start getting the problem Requirements for coupon code "XXX" aren't met. Screenshots are attached for this as well the generated coupon code by the system is "00CACE33". However, when I use it on frontend I am unable to do so

**Screenshots**
Screenshots for all
![1](https://user-images.githubusercontent.com/2155509/57688065-41300d80-7645-11e9-8683-b63b2e243639.png)
![2](https://user-images.githubusercontent.com/2155509/57688067-41300d80-7645-11e9-8c2f-09631334700a.png)
![3](https://user-images.githubusercontent.com/2155509/57688068-41300d80-7645-11e9-8d69-100345b77a06.png)
![4](https://user-images.githubusercontent.com/2155509/57688069-41c8a400-7645-11e9-8384-4603a06a058f.png)
![5](https://user-images.githubusercontent.com/2155509/57688070-41c8a400-7645-11e9-9905-a0000b22b6f4.png)
![6](https://user-images.githubusercontent.com/2155509/57688071-41c8a400-7645-11e9-81e7-9beff9cec88b.png)
![7](https://user-images.githubusercontent.com/2155509/57688072-41c8a400-7645-11e9-9b22-0f2fe37014cd.png)
![8](https://user-images.githubusercontent.com/2155509/57688076-42613a80-7645-11e9-92a0-f4463fb731a2.png)
![9](https://user-images.githubusercontent.com/2155509/57688079-42613a80-7645-11e9-9ad3-e1dca2ba3f91.png)
![10](https://user-images.githubusercontent.com/2155509/57688080-42f9d100-7645-11e9-95d0-15822c0f0cf8.png)

stages are attached

**Comment by aimeos** [comment]
2018.10 versions has some problems with case insensitivity for coupon codes because the collation of the `mshop_coupon_code` table is usually `utf8*_ci` which means all values are treated as case insensitive by the database. Aimeos tries to work around this but that doesn't work in all cases. Can you try to change the collation to `utf8_bin` or `utf8mb4_bin` - depending on what you are using by default (utf8 or utf8mb4)?

**Comment by khalidbashirbajwa** [comment]
Thanks for getting back. The collation is already utf8mb4_bin. Please see the attached screenshot. Is there any way to solve this problem while staying in 2018.10?
![image](https://user-images.githubusercontent.com/2155509/57691795-cf0ff680-764d-11e9-8238-4bae849e087a.png)

**Comment by aimeos** [comment]
OK, then try `utf8mb4_general_ci` instead so the workarounds in 2018.10 can do their job

**Comment by khalidbashirbajwa** [comment]
Thanks. This works.
