### ISSUE TITLE
Order status emails show no information about status of refused items

### ISSUE THREAD

**Issue by khalidbashirbajwa** [aimeos/aimeos-laravel#274]
**Environment**
1. Version (e.g. 2018.10)
2. Operating system (Linux)

**Describe the bug**
In an order with multiple items if the status of on the items is changed to refused and then under the invoice option if we change the delivery status to dispatched an email is generated. But that email shows all items and there is no differentiation of items that were refused and the onces that were dispatched. There should be a differentiation there. The refused items should be mentioned explicitly. 

A linked issue to this is that there seems to be no capability in the system for tracking a partial refund. How can we do that?

**To Reproduce**
1. The screenshots for order and email are attached

**Expected behavior**
The generated email should contain differentiation of items which were refused and which were fulfilled

**Screenshots**
![1](https://user-images.githubusercontent.com/2155509/57700244-3b94f080-7662-11e9-8cc3-d695cf4a3daa.png)
![2](https://user-images.githubusercontent.com/2155509/57700245-3c2d8700-7662-11e9-905e-07bfe304cd23.png)
![3](https://user-images.githubusercontent.com/2155509/57700246-3c2d8700-7662-11e9-878e-a5c0dd2dfff1.png)

**Additional context**

**Comment by aimeos** [comment]
Aimeos is no complete order management system (shop owners usually have their ERP system for that) but it would be nice to have at least a very basic functionality for that. You can create a feature request here: https://github.com/aimeos/ai-admin-jqadm/issues

Regarding the e-mails: Yes, there should be something different if the delivery status of a product is set. At the moment, you should overwrite the e-mail template to do that on your own but you can also add a feature request for future versions here: https://github.com/aimeos/ai-client-html/issues

**Comment by aimeos** [comment]
E-mail feature is implemented, the feature request for partial refunds is still open
