### ISSUE TITLE
Admin page drop down not working

### ISSUE THREAD

**Issue by hyph3nx** [aimeos/aimeos-laravel#275]
I am unable to select a category from a drop down menu in products. It does not show anything.
I cannot add variant attributes to products.
I cannot add items to products bought together.

Previously this all worked. Now it is not. I have tried on both dev server and production server. Ubuntu
![image](https://user-images.githubusercontent.com/6461025/57855362-d130ab80-782d-11e9-9e2b-98623667779e.png)

**Comment by hyph3nx** [comment]
Looks like when I click any of them it does not send a GET request

**Comment by aimeos** [comment]
Which Aimeos version do you use and do you get any error in the browser console?

**Comment by hyph3nx** [comment]
not sure on version, I followed instructions here: https://github.com/aimeos/aimeos
No errors in the browser console. Webpage displays as normal

**Comment by aimeos** [comment]
Please check if your server supports OPTIONS requests. This is most often the problem when the JSON REST API doesn't work as expected.

**Comment by hyph3nx** [comment]
It was working yesterday. Is there a file I may have changed? I can run curl -i -X OPTIONS http://example.org/path from the command line

**Comment by aimeos** [comment]
Can you post the response of the OPTIONS request from your browser console?

**Comment by hyph3nx** [comment]
Not sure how to do that. I built a new instance of aimeos and it works
