### ISSUE TITLE
how to change currency icon e.g Rs to ₹

### ISSUE THREAD

**Issue by ankit20893** [aimeos/aimeos-laravel#279]
**Environment**
1. Version (e.g. 2017.10)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aimeos** [comment]
You can fix it in the Transifex translation: https://www.transifex.com/aimeos/aimeos-core/

Alternatively, you can change it locally by overwriting the translation in your ./config/shop.php file ("i18n" section with translation domain "currency"): https://aimeos.org/docs/Laravel/Overwrite_translations
