### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by muhghazaliakbar** [aimeos/aimeos-laravel#28]
Hi, i have installed aimeos from composer update and clear. but i get an error to run command `php artisan vendor:publish` after add providers in .config/app.php

here my error:

![screenshot_64](https://cloud.githubusercontent.com/assets/8321936/13906480/e3a9f8aa-ef11-11e5-9ded-5f58b1cf0523.png)

**Comment by aimeos** [comment]
Can you please give us some more information? Laravel and Aimeos version for example. What are the exact steps you've did before?
