### ISSUE TITLE
Theme in demo

### ISSUE THREAD

**Issue by ukenpachi** [aimeos/aimeos-laravel#281]
This is not a feature request or bug but a question.
The template is shown in 
![image](https://user-images.githubusercontent.com/5822229/60403365-0e5dbc80-9b94-11e9-800b-b0ae0f46300f.png) is this publically available to be download? also anywhere to find other themes? Thank you

**Comment by aimeos** [comment]
This is a custom home page (not a theme) for the #gigacommerce demo setup:
http://laravel.gigacommerce.aimeos.com/
