### ISSUE TITLE
"Undefined column" on aimeos:setup (with demo shop)

### ISSUE THREAD

**Issue by LPABelgium** [aimeos/aimeos-laravel#282]
**Environment**
1. 2019.04.4
2. Linux - Debian 9 - Nginx
3. Laravel 5.8
4. Postgresql

**Describe the bug**
On "php artisan aimeos:setup --option=setup/default/demo:1" get SQL error =>
```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "column_type" does not exist
LINE 1: SELECT COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TAB
```

cfr screenshot

config/shop.php had been updated as described here https://aimeos.org/docs/Developers/Library/Database_support

**To Reproduce**
1. create fresh laravel 5.8 install (permission on folder "bootstrap/cache" and "storage" not yet set)
2. run composer update
3. add "aimeos/aimeos-laravel": "2019.04.4" to composer.json
4. run compose update
5. add "post-update-cmd" to composer.json
6. run composer update
7. run "php artisan vendor:publish --all"
8. run "php artisan migrate"
9. run "php artisan aimeos:setup --option=setup/default/demo:1"
10. Get the error : cfr screenshot

**Expected behavior**
Demo shop installed on a fresh L5.8 and uptodate Aimeos

**Screenshots**
https://snag.gy/bJIpnA.jpg

**Additional context**
Just thanks for your response ;)

**Comment by aimeos** [comment]
For PostgreSQL you have to set a different configuration: 
https://aimeos.org/docs/Developers/Library/Database_support

**Comment by LPABelgium** [comment]
It's already done has said just before "To Reproduce" ;)

I think I've followed each step but have twice this error. First time with aimeos/aimeos package, second time with aimeos/aimeos-laravel package.

**Comment by LPABelgium** [comment]
https://snag.gy/ksKwQZ.jpg

https://snag.gy/Swqo83.jpg

**Comment by LPABelgium** [comment]
mmm I left "defaultTableOptions" which refer to "database.connections.mysql.charset", it could be an issue ?

**Comment by aimeos** [comment]
Maybe, can you remove it an try again?

**Comment by LPABelgium** [comment]
Same issue. 

When I take a look to the database at this step, I just have the 3 basics table : 
- users
- password_resests
- migrations
& of course the 2 sequences (migrations_id_seq - users_id_seq)

Nothing else.

The error is 
`SQLSTATE[42703]: Undefined column: 7 ERROR:  column "column_type" does not exist
LINE 1: SELECT COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'id'", "COLUMN_TYPE", "db-customer"`

Does the database user has to have all privilege on database ? Will have a try with postgres user

**Comment by LPABelgium** [comment]
Same issue

**Comment by LPABelgium** [comment]
"COLUMN_TYPE" does not seem to exist on postgres => https://www.postgresql.org/docs/9.5/infoschema-columns.html

Could be "Data_type" ?

**Comment by LPABelgium** [comment]
I've updated : 
`ext/ai-laravel/custom/setup/CustomRemoveSignedConstraints.php`

on line 45 have this : 
`$sql = 'SELECT DATA_TYPE as COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = \'users\' AND COLUMN_NAME = \'id\'';`

And the installation goes through ;)

But... new issue ;) Must I do another report ?

**Comment by aimeos** [comment]
Fixed: https://github.com/aimeos/ai-laravel/commit/f38077ff15a1474203f9b22f62a29ad7528dfe0f
Thank you for the hint! :-)
