### ISSUE TITLE
Change your documentation

### ISSUE THREAD

**Issue by microdesign** [aimeos/aimeos-laravel#284]
The setup guide told your users to execute 

php artisan vendor:publish --all

this will publish all config files of all other libs they are installed 

Just add your config tag to be used here

**Comment by aimeos** [comment]
Can you create a PR?

**Comment by bfiessinger** [comment]
Hi @aimeos,

as far as I can see the files published all come from `Aimeos\Shop\ShopServiceProvider`.

So changing `php artisan vendor:publish --all` to `php artisan vendor:publish --provider="Aimeos\Shop\ShopServiceProvider"` should do the trick.

Am I missing any third party packages that need to be published too? If I'm right I can push a PR on this one.

**Comment by aimeos** [comment]
The Aimeos theme extensions also contain service provider which must publish files

**Comment by bfiessinger** [comment]
> The Aimeos theme extensions also contain service provider which must publish files

![Screenshot 2022-09-04 082924](https://user-images.githubusercontent.com/41627893/188300606-5550b2e1-2585-4426-aa7a-f70c5c1411ac.png)

As far as I can see the themes are getting published by the command, aren't they?

**Comment by aimeos** [comment]
Yes, that should be enough to publish the theme files so it's possible to use only `--provider="Aimeos\Shop\ShopServiceProvider"`
