### ISSUE TITLE
How to change middleware

### ISSUE THREAD

**Issue by visualNext** [aimeos/aimeos-laravel#285]
I want to change middleware from web to admin, but an error message "Class admin does not exist". 

Model admin, config/auth.php guards and providers is set, admin can also login.

config/auth.php
```
'guards' => [

    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'api' => [
        'driver' => 'token',
        'provider' => 'users',
    ],

    'admin' => [
        'driver' => 'session',
        'provider' => 'admins',
    ],

],

'providers' => [

    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class,
    ],

   'admins' => [
        'driver' => 'eloquent',
        'model' => App\Admin::class,
    ],

],
```
app/Admin.php
```
class Admin extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';
    protected $guard = 'admin';
    
    protected $guarded = ['id'];

   protected $hidden = [
        'password', 'remember_token',
    ];
}
```

app/User.php
```
class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'admins';
    
    protected $guarded = ['id'];

   protected $hidden = [
        'password', 'remember_token',
    ];
}
```

But the url link to https://localhost/admin/default/jqadm/search/order has a problem. (Class admin does not exist)

**Comment by aimeos** [comment]
Is it only https://localhost/admin/default/jqadm/search/order or doesn't it work at all?

**Comment by visualNext** [comment]
> I want to change middleware from web to admin, but an error message "Class admin does not exist".
> 
> Model admin, config/auth.php guards and providers is set, admin can also login.
> 
> config/auth.php
> 
> ```
> 'guards' => [
> 
>     'web' => [
>         'driver' => 'session',
>         'provider' => 'users',
>     ],
> 
>     'api' => [
>         'driver' => 'token',
>         'provider' => 'users',
>     ],
> 
>     'admin' => [
>         'driver' => 'session',
>         'provider' => 'admins',
>     ],
> 
> ],
> 
> 'providers' => [
> 
>     'users' => [
>         'driver' => 'eloquent',
>         'model' => App\User::class,
>     ],
> 
>    'admins' => [
>         'driver' => 'eloquent',
>         'model' => App\Admin::class,
>     ],
> 
> ],
> ```
> 
> app/Admin.php
> 
> ```
> class Admin extends Authenticatable
> {
>     use Notifiable;
> 
>     protected $table = 'users';
>     protected $guard = 'admin';
>     
>     protected $guarded = ['id'];
> 
>    protected $hidden = [
>         'password', 'remember_token',
>     ];
> }
> ```
> 
> app/User.php
> 
> ```
> class User extends Authenticatable
> {
>     use Notifiable;
> 
>     protected $table = 'admins';
>     
>     protected $guarded = ['id'];
> 
>    protected $hidden = [
>         'password', 'remember_token',
>     ];
> }
> ```
> 
> But the url link to https://localhost/admin/default/jqadm/search/order has a problem. (Class admin does not exist)
