### ISSUE TITLE
Error stetup demo data after clean install

### ISSUE THREAD

**Issue by dronowar** [aimeos/aimeos-laravel#29]
php artisan aimeos:setup --option=setup/default/demo:1

 failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.label' in 'field list'

http://joxi.ru/xAe5QzbcYaZNbA

**Comment by aimeos** [comment]
The Laravel database migration is missing in your setup. Did you forgot to execute `php artisan vendor:publish` and `php artisan migrate` first?

**Comment by dronowar** [comment]
yes, but only 2 table was in /database/migrations/ after install package
`$ php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
`

**Comment by aimeos** [comment]
Did you add the Aimeos service provider class in the `config/app.php` first, so `php artisan vendor:publish` will copy the Aimeos migrations to `./database/migrations`?

**Comment by dronowar** [comment]
my mistake, i did migration before `vendor:publish`

**Comment by pagliaj** [comment]
Laravel Framework version 5.2.43

Doing a fresh aimeos install - its failing on the command: 
php artisan aimeos:setup --option=setup/default/demo:1
And also when I try to create the admin. 

  Checking table "mshop_product_type":                                OK
  Checking table "mshop_service_list_type":                           OK
  Checking table "mshop_service_type":                                OK
  Checking table "mshop_text_list_type":                              OK
  Checking table "mshop_text_type":                                   OK
Adding default code data for site "default"                           
  Checking "customer/group" codes                                     OK
  Checking "product/stock/warehouse" codes                            OK
Processing product demo data                                          added
Processing catalog demo data                                          added
Processing coupon demo data                                           added
Processing customer demo data                                         
                                                                                       
  [Aimeos\MW\DB\Exception]                                                             
  Executing statement "                                                                
  			SELECT DISTINCT lvu."id" AS "customer.id",                                        
  				lvu."label" AS "customer.label", lvu."name" as "customer.code",                  
  				lvu."company" AS "customer.company", lvu."vatid" AS "customer.vatid",            
  				lvu."salutation" AS "customer.salutation", lvu."title" AS "customer.title",      
  ... 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.label' in 'field list'   

Thanks for any help.

**Comment by aimeos** [comment]
Please have a look into your database. Is the `users` table there? How does it look like?

**Comment by pagliaj** [comment]
I missed that. There is no users table. It did not get created?

**Comment by aimeos** [comment]
OK, might be a bug in the most recent Laravel version because the `users` table is created by Laravel (normally). Can you check with the Laravel community why it's not created any more?

**Comment by pagliaj** [comment]
Aimeos thanks for the help. It may be something I did. I am doing a fresh install of Laravel and Aimeos this morning (so I don't waste anyone's time).

**Comment by pagliaj** [comment]
Update, I was installing Aimeos into an existing Laravel site. The user table did exist already and it has many more fields than the "Aimeos clean install user table". It looks like the "php artisan aimeos:account" command fails with custom user tables? My clean Aimeos install worked.

**Comment by aimeos** [comment]
It will fail if there are columns that don't allow NULL values because the `aimeos:account` command doesn't know that they exist and what needs to be inserted
