### ISSUE TITLE
I installed it and now it isn't showing up

### ISSUE THREAD

**Issue by mikeyapina** [aimeos/aimeos-laravel#290]
I installed and got thru the issues, but, now I cannot find the files after all the installion went well.

ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo composer create-project aimeos/aimeos retail
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing aimeos/aimeos (2018.10.3)
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing aimeos/aimeos (2018.10.3): Loading from cache
Created project in retail
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "mkdir('public/files'); mkdir('public/preview'); mkdir('public/uploads');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 94 installs, 0 updates, 0 removals
  - Installing kylekatarnls/update-helper (1.2.0): Loading from cache
  - Installing composer/installers (v1.7.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.12.0): Loading from cache
  - Installing vlucas/phpdotenv (v2.6.1): Loading from cache
  - Installing symfony/css-selector (v4.3.4): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.12.0): Loading from cache
  - Installing symfony/var-dumper (v3.4.31): Loading from cache
  - Installing symfony/routing (v3.4.31): Loading from cache
  - Installing symfony/process (v3.4.31): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v3.4.31): Loading from cache
  - Installing symfony/polyfill-php72 (v1.12.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.12.0): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/polyfill-php70 (v1.12.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.31): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.5): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/event-dispatcher (v4.3.4): Loading from cache
  - Installing symfony/http-kernel (v3.4.31): Loading from cache
  - Installing symfony/finder (v3.4.31): Loading from cache
  - Installing symfony/console (v3.4.31): Loading from cache
  - Installing symfony/polyfill-iconv (v1.12.0): Loading from cache
  - Installing doctrine/lexer (1.1.0): Loading from cache
  - Installing egulias/email-validator (2.1.11): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.1): Loading from cache
  - Installing ramsey/uuid (3.8.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing symfony/translation-contracts (v1.1.6): Loading from cache
  - Installing symfony/translation (v4.3.4): Loading from cache
  - Installing nesbot/carbon (1.39.0): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.1): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing league/flysystem (1.0.55): Loading from cache
  - Installing erusev/parsedown (1.7.3): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing laravel/framework (v5.5.48): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing zendframework/zend-diactoros (1.8.7): Loading from cache
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v4.2.3): Loading from cache
  - Installing fideloper/proxy (3.3.4): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing psy/psysh (v0.9.9): Loading from cache
  - Installing laravel/tinker (v1.0.10): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/dbal (v2.9.0): Loading from cache
  - Installing aimeos/aimeos-core (2018.10.22): Loading from cache
  - Installing aimeos/ai-controller-jobs (2018.10.8): Loading from cache
  - Installing aimeos/ai-controller-frontend (2018.10.7): Loading from cache
  - Installing aimeos/ai-client-jsonapi (2018.10.6): Loading from cache
  - Installing aimeos/ai-client-html (2018.10.21): Loading from cache
  - Installing aimeos/ai-admin-jsonadm (2018.10.5): Loading from cache
  - Installing aimeos/ai-admin-jqadm (2018.10.18): Loading from cache
  - Installing aimeos/ai-laravel (2018.10.3): Loading from cache
  - Installing aimeos/ai-gettext (2018.10.4): Loading from cache
  - Installing aimeos/ai-swiftmailer (2018.10.2): Loading from cache
  - Installing symfony/psr-http-message-bridge (v1.2.0): Loading from cache
  - Installing aimeos/aimeos-laravel (2018.10.4): Loading from cache
  - Installing filp/whoops (2.5.0): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2): Loading from cache
  - Installing mockery/mockery (0.9.11): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.1): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.3): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing webmozart/assert (1.5.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.1): Loading from cache
  - Installing phpspec/prophecy (1.8.1): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.9.3): Loading from cache
  - Installing phpunit/phpunit (6.5.14): Loading from cache
symfony/var-dumper suggests installing ext-symfony_debug
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/console suggests installing symfony/lock
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use Flysystem caching (~1.0).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~3.3).)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
aimeos/aimeos-core suggests installing apigen/apigen (Required for generating the API documentation)
symfony/psr-http-message-bridge suggests installing nyholm/psr7 (For a super lightweight PSR-7/17 implementation)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: aimeos/aimeos-laravel
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Package manifest generated successfully.
> @php artisan vendor:publish --tag=public --force
Copied Directory [/vendor/aimeos/aimeos-laravel/public] To [/public/packages/aimeos/shop]
Publishing complete.
> @php artisan key:generate
Application key [base64:BeaVuWFr14FICBaIJtCIDXEXoie/Rr0MpIv13rEvW3g=] set successfully.
> @php artisan make:auth
Authentication scaffolding generated successfully.
> App\Composer::configure
Database setup
- DB_CONNECTION (mysql): 
- DB_HOST (127.0.0.1): 
- DB_PORT (3306): 
- DB_DATABASE (homestead): retail
- DB_USERNAME (homestead): regenics
- DB_PASSWORD: 
Mail setup
- MAIL_DRIVER (smtp): 
- MAIL_HOST (smtp.mailtrap.io): mail.gmail.com
- MAIL_PORT (2525): 
- MAIL_USERNAME (): mike@regenics.com
- MAIL_ENCRYPTION (): 
- MAIL_PASSWORD: 
> @php artisan migrate
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
> App\Composer::setup
Initializing or updating the Aimeos database tables for site "default"
Renaming product warehouse table                                      OK
Changing warehouseid column in mshop_product_stock                    OK
Adding ctime/mtime/user columns to tables                             
Rename warehouse table                                                
  Drop "mshop_product_stock.fk_msprost_whid"                          OK
  Drop "mshop_product_stock.fk_msprost_stock_warehouseid"             OK
  Rename "mshop_product_stock.wareshouseid"                           OK
  Rename "mshop_product_stock_wareshouse"                             OK
Adding id to order service attribute table                            
  Checking column "id":                                               OK
Adding siteid to order tables                                         
  Checking table "mshop_order_base":                                  OK
  Checking table "mshop_order":                                       OK
  Checking table "mshop_order_base_address":                          OK
  Checking table "mshop_order_base_discount":                         OK
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base_product_attr":                     OK
  Checking table "mshop_order_base_service_attr":                     OK
Adding service ID to order base service table                         
  Checking table "mshop_order_base_service":                          OK
Changing typeid column of product table                               
  Checking table "mshop_product":                                     OK
Renaming column "price" to "value"                                    
  Checking table "mshop_price"                                        OK
Moving product tag tables to own domain                               
  Moving table "mshop_product_tag_type"                               OK
  Moving table "mshop_product_tag"                                    OK
Renaming order base customercode to customerid                        
  Checking table "mshop_order_base":                                  OK
Adding status column to all list tables                               
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_customer_list":                               OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_price_list":                                  OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_text_list":                                   OK
Adding mtime, ctime, editor columns to coupon tables                  
  Checking table "mshop_coupon"                                       
  Checking table "mshop_coupon_code"                                  
  Checking table "mshop_order_base_coupon"                            
Changing typeid of mshop_media table                                  OK
Renaming order base product amount to quantity                        
  Checking table "mshop_order_base_product":                          OK
Migrating order type                                                  
  Checking table "mshop_order":                                       OK
Rename "prodid" to "parentid" in table "mshop_product_stock"          
  Checking column "prodid"                                            OK
Move stock tables to own domain                                       
  Checking "mshop_product_stock"                                      OK
  Checking "mshop_product_stock_type"                                 OK
Adding label and status columns for product warehouse                 
Adding product ID to order base product table                         
  Checking table "mshop_order_base_product":                          OK
Adding warehouse code to order base product table                     OK
Migrating configuration keys in coupon tables                         OK
Adding parentid column to catalog and locale_site                     
  Checking parentid column in "mshop_catalog"                         OK
  Checking parentid column in "mshop_locale_site"                     OK
Migrating order flags to order status list                            
Changing typeid of mshop_text table                                   OK
Renaming order domain                                                 
  Checking table "mshop_order":                                       OK
  Checking table "mshop_order_base_address":                          OK
  Checking table "mshop_order_base_service":                          OK
Adding code column to mshop_catalog                                   OK
Renaming catalog index tables to index                                
  Checking table "mshop_catalog_index_attribute"                      OK
  Checking table "mshop_catalog_index_catalog"                        OK
  Checking table "mshop_catalog_index_price"                          OK
  Checking table "mshop_catalog_index_text"                           OK
Changing "domain" columns                                             
  Checking table "mshop_attribute":                                   OK
  Checking table "mshop_attribute_type":                              OK
  Checking table "mshop_attribute_list_type":                         OK
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_catalog":                                     OK
  Checking table "mshop_catalog_list_type":                           OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_catalog_suggest":                             OK
  Checking table "mshop_media_type":                                  OK
  Checking table "mshop_media_list_type":                             OK
  Checking table "mshop_media":                                       OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_plugin":                                      OK
  Checking table "mshop_price":                                       OK
  Checking table "mshop_product_type":                                OK
  Checking table "mshop_product_list_type":                           OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_product_tag_type":                            OK
  Checking table "mshop_service":                                     OK
  Checking table "mshop_service_list_type":                           OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_text_type":                                   OK
  Checking table "mshop_text":                                        OK
  Checking table "mshop_text_list_type":                              OK
  Checking table "mshop_text_list":                                   OK
Migrating product property domain to "product"                        OK
Renaming shipping to costs                                            
  Checking table "mshop_order_base":                                  OK
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
Migrating order emailflag colum to order status list                  
Adding label to mshop text table                                      OK
Changing typeid of mshop_attribute table                              OK
Renaming order columns pdate,ddate,dstatus,pstatus                    
  Checking columne "ddate":                                           OK
  Checking columne "pdate":                                           OK
  Checking columne "pstatus":                                         OK
  Checking columne "dstatus":                                         OK
Migrating order address salutations                                   
  Checking table "mshop_order_base_address":                          OK
Migrate product code in stock table                                   
Renaming shipping to costs                                            
  Checking table "mshop_price":                                       OK
Renaming column "discount" to "rebate"                                
  Checking table "mshop_price"                                        OK
  Checking table "mshop_order_base"                                   OK
  Checking table "mshop_order_base_product"                           OK
  Checking table "mshop_order_base_service"                           OK
Changing code from "product" to "default" in "mshop_product_type"     OK
Ensure unique codes in mshop_service                                  OK
Adding tax column to order tables                                     
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base":                                  OK
Fixing order email status values                                      OK
Remove left over Laravel user address records                         OK
Remove left over Laravel user list records                            OK
Creating base tables                                                  
  Using schema from locale.php                                        
    Checking table "mshop_locale_site":                               done
    Checking table "mshop_locale_language":                           done
    Checking table "mshop_locale_currency":                           done
    Checking table "mshop_locale":                                    done
  Using schema from attribute.php                                     
    Checking table "mshop_attribute_type":                            done
    Checking table "mshop_attribute":                                 done
    Checking table "mshop_attribute_list_type":                       done
    Checking table "mshop_attribute_list":                            done
    Checking table "mshop_attribute_property_type":                   done
    Checking table "mshop_attribute_property":                        done
  Using schema from customer.php                                      
    Checking table "mshop_customer":                                  done
    Checking table "mshop_customer_address":                          done
    Checking table "mshop_customer_list_type":                        done
    Checking table "mshop_customer_list":                             done
    Checking table "mshop_customer_group":                            done
    Checking table "mshop_customer_property_type":                    done
    Checking table "mshop_customer_property":                         done
    Checking table "users":                                           done
    Checking table "users_address":                                   done
    Checking table "users_list_type":                                 done
    Checking table "users_list":                                      done
    Checking table "users_property_type":                             done
    Checking table "users_property":                                  done
  Using schema from media.php                                         
    Checking table "mshop_media_type":                                done
    Checking table "mshop_media":                                     done
    Checking table "mshop_media_list_type":                           done
    Checking table "mshop_media_list":                                done
    Checking table "mshop_media_property_type":                       done
    Checking table "mshop_media_property":                            done
  Using schema from order.php                                         
    Checking table "mshop_order_base":                                done
    Checking table "mshop_order_base_address":                        done
    Checking table "mshop_order_base_product":                        done
    Checking table "mshop_order_base_product_attr":                   done
    Checking table "mshop_order_base_service":                        done
    Checking table "mshop_order_base_service_attr":                   done
    Checking table "mshop_order_base_coupon":                         done
    Checking table "mshop_order":                                     done
    Checking table "mshop_order_status":                              done
  Using schema from plugin.php                                        
    Checking table "mshop_plugin_type":                               done
    Checking table "mshop_plugin":                                    done
  Using schema from price.php                                         
    Checking table "mshop_price_type":                                done
    Checking table "mshop_price":                                     done
    Checking table "mshop_price_list_type":                           done
    Checking table "mshop_price_list":                                done
  Using schema from product.php                                       
    Checking table "mshop_product_type":                              done
    Checking table "mshop_product":                                   done
    Checking table "mshop_product_list_type":                         done
    Checking table "mshop_product_list":                              done
    Checking table "mshop_product_property_type":                     done
    Checking table "mshop_product_property":                          done
  Using schema from stock.php                                         
    Checking table "mshop_stock_type":                                done
    Checking table "mshop_stock":                                     done
  Using schema from service.php                                       
    Checking table "mshop_service_type":                              done
    Checking table "mshop_service":                                   done
    Checking table "mshop_service_list_type":                         done
    Checking table "mshop_service_list":                              done
  Using schema from supplier.php                                      
    Checking table "mshop_supplier":                                  done
    Checking table "mshop_supplier_address":                          done
    Checking table "mshop_supplier_list_type":                        done
    Checking table "mshop_supplier_list":                             done
  Using schema from text.php                                          
    Checking table "mshop_text_type":                                 done
    Checking table "mshop_text":                                      done
    Checking table "mshop_text_list_type":                            done
    Checking table "mshop_text_list":                                 done
  Using schema from coupon.php                                        
    Checking table "mshop_coupon":                                    done
    Checking table "mshop_coupon_code":                               done
  Using schema from catalog.php                                       
    Checking table "mshop_catalog":                                   done
    Checking table "mshop_catalog_list_type":                         done
    Checking table "mshop_catalog_list":                              done
  Using schema from tag.php                                           
    Checking table "mshop_tag_type":                                  done
    Checking table "mshop_tag":                                       done
  Using schema from index.php                                         
    Checking table "mshop_index_attribute":                           done
    Checking table "mshop_index_catalog":                             done
    Checking table "mshop_index_price":                               done
    Checking table "mshop_index_supplier":                            done
    Checking table "mshop_index_text":                                done
  Using schema from subscription.php                                  
    Checking table "mshop_subscription":                              done
Move list types to separate table                                     
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_attribute_option_list":                       OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
Add locale data for languages and currencies                          
  Adding data for MShop locale languages                              188/188
  Adding data for MShop locale currencies                             156/156
Creating admin tables                                                 
  Using schema from cache.php                                         
    Checking table "madmin_cache":                                    done
    Checking table "madmin_cache_tag":                                done
  Using schema from log.php                                           
    Checking table "madmin_log":                                      done
  Using schema from job.php                                           
    Checking table "madmin_job":                                      done
  Using schema from queue.php                                         
    Checking table "madmin_queue":                                    done
Adding data for MShop locale domain                                   
  Adding data for MShop locale sites                                  done
  Adding data for MShop locales                                       done
Adding locale data if not yet present                                 OK
Setting locale to "default"                                           OK
Renaming service domain                                               
  Checking table "mshop_service":                                     OK
Adding currency ID to order base service table                        done
Renaming plugin domain                                                
  Checking table "mshop_plugin":                                      OK
Adding label column to mshop_plugin table                             OK
Adding typeid column to price table                                   
  Checking column "typeid":                                           OK
Populate weekday column in order table                                done
Adding time columns to order table                                    done
Migrating configuration of "ProductLimit" plugin                      OK
Migrating configuration of "Complete" plugin                          OK
Add domain values to "mshop_product_stock_type" table                 OK
Adding currency ID to order base product table                        done
Changing typeid to not allow NULL values                              
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_text_list":                                   OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_media_list":                                  OK
Add stock type domain values                                          done
Migrating "Complete" to "BasketLimits" plugin                         
  Migrating "minorder"                                                OK
  Migrating "minproducts"                                             OK
  Migrating "Complete"                                                OK
Migrate suppliercode in mshop_product                                 OK
Setting label and status values                                       
  Checking table "mshop_attribute_type":                              OK
  Checking table "mshop_attribute_list_type":                         OK
  Checking table "mshop_catalog_list_type":                           OK
  Checking table "mshop_media_list_type":                             OK
  Checking table "mshop_media_type":                                  OK
  Checking table "mshop_plugin_type":                                 OK
  Checking table "mshop_product_list_type":                           OK
  Checking table "mshop_product_tag_type":                            n/a
  Checking table "mshop_product_type":                                OK
  Checking table "mshop_service_list_type":                           OK
  Checking table "mshop_service_type":                                OK
  Checking table "mshop_text_list_type":                              OK
  Checking table "mshop_text_type":                                   OK
Renaming service configuration                                        OK
Creating platform specific schema                                     
  Using tables from index-mysql.sql                                   
    Checking index "mshop_index_text.idx_msindte_p_s_lt_la_ty_do_va": created
    Checking index "mshop_index_text.idx_msindte_value":              created
  Using tables from order-mysql.sql                                   
    Checking index "mshop_order_base_product_attr.idx_msordbaprat_si_cd_va": created
    Checking index "mshop_order_base_service_attr.idx_msordbaseat_si_cd_va": created
  Using tables from text-mysql.sql                                    
    Checking index "mshop_text.idx_mstex_sid_dom_cont":               created
Processing coupon demo data                                           added
Adding MShop type data for site "default"                             
  Checking "attribute/type" type data                                 11/11
  Checking "attribute/lists/type" type data                           8/8
  Checking "catalog/lists/type" type data                             10/10
  Checking "customer/lists/type" type data                            8/8
  Checking "media/type" type data                                     12/12
  Checking "media/lists/type" type data                               9/9
  Checking "media/property/type" type data                            5/5
  Checking "plugin/type" type data                                    1/1
  Checking "price/type" type data                                     3/3
  Checking "price/lists/type" type data                               2/2
  Checking "product/type" type data                                   4/4
  Checking "product/lists/type" type data                             16/16
  Checking "product/property/type" type data                          4/4
  Checking "stock/type" type data                                     1/1
  Checking "service/type" type data                                   2/2
  Checking "service/lists/type" type data                             8/8
  Checking "supplier/lists/type" type data                            4/4
  Checking "tag/type" type data                                       2/2
  Checking "text/type" type data                                      27/27
  Checking "text/lists/type" type data                                7/7
Adding default code data for site "default"                           
  Checking "customer/group" codes                                     2/2
Processing product demo data                                          added
Processing catalog demo data                                          added
Adding default attribute data for site "default"                      OK
Processing supplier demo data                                         added
Rebuilding index for demo data                                        done
Processing customer demo data                                         added
Adding default plugin data                                            
  Adding data for MShop plugins                                       11/11
Processing service demo data                                          added
Rename "refid" to "parentid" in table "users_address"                 
  Checking column "refid"                                             OK
> App\Composer::account
Create admin account
- E-Mail: mike@regenics.com
- Password: 
Add "admin" group to user "mike@regenics.com" for site "default"

**Comment by aimeos** [comment]
What does this mean? The Aimeos/Laravel application is in your "retail" folder
