### ISSUE TITLE
A non-recoverable error occured

### ISSUE THREAD

**Issue by visualNext** [aimeos/aimeos-laravel#291]
I'm using Laravel 5.3, aimeos/aimeos-laravel "~2018.07", aimeos/aimeos-core "2018.10.*".
Go to https://localhost/list have the problem:

![1567132219258](https://user-images.githubusercontent.com/52145509/63988983-32486a80-cb11-11e9-871e-7c16d45e7aa7.jpg)

And madmin_log table:

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "USE"
LINE 6:      LEFT JOIN "mshop_index_catalog" AS mindca USE INDEX ("i...
                                                       ^
#0 /app/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(378): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /app/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(792): Aimeos\MShop\Common\Manager\Base->getSearchResults(Object(Aimeos\MW\DB\Connection\DBAL), '\n\t\t\t\tSELECT "ke...')
#2 /app/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(219): Aimeos\MShop\Common\Manager\Base->searchItemsBase(Object(Aimeos\MW\DB\Connection\DBAL), Object(Aimeos\MW\Criteria\PgSQL), '\n\t\t\t\tSELECT "ke...', '', Array, NULL, 3)
#3 /app/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Standard.php(83): Aimeos\MShop\Common\Manager\Base->aggregateBase(Object(Aimeos\MW\Criteria\PgSQL), 'index.catalog.i...', 'mshop/index/man...', Array)
#4 [internal function]: Aimeos\MShop\Index\Manager\Standard->aggregate(Object(Aimeos\MW\Criteria\PgSQL), 'index.catalog.i...')
#5 /app/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Decorator/Base.php(51): call_user_func_array(Array, Array)
#6 /app/ext/ai-controller-frontend/controller/frontend/src/Controller/Frontend/Product/Standard.php(179): Aimeos\MShop\Common\Manager\Decorator\Base->__call('aggregate', Array)
#7 /app/ext/ai-client-html/client/html/src/Client/Html/Catalog/Count/Tree/Standard.php(241): Aimeos\Controller\Frontend\Product\Standard->aggregate(Object(Aimeos\MW\Criteria\PgSQL), 'index.catalog.i...')
#8 /app/ext/ai-client-html/client/html/src/Client/Html/Base.php(67): Aimeos\Client\Html\Catalog\Count\Tree\Standard->addData(Object(Aimeos\MW\View\Standard), Array, NULL)
#9 /app/ext/ai-client-html/client/html/src/Client/Html/Catalog/Count/Standard.php(109): Aimeos\Client\Html\Base->addData(Object(Aimeos\MW\View\Standard))
#10 /app/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Base/Page.php(91): Aimeos\Client\Html\Catalog\Count\Standard->getBody()
#11 /app/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Controller/CatalogController.php(32): Aimeos\Shop\Base\Page->getSections('catalog-count')
#12 [internal function]: Aimeos\Shop\Controller\CatalogController->countAction()
#13 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#14 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('countAction', Array)
#15 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Aimeos\Shop\Controller\CatalogController), 'countAction')
#16 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#17 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#40 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#41 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#42 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#43 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /app/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main}

**Comment by aimeos** [comment]
Do you use a MySQL database or something else?

**Comment by visualNext** [comment]
I use postgresSQL.

**Comment by aimeos** [comment]
For PostgreSQL you have to use another configuration:
https://aimeos.org/docs/Developers/Library/Database_support
