### ISSUE TITLE
we have an issue in checkout module, please let me know what is the issue

### ISSUE THREAD

**Issue by gaurav-chaudhari** [aimeos/aimeos-laravel#293]
issue:  customer add to cart one product after that go to the checkout error throw ' Price for the given quantity "1" not available ' stile product has stock see provided images

product view : 
![product display](https://user-images.githubusercontent.com/47390633/66480263-e4cdfe80-eabb-11e9-8984-38bb194776bc.PNG)

basket page:  
![checkout](https://user-images.githubusercontent.com/47390633/66480310-ffa07300-eabb-11e9-976f-a4cc5836496d.PNG)

Error Throw :
![checkouterror](https://user-images.githubusercontent.com/47390633/66479166-928bde00-eab9-11e9-8e69-df1ebddeb663.PNG)

**Comment by aimeos** [comment]
The price for your product has a minimum quantity bigger than 1. Change the miniumn quantity of the product price to 1 in the admin interface.

**Comment by gaurav-chaudhari** [comment]
already we entered minimum qty 1 
![admin qty](https://user-images.githubusercontent.com/47390633/66480859-27440b00-eabd-11e9-9fd9-25ea9b8a9bfb.PNG)

**Comment by aimeos** [comment]
Is that only this product or does it affect more products?

**Comment by gaurav-chaudhari** [comment]
It affected all product

**Comment by aimeos** [comment]
Which basket plugins are enabled? What's the settings of the BasketLimit plugin?

**Comment by gaurav-chaudhari** [comment]
BasketLimit plugin is disabled

**Comment by aimeos** [comment]
BasketLimits plugin is enabled according to your screenshot

**Comment by gaurav-chaudhari** [comment]
you talked about the plugin, so after that, I change and check for anything change or not

**Comment by aimeos** [comment]
Is the minium quantity also "1" for all shipping/payment options?

**Comment by gaurav-chaudhari** [comment]
Thank you, I changed the minimum quantity as "1" in shipping/payment and its working.
