### ISSUE TITLE
SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'users_permissions_user_id_foreign' of table 'ero-6x.users_permissions':

### ISSUE THREAD

**Issue by dukenst2006** [aimeos/aimeos-laravel#295]
**Environment**
1. Version 2019.10
2. Operating system (Windows)

**Describe the bug**
Aimeos\MW\DB\Exception  : SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'users_permissions_user_id_foreign' of table 'ero-6x.users_permissions': ALTER TABLE users ADD superuser SMALLINT DEFAULT 0 NOT NULL, ADD siteid INT DEFAULT NULL, ADD name VARCHAR(255) NOT NULL, ADD salutation VARCHAR(8) NOT NULL, ADD company VARCHAR(100) NOT NULL, ADD vatid VARCHAR(32) NOT NULL, ADD title VARCHAR(64) NOT NULL, ADD firstname VARCHAR(64) NOT NULL, ADD lastname VARCHAR(64) NOT NULL, ADD address1 VARCHAR(200) NOT NULL, ADD address2 VARCHAR(200) NOT NULL, ADD address3 VARCHAR(200) NOT NULL, ADD postal VARCHAR(16) NOT NULL, ADD langid VARCHAR(5) DEFAULT NULL, ADD countryid VARCHAR(2) DEFAULT NULL, ADD telephone VARCHAR(32) NOT NULL, ADD telefax VARCHAR(32) NOT NULL, ADD website VARCHAR(255) NOT NULL, ADD longitude DOUBLE PRECISION DEFAULT NULL, ADD latitude DOUBLE PRECISION DEFAULT NULL, ADD birthday DATE DEFAULT NULL, ADD vdate DATE DEFAULT NULL, ADD editor VARCHAR(255) NOT NULL, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE city city VARCHAR(200) NOT NULL, CHANGE state state VARCHAR(200) NOT NULL, CHANGE status status SMALLINT DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL
I would like to disable the the key constraint with SET FOREIGN_KEY_CHECKS=0; and enable it after but can't find the right location and file to do so. any help will be appreciate.
**To Reproduce**
r
**Expected behavior**
I want the setup success 
**Screenshots**

**Additional context**

**Comment by aimeos** [comment]
You can change the `id` column definition in Aimeos for your setup to your existing definition to it won't be changed: https://github.com/aimeos/ai-laravel/blob/master/lib/custom/setup/default/schema/customer.php#L15

How it's done is documented here: https://aimeos.org/docs/Developers/Library/Setup_tasks/Schema_update#Modify_existing_tables
