### ISSUE TITLE
Weird customer address behavior with onepage checkout

### ISSUE THREAD

**Issue by FlorianMoser** [aimeos/aimeos-laravel#300]
Activating the onepage checkout using the following configuration leads to a weird behavior with order/customer addresses:

```
    'client' => [
        'html' => [
            'checkout' => [
                'standard' => [
                    'onepage' => [
                        'address',
                        'delivery',
                        'payment',
                        'summary',
                    ],
                ],
            ],
        ],
    ],
```

One behavior is, that addresses are not stored with an order. What happens, is that no row is created in mshop_order_base_address, or a previous row is overwritten.

Try this and observe the mshop_order_base_address table before/after each buy:
1. Enable onepage checkout with the above configuration
2. Buy a product as a guest, but leave the "create an account" box checked
3. login as the newly created user and buy again
4. buy a third time

You will notice, that either no address row is generated, or the `basid` of one of the existing row for a user with the same email address (seems random) is simply updated. On the myaccount page you then only see the address for the last order.

I also encountered other issues, where you can't order with an admin account without first creating a new address (simply filling in the billing fields doesn't work, it must be a new address), but this seems depending on other configuration settings.

**Comment by aimeos** [comment]
Thank you for your bug report!

Putting everything (including the summary) on one page is a bit problematic for one more reason:
The customer won't be able to see the total price including the selected shipping/payment options. At least in Europe this isn't allowed.

We will have a look into the problems you mention nevertheless

**Comment by FlorianMoser** [comment]
> The customer won't be able to see the total price including the selected shipping/payment options. 

Yeah, but if you are only selling virtual products there is no shipping cost and payment services very seldom cost something for the customer. So I think this scenario is not that unusual.

Also, wouldn't it be possible to update the checkout summary via JS?

> We will have a look into the problems you mention nevertheless

Thank you.

**Comment by aimeos** [comment]
We've found the problem, minor but big consequence ;-)
https://github.com/aimeos/aimeos-core/commit/2601f5ab90a1a749c1181437bd5b34ced32d8a88

The patch is also in `2019.10.x-dev`. Can you test and tell us if it's fixed for you too?

**Comment by FlorianMoser** [comment]
The problem persists, but slightly different. When I buy with a new user, the address is added to mshop_order_base_address. But on the second (and all to come) buy, there is no address added to that table. Same as before, but before, the baseid was updated to the newest order ID.

This leads to an error when running the jobs (as before):

`Error while trying to send payment e-mail for order ID "4" and status "6": Address not available`

**Comment by aimeos** [comment]
"Second and all to come" means if a >logged in< user buys again?

**Comment by FlorianMoser** [comment]
> "Second and all to come" means if a >logged in< user buys again?

Yes. The address in mshop_order_base_address is only created when filling out the address page the first time. Then, after login and buying again, no more addresses are added.

Something else that might help debug it: When you have your admin account, and in the backend on the client page, you fill in your whole address and then buy something while being logged in, no row is added to mshop_order_base_address.

It seems, that an address row is only created, when you explicitly fill out an empty address form in the checkout. Either the main address when buying as a guest, or the "new address" when being logged in.

**Comment by aimeos** [comment]
We haven't been able to reproduce the issue after using aimeos/aimeos-core 2019.10.x-dev (commit: e765ab24062389ddbc92741e5967a2dafdec6eb0)

If you've installed the same version and the problem still persists, please make a screencast so we know what you are doing to get the error.

**Comment by FlorianMoser** [comment]
I'm currently working with aimeos/aimeos-laravel. Will I get aimeos/aimeos-core 2019.10.x-dev by using aimeos/aimeos-laravel 2019.10.x-dev ? Or how can I update the core only in that situation?

**Comment by aimeos** [comment]
No, just run `composer req aimeos/aimeos-core 2019.10.x-dev`

**Comment by FlorianMoser** [comment]
> No, just run composer req aimeos/aimeos-core 2019.10.x-dev

Ok, my bad. I can confirm it works with this update. Thank you!
