### ISSUE TITLE
Product details

### ISSUE THREAD

**Issue by Tsun13z** [aimeos/aimeos-laravel#301]
hi, i have added products to aimeos e commerce, but when i click the product to see the details i got this errors. can you please tell me how do i fix it?
![image](https://user-images.githubusercontent.com/57425698/68448429-0c78c980-0216-11ea-8ca8-8d576ed46fcd.png)

**Comment by aimeos** [comment]
Seems like you don't have a catalog detail template any more. Did you delete it?

**Comment by Tsun13z** [comment]
hi, where can i find this catalog to check if it is gone?

**Comment by aimeos** [comment]
You can remove the ./ext/ai-client-html directory and run `composer update` again

**Comment by Tsun13z** [comment]
thank you
