### ISSUE TITLE
Wrong product link in summary details

### ISSUE THREAD

**Issue by FlorianMoser** [aimeos/aimeos-laravel#302]
I'm not quite sure from where and from which repository the files in app/ext/ai-laravel come from, otherwise I would have submitted a pull request.

The link to the detail page of a product doesn't work in the summary details (basket, confirmation page, email). It shows something like https://domain.com/shop/ProductName//1

The problem is, that there is no d_pos parameter. In this case, no d_pos and d_prodid parameter should be submitted to Laravels UrlGenerator.

Consider updating Aimeos\MW\View\Helper\Url\Laravel5::transform() to this (added if-statement):

```
/**
 * Returns the URL assembled from the given arguments.
 *
 * @param string|null $target Route or page which should be the target of the link (if any)
 * @param string|null $controller Name of the controller which should be part of the link (if any)
 * @param string|null $action Name of the action which should be part of the link (if any)
 * @param array $params Associative list of parameters that should be part of the URL
 * @param array $trailing Trailing URL parts that are not relevant to identify the resource (for pretty URLs)
 * @param array $config Additional configuration parameter per URL
 * @return string Complete URL that can be used in the template
 */
public function transform( $target = null, $controller = null, $action = null, array $params = [], array $trailing = [], array $config = [] )
{
    $params = $this->sanitize( $params );
    $values = $this->getValues( $config );
    $fragment = ( !empty( $trailing ) ? '#' . implode( '/', $trailing ) : '' );

    if (isset($params['d_pos']) && $params['d_pos'] === '') {
        unset($params['d_pos']);
        unset($params['d_prodid']);
    }

    return $this->builder->route( $target, $params + $this->fixed, $values['absoluteUri'] ) . $fragment;
}
```

**Comment by aimeos** [comment]
The default detail page route contains two optional parameters:
```
Route::match( array( 'GET', 'POST' ), '{d_name}/{d_pos?}/{d_prodid?}', array(
	'as' => 'aimeos_shop_detail',
	'uses' => 'Aimeos\Shop\Controller\CatalogController@detailAction'
))->where( ['site' => '[a-z0-9\.\-]+', 'd_pos' => '[0-9]*'] );
```
You need the d_pos and d_prodid parameter to match that route, even if the route looks a bit arkward:
http://127.0.0.1:8000/shop/Demo_voucher//62

The d_prodid parameter is required to find the product even if the product name isn't found for some reason.

**Comment by FlorianMoser** [comment]
My problem is, that I get a 404 with this "awkward" URL. But I just found out why. I had a custom route for the details page, but without the where() clause:

```
    Route::match(array('GET', 'POST'), 'detail/{d_name}/{d_pos?}/{d_prodid?}', array(
        'as' => 'aimeos_shop_detail',
        'uses' => '\Aimeos\Shop\Controller\CatalogController@detailAction',
    ));
```

Dunno if this has recently been updated or if I simply failed to copy the where-part.
