### ISSUE TITLE
How can I have a main shop where be able to load the other product from other shop?

### ISSUE THREAD

**Issue by ljieyao** [aimeos/aimeos-laravel#304]
As stated in the title, for example, I have created site `A`, `B`, and `C`, and for each of them, I have created product `A1`, `A2`, `A3`, `B1`, `B2`, `B3`, `C1`, `C2`, `C3`, respectively. How can I make site `A` as the main site which be able to load all product regardless of sites while site `B` and `C` remains as the children site which only be able to load their own products?

**Comment by aimeos** [comment]
The Aimeos company offers their market place extension for that:
https://aimeos.com/extensions#c436

**Comment by ljieyao** [comment]
i see. ok. thx.
