### ISSUE TITLE
Change title from Aimeos to AppName

### ISSUE THREAD

**Issue by pvoneat** [aimeos/aimeos-laravel#309]
Hi developers, I am new to the framework. I could not find how to change the title in admin dashboard from "Aimeos admistration interface" to something else. Could anyone guide me how to do so? 

Kind regards,

**Comment by aimeos** [comment]
Overwrite this template: https://github.com/aimeos/aimeos-laravel/blob/master/src/views/jqadm/index.blade.php#L7
Copy it to ./resources/views/vendor/shop/jqadm/index.blade.php and change the title
