### ISSUE TITLE
Please Add payment gateway integration for Razor pay.  Oh just Guide me how to do it.

### ISSUE THREAD

**Issue by care-incogtech** [aimeos/aimeos-laravel#312]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Additional context**

**Comment by aimeos** [comment]
There seems to be an Omnipay driver for Razorpay and for installation use (according to the GitHub page https://github.com/razorpay/omnipay-razorpay):
```
composer req aimeoscom/ai-payments razorpay/omnipay-razorpay

**Comment by care-incogtech** [comment]
@aimeos This package is not working i have tried it. Plus if I installed a payment gateway. How can i configure it? Can you guide?

**Comment by aimeos** [comment]
There are two other packages available that may work:
https://packagist.org/?query=omnipay-razorpay

The configuration for a payment gateway depends a lot on the required configuration for that gateway. You can have a look into how other gateways are configured:
https://aimeos.org/docs/User_Manual/Administration_Interface/Service_list#Supported_by_ai-payments

If you get it to work, it would be great if you could provide documentation how to configure it correctly :-)
