### ISSUE TITLE
Single coupon option

### ISSUE THREAD

**Issue by danb7788** [aimeos/aimeos-laravel#313]
Hi,

I think most ecommerce sites implement a single coupon code feature, in which when a new coupon code is added, any previously entered one is removed. It would be great if Aimeos had a built-in option to choose between multi coupon code and single coupon code functionality in the basket.

To have single coupon code functionality in my project, I just modified the js so that an ajax get request is sent to /shop/basket?b_action=coupon-delete&b_coupon=[name_of_previous_coupon] when a coupon code is entered in the input.

Hope this helps!

**Comment by aimeos** [comment]
Thank you for your feature request. We will see how we can integrate it into the next version.

**Comment by aimeos** [comment]
Your feature request has been implemented now:
https://github.com/aimeos/ai-client-html/commit/62281e9edee4b1423d03341915be1f821b08c18a
