### ISSUE TITLE
No item found for conditions: Array ( [locale.site.code] => default )

### ISSUE THREAD

**Issue by sikandar-helpsquare** [aimeos/aimeos-laravel#314]
I installed complete package but I am running this project through `artisan ` command I am facing this error.
What is the issue ???
And also Facing this exception
`SQLSTATE[HY000]: General error: 1005 Can't create table `ecommerce_app_db`.`users_address` (errno: 150 ER TABLE users_address ADD CONSTRAINT fk_lvuad_pid FOREIGN KEY (parentid) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE`

**Comment by aimeos** [comment]
According to the SQL error, your `users.id` column is different from what's expected by MySQL.
Is your `users.id` column not `unsigned`?
https://github.com/aimeos/ai-laravel/blob/master/lib/custom/setup/default/schema/customer.php#L15
