### ISSUE TITLE
help to issue an invoice

### ISSUE THREAD

**Issue by adansernas** [aimeos/aimeos-laravel#315]
Greetings, I would appreciate if you help me with the following question. How can I invoke a function after making the payment? This will help me to issue an invoice

**Comment by aimeos** [comment]
After the payment, the customer is redirected back to the shop and the page with the checkout confirm component is shown. You can add you own subpart to that component that cares about invoicing:
- https://github.com/aimeos/ai-client-html/tree/master/client/html/src/Client/Html/Checkout/Confirm
- https://aimeos.org/docs/Developers/Html_frontend/Create_new_subparts
