### ISSUE TITLE
Order history being deleted

### ISSUE THREAD

**Issue by FlorianMoser** [aimeos/aimeos-laravel#316]
**Environment**
1. Version aimeos/aimeos-core 2019.10.15, aimeos/aimeos-laravel 2019.10.2
2. Operating system OSX

When ordering as logged in user, meta data from previous order is being overwritten by newest order meta data.

How to reproduce:
1. Create a new user
2. Make an order
3. Check the mshop_order_base_address table, a new line was added for the latest order
4. Order again with the same user (logged in)
5. Check the mshop_order_base_address table. There should be a new line with a new ID, but the previous line from step 2./3. ist just updated to the new order ID

The same happens with the mshop_order_base_service_attr table (maybe other tables like mshop_order_base_coupon are also concerned).

This means, that when you look at older orders (either as admin or as client on the my-account page), there is no address and no order attribute visible.

This is probably related to #300 

Unlike #300 I no longer have a weird checkout configuration. It is now:

````
'client' => [
    'html' => [
        'checkout' => [
            'standard' => [
                'standard' => [
                    'subparts' => [
                        'address',
                        'payment',
                        'summary',
                        'process',
                    ],
                ],
                'onepage' => [
                    'address',
                    'payment',
                ],
            ],
        ],
    ],
],
````

**Comment by aimeos** [comment]
We've done a quick test using a standard setup (no one page checkout) and it did work as expected. No addresses or services had been reused and moved to the new order.

Our composer packages for testing:
```
aimeos/ai-admin-jqadm                 2019.10.9             Aimeos ai-admin-jqadm ext...
aimeos/ai-admin-jsonadm               2019.10.3             Aimeos ai-admin-jsonadm e...
aimeos/ai-client-html                 2019.10.12            Aimeos ai-client-html ext...
aimeos/ai-client-jsonapi              2019.10.3             Aimeos JSON API extension
aimeos/ai-controller-frontend         2019.10.8             Aimeos ai-controller-fron...
aimeos/ai-controller-jobs             2019.10.8             Aimeos ai-controller-jobs...
aimeos/ai-gettext                     2019.10.1             Aimeos Gettext extension
aimeos/ai-laravel                     2019.10.4             Laravel adapter for Aimeo...
aimeos/ai-swiftmailer                 2019.10.1             SwiftMailer adapter for A...
aimeos/aimeos-core                    2019.10.15            Full-featured e-commerce ...
aimeos/aimeos-laravel                 2019.10.2             Professional, full-featur...
```

Does it work for you without your configuration too?

**Comment by FlorianMoser** [comment]
I can confirm I have the same packages installed.

I just cleared my shop config file (removed all kind of customizations) and the user address is still updated instead of being added as a new row.

**Comment by aimeos** [comment]
Can you create a screencast so we can see what exactly are you doing?

**Comment by FlorianMoser** [comment]
I just discovered something that might be helpful:

1. The first time I go through the  order process with a new client, I have to visit every page/form (basket, address, delivery, payment, confirm).
2. The second time I go through the process (while being logged in), I'm directly redirected to the confirmation page/form. I'm never visiting the address page/form. This is where the previous address is overwritten.
3. If I do the process again, but explicitly visit the address page/form (without changing anything, just clicking "next"), a new address is added.

It seems the bug only appears, when the user doesn't explicitly load the address form/page.

Does this help? If not, I will do a screencast.

**Comment by aimeos** [comment]
That hint was very helpful! We've explicitely reset the ID now in https://github.com/aimeos/aimeos-core/commit/c2f6242884237a6065015789ac794a6bc1327396
Can you run `composer req aimeos/aimeos-core:2019.10.x-dev` and see if the problem is gone now?

**Comment by FlorianMoser** [comment]
I can confirm that the update resolves the problem with the address. mshop_order_base_address now properly adds a row for every order.

However, mshop_order_base_service_attr still overwrites values. I suppose it's the same issue with services (payment and delivery page/form being skipped).

**Comment by aimeos** [comment]
OK, forgot the attributes. Now it should work and the unit tests reflect that too.

**Comment by FlorianMoser** [comment]
Perfect, the attributes now work.

However now I discovered something else: I login, make an order, return to the shop, make another order, go to checkout and now on the overview page, it displays the service attributes from the first order (TRANSACTIONID from Stripe, etc.).

This is not an issue for me, as I can hide those attributes on the checkout page, but I'm not sure if this is intended.

**Comment by aimeos** [comment]
For payment services that isn't desired but for delivery services it might be but not always. Not sure how to handle this. Maybe they should be always removed to be on the save side ...

**Comment by FlorianMoser** [comment]
What I also observed:
The first time I buy and klick on the "go to checkout" button, I'm lead to the address page. I can verify address and choose a payment method.

But the second time, I'm lead directly to the overview page. Payment method is set to the method I chose in the first order. I have no option (unless I explicitly click "change" or go back in the order process) to choose a payment method.

I think this is related to the issue. The payment method is probably preselected, because the payment service from the last order is active. If this is the case, I would remove at least the previous payment service on a new order.

**Comment by aimeos** [comment]
You can disable that behavior if you disable the Autofill plugin

**Comment by FlorianMoser** [comment]
Perfect. Thanks for the updates. Will the changes be reflected in a stable release anytime soon?

I'll close the issue, as the main problem has been solved.

**Comment by aimeos** [comment]
The service attributes are now removed in the Autofill plugin before adding the services to the basket.
The changes are in 2019.10.x-dev and will be part of the next release in the next few days.
