### ISSUE TITLE
I wanna separate search bar and its categories and filter option please guide me how to do that.

### ISSUE THREAD

**Issue by noob-coder-elseif** [aimeos/aimeos-laravel#318]
![aimeosgithubsearchbar_LI](https://user-images.githubusercontent.com/61415609/75153206-d4e44d80-5730-11ea-80a1-5df80466a1a8.jpg)

**Comment by aimeos** [comment]
The catalog/filter component is also available as seperate components:
- catalog/search
- catalog/tree
- catalog/supplier
- catalog/attribute

You can use them in the `pages` section (https://github.com/aimeos/aimeos-laravel/blob/master/src/default.php#L17) instead of catalog/filter. You only have to overwrite the Blade template for the list view (https://github.com/aimeos/aimeos-laravel/blob/master/src/views/catalog/list.blade.php) and add single component output.

**Comment by noob-coder-elseif** [comment]
Please tell me what I'm doing wrong....
![defaultphp](https://user-images.githubusercontent.com/61415609/75159125-91441080-573d-11ea-8dcf-fab9a7d97ac5.PNG)
![listbladephp](https://user-images.githubusercontent.com/61415609/75159134-94d79780-573d-11ea-889f-6dd299812015.PNG)
![error](https://user-images.githubusercontent.com/61415609/75159139-9739f180-573d-11ea-9812-ff829411011e.PNG)

**Comment by noob-coder-elseif** [comment]
> The catalog/filter component is also available as seperate components:
> 
> * catalog/search
> * catalog/tree
> * catalog/supplier
> * catalog/attribute
> 
> You can use them in the `pages` section (https://github.com/aimeos/aimeos-laravel/blob/master/src/default.php#L17) instead of catalog/filter. You only have to overwrite the Blade template for the list view (https://github.com/aimeos/aimeos-laravel/blob/master/src/views/catalog/list.blade.php) and add single component output.

Please tell me what I'm doing wrong....
![defaultphp](https://user-images.githubusercontent.com/61415609/75161181-6360cb00-5741-11ea-9551-cce991107443.PNG)
![listbladephp](https://user-images.githubusercontent.com/61415609/75161191-66f45200-5741-11ea-9dc9-5e3cd1b1fcf5.PNG)
![error](https://user-images.githubusercontent.com/61415609/75161198-69ef4280-5741-11ea-963b-a6ca11cf530f.PNG)

**Comment by aimeos** [comment]
Did you changed the `pages` section in your ./config/shop.php file?

**Comment by noob-coder-elseif** [comment]
> Did you changed the `pages` section in your ./config/shop.php file?

yes...
![shophpinconfig](https://user-images.githubusercontent.com/61415609/75162279-4cbb7380-5743-11ea-9b53-7a6785a7086b.PNG)

**Comment by aimeos** [comment]
Seems to be fine. The controller resolves the catalog/search client and adds it to the Blade view:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/CatalogController.php#L68-L78

Can you have a look what happens in the controller?

**Comment by noob-coder-elseif** [comment]
> Seems to be fine. The controller resolves the catalog/search client and adds it to the Blade view:
> https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/CatalogController.php#L68-L78
> 
> Can you have a look what happens in the controller?

Seems Same to me as u suggested
![catalogControllerphp](https://user-images.githubusercontent.com/61415609/75177319-eb53ce80-575b-11ea-8c85-13e5e9dda20d.PNG)
