### ISSUE TITLE
Laravel 5.2 support - when?

### ISSUE THREAD

**Issue by jurchiks** [aimeos/aimeos-laravel#32]
Title says it all.

**Comment by aimeos** [comment]
Laravel 5.2 is already supported in the 2016.x versions

**Comment by jurchiks** [comment]
Your master README says 1.2 is the stable version. I guess I should have rephrased the title - STABLE support - when?

**Comment by aimeos** [comment]
2016.04 will be the next stable branch and scheduled for next week.

**Comment by jurchiks** [comment]
Ok, thanks.
