### ISSUE TITLE
how to add delivery providers that calculate and show price according to delivery city and products weight select?

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#320]
hello, i want to add a delivery provider in such a way that according to customer select a state and city in address, delivery price calculate and show to customer, i mean i have a third-party delivery provider that give delivery price based on the destination city and products weight, because it when customer checkout shop cart and select delivery city, send an API request to delivery provider web service and get price and set it on checkout process, what should I do to implement this?

**Comment by parsester** [comment]
@aimeos please help me for this.

**Comment by aimeos** [comment]
Create a decorator for your delivery service that returns the calculated price:
https://aimeos.org/docs/Developers/Library/Service

If you have more questions, please ask in the Aimeos forum (https://aimeos.org/help). Github issues are only for bug reports and feature requests.
