### ISSUE TITLE
Class 'Aimeos\MShop\Factory' not found in my extension

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#322]
**Environment**
1. Version 2019.10
2. Operating system Windows

**Describe the bug**
i create extension with Aimeos extension builder and add my extension folders to composer.json autoload classmap of laravel app and after that run composer dump-autoload
i add my custom delivery provider in my extension, in the function calcPrice of my own provider add 
$manager = \Aimeos\MShop\Factory::createManager( $this->getContext(), 'price' );
but i get error Class 'Aimeos\MShop\Factory' not found in my extension in /shop/checkout/delivery

**Screenshots**
![2020-04-05_00-29-03](https://user-images.githubusercontent.com/16049244/78460290-d8c2a280-76d4-11ea-97e2-922ff9b9f2c4.jpg)
![2020-04-05_00-30-06](https://user-images.githubusercontent.com/16049244/78460293-dc562980-76d4-11ea-853d-3cf8315c27f0.jpg)
![2020-04-05_00-30-27](https://user-images.githubusercontent.com/16049244/78460296-dd875680-76d4-11ea-8d39-13bc331d0b18.jpg)

@aimeos please help me to fix this problem, i follow your add extension steps.

**Comment by aimeos** [comment]
Where did you read about ` \Aimeos\MShop\Factory::createManager( $this->getContext(), 'price' );`?
It's ` \Aimeos\MShop::create( $this->getContext(), 'price' );` in 2019.x

The deprecation warnings are wrong messages in composer 1.10. We've opened an issue for that:
https://github.com/composer/composer/issues/8722
