### ISSUE TITLE
Want To Get Own Billing/Delivery Address Fields And Calculate Price

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#323]
@aimeos 
please and please and please help me in a simple and clear way to fix my problem with aimeos:

i want to change checkout process like this:
customer add this field for billing and delivery address:
First Name-Last Name-Mobile Number-Telephone Number-State (choose from select box)-City (choose from select box)-Address-Additional
- when customer choose state (state change) options in the City select box change according to selected state ( i mean show cities of chosen state)
- after customer selected city (i have a city id), my Delivery service price updated with send data (include city_id, products_price and products_total_weights) to third party logistic company API and get shipping price and set for delivery cost
- i want to happen this in one page not step by step
- and after that show summary and set order;

please give me a simple solution, i did a search and found that your system is very, very, very complicated, please give me right solution don't refer me to a few different articles.

**Comment by aimeos** [comment]
Please ask questions about configuration and setup in the Aimeos forum: https://aimeos.org/help
