### ISSUE TITLE
In Which File I need to add the 767 bytes Issue ?

### ISSUE THREAD

**Issue by dschiller** [aimeos/aimeos-laravel#324]
This goes to which File ?
```
'connections' => [
    'mysql' => [
        // ...
        'charset' => 'utf8',
        'collation' => 'utf8_unicode_ci',
        // ...
    ]
]
```

**Comment by dschiller** [comment]
Tried that:

![image](https://user-images.githubusercontent.com/3144986/79044797-823ef200-7c07-11ea-939e-22e79a6fb63f.png)


But deosn't work.

Any Help ?

**Comment by dschiller** [comment]
Tried also to move it one level down, but doesn't work:

![image](https://user-images.githubusercontent.com/3144986/79044821-bca88f00-7c07-11ea-80fa-c9fab63ccedb.png)

**Comment by aimeos** [comment]
In ./config/database.php
