### ISSUE TITLE
Import CSV : an option to update (if exists)

### ISSUE THREAD

**Issue by tyteck** [aimeos/aimeos-laravel#325]
First of all, Hi guys and thanks for Aimeos.

I'm using Aimeos Import from CSV file feature. I receive data from many partners and update my store frequently with their data.
They are sending product/stock updates this way.
On every update I will receive and use their product.code.id with (maybe) different updates (stock/price...)

When I run `php artisan aimeos:jobs product/import/csv` the first time everything is fine.
On the second time I obtain (and it's logivcal) `Integrity constraint violation: 1062 Duplicate entry '1-1`.
Is there an option that allow the import to update existing product (if exists) with updateOrCreate function ?

If not, How can I handle this properly ?  Please don't tell me I have to delete a record before insert it it again.

Thanks for any clue.

**Comment by aimeos** [comment]
If the CSV contains the IDs of the records from your partners, use that as product.code value (if you haven't done yet). Your constraint violation for '1-1.' sounds like there are one or more lines without a value for the ID (=product.code). For more suggestions, you should create a thread in the Aimeos forum (https://aimeos.org/help) and post your mapping and a minimal CSV file that produces the error.
