### ISSUE TITLE
product is not deleteing

### ISSUE THREAD

**Issue by Mizan-Rifat** [aimeos/aimeos-laravel#326]
when i try to delete an existing product it shows:

> ErrorPDO::quote() expects parameter 1 to be string, object given, C:\xampp\htdocs\LaravelAimeos\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:89

**Comment by aimeos** [comment]
Which Aimeos version are you using? Can you show us the output of `composer show`

**Comment by Mizan-Rifat** [comment]
`aimeos/ai-admin-jqadm                 2019.10.12 Aimeos ai-admin-jqadm extension
aimeos/ai-admin-jsonadm               2019.10.4  Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html                 2019.10.14 Aimeos ai-client-html extension
aimeos/ai-client-jsonapi              2019.10.5  Aimeos JSON API extension
aimeos/ai-controller-frontend         2019.10.9  Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs             2019.10.12 Aimeos ai-controller-jobs extension
aimeos/ai-gettext                     2019.10.1  Aimeos Gettext extension
aimeos/ai-laravel                     2019.10.6  Laravel adapter for Aimeos web shops and e-commerce solutions
aimeos/ai-swiftmailer                 2019.10.1  SwiftMailer adapter for Aimeos web shops and e-commerce solutions
aimeos/aimeos-core                    2019.10.21 Full-featured e-commerce components for high performance online s...
aimeos/aimeos-laravel                 2019.10.3  Professional, full-featured and high performance Laravel e-commer...
composer/installers                   v1.9.0     A multi-framework Composer library installer
dnoegel/php-xdg-base-dir              v0.1.1     implementation of xdg base directory specification for php
doctrine/cache                        1.10.0     PHP Doctrine Cache library is a popular cache implementation that...
doctrine/dbal                         v2.10.1    Powerful PHP database abstraction layer (DBAL) with many features...
doctrine/event-manager                1.1.0      The Doctrine Event Manager is a simple PHP event system that was ...
doctrine/inflector                    1.3.1      Common String Manipulations with regard to casing and singular/pl...
doctrine/instantiator                 1.3.0      A small, lightweight utility to instantiate objects in PHP withou...
doctrine/lexer                        1.2.0      PHP Doctrine Lexer parser library that can be used in Top-Down, R...
dragonmantank/cron-expression         v2.3.0     CRON for PHP: Calculate the next or previous run date and determi...
egulias/email-validator               2.1.17     A library for validating emails against several RFCs
facade/flare-client-php               1.3.2      Send PHP errors to Flare
facade/ignition                       1.16.1     A beautiful error page for Laravel applications.
facade/ignition-contracts             1.0.0      Solution contracts for Ignition
fideloper/proxy                       4.3.0      Set trusted proxies for Laravel
filp/whoops                           2.7.1      php error handling for cool kids
fzaninotto/faker                      v1.9.1     Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v2.0.0     This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       v0.2
jakub-onderka/php-console-highlighter v0.4       Highlight PHP code in terminal
laminas/laminas-diactoros             1.8.7p2    PSR HTTP Message implementations
laminas/laminas-zendframework-bridge  1.0.3      Alias legacy ZF class names to Laminas Project equivalents.
laravel/framework                     v6.18.6    The Laravel Framework.
laravel/tinker                        v1.0.10    Powerful REPL for the Laravel framework.
laravel/ui                            v1.2.0     Laravel UI utilities and presets.
league/commonmark                     1.3.3      Highly-extensible PHP Markdown parser which fully supports the Co...
league/flysystem                      1.0.66     Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       1.3.1      Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                       2.0.2      Sends your logs to files, sockets, inboxes, databases and various...
myclabs/deep-copy                     1.9.5      Create deep copies (clones) of your objects
nesbot/carbon                         2.32.2     An API extension for DateTime that supports 281 different languages.
nikic/php-parser                      v4.4.0     A PHP parser written in PHP
nunomaduro/collision                  v3.0.1     Cli error handling for console/command-line PHP applications.
nyholm/psr7                           1.2.1      A fast PHP7 implementation of PSR-7
opis/closure                          3.5.1      A library that can be used to serialize closures (anonymous funct...
paragonie/random_compat               v9.99.99   PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.3      Component for reading phar.io manifest information from a PHP Arc...
phar-io/version                       2.0.1      Library for handling version information and constraints
php-http/message-factory              v1.0.2     Factory interfaces for PSR-7 HTTP Message
phpdocumentor/reflection-common       2.0.0      Common reflection classes used by phpdocumentor to reflect the co...
phpdocumentor/reflection-docblock     5.1.0      With this component, a library can provide support for annotation...
phpdocumentor/type-resolver           1.1.0      A PSR-5 based resolver of Class names, Types and Structural Eleme...
phpoption/phpoption                   1.7.3      Option Type for PHP
phpspec/prophecy                      v1.10.3    Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             7.0.10     Library that provides collection, processing, and rendering funct...
phpunit/php-file-iterator             2.0.2      FilterIterator implementation that filters files based on a list ...
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     2.1.2      Utility class for timing
phpunit/php-token-stream              3.1.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       8.5.3      The PHP Unit Testing framework.
psr/container                         1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-factory                      1.0.1      Common interfaces for PSR-7 HTTP message factories
psr/http-message                      1.0.1      Common interface for HTTP messages
psr/log                               1.1.3      Common interface for logging libraries
psr/simple-cache                      1.0.1      Common interfaces for simple caching
psy/psysh                             v0.9.12    An interactive shell for modern PHP.
ramsey/uuid                           3.9.3      Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122...
scrivo/highlight.php                  v9.18.1.1  Server side syntax highlighter that supports 185 languages. It's ...
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.2      Diff implementation
sebastian/environment                 4.2.3      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.2      Provides the functionality to export PHP variables for visualization
sebastian/global-state                3.0.0      Snapshotting of global state
sebastian/object-enumerator           3.0.3      Traverses array structures and object graphs to enumerate all ref...
sebastian/object-reflector            1.1.1      Allows reflection of object attributes, including inherited and n...
sebastian/recursion-context           3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/type                        1.1.3      Collection of value objects that represent the types of the PHP t...
sebastian/version                     2.0.1      Library that helps with managing the version number of Git-hosted...
swiftmailer/swiftmailer               v6.2.3     Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.4.7     Symfony Console Component
symfony/css-selector                  v5.0.7     Symfony CssSelector Component
symfony/debug                         v4.4.7     Symfony Debug Component
symfony/error-handler                 v4.4.7     Symfony ErrorHandler Component
symfony/event-dispatcher              v4.4.7     Symfony EventDispatcher Component
symfony/event-dispatcher-contracts    v1.1.7     Generic abstractions related to dispatching event
symfony/finder                        v4.4.7     Symfony Finder Component
symfony/http-foundation               v4.4.7     Symfony HttpFoundation Component
symfony/http-kernel                   v4.4.7     Symfony HttpKernel Component
symfony/mime                          v5.0.7     A library to manipulate MIME messages
symfony/polyfill-ctype                v1.15.0    Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.15.0    Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn             v1.15.0    Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring             v1.15.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.15.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP ...
symfony/polyfill-php73                v1.15.0    Symfony polyfill backporting some PHP 7.3+ features to lower PHP ...
symfony/process                       v4.4.7     Symfony Process Component
symfony/psr-http-message-bridge       v1.3.0     PSR HTTP message bridge
symfony/routing                       v4.4.7     Symfony Routing Component
symfony/service-contracts             v2.0.1     Generic abstractions related to writing services
symfony/translation                   v4.4.7     Symfony Translation Component
symfony/translation-contracts         v2.0.1     Generic abstractions related to translation
symfony/var-dumper                    v4.4.7     Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.3      A small library for converting tokenized PHP source code into XML...
tijsverkoyen/css-to-inline-styles     2.2.2      CssToInlineStyles is a class that enables you to convert HTML-pag...
vlucas/phpdotenv                      v3.6.3     Loads environment variables from `.env` to `getenv()`, `$_ENV` an...
webmozart/assert                      1.7.0      Assertions to validate method input/output with nice error messages.`

**Comment by aimeos** [comment]
Can you please post the complete stack trace of the error?

**Comment by Mizan-Rifat** [comment]
it's not showing anything else...

**Comment by aimeos** [comment]
Without more information i'ts impossible to find the source of the problem

**Comment by yosirn** [comment]
Having the same issue :
`aimeos/ai-admin-jqadm                 2019.10.14 Aimeos ai-admin-jqadm extension
aimeos/ai-admin-jsonadm               2019.10.4  Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html                 2019.10.16 Aimeos ai-client-html extension
aimeos/ai-client-jsonapi              2019.10.5  Aimeos JSON API extension
aimeos/ai-controller-frontend         2019.10.9  Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs             2019.10.14 Aimeos ai-controller-jobs extension
aimeos/ai-gettext                     2019.10.1  Aimeos Gettext extension
aimeos/ai-laravel                     2019.10.7  Laravel adapter for Aimeos web shops and e-commerce solutions
aimeos/ai-swiftmailer                 2019.10.1  SwiftMailer adapter for Aimeos web shops and e-commerce solutions
aimeos/aimeos-core                    2019.10.25 Full-featured e-commerce components for high performance online shops
aimeos/aimeos-laravel                 2019.10.4  Professional, full-featured and high performance Laravel e-commerce package for online s...
composer/installers                   v1.9.0     A multi-framework Composer library installer
dnoegel/php-xdg-base-dir              v0.1.1     implementation of xdg base directory specification for php
doctrine/cache                        1.10.0     PHP Doctrine Cache library is a popular cache implementation that supports many differen...
doctrine/dbal                         2.10.2     Powerful PHP database abstraction layer (DBAL) with many features for database schema in...
doctrine/event-manager                1.1.0      The Doctrine Event Manager is a simple PHP event system that was built to be used with t...
doctrine/inflector                    1.4.1      PHP Doctrine Inflector is a small library that can perform string manipulations with reg...
doctrine/instantiator                 1.3.0      A small, lightweight utility to instantiate objects in PHP without invoking their constr...
doctrine/lexer                        1.2.0      PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dragonmantank/cron-expression         v2.3.0     CRON for PHP: Calculate the next or previous run date and determine if a CRON expression...
egulias/email-validator               2.1.17     A library for validating emails against several RFCs
facade/flare-client-php               1.3.2      Send PHP errors to Flare
facade/ignition                       1.16.1     A beautiful error page for Laravel applications.
facade/ignition-contracts             1.0.0      Solution contracts for Ignition
fideloper/proxy                       4.3.0      Set trusted proxies for Laravel
filp/whoops                           2.7.2      php error handling for cool kids
fzaninotto/faker                      v1.9.1     Faker is a PHP library that generates fake data for you.
hamcrest/hamcrest-php                 v2.0.0     This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       v0.2      
jakub-onderka/php-console-highlighter v0.4       Highlight PHP code in terminal
laminas/laminas-diactoros             1.8.7p2    PSR HTTP Message implementations
laminas/laminas-zendframework-bridge  1.0.3      Alias legacy ZF class names to Laminas Project equivalents.
laravel/framework                     v6.18.13   The Laravel Framework.
laravel/tinker                        v1.0.10    Powerful REPL for the Laravel framework.
laravel/ui                            v1.2.0     Laravel UI utilities and presets.
league/commonmark                     1.4.3      Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and Githu...
league/flysystem                      1.0.67     Filesystem abstraction: Many filesystems, one API.
mockery/mockery                       1.3.1      Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                       2.0.2      Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                     1.9.5      Create deep copies (clones) of your objects
nesbot/carbon                         2.33.0     An API extension for DateTime that supports 281 different languages.
nikic/php-parser                      v4.4.0     A PHP parser written in PHP
nunomaduro/collision                  v3.0.1     Cli error handling for console/command-line PHP applications.
nyholm/psr7                           1.2.1      A fast PHP7 implementation of PSR-7
opis/closure                          3.5.1      A library that can be used to serialize closures (anonymous functions) and arbitrary obj...
paragonie/random_compat               v9.99.99   PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                      1.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                       2.0.1      Library for handling version information and constraints
php-http/message-factory              v1.0.2     Factory interfaces for PSR-7 HTTP Message
phpdocumentor/reflection-common       2.1.0      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     5.1.0      With this component, a library can provide support for annotations via DocBlocks or othe...
phpdocumentor/type-resolver           1.1.0      A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                   1.7.3      Option Type for PHP
phpspec/prophecy                      v1.10.3    Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             7.0.10     Library that provides collection, processing, and rendering functionality for PHP code c...
phpunit/php-file-iterator             2.0.2      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1      Simple template engine.
phpunit/php-timer                     2.1.2      Utility class for timing
phpunit/php-token-stream              3.1.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       8.5.4      The PHP Unit Testing framework.
psr/container                         1.0.0      Common Container Interface (PHP FIG PSR-11)
psr/http-factory                      1.0.1      Common interfaces for PSR-7 HTTP message factories
psr/http-message                      1.0.1      Common interface for HTTP messages
psr/log                               1.1.3      Common interface for logging libraries
psr/simple-cache                      1.0.1      Common interfaces for simple caching
psy/psysh                             v0.9.12    An interactive shell for modern PHP.
ramsey/uuid                           3.9.3      Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5...
scrivo/highlight.php                  v9.18.1.1  Server side syntax highlighter that supports 185 languages. It's a PHP port of highlight.js
sebastian/code-unit-reverse-lookup    1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator                  3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                        3.0.2      Diff implementation
sebastian/environment                 4.2.3      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    3.1.2      Provides the functionality to export PHP variables for visualization
sebastian/global-state                3.0.0      Snapshotting of global state
sebastian/object-enumerator           3.0.3      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector            1.1.1      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context           3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations         2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/type                        1.1.3      Collection of value objects that represent the types of the PHP type system
sebastian/version                     2.0.1      Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v6.2.3     Swiftmailer, free feature-rich PHP mailer
symfony/console                       v4.4.8     Symfony Console Component
symfony/css-selector                  v5.0.8     Symfony CssSelector Component
symfony/debug                         v4.4.8     Symfony Debug Component
symfony/error-handler                 v4.4.8     Symfony ErrorHandler Component
symfony/event-dispatcher              v4.4.8     Symfony EventDispatcher Component
symfony/event-dispatcher-contracts    v1.1.7     Generic abstractions related to dispatching event
symfony/finder                        v4.4.8     Symfony Finder Component
symfony/http-foundation               v4.4.8     Symfony HttpFoundation Component
symfony/http-kernel                   v4.4.8     Symfony HttpKernel Component
symfony/mime                          v5.0.8     A library to manipulate MIME messages
symfony/polyfill-ctype                v1.16.0    Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.16.0    Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn             v1.16.0    Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring             v1.16.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                v1.16.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                v1.16.0    Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                       v4.4.8     Symfony Process Component
symfony/psr-http-message-bridge       v1.3.0     PSR HTTP message bridge
symfony/routing                       v4.4.8     Symfony Routing Component
symfony/service-contracts             v2.0.1     Generic abstractions related to writing services
symfony/translation                   v4.4.8     Symfony Translation Component
symfony/translation-contracts         v2.0.1     Generic abstractions related to translation
symfony/var-dumper                    v4.4.8     Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                     1.1.3      A small library for converting tokenized PHP source code into XML and potentially other ...
tijsverkoyen/css-to-inline-styles     2.2.2      CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-page...
vlucas/phpdotenv                      v3.6.4     Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagica...
webmozart/assert                      1.8.0      Assertions to validate method input/output with nice error messages.
`

**Comment by aimeos** [comment]
Can you post a full stack trace of the error please?

**Comment by yosirn** [comment]
I don't think I can .
it throws this error instead ` Error PDO::quote() expects parameter 1 to be string, object given, /MyApp/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:92`

**Comment by aimeos** [comment]
Can you record a screen cast what you do when the error occurs?

**Comment by yosirn** [comment]
I just click delete item and confirm , the action get submitted but return this error after a while.
I don't know what the error may be as I didn't change anything from the demo app except some locale configs 
![Screenshot from 2020-05-18 13-42-28](https://user-images.githubusercontent.com/10193377/82220108-bf388b80-990d-11ea-8269-07629e8b389d.png)

**Comment by aimeos** [comment]
Can you please have a look into the Log panel? There should be a stack trace of the error

**Comment by yosirn** [comment]
Only some items produce this error some could be deleted. please find bellow my today's log if that may help.

[log-18-05.log](https://github.com/aimeos/aimeos-laravel/files/4645134/log-18-05.log)

**Comment by aimeos** [comment]
There's no error related to that problem :-/
Which items could you delete and which ones not?

**Comment by aimeos** [comment]
Think, we've found the problem. Can you execute
`composer req aimeos/aimeos-core:2019.10.x-dev`
and test if it works now?

**Comment by yosirn** [comment]
Products I wasn't able delete are IDs 8,11,12 from the demo.
this fixed it now they can be deleted 
Thanks

**Comment by aimeos** [comment]
New release of the core (2019.10.26) is tagged.
Thank you very much for your help!!! :-)
