### ISSUE TITLE
[Vue warn]: Cannot find element: #app in admin index page

### ISSUE THREAD

**Issue by salvatormundiz** [aimeos/aimeos-laravel#327]
**Environment**
1. Laravel Framework 6.18.11
2. Operating system (Linux)
3. aimeos/aimeos-laravel": "~2020.04

**Describe the bug**
When I was log in as admin I have an error under console in admin interface

**To Reproduce**
1. Go to base_
![2020-05-02_034301](https://user-images.githubusercontent.com/62681591/80848209-c67e4a80-8c27-11ea-821b-ec5041628a03.jpg)
![2020-05-02_034301](https://user-images.githubusercontent.com/62681591/80848239-de55ce80-8c27-11ea-9bbb-e74797146664.jpg)

url/admin
2. Click on 'login
3. See error

**Comment by aimeos** [comment]
The problem is most likely something different. Check in the network tab that all files (especially CSS and JS files) are loaded properly

**Comment by salvatormundiz** [comment]
Thanks for your reply. this files not find and I have 404 error.
url: http:// ../admin/default/jqadm/file/js?lang=en
url: http://../admin/default/jqadm/file/css?lang=en

**Comment by aimeos** [comment]
Please check why they are not found, maybe it's a misconfiguration of your web server. The URLs must be something like `http://yourdomain/admin/default/jqadm/file/js?lang=en` and `http://yourdomain/admin/default/jqadm/file/css?lang=en`
