### ISSUE TITLE
error on aimeos:setup

### ISSUE THREAD

**Issue by niusek** [aimeos/aimeos-laravel#329]
hello, the second day I am trying to install aimeos without success :(

**Environment**
1. Version  2020.04
2. Operating system Windows 10, WAMP, MARIADB 10.4.10, PHP 7.3.12

**Describe the bug**
General error: 1005 Can't create table `aimeosbezdemo`.`users_address` (errno: 150 "Foreign key constraint is incorrectly formed"): ALTER TABLE users_address ADD CONSTRAINT fk_lvuad_pid FOREIGN KEY (parentid) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
  at V:\wamp64\www\lara7shopaimeos\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:75
    71|         {
    72|                 try {
    73|                         $result = $this->exec();
    74|                 } catch( \PDOException $e ) {
   75|                         throw new \Aimeos\MW\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
    76|                 }
    77|
    78|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    79|         }

  1   V:\wamp64\www\lara7shopaimeos\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\Task\Base.php:164
      Aimeos\MW\DB\Statement\DBAL\Simple::execute()

  2   V:\wamp64\www\lara7shopaimeos\vendor\aimeos\aimeos-core\lib\mshoplib\setup\TablesCreateMShop.php:173
      Aimeos\MW\Setup\Task\Base::executeList("db-customer")

**To Reproduce**
1. Fresh installed Laravel 7.10.3
2. composer require aimeos/aimeos-laravel:~2020.04
3. add "scripts": {......"  to composer.json
4. composer update with info nothing to migrate
5. php artisan vendor:publish --all
6. php artisan migrate  with info nothing to migrate
7. php artisan aimeos:setup (or php artisan aimeos:setup --option=setup/default/demo:1)
error appears after:
...
 Checking table "users":                                           done
 Checking table "users_address":

**Additional context**
no new entries in the web.php file

tables in database have been created

 table `users_address` 
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parentid` int(10) UNSIGNED NOT NULL,
  `siteid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  ...
  `editor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_lvuad_pid` (`parentid`),
  KEY `idx_lvuad_last_first` (`lastname`,`firstname`),
  KEY `idx_lvuad_post_addr1` (`postal`,`address1`),
  KEY `idx_lvuad_post_city` (`postal`,`city`),
  KEY `idx_lvuad_address1` (`address1`),
  KEY `idx_lvuad_city` (`city`),
  KEY `idx_lvuad_email` (`email`)

table 'users'
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `superuser` smallint(6) NOT NULL DEFAULT 0,
...
  `editor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unq_lvusr_email` (`email`) USING HASH,
  KEY `idx_lvusr_langid` (`langid`),
  KEY `idx_lvusr_last_first` (`lastname`,`firstname`),
  KEY `idx_lvusr_post_addr1` (`postal`,`address1`),
  KEY `idx_lvusr_post_city` (`postal`,`city`),
  KEY `idx_lvusr_lastname` (`lastname`),
  KEY `idx_lvusr_address1` (`address1`),
  KEY `idx_lvusr_city` (`city`)

What to do with this ?

**Comment by aimeos** [comment]
Seems to be OK, both are `int(10) UNSIGNED NOT NULL`:
- table 'users':
`id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,`
- table users_address
`parentid int(10) UNSIGNED NOT NULL,`

Also make sure, the `users` table is of type `InnoDB`!

If that's the case, you can check the last InnoDB error directly after the error occurs:
```
ALTER TABLE users_address ADD CONSTRAINT fk_lvuad_pid FOREIGN KEY (parentid) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;
SHOW ENGINE INNODB STATUS;
```

**Comment by niusek** [comment]
yes, I didn't notice:
ENGINE=MyISAM for table 'users' !

thanks!
