### ISSUE TITLE
Larvel default currency?

### ISSUE THREAD

**Issue by idleup** [aimeos/aimeos-laravel#33]
I cannot seem to find where you specify the default currency for the site, It appears to be using EUR even when I have it disabled and only have USD enabled...

**Comment by aimeos** [comment]
Don't forget to clear the content cache after you've changed the locale settings

**Comment by aimeos** [comment]
The behavior is improved by this commit: https://github.com/aimeos/aimeos-laravel/commit/62930890f0c7a0eed351444c79d53952a5d18b1f

**Comment by dadaycm** [comment]
Reported problem still exists in the current version.
# versions:
[ ] ubuntu v14.04.1
[ ] Homestead 3.19.0-25
[ ] laravel 5.2.31
[ ] aimeos 2016-04
[ ] PHP 7.0.5-2+deb.sury.org~trusty+1 (cli) ( NTS )
# steps:

1. from admin page, tab Product, one new product has been added with text/category/price/stock/media....

- there are two “name” texts, one with language _Chinese_ and _English_.
- there are three prices:

- [ ] -  Chinese Renmenbi (CNY)
- [ ] -  US dollar
- [ ] -  Euro

2. Tab Locale: three combinations have been added:

- [ ] - Chinese, Chinese Yuan Renminbi
- [ ] - Chinese, US Dollar
- [ ] - Chinese, Euro

# Action
Go to frontend, visit URL '/list?locale=**zh**&currency=**CNY**'
# Expected
Product new appended will be displayed, name & price will be shown as Chinese/CNY.
# Result
Product is displayed but name keeps **_English_**, price currency keeps **_Euro_**.

# Other tries
The following is tried and the result keeps the same:

- [ ]    URL '/list?locale=**zh_CN**&currency=**CNY**'

I checked the core code and confirmed that the  _**commit: 6293089**_ has been included already.

Please check it. thanks.
