### ISSUE TITLE
Cannot install Aimeos-Laravel package on the Laravel 7 setup on localhost

### ISSUE THREAD

**Issue by tejparekh** [aimeos/aimeos-laravel#332]
**Environment**
1. 2020.04
2. Operating system ( Mac)
3. Laravel 7 

**Describe the bug**
I am trying to install a aimeos package using the composer method. 
When I do so it fails with the following steps and response in the composer. 

**To Reproduce**
Steps to reproduce the behaviour: Trying to install the package from the composer command

` **composer require aimeos/aimeos-laravel:~2020.04**

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install aimeos/aimeos-laravel 2020.04.2
    - Conclusion: don't install aimeos/aimeos-laravel 2020.04.1
    - Conclusion: remove laminas/laminas-diactoros 2.3.0
    - Installation request for aimeos/aimeos-laravel ~2020.04 -> satisfiable by aimeos/aimeos-laravel[2020.04.1, 2020.04.2, 2020.04.x-dev].
    - Conclusion: don't install laminas/laminas-diactoros 2.3.0
    - aimeos/aimeos-laravel 2020.04.x-dev requires laminas/laminas-diactoros ^1.8.7 -> satisfiable by laminas/laminas-diactoros[1.8.7, 1.8.7p1, 1.8.7p2].
    - Can only install one of: laminas/laminas-diactoros[1.8.7, 2.3.0].
    - Can only install one of: laminas/laminas-diactoros[1.8.7p1, 2.3.0].
    - Can only install one of: laminas/laminas-diactoros[1.8.7p2, 2.3.0].
    - Installation request for laminas/laminas-diactoros (locked at 2.3.0) -> satisfiable by laminas/laminas-diactoros[2.3.0].

Installation failed, reverting ./composer.json to its original content.
`

**Expected behavior**

**Screenshots**

**Additional context**
Please find attached the composer.json file content below:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "authy/php": "3.0.5",
        "doctrine/dbal": "^2.10",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.5",
        "laravel-frontend-presets/argon": "^1.1",
        "laravel/framework": "^7.0",
        "laravel/passport": "^8.4",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "twilio/sdk": "^6.4"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by aimeos** [comment]
There's a version conflict with laravel/passport and we have to see if we can upgrade to laminas/laminas-diactoros:^2.2 too. Currently, Aimeos uses 1.8.7

**Comment by tejparekh** [comment]
Hi. Thanks for your reply. Can you upgrade this anytime soon?

**Comment by aimeos** [comment]
If you install aimeos/aimeos-laravel:dev-master, you get the updated version. Can you test if it works? Unit tests seem to be fine but we've made no real world tests up to now

**Comment by tejparekh** [comment]
Hi,

Thanks for your reply. I have tried your suggestion and it didn't work.
please see the response below.

*composer require aimeos/aimeos-laravel:dev-master*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aimeos/aimeos-laravel dev-master ->
satisfiable by aimeos/aimeos-laravel[dev-master].
    - Installation request for symfony/http-foundation (locked at v5.0.8)
-> satisfiable by symfony/http-foundation[v5.0.8].
    - Can only install one of: symfony/psr-http-message-bridge[v2.0.0,
v1.3.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.3.0,
v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.3.0,
v2.0.0].
    - Conclusion: install symfony/psr-http-message-bridge v1.3.0
    - Installation request for symfony/psr-http-message-bridge (locked at
v2.0.0) -> satisfiable by symfony/psr-http-message-bridge[v2.0.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by aimeos** [comment]
Updated composer.json to allow symfony/psr-http-message-bridge 1.x and 2.x
Can you check again?

**Comment by tejparekh** [comment]
Tried. Installation worked but I guess there are more functional errors. I
didn't get any migration files copied to server after trying the steps in
the documentation. I would rather leave this package to come at the
stability and then use it.
thanks for the help.

**Comment by aimeos** [comment]
There are no Aimeos migration files, only the ones from Laravel because the Aimeos setup uses a more advanced way to update the table structure. We've added the changes in the composer.json file to 2020.04.x-dev (stable branch) and we will tag that soon.

**Comment by lincontroy** [comment]
so basically is there a solution for this error?
