### ISSUE TITLE
I generated an extension, overwrote .php files from core vendor but want to know where to place the files after editting

### ISSUE THREAD

**Issue by steve111MV** [aimeos/aimeos-laravel#333]
**Environment**
Version (2020-04)

I generated an extension, overwrote .php files from core vendor but want to know where to place the files after editting

**Comment by aimeos** [comment]
Which file do you want to overwrite?

**Comment by steve111MV** [comment]
client/html/templates/common/partials/products-standard.php

**Comment by steve111MV** [comment]
i want to give my product <li></li> item a custome HTML style, the documentation didn't help much. I generated the extension and i don't know where to put the files in my project

**Comment by aimeos** [comment]
Save your modified files in the ./ext//client/html/templates/ folder in the same directory structure as in the ai-client-html extension, e.g.
`./ext/ai-client-html/client/html/templates/common/partials/products-standard.php`
store modified file in
`./ext/<yourextname>/client/html/templates/common/partials/products-standard.php`

**Comment by steve111MV** [comment]
i save this single file or all the extension generated files?

**Comment by steve111MV** [comment]
![Screen Shot 2020-06-22 at 00 05 51](https://user-images.githubusercontent.com/12065902/85237137-3df87b00-b41c-11ea-86c4-2a94c1849111.png)
Actually my greatest worry is the possibility to edit here. In which extension file may i overwrite this

**Comment by aimeos** [comment]
In your own
