### ISSUE TITLE
DB prefix error

### ISSUE THREAD

**Issue by cre-mer** [aimeos/aimeos-laravel#335]
**Environment**
1. Version 2020.07
2. MacOS catalina

**Describe the bug**
DB prefix is ignored when admin is being created

**To Reproduce**
1. Start the setup as usual
2. Before setting up DB environment in cli, go to **config/database.php** and add `'prefix' => env('DB_PREFIX', 'test_'),` to **mysql** connection
3. Complete the setup
4. run `artisan aimeos:account --super <email>`

**Expected behavior**
Create new admin

**Screenshots**
This is what I get:
<img width="884" alt="Bildschirmfoto 2020-08-10 um 01 03 31" src="https://user-images.githubusercontent.com/33655900/89743645-50e70d80-daa5-11ea-960b-e256a4697761.png">

**Additional context**
I think there is some hard coding going on in there

**Comment by aimeos** [comment]
The database prefix is currently not supported by Aimeos.
If you are able to add support for that to Aimeos, we appreciate a pull request very much.
