### ISSUE TITLE
Install aimeos/laravel

### ISSUE THREAD

**Issue by fcdeveloper** [aimeos/aimeos-laravel#336]
Cannot install this package under my laravel 7 - php 7.4..2
composer require aimeos/aimeos-laravel:~2020.07

https://share.getcloudapp.com/6quen4Pv
https://share.getcloudapp.com/nOukOyDv

**Comment by fcdeveloper** [comment]
Can you answer please.. 
Thank You!

I notice that you saw my screenshots

**Comment by aimeos** [comment]
Maybe composer is using a different PHP version. Try to execute:
`php composer req aimeos/aimeos-laravel:2020.07`
