### ISSUE TITLE
Cant install on laravel 8.6.0

### ISSUE THREAD

**Issue by NightravenJames** [aimeos/aimeos-laravel#337]
**Environment**
1. Linux

**Describe the bug**

**To Reproduce**
1. Install latest laravel
2. Run `composer require aimeos/aimeos-laravel:~2020.07.2`

**Expected behavior**
The following error occurs
`
Problem 1
    - Conclusion: don't install aimeos/aimeos-laravel 2020.07.2
    - Conclusion: don't install aimeos/aimeos-laravel 2020.07.1
    - Conclusion: remove laravel/framework v8.6.0
    - Installation request for aimeos/aimeos-laravel ^2020.07 -> satisfiable by aimeos/aimeos-laravel[2020.07.1, 2020.07.2, 2020.07.x-dev].
    - Conclusion: don't install laravel/framework v8.6.0
    - aimeos/aimeos-laravel 2020.07.x-dev requires laravel/framework ~6.0||~7.0 -> satisfiable by laravel/framework[6.x-dev, 7.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, v8.6.0].
    - Can only install one of: laravel/framework[7.x-dev, v8.6.0].
    - Installation request for laravel/framework (locked at v8.6.0, required as ^8.0) -> satisfiable by laravel/framework[v8.6.0].
`

**Comment by aimeos** [comment]
Laravel 8.0 is currently only supported by the dev-master branch. The new production-ready 2020.10 LTS version will be released in two weeks.
