### ISSUE TITLE
can't access admin 5.2

### ISSUE THREAD

**Issue by etmind** [aimeos/aimeos-laravel#34]
after successfully login got error InvalidArgumentException in UrlGenerator.php line 307: Route [] not defined.

**Comment by aimeos** [comment]
There seems to be a route configuration missing in your `config/shop.php` file.

We've released the new stable version 2016.04.1 a few minutes ago. Can you please update to this version and make sure you follow the "Upgrade to 2016.x" steps? From this point we can see if the problem still exists and what's maybe missing in your installation.

**Comment by etmind** [comment]
Thanks for an answer, but I'm little bit confused, where  i can found newest version, here ?
my conf/shop.php routes are commented:

'routes' => array(
		// 'login' => array('middleware' => ['web']),
		// 'admin' => array('middleware' => ['web', 'auth']),
		// 'account' => array('middleware' => ['web', 'auth']),
		// 'default' => array('middleware' => ['web']),
		// 'confirm' => array('middleware' => ['web']),
		// 'update' => array(),
	),

**Comment by aimeos** [comment]
Simply change your `composer.json` to use "aimeos/aimoes-laravel": "~2016.04" and execute `composer update`. The readme on GitHub has been updated as well:
https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by aimeos** [comment]
@etmind Did the update fixed your problem?

**Comment by etmind** [comment]
I make fresh install, and everything now is ok.
Thank you !
