### ISSUE TITLE
hi guys

### ISSUE THREAD

**Issue by aimeos** [aimeos/aimeos-laravel#340]
hi guys
in CatalogController we have foreach like this:
foreach( app( 'config' )->get( 'shop.page.catalog-home' ) as $name )
		{....
but in app( 'config' )->get( 'shop.page.catalog-home' ) i haven't catalog-home
how can i fix it?
please help me :(

_Originally posted by @fatemesharafi in https://github.com/aimeos/aimeos-laravel/issue_comments/711840349_

**Comment by aimeos** [comment]
Did you upgrade from an earlier Aimeos version?
2020.10 contains a default configuration for `catalog-home`:
https://github.com/aimeos/aimeos-laravel/blob/master/src/default.php#L17
If there's a problem, try to add this line to yout ./config/shop.php file

**Comment by fatemesharafi** [comment]
I used 2020.10 but I hadn't'catalog-home' => array( 'basket/mini', 'catalog/home' ), in my shop.php file, i added this line and it worked.thanks a milion for suporting 19.10.2020, 11:36, "Aimeos" <notifications@github.com>:
Did you upgrade from an earlier Aimeos version?
2020.10 contains a default configuration for catalog-home:
https://github.com/aimeos/aimeos-laravel/blob/master/src/default.php#L17
If there's a problem, try to add this line to yout ./config/shop.php file
