### ISSUE TITLE
Route error /count

### ISSUE THREAD

**Issue by Dinver** [aimeos/aimeos-laravel#341]
**Environment**
1. Version (~2020.10)
2. Operating system (Windows 10)
3. PHP 7.4

**Describe the bug**
Route /count, error 500 Internal Server Error

Call to a member function toJson() on array

**To Reproduce**
1. Install Laravel 8
2. Install aimeos-laravel demo mode

**Expected behavior**
Work as demo site

**Screenshots**
![shop loc_shop_count(Laptop with HiDPI screen)](https://user-images.githubusercontent.com/36528841/97147750-0ce9d780-177b-11eb-973f-77d51038eecd.png)

**Additional context**

\ext\ai-client-html\client\html\templates\catalog\count\tree-body-standard.php:12
47
\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php
Aimeos\MW\View\Standard:257
46
Aimeos\MW\View\Standard:239
45
Aimeos\Client\Html\Catalog\Count\Tree\Standard:101
44
Aimeos\Client\Html\Catalog\Count\Standard:114
43
Aimeos\Shop\Controller\CatalogController:36
42
Illuminate\Routing\Controller:54
41
Illuminate\Routing\ControllerDispatcher:45
40
Illuminate\Routing\Route:255
39
Illuminate\Routing\Route:197
38
Illuminate\Routing\Router:691
37
Illuminate\Pipeline\Pipeline:128
36
Illuminate\Routing\Middleware\SubstituteBindings:41
35
Illuminate\Pipeline\Pipeline:167
34
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:77
33
Illuminate\Pipeline\Pipeline:167
32
Illuminate\View\Middleware\ShareErrorsFromSession:49
31
Illuminate\Pipeline\Pipeline:167
30
Illuminate\Session\Middleware\StartSession:121
29
Illuminate\Session\Middleware\StartSession:63
28
Illuminate\Pipeline\Pipeline:167
27
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:37
26
Illuminate\Pipeline\Pipeline:167
25
Illuminate\Cookie\Middleware\EncryptCookies:67
24
Illuminate\Pipeline\Pipeline:167
23
Illuminate\Pipeline\Pipeline:103
22
Illuminate\Routing\Router:693
21
Illuminate\Routing\Router:668
20
Illuminate\Routing\Router:634
19
Illuminate\Routing\Router:623
18
Illuminate\Foundation\Http\Kernel:166
17
Illuminate\Pipeline\Pipeline:128
16
Illuminate\Foundation\Http\Middleware\TransformsRequest:21
15
Illuminate\Pipeline\Pipeline:167
14
Illuminate\Foundation\Http\Middleware\TransformsRequest:21
13
Illuminate\Pipeline\Pipeline:167
12
Illuminate\Foundation\Http\Middleware\ValidatePostSize:27
11
Illuminate\Pipeline\Pipeline:167
10
Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance:87
9
Illuminate\Pipeline\Pipeline:167
8
Fruitcake\Cors\HandleCors:37
7
Illuminate\Pipeline\Pipeline:167
6
Fideloper\Proxy\TrustProxies:57
5
Illuminate\Pipeline\Pipeline:167
4
Illuminate\Pipeline\Pipeline:103
3
Illuminate\Foundation\Http\Kernel:141
2
Illuminate\Foundation\Http\Kernel:110
1
\public\index.php:52

**Comment by aimeos** [comment]
Can you please execute
`composer req aimeos/map:~1.8`
Does it work afterwards?

**Comment by Dinver** [comment]
> Can you please execute
> `composer req aimeos/map:~1.8`
> Does it work afterwards?

No not working, in composer.lock aimeos/map 1.8.0.

**Comment by aimeos** [comment]
Can you please post the output of `composer show`?

**Comment by Dinver** [comment]
> Can you please post the output of `composer show`?

aimeos/ai-admin-jqadm                2020.10.2 Aimeos Vue.js+Bootstrap admin interface
aimeos/ai-admin-jsonadm              2020.10.1 Aimeos ai-admin-jsonadm extension
aimeos/ai-client-html                2020.10.5 Aimeos ai-client-html extension
aimeos/ai-client-jsonapi             2020.10.2 Aimeos JSON API extension
aimeos/ai-controller-frontend        2020.10.1 Aimeos ai-controller-frontend extension
aimeos/ai-controller-jobs            2020.10.2 Aimeos ai-controller-jobs extension
aimeos/ai-gettext                    2020.10.1 Aimeos Gettext extension
aimeos/ai-laravel                    2020.10.2 Laravel adapter for Aimeos web shops and e-commerce sol...
aimeos/ai-swiftmailer                2020.10.1 SwiftMailer adapter for Aimeos web shops and e-commerce...
aimeos/aimeos-core                   2020.10.5 Full-featured e-commerce components for high performanc...
aimeos/aimeos-laravel                2020.10.1 Professional, full-featured and high performance Larave...
aimeos/map                           1.8.0     Easy and elegant handling of PHP arrays as array-like m...
asm89/stack-cors                     v2.0.1    Cross-origin resource sharing library and stack middleware
brick/math                           0.9.1     Arbitrary-precision arithmetic library
composer/installers                  v1.9.0    A multi-framework Composer library installer
dnoegel/php-xdg-base-dir             v0.1.1    implementation of xdg base directory specification for php
doctrine/cache                       1.10.2    PHP Doctrine Cache library is a popular cache implement...
doctrine/dbal                        2.12.0    Powerful PHP database abstraction layer (DBAL) with man...
doctrine/event-manager               1.1.1     The Doctrine Event Manager is a simple PHP event system...
doctrine/inflector                   2.0.3     PHP Doctrine Inflector is a small library that can perf...
doctrine/instantiator                1.3.1     A small, lightweight utility to instantiate objects in ...
doctrine/lexer                       1.2.1     PHP Doctrine Lexer parser library that can be used in T...
dragonmantank/cron-expression        v3.0.2    CRON for PHP: Calculate the next or previous run date a...
egulias/email-validator              2.1.22    A library for validating emails against several RFCs
facade/flare-client-php              1.3.7     Send PHP errors to Flare
facade/ignition                      2.4.1     A beautiful error page for Laravel applications.
facade/ignition-contracts            1.0.2     Solution contracts for Ignition
fideloper/proxy                      4.4.1     Set trusted proxies for Laravel
filp/whoops                          2.9.0     php error handling for cool kids
fruitcake/laravel-cors               v2.0.3    Adds CORS (Cross-Origin Resource Sharing) headers suppo...
fzaninotto/faker                     v1.9.1    Faker is a PHP library that generates fake data for you.
graham-campbell/result-type          v1.0.1    An Implementation Of The Result Type
guzzlehttp/guzzle                    7.2.0     Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.4.0     Guzzle promises library
guzzlehttp/psr7                      1.7.0     PSR-7 message implementation that also provides common ...
hamcrest/hamcrest-php                v2.0.1    This is the PHP port of Hamcrest Matchers
laminas/laminas-diactoros            2.4.1     PSR HTTP Message implementations
laminas/laminas-zendframework-bridge 1.1.1     Alias legacy ZF class names to Laminas Project equivale...
laravel/framework                    v8.11.2   The Laravel Framework.
laravel/tinker                       v2.4.2    Powerful REPL for the Laravel framework.
laravel/ui                           v3.0.0    Laravel UI utilities and presets.
league/commonmark                    1.5.6     Highly-extensible PHP Markdown parser which fully suppo...
league/flysystem                     1.1.3     Filesystem abstraction: Many filesystems, one API.
league/mime-type-detection           1.5.1     Mime-type detection for Flysystem
mockery/mockery                      1.4.2     Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                      2.1.1     Sends your logs to files, sockets, inboxes, databases a...
myclabs/deep-copy                    1.10.1    Create deep copies (clones) of your objects
nesbot/carbon                        2.41.5    An API extension for DateTime that supports 281 differe...
nikic/php-parser                     v4.10.2   A PHP parser written in PHP
nunomaduro/collision                 v5.0.2    Cli error handling for console/command-line PHP applica...
nyholm/psr7                          1.3.1     A fast PHP7 implementation of PSR-7
opis/closure                         3.6.0     A library that can be used to serialize closures (anony...
phar-io/manifest                     2.0.1     Component for reading phar.io manifest information from...
phar-io/version                      3.0.2     Library for handling version information and constraints
php-http/message-factory             v1.0.2    Factory interfaces for PSR-7 HTTP Message
phpdocumentor/reflection-common      2.2.0     Common reflection classes used by phpdocumentor to refl...
phpdocumentor/reflection-docblock    5.2.2     With this component, a library can provide support for ...
phpdocumentor/type-resolver          1.4.0     A PSR-5 based resolver of Class names, Types and Struct...
phpoption/phpoption                  1.7.5     Option Type for PHP
phpspec/prophecy                     1.12.1    Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            9.2.0     Library that provides collection, processing, and rende...
phpunit/php-file-iterator            3.0.5     FilterIterator implementation that filters files based ...
phpunit/php-invoker                  3.1.1     Invoke callables with a timeout
phpunit/php-text-template            2.0.4     Simple template engine.
phpunit/php-timer                    5.0.2     Utility class for timing
phpunit/phpunit                      9.4.2     The PHP Unit Testing framework.
psr/container                        1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0     Standard interfaces for event handling.
psr/http-client                      1.0.1     Common interface for HTTP clients
psr/http-factory                     1.0.1     Common interfaces for PSR-7 HTTP message factories
psr/http-message                     1.0.1     Common interface for HTTP messages
psr/log                              1.1.3     Common interface for logging libraries
psr/simple-cache                     1.0.1     Common interfaces for simple caching
psy/psysh                            v0.10.4   An interactive shell for modern PHP.
ralouphie/getallheaders              3.0.3     A polyfill for getallheaders.
ramsey/collection                    1.1.1     A PHP 7.2+ library for representing and manipulating co...
ramsey/uuid                          4.1.1     A PHP library for generating and working with universal...
scrivo/highlight.php                 v9.18.1.3 Server side syntax highlighter that supports 185 langua...
sebastian/cli-parser                 1.0.1     Library for parsing CLI options
sebastian/code-unit                  1.0.7     Collection of value objects that represent the PHP code...
sebastian/code-unit-reverse-lookup   2.0.3     Looks up which function or method a line of code belong...
sebastian/comparator                 4.0.5     Provides the functionality to compare PHP values for eq...
sebastian/complexity                 2.0.1     Library for calculating the complexity of PHP code units
sebastian/diff                       4.0.3     Diff implementation
sebastian/environment                5.1.3     Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   4.0.3     Provides the functionality to export PHP variables for ...
sebastian/global-state               5.0.1     Snapshotting of global state
sebastian/lines-of-code              1.0.1     Library for counting the lines of code in PHP source code
sebastian/object-enumerator          4.0.3     Traverses array structures and object graphs to enumera...
sebastian/object-reflector           2.0.3     Allows reflection of object attributes, including inher...
sebastian/recursion-context          4.0.3     Provides functionality to recursively process PHP varia...
sebastian/resource-operations        3.0.3     Provides a list of PHP built-in functions that operate ...
sebastian/type                       2.3.0     Collection of value objects that represent the types of...
sebastian/version                    3.0.2     Library that helps with managing the version number of ...
swiftmailer/swiftmailer              v6.2.3    Swiftmailer, free feature-rich PHP mailer
symfony/console                      v5.1.7    Symfony Console Component
symfony/css-selector                 v5.1.7    Symfony CssSelector Component
symfony/deprecation-contracts        v2.2.0    A generic function and convention to trigger deprecatio...
symfony/error-handler                v5.1.7    Symfony ErrorHandler Component
symfony/event-dispatcher             v5.1.7    Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v2.2.0    Generic abstractions related to dispatching event
symfony/finder                       v5.1.7    Symfony Finder Component
symfony/http-client-contracts        v2.3.1    Generic abstractions related to HTTP clients
symfony/http-foundation              v5.1.7    Symfony HttpFoundation Component
symfony/http-kernel                  v5.1.7    Symfony HttpKernel Component
symfony/mime                         v5.1.7    A library to manipulate MIME messages
symfony/polyfill-ctype               v1.20.0   Symfony polyfill for ctype functions
symfony/polyfill-iconv               v1.20.0   Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme       v1.20.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn            v1.20.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf...
symfony/polyfill-intl-normalizer     v1.20.0   Symfony polyfill for intl's Normalizer class and relate...
symfony/polyfill-mbstring            v1.20.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php72               v1.20.0   Symfony polyfill backporting some PHP 7.2+ features to ...
symfony/polyfill-php73               v1.20.0   Symfony polyfill backporting some PHP 7.3+ features to ...
symfony/polyfill-php80               v1.20.0   Symfony polyfill backporting some PHP 8.0+ features to ...
symfony/process                      v5.1.7    Symfony Process Component
symfony/psr-http-message-bridge      v2.0.2    PSR HTTP message bridge
symfony/routing                      v5.1.7    Symfony Routing Component
symfony/service-contracts            v2.2.0    Generic abstractions related to writing services
symfony/string                       v5.1.7    Symfony String component
symfony/translation                  v5.1.7    Symfony Translation Component
symfony/translation-contracts        v2.3.0    Generic abstractions related to translation
symfony/var-dumper                   v5.1.7    Symfony mechanism for exploring and dumping PHP variables
tecnickcom/tcpdf                     6.3.5     TCPDF is a PHP class for generating PDF documents and b...
theseer/tokenizer                    1.2.0     A small library for converting tokenized PHP source cod...
tijsverkoyen/css-to-inline-styles    2.2.3     CssToInlineStyles is a class that enables you to conver...
vlucas/phpdotenv                     v5.2.0    Loads environment variables from `.env` to `getenv()`, ...
voku/portable-ascii                  1.5.3     Portable ASCII library - performance optimized (ascii) ...
webmozart/assert                     1.9.1     Assertions to validate method input/output with nice er...

**Comment by aimeos** [comment]
Can you please execute `composer req aimeos/ai-client-html:2020.10.x-dev`?
Does it work then?

**Comment by Dinver** [comment]
> Can you please execute `composer req aimeos/ai-client-html:2020.10.x-dev`?
> Does it work then?

Yes, its working. Thanks!
