### ISSUE TITLE
Wrong interface error in Ominipay call

### ISSUE THREAD

**Issue by thepurpleblob** [aimeos/aimeos-laravel#342]
**Environment**
1. Version (2020.10.x-dev)
2. Operating system (Linux)

**Describe the bug**
Error logged when making Omnipay payment

Argument 1 passed to Aimeos\MShop\Service\Provider\Payment\OmniPay::saveRepayData() must implement interface Omnipay\Common\Message\ResponseInterface,

instance of Omnipay\SagePay\Message\ServerNotifyRequest given,

called in /home/shop/public_html/ext/ai-payments/lib/custom/src/MShop/Service/Provider/Payment/OmniPay.php on line 527 

line 527 is (for me) $this->saveRepayData( $omniResponse, $base->getCustomerId() );

so $omniResponse would appear to be the incorrect class. 
$omniResponse = $omniRequest->send();
$omniRequest appears to be Omi::create(...)

The Gateway looks like...

class ServerNotifyRequest extends AbstractRequest implements NotificationInterface

I appreciate that this is more likely a problem in the PaymentProvider but you might be able to help / comment. 

**To Reproduce**
Make a payment using an Omnipay provider.
I was using Sagepay of course. 

**Expected behavior**
Payment processing failed at SagePay due to missing return url. I'm not sure that this is the problem but I'd like to be able to exclude it.

**Comment by aimeos** [comment]
Omnipay isn't very strict, so depending on the driver different object might be returned.
Can you open an issue in the https://github.com/aimeoscom/ai-payments repo to find a workaround for that issue?
