### ISSUE TITLE
Pricing format customization on product page: MRP, Price, You save, taxes

### ISSUE THREAD

**Issue by parasbhadauria** [aimeos/aimeos-laravel#348]
Hi,
We have Laravel Aimeos Shop installed (latest version released in October 2020)
Please help me out implementing price format as:

1. MRP: Maximum retail price printed on product label
2. Price: Actual price after applying discount
3. You save: It is discounted value comes after substracting price from MRP
4. Inclusive of all the taxes: well there can be 2 option for this:-
  - We can make it easy by just changing VAT to GST.
 - On product page we can replace "Incl. x% VAT" with "Incl. of all the taxes" and then implementing VAT to GST for the basket and billing.
5. Free Shipping badge: For better user experience and lead conversion, Free shipping badge must be visible on the product page in case of free shipping offered by the company

![price format](https://user-images.githubusercontent.com/75558471/101273233-75d06080-37b9-11eb-84b9-a05315f0d505.JPG)

**Comment by aimeos** [comment]
Please use the issue tracker only for bug reports and potential issues.
For help how to implement something, the Aimeos forum is the best place for asking: https://aimeos.org/help
