### ISSUE TITLE
Login/Sign-up Option for better user experience: Guest checkout without signup, Login with email ID/phone number via OTP, Login with Google & Facebook

### ISSUE THREAD

**Issue by parasbhadauria** [aimeos/aimeos-laravel#349]
Hi,
Laravel Aimeos Shop installed (latest version released in october 2020)

For great user experience I want to implement 3 login or sign-up options as mentioned below:

1. Guest checkout without login: By giving this option
> We can make a smooth user flow without asking to create an account during order placement.
> We can make it easy by creating account automaticaly by using the billing or delivery information during guest checkout and make the credentials available on email or SMS

2. Sign-up or login with email-ID or mobile number via sending OTP for verification

3. Login with Google and Facebook: this help
> Mobile User get easy login as Google & Facebook always open on the smartphone

**_I need help to implement all the above options... Please help me out_**
Thanks

**Comment by aimeos** [comment]
Guest checkout and automatic account creation is the default in Aimeos. For the other options, please have a look into the Laravel documentation becaus login and register is handled by Laravel standard means. Login with Google and Facebook for example can be implemented using the Laravle Socialite package.
