### ISSUE TITLE
can't install demo data

### ISSUE THREAD

**Issue by napestershine** [aimeos/aimeos-laravel#35]
![f](https://cloud.githubusercontent.com/assets/8603325/14415287/f5a3a9ca-ffba-11e5-9670-5ee9dc8dee1b.JPG)

**Comment by aimeos** [comment]
You missed one of the steps from the docs so the migrations haven't been done. Please try
```php artisan migrate```
first. If the error stays the same, check if the Aimeos service provider is in `config/app.php` and do the steps in the documentation again (publish, migrate, etc).
