### ISSUE TITLE
Product availability/unavailability & delivery options on some of the zipcode or pincode locations

### ISSUE THREAD

**Issue by parasbhadauria** [aimeos/aimeos-laravel#351]
Hi,
Laravel Aimeos Shop installed (latest version released in october 2020)
I am looking for the solution so that people from some location can check the product availability via entering zipcode or pincode of those locations where product can not be shipped.
**_Please help us to resolve it._**
Thanks

**Comment by aimeos** [comment]
Please use the issue tracker only for bug reports and potential issues.
For help how to implement something, the Aimeos forum is the best place for asking: https://aimeos.org/help
