### ISSUE TITLE
SQLSTATE[HY000] [1049] Unknown database 'myshopdb'

### ISSUE THREAD

**Issue by trancongtu550** [aimeos/aimeos-laravel#352]
**Environment**
1. Version (2020-10)
2. Operating system (Linux, Mac, Windows)
MacOS

**Screenshots**
![image](https://user-images.githubusercontent.com/44827328/101438514-2028bf00-3945-11eb-90f9-6cc0bcdd0a45.png)
. how to fix this problem ?

**Comment by aimeos** [comment]
You haven't created a database named "myshopdb" before.
