### ISSUE TITLE
Can't show my image when i upload

### ISSUE THREAD

**Issue by trancongtu550** [aimeos/aimeos-laravel#353]
**Environment**
1. Version (2020.10)
2. Operating system (Linux, Mac, Windows)
Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/44827328/101989470-0edc0b80-3cd3-11eb-8c2b-e1c28f7718a4.png)

**Comment by aimeos** [comment]
Check your APP_URL setting in the .env file of your application. It must be the same as the base URL as in your browser. Also make sure you have at least aimeos/aimeos-laravel 2020.10.3

**Comment by trancongtu550** [comment]
![image](https://user-images.githubusercontent.com/44827328/102004894-7a5fc080-3d47-11eb-8a05-9e8fbad656eb.png)
like this ??
![image](https://user-images.githubusercontent.com/44827328/102004908-9cf1d980-3d47-11eb-86ab-3418bab3a8b4.png)

**Comment by aimeos** [comment]
Without the slash at the end

**Comment by trancongtu550** [comment]
tks dude
