### ISSUE TITLE
get exception "Price item not available" when define product type selection

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#356]
I use version 2020.07, I add a product with type Selection and add selections with Variant attributes (all variants have same price and I don't set price in every variant separately, just set price in main product), in the frontend when select a selection of this product and add it to basket, everything is ok, when I close the modal of basket and again add product to basket the quantity increase and everything is ok, BUT when I add product to basket and in the basket modal I change the quantity (increase or decrease) I get error with the message "Price item not available", I check codes and find out that this error is an exception in the getLowestPrice method of Aimeos\MShop\Price\Manager.
why $priceList has no value in this method and why this error was happen?

**Comment by aimeos** [comment]
Did you use a minium quantity for the price of the selection product?

**Comment by parsester** [comment]
> Did you use a minium quantity for the price of the selection product?

yes, the value of Minimum quantity* is 1 by default, I try to set it 0 but I get error for saving.

**Comment by aimeos** [comment]
We've found the problem and fixed it in 2020.10.x-dev.
You need to update to 2020.10 LTS first and then run
```
composer req aimeos/ai-controller-frontend:2020.10.x-dev
```

**Comment by parsester** [comment]
this issue was fixed.
