### ISSUE TITLE
Delivery/Payment Service Attributes was cleared when save order from jqadm admin panel

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#359]
**Environment**
1. Version 2020.10
2. Operating system Linux Centos 7

**Describe the bug**
I upgrade my aimeos/laravel from 2020.07 to 2020.10, I set some attributes to payment and delivery service provider like as "shipping_code" at the backend, but when I make a change to an order in the jqadm admin panel (domain/admin/default/jqadm/get/order/1558) like as change address1 (event without change anything) and after that click on the Save button, all of attributes of delivery and payment service was cleared, I check database table "mshop_order_base_service_attr" they was also deleted from this table.

Why does this happen?

**Comment by aimeos** [comment]
This should be fixed in the latest aimeos/ai-admin-jqadm release (2020.10.14). Can you please update and check?

**Comment by parsester** [comment]
> 
> 
> This should be fixed in the latest aimeos/ai-admin-jqadm release (2020.10.14). Can you please update and check?

i update aimeos/ai-admin-jqadm package to 2020.10.14 and after that open an order with exist payment service attribute and just click on the save button (without any change) and get this error:

`Argument 1 passed to Aimeos\MShop\Order\Item\Base\Service\Attribute\Standard::setAttributeId() must be of the type string, null given, called in C:\xampp\htdocs\shop\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Order\Item\Base\Service\Attribute\Standard.php on line 267`

![2021-01-25_21-42-20](https://user-images.githubusercontent.com/16049244/105747739-69b18580-5f56-11eb-9faa-37bf239f230f.jpg)

**Comment by aimeos** [comment]
Fixed in aimeos/aimeos-core 2020.10.16

**Comment by parsester** [comment]
> Fixed in aimeos/aimeos-core 2020.10.16

yes it fixed. thanks a lot...
