### ISSUE TITLE
Installation error: composer create-project aimeos/aimeos myshop 

### ISSUE THREAD

**Issue by davistv** [aimeos/aimeos-laravel#361]
**Environment**
1. Version 2020.10.x-dev
2. Operating system: Mac

**Describe the bug**
myshop install instructions don't work on current Mac OS X. Tried PHP 7 and 8 (installed via brew).

PHP 7 output:
`davistv@Muska2 aimeos-demo % /usr/bin/php /usr/local/bin/composer create-project aimeos/aimeos myshop
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl' (tried: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/intl, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl), /usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so)) in Unknown on line 0
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Creating a "aimeos/aimeos" project at "./myshop"
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing aimeos/aimeos (2020.10.6)
  - Installing aimeos/aimeos (2020.10.6): Extracting archive
Created project in /Users/davistv/Sites/aimeos-demo/myshop
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl' (tried: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/intl, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl), /usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so)) in Unknown on line 0
> @php -r "mkdir('public/files'); mkdir('public/preview'); mkdir('public/uploads');"
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl' (tried: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/intl, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl), /usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so (dlopen(/usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so, 0x0009): dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20180731/intl.so)) in Unknown on line 0
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aimeos/aimeos-laravel[2020.10.1, ..., 2020.10.x-dev] require aimeos/aimeos-core 2020.10.* -> satisfiable by aimeos/aimeos-core[2020.10.1, ..., 2020.10.x-dev].
    - aimeos/aimeos-core[2020.10.1, ..., 2020.10.x-dev] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires aimeos/aimeos-laravel ~2020.10 -> satisfiable by aimeos/aimeos-laravel[2020.10.1, ..., 2020.10.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`

Output with PHP8:
`davistv@Muska2 aimeos-demo % composer create-project aimeos/aimeos myshop 
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Creating a "aimeos/aimeos" project at "./myshop"
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing aimeos/aimeos (2018.10.3)
  - Installing aimeos/aimeos (2018.10.3): Extracting archive
Created project in /Users/davistv/Sites/aimeos-demo/myshop
The "fxp/composer-asset-plugin" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "mkdir('public/files'); mkdir('public/preview'); mkdir('public/uploads');"
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit[6.0.0, ..., 6.5.14] require php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ~6.0 -> satisfiable by phpunit/phpunit[6.0.0, ..., 6.5.14].
`

**To Reproduce**
1. mkdir aimeos-demo
2. cd aimeos-demo
3. composer create-project aimeos/aimeos myshop   (or /usr/bin/php /usr/local/bin/composer create-project aimeos/aimeos myshop for PHP 7)

**Expected behavior**
Install a working myshop demo.

**Comment by aimeos** [comment]
It seems you have a broken PHP installation or at least php-intl extension is missing and something is requiring "fxp/composer-asset-plugin" which isn't compatible to your composer 2.x (but that's not required by the Aimeos package).

**Comment by davistv** [comment]
I'll try installing php-intl for my native PHP install, but I'm not sure how many devs use the built-in PHP for their work. Most devs I know use brew to manage PHP versions for projects. The PHP 8 failure error has to do with phpunit requiring php ^7.0, can that be resolved?

**Comment by davistv** [comment]
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.

https://github.com/fxpio/composer-asset-plugin/issues/334

This isn't getting fixed any time soon, Foxy is supposed to replace composer-asset-plugin now anyway. It seems like this is going to need more work than I can contribute right now.

**Comment by aimeos** [comment]
OK, we've fixed the problem in the composer.json. You can now install Aimeos using PHP 8 (version 2020.10.7)
