### ISSUE TITLE
Have both admin and user registrations

### ISSUE THREAD

**Issue by godadada** [aimeos/aimeos-laravel#362]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
It seems that Aimeos only allow a choice between admin registration and ordinary user registration present in the interface. It would be nice to have both options available in a configuration.

**Describe alternatives you've considered**
See above

**Additional context**
N/A

**Comment by aimeos** [comment]
Users don't need to register in Aimeos. An user account is created at the end of the checkout process automatically if they don't opt out.

**Comment by godadada** [comment]
Thanks, got it.

Best Wishes,   Chunde Shi
godadada@yahoo.com 

    On Saturday, February 13, 2021, 4:45:21 PM GMT+8, Aimeos <notifications@github.com> wrote:  
 
 


Users don't need to register in Aimeos. An user account is created at the end of the checkout process automatically if they don't opt out.
