### ISSUE TITLE
MultiSites No item found for conditions: Array ( [locale.site.code] => www.test.com )

### ISSUE THREAD

**Issue by oulfr** [aimeos/aimeos-laravel#368]
I have enabled multisite then i have this error: No item found for conditions: Array ( [locale.site.code] => www.test.com )

for information the www.test.com is my vhost configured to localhost.

`[2021-03-13 21:24:29] local.ERROR: No item found for conditions: Array
(
    [locale.site.code] => www.test.com
)
 {"exception":"[object] (Aimeos\\MShop\\Exception(code: 0): No item found for conditions: Array
(
    [locale.site.code] => www.test.com
)
 at D:\\workspace\\test\\vendor\\aimeos\\aimeos-core\\lib\\mshoplib\\src\\MShop\\Common\\Manager\\Base.php:625)
[stacktrace]
#0 D:\\workspace\\test\\vendor\\aimeos\\aimeos-core\\lib\\mshoplib\\src\\MShop\\Locale\\Manager\\Site\\Standard.php(367): Aimeos\\MShop\\Common\\Manager\\Base->findItemBase(Array, Array, false)
#1 [internal function]: Aimeos\\MShop\\Locale\\Manager\\Site\\Standard->findItem('www.test.com')
#2 D:\\workspace\\test\\vendor\\aimeos\\aimeos-core\\lib\\mshoplib\\src\\MShop\\Common\\Manager\\Decorator\\Base.php(51): call_user_func_array(Array, Array)
#3 D:\\workspace\\test\\vendor\\aimeos\\aimeos-core\\lib\\mshoplib\\src\\MShop\\Locale\\Manager\\Standard.php(125): Aimeos\\MShop\\Common\\Manager\\Decorator\\Base->__call('findItem', Array)
#4 [internal function]: Aimeos\\MShop\\Locale\\Manager\\Standard->bootstrap('www.test.com', '', '', true)
#5 D:\\workspace\\test\\vendor\\aimeos\\aimeos-core\\lib\\mshoplib\\src\\MShop\\Common\\Manager\\Decorator\\Base.php(51): call_user_func_array(Array, Array)
#6 D:\\workspace\\test\\vendor\\aimeos\\aimeos-laravel\\src\\Aimeos\\Shop\\Base\\Locale.php(71): Aimeos\\MShop\\Common\\Manager\\Decorator\\Base->__call('bootstrap', Array)
#7 D:\\workspace\\test\\vendor\\aimeos\\aimeos-laravel\\src\\Aimeos\\Shop\\Base\\Context.php(101): Aimeos\\Shop\\Base\\Locale->get(Object(Aimeos\\MShop\\Context\\Item\\Standard))
#8 D:\\workspace\\test\\vendor\\aimeos\\aimeos-laravel\\src\\Aimeos\\Shop\\Base\\Shop.php(47): Aimeos\\Shop\\Base\\Context->get()
#9 D:\\workspace\\test\\vendor\\aimeos\\aimeos-laravel\\src\\Aimeos\\Shop\\ShopServiceProvider.php(97): Aimeos\\Shop\\Base\\Shop->__construct(Object(Aimeos\\Shop\\Base\\Aimeos), Object(Aimeos\\Shop\\Base\\Context), Object(Aimeos\\Shop\\Base\\View))
#10 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(799): Aimeos\\Shop\\ShopServiceProvider->Aimeos\\Shop\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#11 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#12 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(785): Illuminate\\Container\\Container->resolve('aimeos.shop', Array, true)
#13 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Foundation\\Application->resolve('aimeos.shop', Array)
#14 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(770): Illuminate\\Container\\Container->make('aimeos.shop', Array)
#15 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1245): Illuminate\\Foundation\\Application->make('aimeos.shop')
#16 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(198): Illuminate\\Container\\Container->offsetGet('aimeos.shop')
#17 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(166): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('aimeos.shop')
#18 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(255): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#19 D:\\workspace\\test\\vendor\\aimeos\\aimeos-laravel\\src\\Aimeos\\Shop\\Controller\\CatalogController.php(90): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#20 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): Aimeos\\Shop\\Controller\\CatalogController->listAction('www.test.com')
#21 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('listAction', Array)
#22 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Aimeos\\Shop\\Controller\\CatalogController), 'listAction')
#23 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#24 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(681): Illuminate\\Routing\\Route->run()
#25 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 D:\\workspace\\test\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 D:\\workspace\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#58 D:\\workspace\\test\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#59 {main}
"} 
`

**Comment by aimeos** [comment]
You forgot the create the site in Aimeos like stated in the documentation for multi-site setups:
```
php artisan aimeos:setup www.test.com
```
See: https://aimeos.org/docs/latest/laravel/customize/#adapt-the-routing (end of the section).

**Also keep in mind that `www.test.com` and `test.com` are different sites!**

**Comment by oulfr** [comment]
Yes but the www.test.com is the default admin site how to change default alias to be www.test.com

**Comment by aimeos** [comment]
The "default" site is special because it's the standard one if no site code is available and this is hard-coded at several locations in the code. You should use the "default" site for your main domain (www.test.com) and use additional sites for further domains.
