### ISSUE TITLE
Terms & Condition (Exception)

### ISSUE THREAD

**Issue by 1SA1** [aimeos/aimeos-laravel#369]
![Capture](https://user-images.githubusercontent.com/49856819/111826314-5a253c00-890a-11eb-86fb-b41ae63ea2ab.PNG)

everything is working fine on "Checkout" => "Summary"
Terms and conditions
 I accept the terms and "conditions, privacy policy" and "cancellation policy" which i click on these link i see exception results shown in picture

**Comment by aimeos** [comment]
Did you customized the `app.blade.php` and added the error variable? In the standard template it's not part of the code.

**Comment by 1SA1** [comment]
i have fixed this issue by myself 
in /routes/web.php
paste this simply
Route::get('/privacy', '\Aimeos\Shop\Controller\PageController@privacyAction')->name('aimeos_shop_privacy');
