### ISSUE TITLE
Pagination not working correctly

### ISSUE THREAD

**Issue by oulfr** [aimeos/aimeos-laravel#370]
to reproduce the bug the scenario is:
we need many orders to have the bug.
1. Go to order page
2. Paginate to page 2 by clicking in 2 number
3. Now shoose to display 200 items
4. Order by invoice not working

**Comment by aimeos** [comment]
Is this in the admin backend or the user profile in the frontend?
Can you explain 4.) in more detail? What exactly happens?
Do you have any clue why that happens or a fix for the problem?

**Comment by oulfr** [comment]
this bug is in admin side.
if you create some orders to have 2 pages then you hit this url:

admin/default/jqadm/search/order?page%5Boffset%5D=25&page%5Blimit%5D=200&lang=en

Then click in order by Invoice the order is not correct.

**Comment by aimeos** [comment]
Seems like the page offset isn't reset when changing the limit and this is fixed now. If you use 2020.10, can you please execute:
```
composer req aimeos/ai-admin-jqadm:2020.10.x-dev
```
Does it work as expected then?

**Comment by oulfr** [comment]
Yep great you can close it
