### ISSUE TITLE
Called unknown method "getBirthday" on class "Aimeos\MShop\Customer\Item\Standard"

### ISSUE THREAD

**Issue by oulfr** [aimeos/aimeos-laravel#371]
In customer tables, when i choose to display the column birthday i have this exception

**Comment by aimeos** [comment]
Thanks for the hint. The problem is now fixed in `aimeos/ai-admin-jqadm:2020.10.x-dev`:
https://github.com/aimeos/ai-admin-jqadm/commit/d3b0421f8034be8baba9cd0a7d9b890b4095fa55
