### ISSUE TITLE
Product CSV Import gives error

### ISSUE THREAD

**Issue by babvi** [aimeos/aimeos-laravel#374]
**Environment**
1. Version (2020.10)
2. Operating system (Linux)

**Describe the bug**
when doing import as example file given, gets below error

 php artisan aimeos:jobs product/import/csv -vvv
Executing the Aimeos jobs for "default"
Invalid product lines in "/home/myuser/html/myshop/public/uploads/product_csv/": 2/3#0 /home/myuser/html/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(76): Aimeos\Controller\Jobs\Product\Import\Csv\Standard->run()
#1 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\{closure}(Object(Aimeos\MShop\Context\Item\Standard), Object(Aimeos\Bootstrap), 'product/import/...')
#2 /home/myuser/html/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(176): call_user_func_array(Object(Closure), Array)
#3 /home/myuser/html/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Pcntl.php(111): Aimeos\MW\Process\Pcntl->exec(Object(Closure), Array)
#4 /home/myuser/html/myshop/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/Process/Decorator/Check.php(61): Aimeos\MW\Process\Pcntl->start(Object(Closure), Array, false)
#5 /home/myuser/html/myshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(79): Aimeos\MW\Process\Decorator\Check->start(Object(Closure), Array, false)
#6 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Aimeos\Shop\Command\JobsCommand->handle()
#7 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#9 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#10 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#11 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#12 /home/myuser/html/myshop/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /home/myuser/html/myshop/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/myuser/html/myshop/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Aimeos\Shop\Command\JobsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/myuser/html/myshop/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/myuser/html/myshop/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/myuser/html/myshop/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}Process (PID "25777") failed with status "256"

When I looked into csv, its creating issue for a

attribute code | attribute type
-- | --
S/M | size
M/L | size

**To Reproduce**
1. Install & setup with PHP 7.3
2. configure import o shop.php
3. run import cmd

**Comment by aimeos** [comment]
Make sure the `size` attribute type is existing. If not, create it in the admin backend in the Attributes panel
