### ISSUE TITLE
port 443: Connection refused

### ISSUE THREAD

**Issue by 007sunilgautam** [aimeos/aimeos-laravel#375]
[Composer\Downloader\TransportException]
  curl error 7 while downloading https://packages.aimeos.org/aimeoscom/packages.json: Failed to connect to packages.a
  imeos.org port 443: Connection refused
![image](https://user-images.githubusercontent.com/53964910/113552410-bdee7b00-9613-11eb-93cc-c7ffd797f989.png)

**Comment by aimeos** [comment]
The server was down and is now up again.
