### ISSUE TITLE
Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by yunuskarakaya** [aimeos/aimeos-laravel#379]
I get this error when I go to the link after the installation of the application. 
I ran the following lines of code:
`composer create-project aimeos/aimeos myshop`
`php artisan serve`

I could not find the solution.
error messages are below.

Symfony\Component\Debug\Exception\FatalThrowableError
Cannot use a scalar value as an array
http://127.0.0.1:8000/index.php/shop

vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Attribute/Standard.php:81

**Comment by yunuskarakaya** [comment]
duplicated

**Comment by Samoylenko666** [comment]
good job. I asked myself, I found the answer myself, I closed it myself. Can you link to the material?
