### ISSUE TITLE
Unable to save basketvalues.total-value-min/max value at backend

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/aimeos-laravel#382]
**Environment**
1. Version (e.g. 2021.04)
2. Operating system (Mac)
3. Laravel

**Describe the bug**
Unable to save when trying to add decorator BasketValues with option basketvalues.total-value-min and basketvalues.total-value-max. Error: basketvalues.total-value-min: Not a key/value map

**To Reproduce**
1. Go to Configuration > Services
2. Click on any payment
3. Add decorator "Basketvalues"
4. Fill in the value for basketvalues.total-value-min and basketvalues.total-value-max
5. Click save
6. Error: basketvalues.total-value-min: Not a key/value map will show

**Screenshots**
![image](https://user-images.githubusercontent.com/82187386/118954458-5d7f8700-b990-11eb-8fd6-0ff246296b68.png)

**Additional context**
I think it's due to checkConfigBE issue when the <kbd>type</kbd> equals to <kbd>map</kbd>

**Comment by switch-cheehau** [comment]
Thanks for the reply, after composer update, i'm still having the same issue, i guess it's because i'm not using master branch.
I'm using branch 2021.04

I'll try to test on main branch

**Comment by aimeos** [comment]
You are right, the fix haven't been merged into the 2021.04 branch. This is done now and you can get the fix by executing:
```
composer req aimeos/ai-admin-jqadm:2021.04.x-dev
```

**Comment by switch-cheehau** [comment]
Perfect! it works!

Thanks for the awesome codes. Look forward to contribute as well in future.
