### ISSUE TITLE
Look for proper way to add additional field in checkout/address page

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/aimeos-laravel#384]
Hi Aimeos,

Hope you can guide me on this:

I'm trying to add new field <kbd>passport no.</kbd> in the checkout process.
So in order to make the checkout process seamlessly:

1. Extend the table <kbd>users</kbd> and <kbd>mshop_order_base_address</kbd> with new column passport
- adding in <kbd>users</kbd> table is to set a default passport number.

2. adapting client/html/templates/checkout/standard/address-partial-standard.php to add the new field
- but i do not know how to pass in the value from customer.password into  <?= $enc->attr( $this->value( 'address', 'order.base.address.passport' ) ) ?>

3. adapting client/html/templates/common/summary/address-standard.php to display the new field in summary tab
4. Save the new field into order.base.address.passport

I'm refering to this doc:
https://aimeos.org/docs/2021.x/infrastructure/extend-managers/#item-properties
But i'm having hard time to relate to my problem.

Can you shed some light over here?

**Comment by aimeos** [comment]
Can you please ask support questions in the Aimeos forum?
https://aimeos.org/help

Thanks

**Comment by switch-cheehau** [comment]
Ah, sorry, i'll close the case and ask over there.
