### ISSUE TITLE
Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by BrainStormDevel** [aimeos/aimeos-laravel#385]
**Environment**
1. Version: 2021.04.4
2. Operating system: Windows

**Describe the bug**
If  ext-intl was not enabled in php.ini, Class "NumberFormatter" was not found.

**To Reproduce**
Comment php_intl.dll in extensions.

**Expected behavior**
A require in composer.json for ext-intl will fix the issue.

**Comment by aimeos** [comment]
`ext-intl` is already required by the Aimeos core:
https://github.com/aimeos/aimeos-core/blob/master/composer.json#L21

Isn't that enforcing `ext-intl` to be installed?

**Comment by BrainStormDevel** [comment]
No, I have created the shop with: php composer create-project aimeos/aimeos myshop with success. After installation, the shop show me Class "NumberFormatter" not found error.

**Comment by aimeos** [comment]
That seems to be a composer issue that php extension requirements are ignored if they are not listed in the root composer.json even if the documentation doesn't make are restrictions: https://getcomposer.org/doc/04-schema.md#package-links

Can you please open a bug report for composer and add a link here for referenc?
Thank you

**Comment by Seldaek** [comment]
What I am assuming is the problem here is that your CLI PHP config (in php.ini) is different from the one you run in your web server. So composer installed fine as intl is enabled in CLI, but intl is not present in the web config and so when running the software it fails.
