### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [aimeos/aimeos-laravel#386]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by aimeos** [comment]
@huntr-helper @JamieSlome Please use the contact form at aimeos.org to report security issues:
https://aimeos.org/contact#c198

The SECURITY.md file is sub-optimal because we have a lot of repositories. We will see what we can do for the future.

**Comment by JamieSlome** [comment]
@aimeos - thanks for your response.

Do you have an e-mail we could directly send the details to?

**Comment by aimeos** [comment]
We don't publish any e-mail addresses as this only leads to spam. Please use the contact form instead.

**Comment by JamieSlome** [comment]
@aimeos - I have sent over the advisory URLs via your contact form!

Let me know if you have any questions.
