### ISSUE TITLE
php artisan vendor:publish not publishing any files

### ISSUE THREAD

**Issue by sjeswinder** [aimeos/aimeos-laravel#39]
HI
I created a new laravel project and installed aimeos using steps from documentation. Post composer update no fioles are published to config folder.

here is my composer .json

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "prefer-stable": true,
    "minimum-stability": "dev",

    "require": {
        "php": ">=5.5.9",
         "aimeos/aimeos-laravel": "~2016.04",
        "laravel/framework": "5.2.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
        "php artisan vendor:publish --tag=public --force",
            "php artisan vendor:publish",
            "php artisan migrate",
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
   
}

```
Following is the output from composer update
```
D:\trainings\aimeos-demo>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> php artisan vendor:publish --tag=public --force
Nothing to publish for tag [public].
> php artisan vendor:publish
Nothing to publish for tag [].
> php artisan migrate
Nothing to migrate.
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

**Comment by aimeos** [comment]
Then you've probably forgotten to add the service provider line in `config/app.php`

**Comment by sjeswinder** [comment]
If i refer to documentation there it asks to add service provider post running 

`composer update`
![laravel-install aimeos - aimeos documentation 2016-04-27 17-46-22](https://cloud.githubusercontent.com/assets/17142364/14851841/1dd5a2a8-0ca0-11e6-9212-4684899e9bc9.png)

**Comment by aimeos** [comment]
After you've added the service provider, there are four "artisan" command which you have to execute. The first one will publish the files.

**Comment by sjeswinder** [comment]
I got that . it's working. I just want to suggest for right flow of command. One need to add the service provider in config/app.php before executing composer update. 

I think there can be a small change in docs mentioning this.  Hope you got what i want to say.

**Comment by aimeos** [comment]
There was a problem when you do it before. That led to an exception as far as I remember.

**Comment by sjeswinder** [comment]
Without adding service provider to config/app.php , if you run composer update, it won't publish the files. This is what i faced after reading the documentation, which adds the service provider after running composer update. You added three line in composer.json...

Anyways my issue is resolved. Hope you can modify the documentation marking users to add service provider and then run command to publish the file.

**Comment by aimeos** [comment]
This is already the case. `php artisan vendor:publish` is among the last commands to be executed and in the documentation after adding the service provider class.

**Comment by sjeswinder** [comment]
Got it !! I thought you just referred to the three publish command given in composer.json at top of doc page.

**Comment by MohamedHana** [comment]
# Follow these steps:
1- Add service provider to providers array on the config/app.php
2- Run  **php artisan config:cache** 
3- Run **composer update**
4- Run  **php artisan config:cache**  
5- Run **php artisan vendor:publish**

**Comment by rockeycse** [comment]
I can't use this package as local url like http://localhost/aimeos/public/admin. How can I run the package without artisan command?

**Comment by aimeos** [comment]
The "public" directory needs to be the document root.
You need the artisan commands not only for installation but also for e.g. sending the e-mail confirmations or rebuilding the product index. Without, you won't have any fun.
