### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by chintala1002** [aimeos/aimeos-laravel#390]
Hi,

I am getting below issue while adding this aimeos-laravel.

Problem 1                                                                                                                 - aimeos/aimeos-laravel[2021.07.1, ..., 2021.07.x-dev] require laravel/framework ^6.20.12||^7.30.4||^8.40.0 -> found laravel/framework[v6.20.12, ..., 6.x-dev, v7.30.4, 7.x-dev, v8.40.0, ..., 8.x-dev] but it conflicts with your root composer.json require (5.5.*).                                                                                                  - Root composer.json requires aimeos/aimeos-laravel ~2021.07 -> satisfiable by aimeos/aimeos-laravel[2021.07.1, 2021.07.x-dev].

**Comment by aimeos** [comment]
Your composer.json requires Laravel 5.5 but the minimum version required by Aimeos is Laravel 6 LTS.

**Comment by chintala1002** [comment]
Can you please help me with how can I fix this issue, I installed fresh application of "aimeos/aimeos"  yesterday only.

**Comment by aimeos** [comment]
What's the output of `php -v`?

**Comment by chintala1002** [comment]
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )                                               Copyright (c) The PHP Group                                                                                             Zend Engine v3.4.0, Copyright (c) Zend Technologies  

Can you please share me any reference links for fixing above issue

**Comment by chintala1002** [comment]
Now i done the fresh installation but getting new issue
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`))                                                                                                                           at C:\wamp64n\ghub\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669                                    665|         // If an exception occurs when attempting to run a query, we'll format the error                           666|         // message to include the bindings with SQL, which will make this exception a                              667|         // lot more helpful to the developer instead of just the database's errors.                                668|         catch (Exception $e) {                                                                                   > 669|             throw new QueryException(                                                                              670|                 $query, $this->prepareBindings($bindings), $e                                                      671|             );                                                                                                     672|         }                                                                                                          673|                                                                                                                                                                                                                                          Exception trace:                                                                                                                                                                                                                                1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")                                                                                        C:\wamp64n\ghub\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18                                                                                                                                                          2   Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))                                                           C:\wamp64n\ghub\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:114                                                                                                                                                          Please use the argument -v to see more details.                                                                       Script @php artisan migrate handling the post-create-project-cmd event returned with error code 1

**Comment by aimeos** [comment]
PHP 7.4 is OK but your MySQL database is too old. Aimeos requires MysQL 5.7.8+ or a corresponding MariaDB version. There's a workaround for older versions:
https://github.com/aimeos/aimeos-laravel#database

**Comment by chintala1002** [comment]
Thank you for your support. Now it is working fine.
