### ISSUE TITLE
sub-category issues

### ISSUE THREAD

**Issue by LastJoeru** [aimeos/aimeos-laravel#392]
**Environment**
1. Version - latest installed in Jun2021
2. Operating system (Linux)

**Describe the bug**
Adding sub-categories further than 2 deep down appears to save but fail and only saves them at level 1.

**To Reproduce**
1. Go to admin panel
2. Select Catalog > Categories
3. Create sub categories more than 2 deep down
4. Refresh

**Expected behavior**
Sub-Categories should be saved in the level they are created

**Comment by aimeos** [comment]
Please make sure you've selected the category you want to add the sub-category before clicking on the "+" symbol.

**Comment by LastJoeru** [comment]
> Please make sure you've selected the category you want to add the sub-category before clicking on the "+" symbol.

Yeah, that works for only 2 levels, for the next level down, it always reverts back to level one.  
I've reinstalled Aimeos fresh multiple times and only created sub categories, but still get the same issue

**Comment by LastJoeru** [comment]
In addition, also sometimes the catalog structure does not display properly, instead it repeats in cycles
![image](https://user-images.githubusercontent.com/29390949/125865529-dc5716f1-1490-4670-aca9-ec71a3c9d751.png)

**Comment by aimeos** [comment]
This has been fixed some time ago. Can you please post the output of `composer show` to see which version are you using?

**Comment by Cyber-Devs** [comment]
try to refresh ur database if u using dev2021 and then check✌️

**Comment by LastJoeru** [comment]
> This has been fixed some time ago. Can you please post the output of `composer show` to see which version are you using?

I've installed a clean new version 2021.07.3
My previous issue with multiple sub-categories has been fixed.
However now, when I add a new subcategory under the main Home category, only one 1st level category is displayed in the menus when user not logged in.  
example tree: 
Home -
    - cat 1
    - cat 2
    - cat 3

in the menu nav bar only cat 1 is displayed on the default / path.   
if user is logged in all categories are displayed
This is a fresh install without any changes just adding categories.

**Comment by aimeos** [comment]
Seems to be a caching issue and has been fixed in dev-master and 2021.07. Can you confirm?

**Comment by LastJoeru** [comment]
caching is not disabled

	'madmin' => [
		'cache' => [
			'manager' => [
				// 'name' => 'None', // Disable caching for development
			],
		],

and I'm using 2021.07

**Comment by aimeos** [comment]
Did you update your installation to get the latest packages released yesterday?

**Comment by LastJoeru** [comment]
tried to upgrade but failed, had to do a full reinstall, issue appears to be fixed, thanks.
