### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by abdelrahman-varit** [aimeos/aimeos-laravel#397]
I'm trying to install the project using
`wget https://getcomposer.org/download/latest-stable/composer.phar -O composer
php composer create-project aimeos/aimeos myshop
`
But I get:
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aimeos/ai-cms-grapesjs[2021.07.1, ..., 2021.07.x-dev] require aimeos/aimeos-core 2021.07.* -> satisfiable by aimeos/aimeos-core[2021.07.1, 2021.07.2, 2021.07.x-dev].
    - aimeos/aimeos-core[2021.07.1, ..., 2021.07.x-dev] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires aimeos/ai-cms-grapesjs 2021.07.* -> satisfiable by aimeos/ai-cms-grapesjs[2021.07.1, ..., 2021.07.x-dev].
`

**Comment by abdelrahman-varit** [comment]
Also I tried:
`wget https://getcomposer.org/download/latest-stable/composer.phar -O composer
php composer require aimeos/aimeos-laravel:~2021.07
`
But I get: 
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aimeos/aimeos-laravel[2021.07.1, ..., 2021.07.4] require aimeos/aimeos-core 2021.07.* -> satisfiable by aimeos/aimeos-core[2021.07.1, 2021.07.2].
    - aimeos/aimeos-core[2021.07.1, ..., 2021.07.2] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires aimeos/aimeos-laravel ~2021.07 -> satisfiable by aimeos/aimeos-laravel[2021.07.1, 2021.07.2, 2021.07.3, 2021.07.4].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-bcmath.ini
    - /etc/php/7.4/cli/conf.d/20-bz2.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-curl.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-imagick.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/20-zip.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.
`

**Comment by aimeos** [comment]
Your PHP installation is missing the "intl" extension

**Comment by abdelrahman-varit** [comment]
> Your PHP installation is missing the "intl" extension

Thanks, It works!
