### ISSUE TITLE
categories and product are not showing up on frontend

### ISSUE THREAD

**Issue by Virendra786** [aimeos/aimeos-laravel#4]
I have installed this package and all goes well.
but when i add categories and products from backend ,products got added but they are not showing up in frontend.

and one more problem when i run  this application on local apache server index.php/list page is showing but when i click on any link it leads to object not found error.

**Comment by aimeos** [comment]
Have you assigned the products to any category? Without, the products won't show up. You also need to save the product once again after you've added it to a category, so the index is updated. Alternatively, you can run ```./artisan aimeos:jobs catalog/index/rebuild``` on the command line to recreate the complete catalog index.

Can you post the error and the stack trace?

**Comment by Virendra786** [comment]
i have assigned products to category by going through category drag a
product from right panal to left and then saved the product but still it is
not showing in fornted and category that i created is showing also in
frontend

**Comment by aimeos** [comment]
Did you've enabled both, the product and category using the "status" drop-down in their detail views?

**Comment by Virendra786** [comment]
My problem got solved after disabling cache in shop.php
 i have one more questing is it possible to add a root category which is
not child of any category

**Comment by aimeos** [comment]
The categories are organized as a tree and there can be only one per shop. But you can work around this if you add two children to the root node and let your displayed tree start with the first node by configuring its ID with the client/html/catalog/filter/tree/startid setting:
http://aimeos.org/docs/Configuration/Core/client/html/Adapt_catalog_filter

The other category is then available but not shown.

**Comment by aimeos** [comment]
We've fixed the cache invalidation problem. The code in the master branch works now as expected.

**Comment by AlexFoster009** [comment]
For some reason the prices i set in the backend are not displaying on the frontend

**Comment by aimeos** [comment]
Problem was that the required site/language/currency combination in the "Locale" -> "List" tab (expert mode admin interface) was not the first one, so default/en/EUR was used instead of default/en/USD
