### ISSUE TITLE
Laravel/Add locale selector failed as "the page you are looking for could not be found"

### ISSUE THREAD

**Issue by dadaycm** [aimeos/aimeos-laravel#40]
# Background:
**versions:**
- [ ] ubuntu v14.04.1
- [ ] Homestead 3.19.0-25
- [ ] laravel 5.2
- [ ] aimeos 2016-04
- [ ] PHP 7.0.5-2+deb.sury.org~trusty+1 (cli) ( NTS )
 
# What's done before this error appears
1. a new laravel5.2 project was created by command "laravel new ..."
1. aimeos was installed, demo data has been successfully setup
  url "/list" and "/extadm" works well.
1. instructions on "_/docs/User_Manual/Create_the_first_product_" have been followed
One  new product has been added with name/category/price. 
-  2 "name" texts, one with language Chinese and the other with language English.
-  2 prices, one is Chinese Yuan, another is US dollar
1.  from **Locale** panel, two combinations have been added:
-  Chinese, Chinese Yuan Renminbi
-  Chinese, US Dollar

**So far, so good.**
Now,  I am trying to open another browser(eg, switch from Chrome to Firefox) to login as another user (not admin) then open ".../list", and I am expecting to see Chinese name and price with CNY or USD instead of default Europe.
I tried many ways but failed and then I read to the document _https://aimeos.org/docs/Laravel/Add_locale_selector_  but strange errors happened. Please see below.

# Error Description:
From
_https://aimeos.org/docs/Laravel/Add_locale_selector_
Changes have been applied to **config/shop.php** and** 4 templates** under directory _resources/views/vendor/shop/..._ as instructed. Good, **new component "locale/select" appeared at 4 pages** as expected. Cool! But...

Error happened at section **Routes**,
After the prefix line was added as below (see bold line):
```
		'account' => array(
**_			'prefix' => '{locale}/{currency}',_**
			'middleware' => ['web', 'auth'],
			),
```
then go to the page "/myaccount", error was reported as below:
```
Sorry, the page you are looking for could not be found.
1/1 NotFoundHttpException in RouteCollection.php line 161:

    in RouteCollection.php line 161
    at RouteCollection->match(object(Request)) in Router.php line 823
    at Router->findRoute(object(Request)) in Router.php line 691
    at Router->dispatchToRoute(object(Request)) in Router.php line 675
    at Router->dispatch(object(Request)) in Kernel.php line 246
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
    at CheckForMaintenanceMode->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
    at Pipeline->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Kernel.php line 132
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
    at Kernel->handle(object(Request)) in index.php line 53
```
# After the prefix line was commented out,  the route "myaccount" could be visited once again.
But **unexpected** point still exists:
- The new component _"locale/select" _ appeared and it could be operated against.
- after the above component was clicked, "Chinese" and "CNY" selected, the **URL line in browser** changed to: .../myaccount?locale=zh&currency=CNY
- the articles shown in the page is still in orignal language/currency(English/Europe) and the selection does not take effect.

Please have a check, thanks.

**Comment by aimeos** [comment]
OK, step by step:

By default the first active site/language/currency combination listed in the "Locale" -> "List" tab of the expert mode admin interface will be shown in the frontend. If you haven't disabled the caching for development (https://github.com/aimeos/aimeos-laravel#hints), you will need to clear the cache using "./artisan aimeos:cache".

Afterwards, you should see the first configured language/currency in the frontend. Is this the case?

**Comment by dadaycm** [comment]
Thank you so much for your quickly reply. 

Yes, I have disabled the caching for development already. Exactly following doc to append that section in the end of config file. 

- Following your suggestion, I adjusted the value of position to make sure that combination Chinese/CNY is the first active. Now from the list page, Product **name** is shown as Chinese, exactly as expected, perfect! 
- But, **price** is displayed as **plain text** instead of a **_number_** which is set at admin panel.
- After setting language/currency back to English/Euro from admin, then visiting front end, product **price**  are displayed normally ( as **number**) once again.
- **Prefix bug** keeps the same. Once the routes/page `'prefix' => '{locale}/{currency}',` is assigned to the page, it can not be visited. please see attached config file: [shop.php.txt](https://github.com/aimeos/aimeos-laravel/files/247962/shop.php.txt)


Attached screenshot may be helpful if my description is not clear.
1. Price setting from admin
![price](https://cloud.githubusercontent.com/assets/17735924/15001805/4321bcae-11cd-11e6-8911-619bcd80fc22.png)
2. Set Local to make CNY first
![local-cn-first](https://cloud.githubusercontent.com/assets/17735924/15001872/cb71c3ec-11cd-11e6-95b3-e146c363e9c6.png)
3. List page : unexpected price display
![list-cny](https://cloud.githubusercontent.com/assets/17735924/15001884/e5e4922c-11cd-11e6-9acf-d2383936c52d.png)
4. Set Local back to English/Euro first
![local-eng-euro-first](https://cloud.githubusercontent.com/assets/17735924/15001893/f8ea9f92-11cd-11e6-897a-d4f4827006b3.png)
5. List page: normal price display
![list-english-euro](https://cloud.githubusercontent.com/assets/17735924/15001900/137e4494-11ce-11e6-9b86-7f1109274474.png)
6. Prefix bug -- myaccount page
![myaccount-prefix-route-bug](https://cloud.githubusercontent.com/assets/17735924/15001907/1c8471c6-11ce-11e6-90a4-34d33899fe72.png)

**Comment by dadaycm** [comment]
One more discovery about locale select component: 
Three points have not been synchronized in:
- URL
- locale/select component
- product name/price

# Steps:

1. Comment out the prefix line`  'prefix' => '{locale}/{currency}'` in config file.
2. Add locale/select comment to page catelog/list in both config file and page template.
3. visit catelog/list page and the locale/select component is shown and can be operated.
4. Change value by operate catelog/select component to select **English/Euro** and observe three things:
- URL
- locale/select component
- product name/price

# Expecation:
when selection from locate/select component changes, the URL line and  product item name/price  will be changed accordingly.
- URL  English/Euro
- locale/select component    English/Euro
- product name/price  English/Euro

# Result:
Three parts are not synchronized as expected. 
Most unexpected is that, the **component itself** is shown to other value which is very different from what is intented.
Please see attached screen shot.

![list-local3-no-sync](https://cloud.githubusercontent.com/assets/17735924/15002391/537494a4-11d3-11e6-8dbc-1a991b5074a9.png)

**Comment by aimeos** [comment]
The problem why "price:default" is shown is simply because there's no translation in Chinese available. It should be something like `%1$s %2$s` or `%2$s %1$s` depending on where the currency symbol should be shown (%1 is the price and %2 is the currency symbol).

**Comment by aimeos** [comment]
Did you enter the `/myaccount` URL by hand? If you add the prefix to its route, your URL must then be `/zh_CN/CNY/myaccount` (including the language and currency codes). Otherwise, the Laravel router won't be able to match the route any more.

**Comment by aimeos** [comment]
`/list?locale=zh_CN&currency=CNY` is not accepted in your setup because only route parameters are currently evaluated, so only `/zh_CN/CNY/list` works.
We changed the code to use the query parameters in the future as well: https://github.com/aimeos/aimeos-laravel/commit/585a697b606151dbc25261e551829bf669b65f90

**Comment by dadaycm** [comment]
Thanks for your response.

Unfortunately, the url format what you suggested as below does NOT work.
`/zh_CN/CNY/myaccount`
`/en/EUR/myaccount`
Neither of the above works. Error was reported as:
```
Sorry, the page you are looking for could not be found.
1/1 NotFoundHttpException in RouteCollection.php line 161:
```

Let me answer your question below:

> Did you enter the /myaccount URL by hand?

No. The url `/myaccount?locale=en&currency=EUR`  was not entered by hand, but genereated by browser after **locale/select** comonent is operated. When new language/currency combination is selected, the url from browser is changed automatically.
Thanks.

**Comment by aimeos** [comment]
Do you still have the `'prefix' => '{locale}/{currency}'` configuration in your "routes/account" section of your `config/shop.php`?

**Comment by dadaycm** [comment]
> Do you still have the 'prefix' => '{locale}/{currency}' configuration in your "routes/account" section of your config/shop.php?

Of course no. If they were there, it would fail to visit the page.

**Comment by aimeos** [comment]
For `/zh_CN/CNY/myaccount` you have to add the prefix. Otherwise, it won't work at all.
