### ISSUE TITLE
DB table problem, Postgres

### ISSUE THREAD

**Issue by xhostcom** [aimeos/aimeos-laravel#400]
Hi I have small problem after migrate , in Postgresql.

Aimeos\MW\DB\Exception
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "mshop_locale_site" does not exist LINE 10: FROM "mshop_locale_site" AS mlocsi ^: SELECT mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."icon" AS "locale.site.icon", mlocsi."logo" AS "locale.site.logo", mlocsi."supplierid" AS "locale.site.supplierid",

Have I missed a step in setup?

**Comment by aimeos** [comment]
You have missed to run:
```
php artisan aimeos:setup --option=setup/default/demo:1
// or
php artisan aimeos:setup
```

**Comment by xhostcom** [comment]
OK thanks
