### ISSUE TITLE
get "Couldn't create directory" error when try add product with media

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#402]
**Environment**
1. aimeos/aimeos-laravel Version 2021.07.4
2. Operating System: Windows
3. Local Dev With: XAMPP

**Describe the bug**
I use xampp to develop my aimeos shop, in new installation of aimeos/aimeos-laravel 2021.07.4 when i try to add media for products and save it, i get error "Couldn't create directory "1./files/e/0""
I create public/files public/preview public/uploads folders but still have error
also I create public/aimeos/files public/aimeos/preview public/aimeos/uploads folders but still have error

my htdocs folder in xampp have Full Controll permission to read, write and modify but why this happen?

**Comment by aimeos** [comment]
The used directories have changed in 2021.07 to comply to the Laravel standards. We've added a hint now:
https://github.com/aimeos/aimeos-laravel#test

**Comment by parsester** [comment]
I change that line and add `d` character after `${siteid}` and then upload succeed, keep this change anymore? 
if keep it when I update aimeos this change discarded, what can I do?

**Comment by aimeos** [comment]
This was just for testing if it works. The change has been added to dev-master and 2021.07.x now.
Please run "composer up" to get the latest version.
