### ISSUE TITLE
2021.7 is not compatible with PHP 8, 2020.4 is.

### ISSUE THREAD

**Issue by Thiritin** [aimeos/aimeos-laravel#403]
**Environment**
1. Version (e.g. 2017.10)
2021.7
2. Operating system (Linux, Mac, Windows)
Linux

**Describe the bug**
The Version 2021.7 is not compatbile with PHP 8.

**To Reproduce**
1. Create a fresh Laravel repo
2. Run composer require aimeos/aimeos-laravel:~2021.07

**Additional context**

![image](https://user-images.githubusercontent.com/6755282/129112511-bdb62750-21d2-4caf-b670-6151b304ce9b.png)

**Comment by aimeos** [comment]
Works without problems in our tests and aimeos/aimeos-laravel has no PHP version constraint.
It's more likely that you use composer before version 2.1. Check with `composer -V`
