### ISSUE TITLE
New Theme is not used.

### ISSUE THREAD

**Issue by LastJoeru** [aimeos/aimeos-laravel#404]
**Environment**
1. Version (2021.07)
2. Operating system (Linux)

**Describe the bug**
followed the instructions from https://aimeos.org/docs/latest/frontend/html/create-themes/ the new theme does not get used

**To Reproduce**
follow documented steps https://aimeos.org/docs/latest/frontend/html/create-themes/

**Expected behavior**
New theme should be used instead of the default

**Screenshots**

**Additional context**
To me it appears there is missing steps to let the system know which theme to use, also there are some path names in the document that are no longer valid.

**Comment by aimeos** [comment]
Do you really have installed the unsupported version Aimeos 2017.10? Current version is 2021.07

**Comment by LastJoeru** [comment]
sorry should have edited that to 2021.07

**Comment by aimeos** [comment]
Since 2021.07, this article was only half of the truth because now it's possible to create theme extensions for Laravel. We've now finished the documenation for theme packages, which you can find here:
https://aimeos.org/docs/latest/laravel/themes/
