### ISSUE TITLE
Checkout TypeError

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#405]
**Environment**
1. Version (e.g. 2021.7.x dev-master)
2. Operating system (Linux, Mac, Windows)

Checkout Error
"TypeError
Return value of Aimeos\MShop\Order\Item\Base\Product\Standard::getStatus() must be of the type int, null returned"

after fresh installication as well the same error, it sent the order to admin but cant open in jquerry admin,

**Comment by aimeos** [comment]
Thanks for the hint. Problem has been fixed in dev-master but isn't present in 2021.07.x-dev

**Comment by Cyber-Devs** [comment]
thanks alot its fixed now.
