### ISSUE TITLE
dead links, 419 PageExpired

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#410]
**Environment**
1. Version (laravel dev-master)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**
dead links. in 
PageExpired 
code 419
/shop/pin?pin_action=add&pin_id=1&d_name=Demo-article&site=default
/shop/pin?pin_action=add&pin_id=1&d_name=Demo-article&site=default&locale=de&currency=EUR
/profile/favorite/add/1/Demo-article?site=default&locale=de&currency=EUR

**Comment by aimeos** [comment]
This is currently work in progress, please stay tuned.

**Comment by aimeos** [comment]
Issue is fixed now: https://github.com/aimeos/ai-client-html/commit/db1c36d3e25ac44b05d7fa398135bd183c964de2
