### ISSUE TITLE
Amieos with MSSQL

### ISSUE THREAD

**Issue by atul-khatri** [aimeos/aimeos-laravel#412]
**Environment**
1. 2021.x (e.g. 2020.10)
2. Windows (Linux, Mac, Windows)

**Describe the bug**
I have install the amieos application with using mysql db. Then I have migrate my db into MSSQL server. Then I change the env parameter to sqlsrv and other param. After this I have run the server and getting below error.

Aimeos\MW\DB\Exception
SQLSTATE[42S02]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'mshop_locale_site'.: SELECT mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."icon" AS "locale.site.icon", mlocsi."logo" AS "locale.site.logo", mlocsi."supplierid" AS "locale.site.supplierid", mlocsi."theme" AS "locale.site.theme", mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime", mlocsi."ctime" AS "locale.site.ctime" FROM "mshop_locale_site" AS mlocsi WHERE ( mlocsi."code" = 'default' ) ORDER BY mlocsi."id" ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

**To Reproduce**
1. Install fresh Amieos project with MySQL
2. Migrate Mysql DB to MSSQL
3. Change the env parmater and change dbconnection, host, username etc
4. Run php artisan serve
5. See error

**Expected behavior**

**Additional context**
![bug](https://user-images.githubusercontent.com/89908023/135595249-dac94b97-fcb6-42d5-b6d4-0c9ad872464a.png)

**Comment by aimeos** [comment]
Doubt that your migration was successful because the mshop_locale_site table (and probably others too) are not there.

**Comment by atul-khatri** [comment]
Can you please share the link to install aimeos with MSSQL server?

**Comment by aimeos** [comment]
Just use MSSQL server from the beginning (instead of MySQL) and migrate the data afterwards

**Comment by atul-khatri** [comment]
I have run below command,

composer create-project aimeos/aimeos myshop

After that once I gave DB_connection=sqlsrv, db_hostname, db_username etc details, it stuck at below point.
I am using SQL-Server 2019 express version.

    Using schema from customer.php
      Checking table "mshop_customer":                                  done
      Checking table "mshop_customer_address":                          done
      Checking table "mshop_customer_group":                            done
      Checking table "mshop_customer_list_type":                        done
      Checking table "mshop_customer_list":                             done
      Checking table "mshop_customer_property_type":                    done
      Checking table "mshop_customer_property":                         done
      Checking table "users":
     Aimeos\MW\DB\Exception  : SQLSTATE[42000]: [Microsoft][ODBC Driver 11 fo
  r SQL Server][SQL Server]Incorrect syntax near the keyword 'IDENTITY'.: ALT
  ER TABLE users ALTER COLUMN id BIGINT IDENTITY NOT NULL

    at C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\
  Statement\DBAL\Simple.php:75
      71|       {

      72|               try {

      73|                       $result = $this->exec();

      74|               } catch( \PDOException $e ) {

    > 75|                       throw new \Aimeos\MW\DB\Exception( $e->getMessag
e() . ': ' . $th
  is->sql, $e->getCode() );
      76|               }

      77|
      78|               return new \Aimeos\MW\DB\Result\PDO( $result );

      79|       }


    Exception trace:

    1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
        C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Se
  tup\Task\Base.php:164

    2   Aimeos\MW\Setup\Task\Base::executeList("db-customer")
        C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mshoplib\setup\
  TablesCreateMShop.php:177

    Please use the argument -v to see more details.


  Error Output:
  ================


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--p
refer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSI
TORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-s
cripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-ins
tall] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--as
k] [--] [<package>] [<directory>] [<version>]

**Comment by aimeos** [comment]
Seems like Doctrine DBAL generates a wrong SQL statement for SQL Server. Is the `users` table already created and if yes, what does `exec sp_columns 'users'` return?

**Comment by atul-khatri** [comment]
It seems, IDENTITY keyword is not converted by DBAL in this query "ALTER TABLE users ALTER COLUMN id BIGINT IDENTITY NOT NULL". Also multiple foreign constraint with DELETE CASCADE giving issues.

**Comment by aimeos** [comment]
There must be something else because MSSQL tests run without problems and e.g. "mshop_order" table also has a "BIGINT IDENTITY" column:

- https://app.circleci.com/pipelines/github/aimeos/aimeos-core/599/workflows/8b9bcb4a-9165-4e61-9889-a34ef41b39c8/jobs/2590
- https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/setup/default/schema/order.php#L275
- https://github.com/aimeos/ai-laravel/blob/master/lib/custom/setup/default/schema/customer.php#L18

**Comment by atul-khatri** [comment]
Can you share link for installing aimeos with mssql with step by step?

**Comment by aimeos** [comment]
There are not other steps required besides these:
https://aimeos.org/docs/latest/infrastructure/databases/#sql-server

But they are only required after installation. You have to find out why creating the users table failed in your setup. For a start, you can put a `print_r($stmts);` here and run `php artisan aimeos:setup` to print out all executed SQL statements:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/setup/TablesCreateMShop.php#L176

**Comment by atul-khatri** [comment]
Ohk I put print_r($stmts). Now I got this below.

OK
    Checking table "mshop_locale_site":                               Array
(
    [0] => ALTER TABLE mshop_locale_site ALTER COLUMN siteid NVARCHAR(255) NOT N
ULL UNIQUE
    [1] => ALTER TABLE mshop_locale_site ALTER COLUMN code NVARCHAR(255) NOT NUL
L
    [2] => ALTER TABLE mshop_locale_site ALTER COLUMN supplierid NVARCHAR(36) NO
T NULL
)

   Aimeos\MW\DB\Exception  : SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL
 Server][SQL Server]Incorrect syntax near the keyword 'UNIQUE'.: ALTER TABLE msh
op_locale_site ALTER COLUMN siteid NVARCHAR(255) NOT NULL UNIQUE

  at C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\State
ment\DBAL\Simple.php:75
    71|         {
    72|                 try {
    73|                         $result = $this->exec();
    74|                 } catch( \PDOException $e ) {
  > 75|                         throw new \Aimeos\MW\DB\Exception( $e->getMessag
e() . ': ' . $this->sql, $e->getCode() );
    76|                 }
    77|
    78|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    79|         }

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\T
ask\Base.php:164

  2   Aimeos\MW\Setup\Task\Base::executeList("db-locale")
      C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mshoplib\setup\Table
sCreateMShop.php:177

  Please use the argument -v to see more details.

**Comment by aimeos** [comment]
According to the SQL Server docs, the statement is totally valid:
```
ALTER TABLE mshop_locale_site ALTER COLUMN siteid NVARCHAR(255) NOT NULL UNIQUE
```
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-column-definition-transact-sql?view=sql-server-ver15

Which driver do you use? It must be **`sqlsrv`**

**Comment by atul-khatri** [comment]
Yes sqlsrv. Ohk I am sharing the shop.php changes.

'resource' => [
		'db' => [
			'adapter' => 'sqlsrv',
			'host' => 'localhost',
			'port' => '1433',
			'socket' => '',
			'database' => 'myshop2',
			'username' => 'atul',
			'password' => 'swl@2021',
			'stmt' => [],
			'limit' => 3, // maximum number of concurrent database connections
			'defaultTableOptions' => [
					'charset' => config('database.connections.' . config( 'database.default', 'mysql' ) . '.charset'),
					'collate' => config('database.connections.' . config( 'database.default', 'mysql' ) . '.collation'),
			],
			'driverOptions' => config( 'database.connections.' . config( 'database.default', 'mysql' ) . '.options' ),
		],
	],

'mshop' => [
		'index' => [
	        'manager' => [
	            'name' => 'SQLSrv',
	        ],
    	],
	],

and in env here is the configs

DB_CONNECTION=sqlsrv
DB_HOST=localhost
DB_PORT=1433
DB_DATABASE=myshop3
DB_USERNAME=atul
DB_PASSWORD=swl@2021

**Comment by atul-khatri** [comment]
Now this is giving new issue. NewID throwing null. Please check.

   Symfony\Component\Debug\Exception\FatalThrowableError  : Return value of Aime
os\MShop\Common\Manager\Base::newId() must be of the type string, null returned

  at C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Co
mmon\Manager\Base.php:365
    361|                        throw new \Aimeos\MShop\Exception( $msg );
    362|                }
    363|                $result->finish();
    364|
  > 365|                return $row[0];
    366|        }
    367|
    368|
    369|        /**

  Exception trace:

  1   Aimeos\MShop\Common\Manager\Base::newId(Object(Aimeos\MW\DB\Connection\DBA
L), "mshop/customer/manager/lists/type/laravel/newid")
      C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\C
ommon\Manager\Type\Base.php:147

  2   Aimeos\MShop\Common\Manager\Type\Base::saveItem(Object(Aimeos\MShop\Common
\Item\Type\Standard))
      C:\xampp\htdocs\myshop3\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\C
ommon\Manager\Decorator\Base.php:51

  Please use the argument -v to see more details.

**Comment by aimeos** [comment]
Your configuration seems to be correct. No clue why SQL Server reports errors in your setup. The SQL Server tests run without problems:
https://app.circleci.com/pipelines/github/aimeos/aimeos-core/599/workflows/8b9bcb4a-9165-4e61-9889-a34ef41b39c8/jobs/2590
