### ISSUE TITLE
Lighthouse-php GraphQL compatibility?

### ISSUE THREAD

**Issue by binaryfire** [aimeos/aimeos-laravel#414]
Hi guys

Will the Laravel Aimeos package work with the lighthouse-php GraphQL package?

Thanks!

**Comment by aimeos** [comment]
Lighthouse-php requires Eloquent models which we don't use for performance reasons. Thus, the package isn't compatible with Aimeos if you don't implement models for the tables Aimeos is using.

GraphQL is very good for write-heavy applications but as frontend for read-heavy e-commerce applications it's not suited and we recommend the JSON:API which scales infinitely compared to GraphQL.

**Comment by aimeos** [comment]
A GraphQL API for administration is now included in Aimeos 2022.10.1+
