### ISSUE TITLE
Unable to scale image

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#415]
**Environment**
1. Version 2021.07
2. OS: Linux CentOS 7
3. Web Server: NGINX 1.20
4. Laravel v8.53.1 (PHP v8.0.11)

**Describe the bug**
I try to add image media to the product and get error saving data and when check logs, i have "Unable to scale image" error.

why this happen?

this is full error: [trace.txt](https://github.com/aimeos/aimeos-laravel/files/7323364/trace.txt)

![2021-10-11_18-08-58](https://user-images.githubusercontent.com/16049244/136810029-238a7dcb-f885-4dd3-ace7-4fdfce6f7b40.jpg)

**Comment by parsester** [comment]
> GD problem

ok, but php-gd-8.0.11 installed, what is this problem and what can I do?

**Comment by aimeos** [comment]
You have to find out why `imagescale()` returns an error. Maybe the image type isn't supported

**Comment by parsester** [comment]
> GD is our fallback if Imagick isn't available, even if Imagick is preferrable because it doesn't have problems wen scaling images with transparent backgrounds. Thus, it's good if using most compatible settings for GD and we removed the mode from `imagescale()` now. The change is available in dev-master and 2021.10.x-dev.

thanks, 
please check https://github.com/aimeos/aimeos-core/blob/2021.10/lib/mwlib/src/MW/Media/Image/Standard.php#L286-L288

you remove `IMG_BICUBIC from` `resize` method but still `IMG_BICUBIC` has been used in watermark method.
and here that return same error.
please remove it from this line.

**Comment by aimeos** [comment]
Thanks for the hint. Now, this occurence has been remove too
