### ISSUE TITLE
Broken installation in fresh Laravel 5.2

### ISSUE THREAD

**Issue by LastTemplar** [aimeos/aimeos-laravel#42]
Hi guys,
I just did a fresh install of Laravel 5.2 and added the Aimeos Laravel package on top.
All went well, I also installed the demo package and did not get any errors along the way.

Now, when I go to the "list" route, I get the menu on top and an error in the content section saying "Catalog node for ID "" not available". Not sure if that is how it should be, my guess was that it should show something since the demo data was installed.
Screenshot: http://i.imgur.com/hBcEdjw.jpg

Then I logged in and went into the admin panel, the only thing I see here is this:
http://i.imgur.com/Gh5stiW.jpg
I don't see any Category management or anything else (I kinda expected to see something more).

I then clicked on the "+" icon to add a product, but noticed that none of the links actually work, they point to "**http://localhost/jqadm/create/product?site=default&lang=en**" although my project is actually installed under "**http://localhost/aimeos/public/**".

I then went and did some searches regarding these issues and tried to run this command:
**php artisan aimeos:jobs catalog/index/rebuild**

But it only came back to me with this:
**Executing the Aimeos jobs for "default"
[Aimeos\Controller\Jobs\Exception]
Invalid controller "catalog\index\rebuild" in "catalog\index\rebuild"**
So probably something is broken there too?

Could you help me figure out what's wrong with my installation?

Thank you!

**Comment by aimeos** [comment]
No demo data has been installed during setup in your installation. You can add it executing:
`php artisan aimeos:setup --option=setup/default/demo:1`.

Please make sure you've executed all `artisan` commands listed in https://github.com/aimeos/aimeos-laravel#installation-or-update

I'm not sure if it works flawlessly to install a Laravel application in a subdirectory. Laravel expects the `public` directory to be the document root.

For Laravel 5.2, rebuilding the index is done by `php artisan aimeos:jobs index/rebuild` like stated in the docs: https://aimeos.org/docs/Laravel/Configure_cronjobs#Setup
