### ISSUE TITLE
Unable to find product "Demo-selection-article"

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#420]
**Environment**
1. Version (e.g. dev-master laravel 8.*)
2. Operating system (Linux, Mac)

**Describe the bug**
Unable to find product "Demo-selection-article"
bug  are in selection as well in bundle article, 

**log**
Unable to find product "Demo-selection-article"
#0 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Catalog/Detail/Standard.php(546): Aimeos\Controller\Frontend\Product\Standard->resolve('Demo-selection-...')
#1 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Common/Decorator/Context.php(48): Aimeos\Client\Html\Catalog\Detail\Standard->addData(Object(Aimeos\MW\View\Standard), Array, NULL)
#2 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Catalog/Detail/Standard.php(279): Aimeos\Client\Html\Common\Decorator\Context->addData(Object(Aimeos\MW\View\Standard), Array, NULL)
#3 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Common/Decorator/Base.php(92): Aimeos\Client\Html\Catalog\Detail\Standard->getHeader('')
#4 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Controller/CatalogController.php(55): Aimeos\Client\Html\Common\Decorator\Base->getHeader()
#5 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Aimeos\Shop\Controller\CatalogController->detailAction('Demo-selection-...', '2')
#6 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('detailAction', Array)
#7 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Aimeos\Shop\Controller\CatalogController), 'detailAction')
#8 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#9 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Route->run()
#10 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\closure(Object(Illuminate\Http\Request))
#11 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#12 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#14 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#16 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#18 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#20 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#21 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#23 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#25 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#27 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#30 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\closure(Object(Illuminate\Http\Request))
#33 /Users/cyber/Sites/eshop/newshop/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#34 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#36 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#39 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#42 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#44 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/cyber/Sites/eshop/newshop/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#46 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#48 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#50 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /Users/cyber/Sites/eshop/newshop/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 /Users/cyber/Sites/eshop/newshop/server.php(21): require_once('/Users/cyber/Si...')
#54 main

**Additional context**
The same dead links in fresh installation as well.

**Comment by aimeos** [comment]
What's the problem?

**Comment by Cyber-Devs** [comment]
For me it's strange as well because everything working as except . let me a bit more dive into. in my code base the lats updated stage araise this problem. in the rest stages its all ok..:)
