### ISSUE TITLE
 Class 'Aimeos\MW\Setup\Manager\Multiple' not found

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#421]
After update dev-maste error.
LARAVEL aimeos (mac)
Error 

  Class 'Aimeos\MW\Setup\Manager\Multiple' not found

  at vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/SetupCommand.php:68
     64▕                \Aimeos\MShop::cache( false );
     65▕                \Aimeos\MAdmin::cache( false );
     66▕ 
     67▕                $taskPaths = $this->getLaravel()->make( 'aimeos' )->get()->getSetupPaths( $template );
  ➜  68▕                $manager = new \Aimeos\MW\Setup\Manager\Multiple( $ctx->getDatabaseManager(), $dbconfig, $taskPaths, $ctx );
     69▕ 
     70▕                $this->info( sprintf( 'Initializing or updating the Aimeos database tables for site "%1$s"', $site ) );
     71▕ 
     72▕                $manager->migrate( $task );

      +13 vendor frames 
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by aimeos** [comment]
We are currently making bigger changes in the core and the integrations are not updated yet. Please stay tuned.

**Comment by Cyber-Devs** [comment]
resolved....✋
