### ISSUE TITLE
error in products filter

### ISSUE THREAD

**Issue by yasrebi** [aimeos/aimeos-laravel#422]
**Environment**
1. Version (lastest version)
2. Operating system (Windows)

**Describe the bug**
I have problem in products filter , when i filter product by price or color or enything i see this message 
"ErrorException Array to string conversion"

**To Reproduce**
1. Follow aimeos documention
2. Test it 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/76174817/139707075-cb30683f-1368-46a3-861b-c2e2723310d2.png)
![image](https://user-images.githubusercontent.com/76174817/139707192-18abba8c-9457-4000-8eab-cadf19e42c46.png)

**Comment by aimeos** [comment]
We cannot reproduce the issue. Can you create a screencast of what you do?

**Comment by yasrebi** [comment]
never mind, i develop another project
