### ISSUE TITLE
Symfony\Component\ErrorHandler\Error\FatalError

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#423]
**Environment**
1. Version (amieos:dev-mister, aimeos/ai-cms-grapesjs:dev-master laravel8.*)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**
Symfony\Component\ErrorHandler\Error\FatalError

Class Aimeos\Client\Html\Cms\Page\Standard contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Aimeos\Client\Html\Iface::body)

**Comment by aimeos** [comment]
The ai-cms-grapesjs extension is now in par with ai-client-html again.
