### ISSUE TITLE
Called unknown method "init" on class

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#425]
**Environment**
1. Version (dev-master Laravel 8.*)
2. Operating system (Linux, Mac, Windows)

**Jquery-admin Log**
"Aimeos\Controller\Frontend\Service\Standard"
#0 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Checkout/Standard/Process/Standard.php(411): Aimeos\Controller\Frontend\Base->__call('init', Array)
#1 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Checkout/Standard/Process/Standard.php(282): Aimeos\Client\Html\Checkout\Standard\Process\Standard->processPayment(Object(Aimeos\MShop\Order\Item\Base\Standard), Object(Aimeos\MShop\Order\Item\Standard))
#2 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Base.php(177): Aimeos\Client\Html\Checkout\Standard\Process\Standard->init()
#3 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Checkout/Standard/Standard.php(343): Aimeos\Client\Html\Base->init()
#4 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/ai-client-html/client/html/src/Client/Html/Common/Decorator/Base.php(166): Aimeos\Client\Html\Checkout\Standard\Standard->init()
#5 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Base/Shop.php(70): Aimeos\Client\Html\Common\Decorator\Base->init()
#6 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Aimeos\Shop\Base\Shop->get('checkout/standa...')
#7 /Users/cyber/Sites/eshop/newshop/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Controller/CheckoutController.php(53): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#8 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Aimeos\Shop\Controller\CheckoutController->indexAction('process')
#9 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('indexAction', Array)
#10 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Aimeos\Shop\Controller\CheckoutController), 'indexAction')
#11 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#12 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Route->run()
#13 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\closure(Object(Illuminate\Http\Request))
#14 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#15 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#17 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#19 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#21 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#23 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#24 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#26 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#28 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#30 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#33 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\closure(Object(Illuminate\Http\Request))
#36 /Users/cyber/Sites/eshop/newshop/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#37 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#39 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#42 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#45 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#47 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/cyber/Sites/eshop/newshop/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#49 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#51 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\closure(Object(Illuminate\Http\Request))
#53 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /Users/cyber/Sites/eshop/newshop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 /Users/cyber/Sites/eshop/newshop/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 /Users/cyber/Sites/eshop/newshop/server.php(21): require_once('/Users/cyber/Si...')
#57 main

**Front-end**
 Payments **(A non-recoverable error occurred**) the same issue with every payments method

**Comment by aimeos** [comment]
Thanks for the hint, it's fixed now in ai-client-html:dev-master
