### ISSUE TITLE
Unable to call method "getView"

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#426]
**Environment**
1. Version (e.g. dev-master laravel 8 *.*)
2. Operating system (Linux, Mac, Windows)

**bug**
Aimeos\Admin\JQAdm\Base::__call
vendor/aimeos/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm/Base.php:56

 
**Additional context Stacktrace**
/aimeos/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm/Common/Decorator/Base.php:51

**Comment by aimeos** [comment]
Thanks, it should be fixed now in dev-master

**Comment by aimeos** [comment]
We are currently changing other parts too, so dev-master won't work at the moment until we are done

**Comment by Cyber-Devs** [comment]
still Error in getView

**Comment by aimeos** [comment]
Like said, the packages had not been in line during implementing the breaking changes.
Now, they are in line again.
