### ISSUE TITLE
different pricing for select type products logically not working correctly

### ISSUE THREAD

**Issue by parsester** [aimeos/aimeos-laravel#427]
**Environment**
1. Aimeos/Laravel 2021.10.3
2. CentOS 7
3. PHP v8.0.11
4. Laravel v8.70.2

**Describe the bug**
for a product with select type, when I set second price such a way that minimum quantity is 2, when I select 2 item of this product with different selection property, the second pricing does not work.
I don't set price for each property separately and just set price for Parent Select Type product, that mean customer select 2 different property of a same product and second pricing logically must work. 

I think for this situation must be a solution, what can I do?

**Comment by aimeos** [comment]
We can't reproduce the problem. This is how we test:

1.) Create a product with type "select"
2.) Create two prices with 30€ for one item and 20€ for two items in the price tab
3.) Create two variant products in the "Variants" tab with different variant attributes ("blue" and "black" in our case)
4.) Add the product to a category

If you select one of the variants in the frontend and add it to the basket with a quantity of "2", that the single price is 20€ and the total is 40€ like expected.

**Comment by parsester** [comment]
yes but I mean customer select two different Variants of "select" type product, so in your example when customer select a product with "blue" color and select another with "black" color, **in fact and logically customer buy 2 number of "select" product** and price may calculate with quantity of "2".
because in reality the product is the same product and just colors is different.

**Comment by aimeos** [comment]
Then, this are two different products and tier pricing doesn't apply here because it's only for one product.

You can create your own basket plugin which handles that situation:
https://aimeos.org/docs/latest/providers/basket-plugins/

**Comment by parsester** [comment]
ok, and how about Pricing rules (https://aimeos.org/docs/latest/providers/rules/) does this help me?
please give me your optimized code to put in my TirePricingPlugin or give code for non "select" type product to use it in plugin, I have no idea about it.

**Comment by aimeos** [comment]
The price rules won't help here because you can only use them to give a discount to all articles based on some criteria.

If only the selection product has prices, you could adapt this code to use the sum of all variant articles belonging to that selection product and pass it to `getLowestPrice()`:
https://github.com/aimeos/aimeos-core/blob/2020.10/lib/mshoplib/src/MShop/Plugin/Provider/Order/ProductPrice.php#L229-L250

**Comment by parsester** [comment]
thanks @aimeos

I create "SelectTypeTirePricingPlugin" by making changes to the file [aimeos ProductPrice Plugin](https://github.com/aimeos/aimeos-core/blob/2020.10/lib/mshoplib/src/MShop/Plugin/Provider/Order/ProductPrice.php).
- add "$prodQuantities" array after line 122
- add below lines after line 134: 
`if( isset($prodQuantities[$item->getProductId()]) ) $prodQuantities[$item->getProductId()] = $item->getQuantity() + $prodQuantities[$item->getProductId()];
                else $prodQuantities[$item->getProductId()] = $item->getQuantity();`
- make change to "getPrice()" method and add another new parameter "$qty" as quantity of product and pass this parameter to it at line 126 like below code:
`$price = $this->getPrice($orderProduct, $refPrices, $attributes, $pos, $prodQuantities[$orderProduct->getProductId()]);`
- on the "getPrice" method I use "$qty" instead of "$orderProduct->getQuantity()" just on line 254 and change it as below line:
`$price = clone $priceManager->getLowestPrice( $refPrices, $qty, $currency );`

I attach my "SelectTypeTirePricingPlugin" file to this comment for your review.


this changes work correctly when I add product to basket from frontend /shop components **but I** create a laravel livewire component and use it from another route for add order by admin users. at this livewire component I have addToBasket method with below lines:

    public function addToBasket($productCode, $qty, $type, $variant) {
        $context = app('aimeos.context')->get();
        $basketCtrl = \Aimeos\Controller\Frontend::create( $context, 'basket' );

        $productManager = \Aimeos\MShop::create( $context, 'product');
        $productSearch = $productManager->filter();
        $expr = array(
            $productSearch->compare( '==', 'product.code', $productCode ),
        );
        $productSearch->setConditions( $productSearch->combine( '&&', $expr ) );
        $productItem = $productManager->search( $productSearch, ['product', 'price', 'text', 'attribute'] )->first();
        if ($type == 'select') {
            $basketCtrl->addProduct($productItem, $qty, $variant);
        } else {
            $basketCtrl->addProduct($productItem, $qty);
        }
        $this->position = $this->position + 1;
        $this->emit('basketUpdate');
    }

but when I add a product on the above method, my "SelectTypeTirePricingPlugin" don't work and not called?
why now work here and how can use "SelectTypeTirePricingPlugin" in the livewire component or other laravel controllers?

**Comment by aimeos** [comment]
> 1. Is what I did right?

In principle, yes.

> 2. because this plugin is exactly copy of ProductPrice plugin, Will this plugin slow down the process of adding the product to the cart?

No, but you only need to activate your plugin and disable the original ProductPrice plugin.

> 4. Do you have any plans to consider requests similar to my request in the next update?

If you create a PR with your changes, we will see if we can merge it for 2022.x

> 5. because this plugin is exactly copy of ProductPrice plugin, Can I disable your plugin and enable this plugin?

Yes, and you have to.
