### ISSUE TITLE
TypeError--Aimeos\MShop\Catalog\Item\Standard::getListItem(): Argument #3 ($refId) must be of type string, null given, called in

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#429]
**Environment**
1. Version (e.g. dev-master laravel 8.*)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**
xxx/xxx/vendor/aimeos/ai-admin-jqadm/admin/jqadm/src/Admin/JQAdm/Catalog/Text/Standard.php on line 305.

**Comment by aimeos** [comment]
Thanks for the hint, admin code has been updated to the stricter checking in the core
