### ISSUE TITLE
FatalErrorException in Base.php line 251

### ISSUE THREAD

**Issue by tiramisujin** [aimeos/aimeos-laravel#43]
I am using Laravel 5.2 with PHP 5.6.16, wamp server.
Everything works fine until I tried to add an item into basket.
![error](https://cloud.githubusercontent.com/assets/4206804/15599910/49896818-2419-11e6-91eb-51a12d56cc66.jpg)
Anyone has the same problem as I do? And how to solve this?

**Comment by aimeos** [comment]
You are using PHP 7, which is buggy until 7.0.4. Please update.

**Comment by tiramisujin** [comment]
It works now. Thank you! :+1:
