### ISSUE TITLE
Locale item for site "default" not found after disabling default currency

### ISSUE THREAD

**Issue by drkNsubuga** [aimeos/aimeos-laravel#430]
**Environment**
1. Aimeos-laravel 2021.10.*
2. PHP 8.0.12

**Describe the bug**
An error occurs after disabling the default currency in the admin panel > locales.  
***The error:*** Locale item for site "default" not found*

**Expected behavior**
An alert should show in case the default currency is to be disabled.

**Comment by aimeos** [comment]
Thanks for your report.
This should not happen even if the locales, languages or currencies are deleted. It's fixed in 2021.10.x-dev and will be part of the next minor release.
