### ISSUE TITLE
Contact us Page not working

### ISSUE THREAD

**Issue by swhhhub** [aimeos/aimeos-laravel#433]
**Created a 'contact us' page  using Admin CMS for this**

![Screenshot 2021-11-30 180013](https://user-images.githubusercontent.com/94544395/144047752-cddc5941-a6d0-4b72-b50f-bea936b11149.png)

**when submitting this contact us form in frontend an error is occurring**

![Screenshot 2021-11-30 180051](https://user-images.githubusercontent.com/94544395/144049762-8f9aba7c-73f2-40ad-baf6-8e3adb85a035.png)

**Comment by aimeos** [comment]
Can you please change this https://github.com/aimeos/aimeos/blob/master/routes/web.php#L30-L31 to:
```
Route::match(['GET', 'POST'], '{path?}', '\Aimeos\Shop\Controller\PageController@indexAction')
    ->name('aimeos_page')->where( 'path', '.*' );
```

**Comment by swhhhub** [comment]
it works, Thanks!!

**Comment by swhhhub** [comment]
mail is also not working. page is getting expired now . after submitting the form.
![Screenshot 2021-11-30 205621](https://user-images.githubusercontent.com/94544395/144076222-9a54b800-8985-4e36-9c27-eb7e9a9e65aa.png)

**Comment by aimeos** [comment]
You must not be logged into the admin backend when using the contact form.
Otherwise, the CSRF token is not added due to potential security risks.
