### ISSUE TITLE
Not able to send mail in Html template from contact us page

### ISSUE THREAD

**Issue by swhhhub** [aimeos/aimeos-laravel#435]
I am trying to send firstname, lastname, phone number etc along with the text message from contact us (added from cms ) page, but its not working.
$context->mail()->createMessage()
				->addTo( $toAddr, $toName )
				->addFrom( $email, $name )
				->setSubject( $i18n->dt( 'client', $subject ) . ' - HipHipHub AG' )
				->setBody( $msg )
				->send();
What I should use in palace of  setBody( $msg ) to send a msg in  html format?
or there is some other way to merge my form fields value with  $msg ?

**Comment by aimeos** [comment]
`setBodyHtml()` adds the content for HTML e-mails:
https://github.com/aimeos/aimeos-core/blob/2021.10/lib/mwlib/src/MW/Mail/Message/Iface.php#L109-L115

Please ask for further help in the Aimeos forum because the Github issues are only for bugs and improvements:
https://aimeos.org/help
