### ISSUE TITLE
Language dropdown of demo page is not dark-mode compatible

### ISSUE THREAD

**Issue by MartinP7r** [aimeos/aimeos-laravel#436]
Sorry I'm keeping this short as I stumbled onto it on the demo page and therefore it should be easily reproducible.

**Describe the bug**
E.g. have a look at this page
https://admin.demo.aimeos.org/admin/nope/jqadm/get/product/6958?locale=en#text

<img width="569" alt="Screen Shot 2021-12-15 at 6 48 13" src="https://user-images.githubusercontent.com/2669027/146130758-6094ef31-2e6a-4f6c-8eb5-7f9eef5a01c5.png">

the text is the same color as the background unless hovered.

Cheers,
Martin

**Comment by aimeos** [comment]
Thanks for the hint, the problem has been fixed now
