### ISSUE TITLE
Error Call to undefined method

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#437]
**Environment**
1. Version (Aimeos-dev Laravel.*)
2. Operating system (Linux, Mac)

Call to undefined method Aimeos\MShop\Context\Item\Standard::getLocale() (View: /xx/xx/vendor/aimeos/aimeos-laravel/src/views/base.blade.php)

 **line 14**
_**<link rel="icon" href="{{ asset( 'aimeos/' . ( app( 'aimeos.context' )->get()->getLocale()->getSiteItem()->getIcon() ?: '../vendor/shop/themes/default/media/aimeos-icon.png' ) ) }}"/>**_

**Comment by aimeos** [comment]
Thanks, code has been adapted to core changes
