### ISSUE TITLE
aimeos don't send email  

### ISSUE THREAD

**Issue by Dhaoui0Chaher** [aimeos/aimeos-laravel#438]
When i execute cronjobs in terminal, i don't receive any email, and i don't find any errors in the log table.

cronjobs command :
`php artisan aimeos:jobs "order/export/csv order/email/delivery order/email/payment order/email/voucher order/service/delivery subscription/export/csv customer/email/account"`

mshop_order_status 
![aimeos](https://user-images.githubusercontent.com/57814417/148291416-3e7821ea-abde-4a5f-a4dc-99d8ee676f39.png)

my .env  code
`MAIL_DRIVER=smtp`
`MAIL_HOST=smtp.mail.*****.com.tn` 
`MAIL_PORT=465`
`MAIL_USERNAME=***@*****.com.tn`
`MAIL_PASSWORD=************`
`MAIL_ENCRYPTION=ssl`

config/mail.php code 
`'mailers' => [
        '....
smtp' => [
            'transport' => 'smtp',
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'ssl'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
            'auth_mode' => null,
        ],
...`

config/shop.php code
....
'client' => [
		'html' => [
			'basket' => [
				'cache' => [
					// 'enable' => false, // Disable basket content caching for development
				],
			],
			'common' => [
				'template' => [
					 'baseurl' => 'packages/aimeos/shop/themes/elegance',
				],
			],
			'email' =>[
				'from-email' => '***@*****.com.tn',
            			'from-name' => 'My name',
			],
			'catalog' => [
				'selection' => [
					'type' => [
						'color' => 'radio',
						'length' => 'radio',
						'width' => 'radio',
					],
				],
			],
		],
	],
....

my cronjobs are added to my Cpanel cronjobs correctly.

what you propose as a solution ?

**Comment by aimeos** [comment]
Does it work if you execute the artisan command manually at the command line?

**Comment by Dhaoui0Chaher** [comment]
No, it not work.
I mean it's the same as I describe

**Comment by aimeos** [comment]
According to your screenshot, the e-mails has been sent. Otherwise, there would be no records in the `mshop_order_status` table.

**Comment by Dhaoui0Chaher** [comment]
so how i can find the problem or fix it ? 
is there any missing step in the mail configuration ?

**Comment by Dhaoui0Chaher** [comment]
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mail.**********.com.tn
MAIL_PORT=465
MAIL_USERNAME=****@********.com.tn
MAIL_PASSWORD=**************
MAIL_ENCRYPTION=TLS

**Comment by Dhaoui0Chaher** [comment]
when i try Mailtrap, it shows this errors in the `madmin_log` table 

```
Error while trying to send payment e-mail for order ID "19" and status "5": Connection could not be established with host smtp.mailtrap.io :stream_socket_client(): unable to connect to tcp://smtp.mailtrap.io:2525 (Connection refused)
#0 [internal function]: Swift_Transport_StreamBuffer->{closure}(2, 'stream_socket_c...', '/home/...', 264, Array
```
`
#1 
home/.../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(264): stream_socket_client('tcp://smtp.mail...', 111, 'Connection refu...', 30, 4, Resource id #1182)
`
`#2 /home/radiosid/laboratoiresnerolina.com.tn/shop/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()`
....

**Comment by aimeos** [comment]
Connection to Mailtrap is not possible from your computer (`unable to connect to tcp://smtp.mailtrap.io:2525`) but connection paramters seem to be OK. Maybe there's a firewall in between blocking the connection to that port. You could try to use port 25 instead.
