### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#439]
**Environment**
Uncaught (in promise) TypeError: **AimeosBasketMini.**update is not a function
        **at Object.updateBasket (aimeos.js:591)
           at aimeos.js:858**

**Comment by aimeos** [comment]
We are currently splitting up the CSS/JS files in the HTML client.
Please stay tuned until we completed this task.

**Comment by Cyber-Devs** [comment]
thanks alot 👍
