### ISSUE TITLE
Aimeos - CMS Page - Home: Not rendering CMS page content

### ISSUE THREAD

**Issue by woodwardmatt** [aimeos/aimeos-laravel#443]
**Environment**
1. Version = 2020.10
2. Operating system = WSL, Windows -> Docker: Ubuntu

I have a working install of Aimeos-Laravel. I notice that the Homepage CMS content is not being rendered despite the route being in place for this (in routes/web.php)... 

`Route::get('/', '\Aimeos\Shop\Controller\CatalogController@homeAction')->name('aimeos_home');`

... and having a cms page with the url of "/" that is enabled.

The site loads / function correctly otherwise. Any advice?

**Comment by Cyber-Devs** [comment]
> **Environment**
> 
> 1. Version = 2020.10
> 
> 2. Operating system = WSL, Windows -> Docker: Ubuntu
> 
> 
> 
> I have a working install of Aimeos-Laravel. I notice that the Homepage CMS content is not being rendered despite the route being in place for this (in routes/web.php)... 
> 
> 
> 
> `Route::get('/', '\Aimeos\Shop\Controller\CatalogController@homeAction')->name('aimeos_home');`
> 
> 
> 
> ... and having a cms page with the url of "/" that is enabled.
> 
> 
> 
> The site loads / function correctly otherwise. Any advice?
> 
> 

you have to add “cms/page" component to config/shop.php on home-page....

**Comment by aimeos** [comment]
@Cyber-Devs Thanks for the solution!

We've updated the README of the extension accordingly:
https://github.com/aimeos/ai-cms-grapesjs#laravel

**Comment by woodwardmatt** [comment]
Perfect! That's sorted it! Thank you both for your efforts and support :)

**Comment by woodwardmatt** [comment]
Just a query in relation to this. I have two environments, in one I had to add in the above fix for the cms content to work and in the other it seemed to work anyway (the shop.config hasn't got the cms/page added). Is there a setting elsewhere that controls the cms page content showing too? 

Just trying to make sure I'm across how this is controlled.

**Comment by aimeos** [comment]
If you install the Aimeos distribution (`aimeos/aimeos`), then it's preconfigured.
