### ISSUE TITLE
Unknown database type point requested

### ISSUE THREAD

**Issue by VadimSaratov** [aimeos/aimeos-laravel#444]
I tried to install Aimeos in an already existing laravel application and followed the installation steps described in the documentation but when I run the command "php ./artisan aimeos:setup" I get the following error

![image](https://user-images.githubusercontent.com/29757275/152347093-34753456-8e19-424e-b577-53292bd7e366.png)

MySQL - 8.0.23
Laravel Framework 6.20.44
PHP 7.3.6
"aimeos/aimeos-laravel": "~2021.10"

**Comment by aimeos** [comment]
Your `users` table contains a column of type `point` and it seems Doctrine DBAL can't handle that :-/

**Comment by VadimSaratov** [comment]
@aimeos ok thanks, will fix it at the database level then
