### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by quantumwebco** [aimeos/aimeos-laravel#446]
Unable to install to Laravel 9 because aimeos-laravel requires ^6.20.12||^7.30.4||^8.40.0
Please add ^9.0

**Comment by aimeos** [comment]
Please be patient, we need to switch to symfony/mailer and Flysystem 3.0 APIs first for Laravel 9

**Comment by nicklegroe** [comment]
Hi what is the status for Laravel 9?

**Comment by aimeos** [comment]
The switch to Flysystem 3.x is done but Symfony mailer makes more problems than expected. Nevertheless, Laravel 9 will be fully supported by the Aimeos 2022.04 release next month.

**Comment by aimeos** [comment]
You can now install Aimeos dev-master with Laravel 9 :-)
