### ISSUE TITLE
Class "Aimeos\MW\Mail\Swift" not found

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#449]
**Environment**
1. Version (e.g. dev-master)
2. Operating system (Linux, Mac.)

**Describe the bug**
protected function addMailer( \Aimeos\MShop\Context\Item\Iface $context ) : \Aimeos\MShop\Context\Item\Iface
      180▕        {
  **➜ 181▕                $mail = new \Aimeos\MW\Mail\Swift( function() { return app( 'mailer' )->getSwiftMailer(); } );**
      182▕ 
      183▕                return $context->setMail( $mail );
      184▕        }

**Comment by aimeos** [comment]
Fixed. We are currently reworking the core adapter classes and it's likely that this will happen again in the next 1-2 weeks.
