### ISSUE TITLE
View [app] not found

### ISSUE THREAD

**Issue by warmjaijai** [aimeos/aimeos-laravel#45]
Dear developers,

I have been following the steps to install aimeos till the point where i direct to http://127.0.0.1:8000/index.php/list
but the following error appears:

ErrorException in FileViewFinder.php line 137:
View [app] not found. (View: C:\xampp\htdocs\laravel\resources\views\vendor\shop\base.blade.php) (View: C:\xampp\htdocs\laravel\resources\views\vendor\shop\base.blade.php)

please help thanks!

**Comment by aimeos** [comment]
You've missed to create the app.blade.php template in the right location (`resources/views/app.blade.php`). See https://github.com/aimeos/aimeos-laravel#setup for more information.

**Comment by warmjaijai** [comment]
Thanks it was solved like a magic, however..... the 2nd problem encountered straightaway when i trying to set up admin acc..

c:\xampp\htdocs\laravel>php artisan aimeos:account <email> --admin
The system cannot find the file specified.

**Comment by aimeos** [comment]
Which file? The Laravel `artisan` command or the `php` interpreter? In both cases you need to see where these files in your installation are and adapt the command accordingly. In doubt, please ask in one of the Laravel forums how to get Laravel running when using a Windows environment.

You also have to use a e-mail address in that command like:
`php artisan aimeos:account --admin you@example.com`

**Comment by fatemesharafi** [comment]
hi guys
in CatalogController we have foreach like this:
foreach( app( 'config' )->get( 'shop.page.catalog-home' ) as $name )
		{....
but in app( 'config' )->get( 'shop.page.catalog-home' ) i haven't catalog-home
how can i fix it?
please help me :(
