### ISSUE TITLE
Multi-Shop - Custom Domains - Default Site Code

### ISSUE THREAD

**Issue by woodwardmatt** [aimeos/aimeos-laravel#450]
**Environment**
1. Version (e.g. 2021.10.4)
2. Operating system (Ubuntu 20:04)

I've successfully setup 3/4 new sites with custom domains, but I'm still running into some strange routing issue with regards to the default site code. 

It seems that in order for the for the front (customer facing) end of the application to be happy, the default site code needs to match the custom domain used. But then for the admin (business facing) end of the application to render is wants the default site code to be "default"

Can anyone shed light on this for me?

I've also tried setting the "mshop" > "locale" > "site" value to match the default custom domain, but this doesn't seem to have any effect.

**Comment by aimeos** [comment]
The admin backend redirects to the "default" site if no site from another source is available:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/AdminController.php#L49

For the frontend, you can already configure a different default site:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/Locale.php#L57

Does it work if you add this here: https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/AdminController.php#L49
```
config( 'shop.mshop.locale.site', 'default' )
```

**Comment by woodwardmatt** [comment]
So to confirm, do you mean instead of...

`$siteCode = ( $siteId ? $siteManager->get( $siteId )->getCode() : 'default' );`

at https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Controller/AdminController.php#L49 to try...

`$siteCode = ( $siteId ? $siteManager->get( $siteId )->getCode() : config( 'shop.mshop.locale.site', 'default' ) );`

..instead?

**Comment by woodwardmatt** [comment]
I've tried that (whilst the site code was set to the domain in both the config/shop.php (under mshop/locale/site) and the database - and therefore was seeing issues trying to access the admin area) - I also cleared view / route & aimeos caches, but the change above didn't resolve the issue.

I still see the error: "No item found for conditions: Array ( [locale.site.code] => default )" when trying to reach the admin area & login.

**Comment by woodwardmatt** [comment]
I also tried hard-coding the site code at that location, but this also gave the same response. It's made me wonder if it's not the AdminController that needs changing here and maybe the LoginController?

**Comment by aimeos** [comment]
It works pretty well with the additional code and this configuration in the ./config/shop.php:
```
	'mshop' => [
		'locale' => [
			'site' => '<custom site code>'
		]
	],
```

**Comment by woodwardmatt** [comment]
Was the code change I proposed above correct then?

`$siteCode = ( $siteId ? $siteManager->get( $siteId )->getCode() : config( 'shop.mshop.locale.site', 'default' ) );`

**Comment by aimeos** [comment]
Yes. The code is now also part of the aimeos/aimeos-laravel package and you can install it using:
```
composer req aimeos/aimeos-laravel:2021.10.x-dev
```

**Comment by woodwardmatt** [comment]
Hmm... so I've updated the Laravel version to include that latest version of the code. I've checked this has updated successfully in the vendor directory (which it has). I've cleared cached routes / views / aimeos, then checked the shop.config has the default site code (as a custom domain), then retried - still seeing the same error message:

> Aimeos\MShop\Exception
> No item found for conditions: Array ( [locale.site.code] => default )
> https://my.custom.domain/login?en=

I've also tried this in a different environment. In that environment I don't see the routing error, but I do see that the theme always seems to revert to the default site's theme on the login page (even if accessed through a secondary custom domain).

Any other thoughts / advice?

**Comment by aimeos** [comment]
Your configuration doesn't seem to match with your code in the locale site item because if you have this in your config/shop.php:
```php
	'mshop' => [
		'locale' => [
			'site' => 'default'
		]
	],
```
then, you also need `default` as code in the locale site item. Change both to the same value to work.

**Comment by aimeos** [comment]
Finally, we've found the problem. Some URLs for redirects used `default` as standard site code without checking if there's another one configured. Please execute this to get the latest version:
```
composer req aimeos/aimeos-laravel:2021.10.x.dev
```

**Comment by woodwardmatt** [comment]
That sounds promising! I've updated with composer, cleared caches and retried but no change :(

The current theme I have runs from a /packages directory in the root of the repo (as a local package) - do I need to copy anything to / from this to ensure this change operates as expected?

**Comment by aimeos** [comment]
No, the changes are not related to the templates. This are the applied changes: https://github.com/aimeos/aimeos-laravel/commit/fd24b09dfef8060e5b4f4efc2f5763ad6cfe1e22

**Comment by woodwardmatt** [comment]
Just revisited this today to sanity check I'd updated properly. I've run `composer update` again and ensured that everything is updated and that caches are cleared. But I'm still seeing the below issue when I try to go to the admin area at `<domain>/admin`

![image](https://user-images.githubusercontent.com/461398/159400856-3fbfc0bd-e769-49c7-a760-b65d646ae307.png)

**Comment by aimeos** [comment]
Can you share that exception on Flare ("Share" button right in the menu above the stack trace)?

**Comment by woodwardmatt** [comment]
Sure - here it is...

https://flareapp.io/share/dmkv8wp5#F57

I will need to remove this once you've had a look - can you let me know when you're happy for me to remove this?

**Comment by aimeos** [comment]
Is there a GET variable `?site=default` in your URL for the login page?
The stack trace suggests so: https://flareapp.io/share/dmkv8wp5#F50L57

**Comment by woodwardmatt** [comment]
Nope just the `?en` like in the screen shot

**Comment by woodwardmatt** [comment]
I'm just going to remove the shared trace before I lose reference to be able to. Hope that's ok. I can always re-run / share it if needed.

Also just double checked the config, routes (and searched the source code) and cant see any reference to ?site=default in there either.

**Comment by aimeos** [comment]
In that case, either `config( 'shop.mshop.locale.site', 'default' )` returns `default` because `mshop/locale/site` is not configured in `config/shop.php` or the route contains a `{site}` placeholder

**Comment by woodwardmatt** [comment]
I'll just double check those now two secs

**Comment by woodwardmatt** [comment]
The custom domain (blurred out) is in the `shop.php` config file:

![image](https://user-images.githubusercontent.com/461398/159462034-4cd91166-661f-42ef-b8c4-c1afc4bb4fa3.png)

The `web.php` routes does have a {site} placeholder as per the docs for multi-shop home page setup - is that causing the issue with the admin / login route?

![image](https://user-images.githubusercontent.com/461398/159462386-6997462b-db12-429c-854c-d17b953f36fc.png)

**Comment by aimeos** [comment]
Can you please debug here what the value of `$site` is and where it is set?
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/Locale.php#L57-L63

Also note that changes in `config/shop.php` are not used if Laravel caches the configuration. You can clear the cache with:
```
php artisan config:clear
```

**Comment by woodwardmatt** [comment]
Ok, so....

I've dumped the `$site` variable at - https://github.com/aimeos/aimeos-laravel/blob/5f743125f03da3fcb197f88548b23bf14c711b61/src/Aimeos/Shop/Base/Locale.php#L60 - and the result was `"default"`

I've also dumped the `$site` variable at - https://github.com/aimeos/aimeos-laravel/blob/5f743125f03da3fcb197f88548b23bf14c711b61/src/Aimeos/Shop/Base/Locale.php#L65 - and also gotten `"default"`

So it looks like its getting set last within the condition statement of: 

`if( Route::current() )`

**Note**: I also cleared cache before testing these two locations - the same behavior was observed.

**Comment by aimeos** [comment]
> I've dumped the `$site` variable at -
> 
> https://github.com/aimeos/aimeos-laravel/blob/5f743125f03da3fcb197f88548b23bf14c711b61/src/Aimeos/Shop/Base/Locale.php#L57
> 
> - and the result was `"default"`

The problem is already here because if "default" is returned there, the mshop/locale/site configuration in `config/shop.php` is not set correctly (wrong location, overwritten later, etc.) or not used due to Laravels configuration cache.

**Comment by woodwardmatt** [comment]
So, on those two thoughts, I'll check in the morning and share further info, but to my knowledge, the configuration is as above with the custom domain in the shop.php file and I've also tried clearing the caches. Neither of these seem to have resolved the issue.

I know that on the same server I am working from there is another instance of Aimeos, under a different URL and domain in Apache (and separate database). Could it get possible configuration is somehow being confused between the two??

Otherwise I'm a little lost on what's not setup correctly 🤷

**Comment by woodwardmatt** [comment]
Just to confirm the site is set to the main custom domain ....

![image](https://user-images.githubusercontent.com/461398/159804449-1107f872-abbd-4c89-8247-1c64dd9e85bd.png)

I've also run the clear config cache command: `php artisan config:clear` then tried to access to site's admin again but still getting the error `No item found for conditions: Array ( [locale.site.code] => default )`

**Comment by aimeos** [comment]
You need to find out why this line returns "default" instead of your configured domain:
https://github.com/aimeos/aimeos-laravel/blob/5f743125f03da3fcb197f88548b23bf14c711b61/src/Aimeos/Shop/Base/Locale.php#L57

Maybe you've overwritten the `mshop` key in the `config/shop.php` twice?
