### ISSUE TITLE
All type of image upload 403(Forbidden)

### ISSUE THREAD

**Issue by Md-Asaduzzaman-Muhid** [aimeos/aimeos-laravel#451]
I have checked storage and public folder permission and set 777
.env is fine(
APP_URL=perfect url
DB_HOST=192.168.*.*
DB_PORT=3306
DB_DATABASE=dbname
DB_USERNAME=user
DB_PASSWORD="password"
) 
I can save text in both CMS and product but i can't upload image as always showing 403 forbidden.
In my network i got (
Request URL: https://www.site.com/admin/default/jqadm/save/cms?id=2&locale=en
Request Method: POST
Status Code: 403 Forbidden
Remote Address: 103.125.254.**:443
Referrer Policy: strict-origin-when-cross-origin
)
can you please solve it i am using latest aimeos.
It works fine at my local PC but when i am hosting it on shared server it shows error.

**Comment by aimeos** [comment]
This is not a common problem and seems to be related to your installation.
Does uploading images in product panel work?

**Comment by Md-Asaduzzaman-Muhid** [comment]
yes all images previously in are present , and showing /working perfectly but i can't upload image and save. though i can access db by editing only texts, if there any images found in product or cms it redirects a pages having only header and footer only console get 403 error.

**Comment by Md-Asaduzzaman-Muhid** [comment]
https://user-images.githubusercontent.com/52190964/158373322-62a0e2da-fd92-4b6b-9880-24a519154579.mp4

please see

**Comment by Md-Asaduzzaman-Muhid** [comment]
https://user-images.githubusercontent.com/52190964/158374718-e9faa4ec-6d55-4d93-b027-a160a4857a3c.mp4

**Comment by aimeos** [comment]
After clicking on "Save", your web server seems to respond with the content of `https://yourdomain.com/` instead of the result of the admin backend even if the URL is the one of the admin backend. You should check your web server configuration.

**Comment by Md-Asaduzzaman-Muhid** [comment]
can you please suggest any specific configuration ?
