### ISSUE TITLE
Disable delivery

### ISSUE THREAD

**Issue by MicheleMorescreens** [aimeos/aimeos-laravel#452]
**Is your feature request related to a problem?**
I would like to use the ecommerce to sell software/license and in this case the delivery is not needed

**Describe the solution you'd like**
remove the delivery from the checkout

**Describe alternatives you've considered**
maybe put a 0 shipping but it's not an elegant solution

**Comment by aimeos** [comment]
Please ask question in our forum at https://aimeos.org/help

The solution is to change the configuration of the ServicesAvailable basket plugin:
https://aimeos.org/docs/latest/manual/plugins/#servicesavailable
