### ISSUE TITLE
hey there1

### ISSUE THREAD

**Issue by Safina-Nyirasafari** [aimeos/aimeos-laravel#453]
**Environment**
1. Version (e.g. 2020.10)
2. Operating system (Linux, Mac, Windows)

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and con
 description of what you expected to happen.

**Screenshots**

**Additional context**
![Screenshot 2022-04-04 033349](https://user-images.githubusercontent.com/93988054/161527378-9c6e69ba-9939-4591-8db5-3b54bdc067a7.jpg)

**Comment by aimeos** [comment]
Download composer first, see: https://github.com/aimeos/aimeos-laravel#full-shop-application
