### ISSUE TITLE
error Root composer.json requires aimeos/aimeos-laravel ~2022.04 while installing Aimeos package to a laravel project

### ISSUE THREAD

**Issue by ibrahim-h-najjar** [aimeos/aimeos-laravel#454]
**Environment**
1. Xampp with PHP Version (7.3|^8.0)
2. Operating system (Windows)

**Describe the bug**
I'm trying to install aimeos package to my already existing laravel project -the default laravel project that can be installed- , I used steps from that link: 
https://github.com/aimeos/aimeos-laravel#installation

**To Reproduce**
1. install and launch a Laravel project using this command
$ composer create-project laravel/laravel:^8.0 laravel-to-test-project

2. Edit composer.json to be like this:
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.75",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "aimeos/aimeos-laravel": "~2022.04"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^5.10",
        "phpunit/phpunit": "^9.5.10"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan migrate",
            "@php artisan vendor:publish --tag=public --force",
            "\\Aimeos\\Shop\\Composer::join"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```
3. run composer update

4. See the error

5. Tried to run: 
composer update --ignore-platform-reqs 
composer update --ignore-platform-reqs
composer update --with-all-dependencies

6. See the error again
**Expected behavior**
The packages to be installed

**Comment by aimeos** [comment]
For Laravel 8 and earlier, you need Aimeos version 2021.10.
2022.04 is only compatible to Laravel 9 due to breaking changes in Laravel 9.

**Comment by ibrahim-h-najjar** [comment]
Edited Line 14 in composer.json to be         "aimeos/aimeos-laravel": "~2021.10"

Worked! Thanks!

**Comment by ibrahim-h-najjar** [comment]
Ok now in the next step, after running 
 I have this errors, after running : 
`composer require laravel/ui:^2.0
php artisan ui vue --auth
npm install && npm run dev `
I faced these errors:


  Problem 1
    - aimeos/aimeos-core 2021.10.16 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - aimeos/aimeos-laravel 2021.10.5 requires aimeos/aimeos-core 2021.10.* -> satisfiable by aimeos/aimeos-core[2021.10.16].
    - aimeos/aimeos-laravel is locked to version 2021.10.5 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd` to temporarily ignore these required extensions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.



$ php artisan ui vue --auth
  Command "ui" is not defined.

**Comment by aimeos** [comment]
PHP GD extension is missing in your installation like reported by composer.
