### ISSUE TITLE
Error when installing aimeos package 2021.10 to an existed Laravel project

### ISSUE THREAD

**Issue by ibrahim-h-najjar** [aimeos/aimeos-laravel#455]
**Environment**
1. Version (PHP 8.0.17 , Laravel 8.83.9 , Aimeos 2021.10)
2. Operating system ( Windows)

**Describe the bug**
Trying to install aimeos package into my project, having this error s:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires aimeos/aimeos-laravel ~2021.10 -> satisfiable by aimeos/aimeos-laravel[2021.10.1, ..., 2021.10.x-dev].
    - aimeos/aimeos-laravel[2021.10.1, ..., 2021.10.x-dev] require doctrine/dbal ~2.5 -> found doctrine/dbal[v2.5.0-BETA2,..., 2.13.8] but it conflicts with your root composer.json require (^3.1).
  Problem 2
    - spatie/laravel-sitemap 5.8.0 requires php ^7.2 -> your php version (8.0.17) does not satisfy that requirement.
    - spatie/laravel-sitemap[5.9.0, ..., 5.9.2] require guzzlehttp/guzzle ^7.2 -> found guzzlehttp/guzzle[dev-master, 7.2.0, ..., 7.4.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (6.3.*).
    - Root composer.json requires spatie/laravel-sitemap ^5.8 -> satisfiable by spatie/laravel-sitemap[5.8.0, 5.9.0, 5.9.1,
 5.9.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**To Reproduce**
1. add these lines to the composer.json: 
`    "prefer-stable": true,
    "minimum-stability": "dev",
    "require": {
        "aimeos/aimeos-laravel": "~2022.04",
        ...
    },
    "scripts": {
        "post-update-cmd": [
            "@php artisan migrate",
            "@php artisan vendor:publish --tag=public --force",
            "\\Aimeos\\Shop\\Composer::join"
        ],
        ...
    }`

3.  Run composer update
4. Then try run  `composer install --ignore-platform-reqs
`

**Expected behavior**
package to be installed.

**Comment by aimeos** [comment]
```
- aimeos/aimeos-laravel[2021.10.1, ..., 2021.10.x-dev] require doctrine/dbal ~2.5 -> found doctrine/dbal[v2.5.0-BETA2,..., 2.13.8] but it conflicts with your root composer.json require (^3.1).
```
You have `doctrine/dbal:^3.1` in your composer.json but due to other constraints, `doctrine/dbal:~2.5` is required.

```
- spatie/laravel-sitemap 5.8.0 requires php ^7.2 -> your php version (8.0.17) does not satisfy that requirement.
- spatie/laravel-sitemap[5.9.0, ..., 5.9.2] require guzzlehttp/guzzle ^7.2 -> found guzzlehttp/guzzle[dev-master, 7.2.0, ..., 7.4.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (6.3.*).
```
This is related to the `spatie/laravel-sitemap` package you include in your composer.json
