### ISSUE TITLE
Mshop Frontend - Wrong site code

### ISSUE THREAD

**Issue by lioncobe** [aimeos/aimeos-laravel#459]
**Environment**
1. Version (e.g. 2022.04)
2. Operating system (Linux / Ubuntu 22.04)
3. Laravel 9.14.1
4. PHP 8.1.2

**Describe bug 1**
When activating SHOP_MULTISHOP and creating a new site (code: shop.myshop.be) with a new homepage the default homepage keeps showing.

When printing $site I get the CODE "default" on the homepage (shop.myshop.be) and the CODE "shop.myshop.be" on the shop.myshop.be/shop page. 

Also when looking at the sourcecode of the new site I notice it keeps referencing to the default URL (localhost) instead of the new site URL (shop.myshop.be).

**shop.php routes:**
if( config( 'app.shop_multishop' ) || config( 'app.shop_registration' ) ) {
	$routes = ['routes' => [
		'admin' => ['prefix' => 'admin', 'middleware' => ['web', 'verified']],
		'jqadm' => ['prefix' => 'admin/jqadm', 'middleware' => ['web', 'auth', 'verified']],
		'jsonadm' => ['prefix' => 'admin/jsonadm', 'middleware' => ['web', 'auth', 'verified']],
		'jsonapi' => ['domain' => '{site}', 'prefix' => 'jsonapi', 'middleware' => ['web', 'api']],
		'account' => ['domain' => '{site}', 'prefix' => $prefix . 'profile', 'middleware' => ['web', 'auth', 'verified']],
		'default' => ['domain' => '{site}', 'prefix' => $prefix . 'shop', 'middleware' => ['web']],
		'supplier' => ['domain' => '{site}', 'prefix' => $prefix . 's', 'middleware' => ['web']],
		'update' => ['domain' => '{site}'],
	] ];
}

**Expected behavior**
Display the correct homepage depending on the domain.

**Screenshots**

![screen-sites](https://user-images.githubusercontent.com/53877184/170720166-1d0c788e-1eff-43c5-b517-68da01b3e85f.png)

![screen-web](https://user-images.githubusercontent.com/53877184/170719709-4c5a9a70-b142-490f-acdf-788f35be1fea.png)

**Not OK => Should be shop.myshop.be**
![screen-homepage](https://user-images.githubusercontent.com/53877184/170719711-e6b390dc-763a-4137-83a6-1630251969a2.png)

**OK**
![screen-shop](https://user-images.githubusercontent.com/53877184/170719713-9cb80031-39c2-4838-a607-b01749dc7f2b.png)

![screen-shop-localhost-02](https://user-images.githubusercontent.com/53877184/170719718-2f069309-b1ee-49a0-bc36-7a900673c5a8.png)

**Wrong domain in the source code.**
Should be shop.myshop.be instead of localhost.

![screen-sourcecode-localhost](https://user-images.githubusercontent.com/53877184/170724324-e52cee81-2ed8-406a-acea-9067b4ca10cc.png)

**Comment by aimeos** [comment]
If you use another site code that should be the new default one, you must also set this option to your new site code:
https://github.com/aimeos/aimeos/blob/master/config/shop.php#L149

We've improved in dev-master the routing for multi-site setups. Maybe you want to try that version too:
```
composer create-project aimeos/aimeos:dev-master myshop
```

**Comment by lioncobe** [comment]
Thank you for the quick response!

I did a clean install with _aimeos:dev-master_ and it looks promising.

First thing I did before setting SHOP_MULTISHOP to "true" was go to _Admin > Locales > Sites_ and change the default code to localhost (my domain).

**After this I changed shop.php:**
```
if( config( 'app.shop_multishop' ) || config( 'app.shop_registration' ) ) {
	$routes = ['routes' => [
		'admin' => ['prefix' => $prefix . 'admin', 'middleware' => ['web', 'auth', 'verified']],
		'jqadm' => ['domain' => '{site}', 'prefix' => 'admin/jqadm', 'middleware' => ['web', 'auth', 'verified']],
		'jsonadm' => ['domain' => '{site}', 'prefix' => 'admin/jsonadm', 'middleware' => ['web', 'auth', 'verified']],
		'jsonapi' => ['domain' => '{site}', 'prefix' => 'jsonapi', 'middleware' => ['web', 'api']],
		'account' => ['domain' => '{site}', 'prefix' => $prefix . 'profile', 'middleware' => ['web', 'auth', 'verified']],
		'default' => ['domain' => '{site}', 'prefix' => $prefix . 'shop', 'middleware' => ['web']],
		'supplier' => ['domain' => '{site}', 'prefix' => $prefix . 's', 'middleware' => ['web']],
		'page' => ['domain' => '{site}', 'prefix' => $prefix . 'p', 'middleware' => ['web']],
		'home' => ['domain' => '{site}', 'prefix' => $prefix , 'middleware' => ['web']],
		'update' => ['domain' => '{site}'],
	] ];
}
```
...
```
'mshop' => [
		'locale' => [
			// 'site' => '<custom site code>', // used instead of "default"
			'site' => 'localhost'
		]
	],
```
...

**I updated the .env file:**
_SHOP_MULTISHOP=true_

**Installed a second site:**
`php artisan aimeos:setup shop.myshop.be`

**And cleared the caches:**
```
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan aimeos:clear
```

Now _http://localhost_ & _http://localhost/shop_ look perfect.

But when visiting the new shop (http://shop.myshop.be) it seems not to load the new site/domain correct.
I don't know how to solve this. I hope you can help me.

Looking at a part of the header I found this:
```
<link rel="stylesheet" href="<?= $enc->attr( $this->content( $this->get( 'contextSiteTheme', 'default' ) . '/locale-select.css', 'fs-theme', true ) ) ?>">
<script defer src="<?= $enc->attr( $this->content( $this->get( 'contextSiteTheme', 'default' ) . '/locale-select.js', 'fs-theme', true ) ) ?>"></script>
```

**Print-screens**
![screen-sites2](https://user-images.githubusercontent.com/53877184/170778366-caddc7d0-57f6-4d9a-b254-2ae372bb13ae.png)
![mshop-errors](https://user-images.githubusercontent.com/53877184/170778363-a28a2cb1-435c-4377-9e1f-1a99f7a5bc86.png)

Kind regards,
Jeroen

**Comment by Cyber-Devs** [comment]
update your .env file  e.g absolute => APP_URL=http://localhost:8000 not  APP_URL=http://127.0.0.1:8000
ASSET_URL=http://localhost:8000. and then use Aimeos:clear or optimise:clear then CSP will be allow the require files to load...

**Comment by lioncobe** [comment]
> update your .env file e.g absolute => APP_URL=http://localhost:8000 not APP_URL=http://127.0.0.1:8000 ASSET_URL=http://localhost:8000. and then use Aimeos:clear or optimise:clear then CSP will be allow the require files to load...

Thank you for the suggestion but this did not solve this issue.
This update caused http://localhost to stop working as expected. 
It also did not resolve the incorrect domain at http://shop.myshop.be/ (see my previous comment).

**:8000 error**
![localhost_8000](https://user-images.githubusercontent.com/53877184/170803407-cd5a96b6-0025-484b-a479-2217274cce8d.png)

![mshop-errors2](https://user-images.githubusercontent.com/53877184/170803243-6e44fb6c-8220-42db-90b3-d0c11a3dcd66.png)

**Comment by aimeos** [comment]
It will resolve correctly if you change APP_URL and ASSET_URL to  http://shop.myshop.be

**Comment by aimeos** [comment]
We've added a change to `aimeos/aimeos-laravel:dev-master` and `aimeos/aimeos-laravel:2022.04.x-dev` that sets the base URL to the current base URL if not `ASSET_URL` is explicitly configured. Thus, it will automatically work for different domains, esp. in multi-site setups.

**Comment by lioncobe** [comment]
Thank you very much!

Removing the main domain at ASSETS_URL solved the issue for me.

**.env**
```
...
APP_URL=http://localhost
ASSET_URL=
...
```
