### ISSUE TITLE
404 on all site pages

### ISSUE THREAD

**Issue by demeja1610** [aimeos/aimeos-laravel#469]
**Environment**
1. Version 2022.10
2. Operating system Windows

**Describe the bug**
All of pages returns 404, except shop pages

**To Reproduce**
1. Install laravel
2. Install aimeos following your readme file
3. install laravel breeze
4. Try to open /login
5. GET 404

**Expected behavior**
Get login page

**Additional context**
My guess this happened because of this commit https://github.com/aimeos/aimeos-laravel/commit/fa7ac7535b3fdec0736013147efab1f6badff451
If i return "/p" all pages load correctly

**Comment by aimeos** [comment]
Can you post the output of `php artisan route:list`?

**Comment by demeja1610** [comment]
> Can you post the output of `php artisan route:list`?

https://ibb.co/4t45Px1

**Comment by aimeos** [comment]
The interesting lines are missing and a text ouput would be better.

**Comment by demeja1610** [comment]
> The interesting lines are missing and a text ouput would be better.

  GET|HEAD  / ......................................................................................................... aimeos_home › Aimeos\Shop › CatalogController@homeAction
  GET|HEAD  _debugbar/assets/javascript ............................................................................ debugbar.assets.js › Barryvdh\Debugbar › AssetController@js  
  GET|HEAD  _debugbar/assets/stylesheets ......................................................................... debugbar.assets.css › Barryvdh\Debugbar › AssetController@css  
  DELETE    _debugbar/cache/{key}/{tags?} ................................................................... debugbar.cache.delete › Barryvdh\Debugbar › CacheController@delete  
  GET|HEAD  _debugbar/clockwork/{id} .................................................................. debugbar.clockwork › Barryvdh\Debugbar › OpenHandlerController@clockwork  
  GET|HEAD  _debugbar/open ............................................................................. debugbar.openhandler › Barryvdh\Debugbar › OpenHandlerController@handle  
  POST      _ignition/execute-solution ........................................................... ignition.executeSolution › Spatie\LaravelIgnition › ExecuteSolutionController  
  GET|HEAD  _ignition/health-check ....................................................................... ignition.healthCheck › Spatie\LaravelIgnition › HealthCheckController  
  POST      _ignition/update-config .................................................................... ignition.updateConfig › Spatie\LaravelIgnition › UpdateConfigController  
  GET|HEAD  admin ................................................................................................ aimeos_shop_admin › Aimeos\Shop › AdminController@indexAction  
  POST      admin/{site}/graphql ........................................................................ aimeos_shop_graphql_post › Aimeos\Shop › GraphqlController@indexAction  
  POST      admin/{site}/jqadm/batch/{resource} ............................................................ aimeos_shop_jqadm_batch › Aimeos\Shop › JqadmController@batchAction  
  GET|HEAD  admin/{site}/jqadm/copy/{resource}/{id} .......................................................... aimeos_shop_jqadm_copy › Aimeos\Shop › JqadmController@copyAction  
  GET|HEAD  admin/{site}/jqadm/create/{resource} ......................................................... aimeos_shop_jqadm_create › Aimeos\Shop › JqadmController@createAction  
  POST      admin/{site}/jqadm/delete/{resource}/{id?} ................................................... aimeos_shop_jqadm_delete › Aimeos\Shop › JqadmController@deleteAction  
  GET|POST|HEAD admin/{site}/jqadm/export/{resource} ..................................................... aimeos_shop_jqadm_export › Aimeos\Shop › JqadmController@exportAction  
  GET|HEAD  admin/{site}/jqadm/file/{type} ................................................................... aimeos_shop_jqadm_file › Aimeos\Shop › JqadmController@fileAction  
  GET|HEAD  admin/{site}/jqadm/get/{resource}/{id} ............................................................. aimeos_shop_jqadm_get › Aimeos\Shop › JqadmController@getAction  
  POST      admin/{site}/jqadm/save/{resource} ............................................................... aimeos_shop_jqadm_save › Aimeos\Shop › JqadmController@saveAction
  GET|POST|HEAD admin/{site}/jqadm/search/{resource} ..................................................... aimeos_shop_jqadm_search › Aimeos\Shop › JqadmController@searchAction  
  OPTIONS   admin/{site}/jsonadm/{resource?} ....................................................... aimeos_shop_jsonadm_options › Aimeos\Shop › JsonadmController@optionsAction  
  DELETE    admin/{site}/jsonadm/{resource}/{id?} .................................................... aimeos_shop_jsonadm_delete › Aimeos\Shop › JsonadmController@deleteAction  
  GET|HEAD  admin/{site}/jsonadm/{resource}/{id?} .......................................................... aimeos_shop_jsonadm_get › Aimeos\Shop › JsonadmController@getAction  
  PATCH     admin/{site}/jsonadm/{resource}/{id?} ...................................................... aimeos_shop_jsonadm_patch › Aimeos\Shop › JsonadmController@patchAction  
  POST      admin/{site}/jsonadm/{resource}/{id?} ........................................................ aimeos_shop_jsonadm_post › Aimeos\Shop › JsonadmController@postAction  
  PUT       admin/{site}/jsonadm/{resource}/{id?} .......................................................... aimeos_shop_jsonadm_put › Aimeos\Shop › JsonadmController@putAction  
  GET|HEAD  api/user ...........................................................................................................................................................  
  GET|HEAD  confirm-password ........................................................................................ password.confirm › Auth\ConfirmablePasswordController@show  
  POST      confirm-password .......................................................................................................... Auth\ConfirmablePasswordController@store  
  GET|HEAD  dashboard ................................................................................................................................................ dashboard  
  POST      email/verification-notification ............................................................. verification.send › Auth\EmailVerificationNotificationController@store  
  GET|HEAD  forgot-password ......................................................................................... password.request › Auth\PasswordResetLinkController@create  
  POST      forgot-password ............................................................................................ password.email › Auth\PasswordResetLinkController@store  
  GET|OPTIONS|HEAD jsonapi/{resource?} ............................................................. aimeos_shop_jsonapi_options › Aimeos\Shop › JsonapiController@optionsAction  
  DELETE    jsonapi/{resource} ....................................................................... aimeos_shop_jsonapi_delete › Aimeos\Shop › JsonapiController@deleteAction  
  GET|HEAD  jsonapi/{resource} ............................................................................. aimeos_shop_jsonapi_get › Aimeos\Shop › JsonapiController@getAction  
  PATCH     jsonapi/{resource} ......................................................................... aimeos_shop_jsonapi_patch › Aimeos\Shop › JsonapiController@patchAction  
  POST      jsonapi/{resource} ........................................................................... aimeos_shop_jsonapi_post › Aimeos\Shop › JsonapiController@postAction  
  PUT       jsonapi/{resource} ............................................................................. aimeos_shop_jsonapi_put › Aimeos\Shop › JsonapiController@putAction  
  GET|HEAD  login ........................................................................................................... login › Auth\AuthenticatedSessionController@create  
  POST      login .................................................................................................................... Auth\AuthenticatedSessionController@store  
  POST      logout ........................................................................................................ logout › Auth\AuthenticatedSessionController@destroy  
  GET|POST|HEAD profile ...................................................................................... aimeos_shop_account › Aimeos\Shop › AccountController@indexAction  
  GET|POST|HEAD profile/download/{dl_id} ......................................................... aimeos_shop_account_download › Aimeos\Shop › AccountController@downloadAction  
  GET|POST|HEAD profile/favorite/{fav_action?}/{fav_id?}/{d_name?}/{d_pos?} ......................... aimeos_shop_account_favorite › Aimeos\Shop › AccountController@indexAction
  GET|POST|HEAD profile/watch/{wat_action?}/{wat_id?}/{d_name?}/{d_pos?} ............................... aimeos_shop_account_watch › Aimeos\Shop › AccountController@indexAction  
  GET|HEAD  register ........................................................................................................... register › Auth\RegisteredUserController@create  
  POST      register ....................................................................................................................... Auth\RegisteredUserController@store  
  POST      reset-password .................................................................................................. password.update › Auth\NewPasswordController@store  
  GET|HEAD  reset-password/{token} .......................................................................................... password.reset › Auth\NewPasswordController@create  
  GET|HEAD  sanctum/csrf-cookie .............................................................................. sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show  
  GET|POST|HEAD shop ............................................................................................. aimeos_shop_list › Aimeos\Shop › CatalogController@listAction  
  GET|POST|HEAD shop/basket .................................................................................... aimeos_shop_basket › Aimeos\Shop › BasketController@indexAction  
  GET|POST|HEAD shop/checkout/{c_step?} .................................................................... aimeos_shop_checkout › Aimeos\Shop › CheckoutController@indexAction  
  GET|POST|HEAD shop/confirm/{code?} ...................................................................... aimeos_shop_confirm › Aimeos\Shop › CheckoutController@confirmAction  
  GET|POST|HEAD shop/count ..................................................................................... aimeos_shop_count › Aimeos\Shop › CatalogController@countAction  
  GET|POST|HEAD shop/pin ............................................................................ aimeos_shop_session_pinned › Aimeos\Shop › CatalogController@sessionAction  
  GET|POST|HEAD shop/stock ..................................................................................... aimeos_shop_stock › Aimeos\Shop › CatalogController@stockAction  
  GET|POST|HEAD shop/suggest ............................................................................... aimeos_shop_suggest › Aimeos\Shop › CatalogController@suggestAction  
  GET|POST|HEAD shop/{d_name}/{d_pos?}/{d_prodid?} ........................................................... aimeos_shop_detail › Aimeos\Shop › CatalogController@detailAction  
  GET|POST|HEAD shop/{f_name}~{f_catid}/{l_page?} ................................................................ aimeos_shop_tree › Aimeos\Shop › CatalogController@treeAction  
  GET|POST|HEAD supplier/{s_name}/{f_supid} ............................................................... aimeos_shop_supplier › Aimeos\Shop › SupplierController@detailAction  
  GET|HEAD  test-lalala ........................................................................................................................................................  
  GET|POST|HEAD update ...................................................................................... aimeos_shop_update › Aimeos\Shop › CheckoutController@updateAction  
  GET|HEAD  verify-email ................................................................................. verification.notice › Auth\EmailVerificationPromptController@__invoke
  GET|HEAD  verify-email/{id}/{hash} ................................................................................. verification.verify › Auth\VerifyEmailController@__invoke  
  GET|POST|HEAD {path?} ................................................................................................. aimeos_page › Aimeos\Shop › PageController@indexAction

**Comment by aimeos** [comment]
Yes, the `/p` prefix is missing because it has been moved to the `config/shop.php`. Please add it here in your copy:
https://github.com/aimeos/aimeos/blob/master/config/shop.php#L40

**Comment by demeja1610** [comment]
> Yes, the `/p` prefix is missing because it has been moved to the `config/shop.php`. Please add it here in your copy: https://github.com/aimeos/aimeos/blob/master/config/shop.php#L40

Yes, all works, thanks a lot
