### ISSUE TITLE
Postgres sql installation, command fails  `php artisan aimeos:setup --option=setup/default/demo:1`

### ISSUE THREAD

**Issue by Jossnaz** [aimeos/aimeos-laravel#47]
i follow ur installation guide:
i have laravel 5.1
i use postgres

this is my env file:

```

APP_ENV=local
APP_DEBUG=true
APP_KEY=BiX2k39vbtTW4sio0ffeAAiuPeNy1t7h

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_DATABASE=fixturefix
DB_USERNAME=postgres
DB_PASSWORD=postgres123

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

```

I perform:

`php artisan aimeos:setup --option=setup/default/demo:1`

i get:

`[Aimeos\MW\DB\Exception]                                                   
  SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)  `

now if u only support mysql thats fine, but please, tell me, is it because you only support mysql? does nothing of the demo work for postgresql?

**Comment by Jossnaz** [comment]
now if u only support mysql thats fine, but please, tell me, is it because you only support mysql? does nothing of the demo work for postgresql?

**Comment by aimeos** [comment]
PostgreSQL is supported in the latest dev-master version. A new official release will be created next month but meanwhile you have to use `"aimeos/aimeos-laravel": "dev-master"` in your composer.json file.

Additionally, you have to change the `config/shop.php` file and use `pgsql` for the `resource/db/adapter` configuration

**Comment by AdebisiJoe** [comment]
i have installed this package but i want to use xampp server with aimeos routes instead of the internal php server how can i do that

**Comment by Jossnaz** [comment]
@AdebisiJoe i would not use postgresql until it is really released... just stick with mysql.

Generally on how to? a test.php with echo "hello world" works on your xampp installation? generally... just drop the laravel folder into the htdocs directory. YOu are on windows, right?
