### ISSUE TITLE
Route problem in multisite

### ISSUE THREAD

**Issue by mukulviru** [aimeos/aimeos-laravel#471]
**Environment**
1. Version ( 2022.10.3)
2. Operating system (Windows)

Missing required parameter for [Route: verification.verify] [URI: {site}/verify-email/{id}/{hash}] [Missing parameter: site].

![3](https://user-images.githubusercontent.com/26219005/197138974-809f66cc-8867-416f-a503-eb1a04d8b3a9.PNG)

**Comment by aimeos** [comment]
See https://aimeos.org/help/viewtopic.php?f=18&t=4844&p=18903#p18903

**Comment by mukulviru** [comment]
> See https://aimeos.org/help/viewtopic.php?f=18&t=4844&p=18903#p18903

sorry , i couldn't understand from this topic because there is no explanation in detail
