### ISSUE TITLE
Missing script: "build"

### ISSUE THREAD

**Issue by chacles** [aimeos/aimeos-laravel#472]
**Environment**

1. Laravel Version (8.6.12)
2. Version (2021.10)
3. Operating system (Windows)

**Describe the bug**
Run "npm install && npm run build"
Error:
```
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\james\AppData\Local\npm-cache\_logs\2022-10-21T11_42_59_008Z-debug-0.log
```

**To Reproduce**
1. composer create-project laravel/laravel example-app && cd example-app
2. composer require aimeos/aimeos-laravel:~2021.10
3. ...
4. npm install && npm run build

**Comment by Cyber-Devs** [comment]
its not a aimeos problem, you don't have build in you're package.json file. just config you're script accordingly,check doc of build tools eg webpack or vite

**Comment by aimeos** [comment]
For older Laravel versions it's `npm install && npm run dev`
