### ISSUE TITLE
ERROR  Can't locate path: <ext/custom/client/html/>

### ISSUE THREAD

**Issue by Arturbox** [aimeos/aimeos-laravel#474]
aimeos/aimeos-laravel: 2022.10

In Aimeos\Shop\ShopServiceProvider boot method  add slash in 'themes/client/html/' 
Result '/themes/client/html/'

if( file_exists( $basepath = base_path( 'ext' ) ) )
		{
			foreach( new \DirectoryIterator( $basepath ) as $entry )
			{
				if( $entry->isDir() && !$entry->isDot() && file_exists( $entry->getPathName() . '/themes/client/html' ) ) {
					$this->publishes( [$entry->getPathName() . 'themes/client/html/' => public_path( 'vendor/shop/themes' )], 'public' );
				}
			}
		}

**Comment by aimeos** [comment]
`$entry->getPathName()` shouldn't add a slash by default so the resulting absolute path should be:
`/.../laravelapp/ext/testext/themes/client/html`

If it's not, try to find out why so we can fix it if possible.

**Comment by Arturbox** [comment]
Custom extension name created with aimeos => optimize 
During  composer update  I am getting this error =>  ERROR  Can't locate path: <ext/optimizethemes/client/html/>.

**Comment by Arturbox** [comment]
And the second question.
I tried to redefine one of the Base abstract classes in different ways, but it doesn't work. If you help I will be grateful))

Here is manifest.php 
![Screenshot from 2022-11-03 03-58-26](https://user-images.githubusercontent.com/36479457/199624676-d67d4282-d39d-48a6-adbc-71b0d2ca8c3b.png)


Here is the structure
![Screenshot from 2022-11-03 04-05-45](https://user-images.githubusercontent.com/36479457/199624775-674e3ff1-7507-4a6b-9571-fb6b4878788f.png)

Tried to redefine as abstract cl
![Screenshot from 2022-11-03 04-07-21](https://user-images.githubusercontent.com/36479457/199624949-c1a5b6d0-d901-4271-98a6-d859a156a392.png)

I even tried to create a simple class that does extend from an abstract class but still does not redefine

Thanks in advance!

**Comment by aimeos** [comment]
> Custom extension name created with aimeos => optimize During composer update I am getting this error => ERROR Can't locate path: <ext/optimizethemes/client/html/>.

This usually happens if you add the files to Git and make a checkout of the repo afterwards (or use composer to install it) because Git doesn't add empty directories. Place a `.gitkeep` file inside the empty directory and commit to Git to fix this.

**Comment by aimeos** [comment]
Regarding your second question:
You can't overwrite base classes, only the classes that uses that class.
