### ISSUE TITLE
How to fix this "INFO  Nothing to migrate" Bug and others when installing "Aimeos" in LARAVEL 9.19 ???

### ISSUE THREAD

**Issue by chegmarco1989** [aimeos/aimeos-laravel#479]
**Environment**
_1. **LARAVEL:** 9.19
2. **Aimeos-Laravel:** 2022.10
3. **Operating system** (Windows: 10)_

**Describe the bug**

- I get `INFO  Nothing to migrate` **as the first error** when I execute `php artisan migrate` after have lauched `php artisan vendor:publish --provider="Aimeos\Shop\ShopServiceProvider"`.
- I also get ` Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.` **as the second error** when I execute `php artisan aimeos:setup`.

**To Reproduce**
1. `composer require aimeos/aimeos-laravel`
2. `php artisan vendor:publish --provider="Aimeos\Shop\ShopServiceProvider"`
3. `php artisan migrate`
4. `php artisan aimeos:setup`

**Screenshots**
![image](https://user-images.githubusercontent.com/51763985/221358502-729fa44b-91d4-43a9-a3d2-ccff99ff2c20.png)

Please help to fix these bugs.
Awaiting.

**Comment by aimeos** [comment]
"Nothing to migrate" is not an error. The Doctrine error occurs because one of your custom tables (or the users table) contains an ENUM column, which isn't supported by Doctrine.
