### ISSUE TITLE
Some functions report an error 

### ISSUE THREAD

**Issue by uouaks** [aimeos/aimeos-laravel#484]
_npm --version                                                                                         
8.11.0                                                                                                           
node --version                                                                                        
v17.9.1                                                                                                          
nvm --version                                                                                         
0.35.3 
php -v                                                                                                
PHP 8.1.10_

Version: aimeos-laravel/releases/tag/2023.04.1

Categories  - Products 
- product list is not displayed in the category.
TypeError: Cannot read properties of undefined (reading 'product.lists.siteid')

Product - Type Variants
- button is not active, I can't add
ReferenceError: getArticles is not defined

It seems that both problems are related to the same file: jsdelivr-separator.js 
Screenshot 1: https://ibb.co/qDT9v9M
Screenshot 2: https://ibb.co/qCN1Mvy

**Comment by aimeos** [comment]
Thanks for reporting those issues. We can reproduce the issues and will care about them immediately

**Comment by uouaks** [comment]
Amazing! The two functions are working again. Thanks
