### ISSUE TITLE
laminas/laminas-diactoros problem with Laravel 10 and PHP 8.1+

### ISSUE THREAD

**Issue by slps970093** [aimeos/aimeos-laravel#486]
composer require aimeos/aimeos-laravel:~2023.04
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 127.0.0.1:9003 (through xdebug.client_host/xdebug.client_port).
./composer.json has been updated
Running composer update aimeos/aimeos-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-diactoros[2.5.0, ..., 2.6.0] require php ^7.3 || ~8.0.0 -> your php version (8.1.17) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.7.0, ..., 2.24.2] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laminas/laminas-diactoros[2.25.0, ..., 2.25.2] require psr/http-message ^1.1 -> found psr/http-message[1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - aimeos/aimeos-laravel 2023.04.1 requires laminas/laminas-diactoros ~2.5 -> satisfiable by laminas/laminas-diactoros[2.5.0, ..., 2.25.2].
    - Root composer.json requires aimeos/aimeos-laravel ~2023.04 -> satisfiable by aimeos/aimeos-laravel[2023.04.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by aimeos** [comment]
Solution described here (downgrade psr/php-message package):
https://github.com/aimeos/aimeos/issues/107

The problem is that there's no version of the laminas/laminas-diactoros package for psr/php-message:2.0 yet.
