### ISSUE TITLE
error while running aimeos:setup

### ISSUE THREAD

**Issue by godwnwaswa** [aimeos/aimeos-laravel#489]
php artisan aimeos:setup

   Exception

  Extension "ai-laravel" exists twice in "/data/data/com.termux/files/home/projects/realdriss/vendor/aimeos/ai-laravel" and in "/data/data/com.termux/files/home/projects/realdriss/ext/ai-laravel"

  at vendor/aimeos/aimeos-core/Bootstrap.php:403
    399▕                        if( isset( $this->extensions[$manifest['name']] ) )
    400▕                        {
    401▕                                $location2 = $this->extensions[$manifest['name']]['location'];
    402▕                                $msg = 'Extension "%1$s" exists twice in "%2$s" and in "%3$s"';
  ➜ 403▕                                throw new \Exception( sprintf( $msg, $manifest['name'], $location, $location2 ) );
    404▕                        }
    405▕
    406▕                        if( !isset( $manifest['depends'] ) || !is_array( $manifest['depends'] ) ) {
    407▕                                throw new \Exception( sprintf( 'Incorrect dependency configuration in manifest "%1$s"', $location ) );

      +15 vendor frames

  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by aimeos** [comment]
Please read: https://github.com/aimeos/aimeos-laravel/issues/442#issuecomment-1028724797
