### ISSUE TITLE
Information about the logger?

### ISSUE THREAD

**Issue by Jossnaz** [aimeos/aimeos-laravel#49]
aimeos 2016.04.2 if i am not wrong

`laravelinstall/vendor/aimeos/aimeos-core/controller/jobs/src/Controller/Jobs/Product/Import/Csv/Standard.php`

line

542

```

			catch( \Exception $e )
			{
				$manager->rollback();

				$msg = sprintf( 'Unable to import product with code "%1$s": %2$s', $code, $e->getMessage() );
				$context->getLogger()->log( $msg );

				$errors++;
			}

```

i figured my way through the code... we are logging into the `madmin_log` table. i didn't know. I wish that would have been written down somewhere, or how i can change it as well to log to the logfile.

**Comment by aimeos** [comment]
A hint have been added to the docs. The logging target can be changed but unfortunately not via configuration. It's added to the context here:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/Context.php#L87
