### ISSUE TITLE
404 on catalog-filter.js and catalog-filter.css

### ISSUE THREAD

**Issue by vishnuamiyon** [aimeos/aimeos-laravel#491]
**Environment**
1. Version 
         "php": "^8.1",
        "aimeos/aimeos": "^2023.04",
        "aimeos/aimeos-laravel": "~2023.04",
2. Operating system 
        Windows(XAMPP)

Hi Peps,
 I'm new here so please help me out with the installation. I tried to follow all the procedure mentioned in Readme.me except php artisan serve as I have installed in XAMPP htdocs folder.
 When I open the page, The catalog section is messed up. caused by missing /public/ in it's url. when I checked the generated source from chrome dev tools, the link and script src starts like "/vendor/.." and all other starts with "http://localhost/.."
 Please help me with this issue.
 Thanks and regards.

**Comment by aimeos** [comment]
Make sure ./public is the document root of your vhost. It must not be accessible at `http://localhost/public` !

**Comment by vishnuamiyon** [comment]
Yes. It's there.

**Comment by vishnuamiyon** [comment]
![image](https://github.com/aimeos/aimeos-laravel/assets/50130931/9112acdd-09c9-4eff-9458-a27a5b3bcb2a)
![image](https://github.com/aimeos/aimeos-laravel/assets/50130931/3ca530b2-26d8-4d6e-be92-414588256eda)
![image](https://github.com/aimeos/aimeos-laravel/assets/50130931/07a87a16-4f48-4a83-8d24-afbb01bfdfde)

I'm uploading some images for your ref. please look into this.

**Comment by aimeos** [comment]
What's your APP_URL and APP_ASSET settings in your .env file?

**Comment by vishnuamiyon** [comment]
I don't have APP_ASSET
Other variables are these : 
APP_URL=http://localhost/example-app
ASSET_URL=http://localhost/example-app/public

**Comment by aimeos** [comment]
Both must be only:
```
APP_URL=http://localhost/
ASSET_URL=http://localhost/
```
