### ISSUE TITLE
Showing Class "\Aimeos\MShop\User\Manager\Standard" not found

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos-laravel#492]
**Environment**
1. Version 2023.04.*
2. Operating system Windows

**Describe the bug**
I am trying to include a notification icon in the dashboard, by clicking that a pop will generate having user list based on some conditions.
I need User data in the dashboard, So I included $manager = \Aimeos\MShop::create( $this->context(), 'user' ); in below file
aimeos\ai-admin-jqadm\src\Admin\JQAdm\Dashboard\Standard.php. It returns Class "\Aimeos\MShop\User\Manager\Standard" not found.
please advice @aimeos 

**Expected behavior**
should returns user data from users table and can be included in template file

**Comment by aimeos** [comment]
There's no "user" manager, it's called "customer":
```php
$manager = \Aimeos\MShop::create( $this->context(), 'customer' );
```
