### ISSUE TITLE
How these actions are defined ?

### ISSUE THREAD

**Issue by damanmokha** [aimeos/aimeos-laravel#495]
Hello,

I have been working on modifying some functionalities, but I am unable to locate the action functions that are used in the "notify" trait. Some examples of these actions are:

```
$this->notify( 'setCustomerId.before', (string) $customerid );
$this->notify( 'setCustomerId.after', (string) $customerid );
$this->notify( 'check.before', $what );
$this->notify( 'check.after', $what );
```

Could you kindly provide information about where the `'check.before'` and `'check.after'` actions are defined? Furthermore, I would like to understand the purpose and process of the `'check.after'` action, and if possible, how to modify it.

Your assistance in clarifying these matters would be greatly appreciated.

Thank you.

**Comment by aimeos** [comment]
The events are published to listener plugin classes and you can find documentation about basket plugins here:
https://aimeos.org/docs/latest/providers/basket-plugins/
