### ISSUE TITLE
Correction to installation instructions needed when installing Laravel Breeze

### ISSUE THREAD

**Issue by connektiv8** [aimeos/aimeos-laravel#496]
**Is your feature request related to a problem?**
When following your installation instructions the installation of "php artisan laravel/breeze" now forks into different options for which type of scaffolding to use, so you may want to include that in your instructions.

![image](https://github.com/aimeos/aimeos-laravel/assets/83831086/068245a7-c0be-43fe-adaf-d64de03e5b44)

**Describe the solution you'd like**
A clear and concise set of instructions that can get Aimeos installed.

**Comment by aimeos** [comment]
Thanks, README is updated now :-)
