### ISSUE TITLE
[Solved] Dependency issue when installing aimeos... psr/http-message

### ISSUE THREAD

**Issue by christoferd** [aimeos/aimeos-laravel#499]
**Environment**
1. 2023.10
2. Windows

**Describe the bug**
Fresh install dependency issue.
```
Problem 1
    - aimeos/aimeos-core[2023.10.1, ..., 2023.10.3] require psr/http-message ~1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match
```
**To Reproduce**
1. Install Laravel
2. Install Breeze
3. composer require aimeos/aimeos-laravel:~2023.10

**Expected behavior**
Expect to install gracefully with instructions provided :-)

**Screenshots**
![image](https://github.com/aimeos/aimeos-laravel/assets/1835883/b743f6f1-afa2-49ad-b459-f61359bc9fa2)

**Additional context**
**[Solved]**
Instead of: composer require aimeos/aimeos-laravel:~2023.10
Run: composer require aimeos/aimeos-laravel:~2023.10 **--with-all-dependencies**

**Comment by aimeos** [comment]
Thanks for the hint, the `-W` flag has been added to the README now
