### ISSUE TITLE
Modifying core html layouts

### ISSUE THREAD

**Issue by ujackson** [aimeos/aimeos-laravel#5]
I am trying to modify the core html layouts. I created an extenion and saved it in laravel ext folder.
Copied the files in vedndor/arcavias-core/client/html/layouts to the new extension folder. How do I make the changes in the ext folder overwrite the ones in the core

**Comment by aimeos** [comment]
Did you copy it into the same directory structure? It must be "./ext/<yourext>/client/html/layouts/..." and the file and directory names below must be the same as in the core. The "./ext/<yourext>/manifest.php" must list the directory name "client/html/layouts". 

Did you created your extension using our extension builder? https://aimeos.org/developer/extensions/

**Comment by ujackson** [comment]
The extension was created using the aimeos extension builder. Yes I copied the same directory structure. I placed the contents from ./vendor/arcavias/arcavias-core/client/html/layouts/ inside ai-default folder in the L5 ext directory.

**Comment by aimeos** [comment]
Can you send us your Aimeos extension as .zip file to aimeos@aimeos.org? Then we can have a look into it and see what's maybe wrong.

**Comment by aimeos** [comment]
Did you've already solved it yourself? We didn't received an e-mail up to now.

To overwrite e.g. the catalog list items template (items-body-default.html), you have to place your modified copy into this directory of your Aimeos extension (ai-default in your case):
yourlaravelapp/ext/ai-default/client/html/layouts/catalog/list/items-body-default.html

**Comment by ujackson** [comment]
I was able to resolve the issue by creating another extension. Everything is working fine now. Thanks
