### ISSUE TITLE
Integration Aimeos with asgardcms

### ISSUE THREAD

**Issue by wassimhattab** [aimeos/aimeos-laravel#50]
Hello,
I installed aimeos with laravel with no problem by the steps shown on the aimeos website https://aimeos.org/docs/Laravel/Install_Aimeos
But i i want to install aimeos with asgard it's not working have anyone tried to install aimeos on asgard cms?

**Comment by aimeos** [comment]
You might get it to work but the Aimeos admin interface won't be integrated into the Asgard admin.
What exactly isn't working?
