### ISSUE TITLE
The extension jqadm's index.blade.php is not taken into consideration

### ISSUE THREAD

**Issue by merouanekhalili** [aimeos/aimeos-laravel#500]
**Environment**
1. Version : 2023.10
2. Operating system : Windows

**Describe the bug**
I generated a new theme extention and update my-theme\views\jqadm\index.blade.php file, but the the application still use the default one from the framework.

I think that this line, which is responsible for this : https://github.com/aimeos/aimeos-laravel/blob/0a9179ac7685defc4fe047e18fa1e91e1b26c52b/src/Controller/JqadmController.php#L282

**Comment by aimeos** [comment]
The laravel theme extensions are for the frontend only. Using a different backend theme is only supported by overwriting the styles in the themes/admin/jqadm/custom.css file and placing a copy of the jqadm/index.blade.php in the ./resources/views/vendor/shop/jqadm/ directory.
