### ISSUE TITLE
Auth API

### ISSUE THREAD

**Issue by nvdid** [aimeos/aimeos-laravel#503]
Would it be relevant to the project to have a laravel pacakge/extension for API authentication?

I was working on aimeos-headless. Then I had to authenticate in my front-end (which is not aimeos).
I created a laravel package for simple authentication in API using laravel's built-in auth. If it would be useful for other users to have a ready package to handle a simple authentication for APIs, then I can publish it somewhere.

**Comment by aimeos** [comment]
The existing JWT-based API  in the Aimeos headless distribution for authentication wasn't useful for you?

**Comment by nvdid** [comment]
Actually I forgot about its existence when I was working on the matter. But what I did wasn't quite reinventing the wheel as I needed OTP for authentication. So I assume we have the wheel out there👍

**Comment by aimeos** [comment]
Feel free to offer an extension with an alternate API if it has some advantages :-)
