### ISSUE TITLE
change the Hot Deals Text

### ISSUE THREAD

**Issue by lembarek** [aimeos/aimeos-laravel#508]
**Environment**
1. Version : dev-master
2. Operating system : linux

**Describe the bug**
when I try to change the Hot Deals link to 'Bonnes Affaires' (For French)

**To Reproduce**
1. Go to admin 
2. then Catalog 
3. then Categories 
4. then Hot Deals  
5. then Text then 
6. select Type as Name
7. change the content
8. save
9. then select type as short description
10. add your desciption (Offres exceptionnelles pour ce mois)
11. save

**Expected behavior**
the 
https://github.com/user-attachments/assets/c6056205-9ccb-4cbf-a835-ef420917b5bd
 Text in navbar become 'Bonnes Affaires'
and the short text become  (Offres exceptionnelles pour ce mois))
But

the Hot Deals did not change

**Screenshots**

**Additional context**

**Comment by lembarek** [comment]
I think the problem is query of update
the first update is 
SET  "langid" = 'fr', "type" = 'name', "domain" = 'catalog', "label"= 'Bonnes affaires',

and the second update is 
SET "langid" = 'fr', "type" = 'short', "domain" = 'catalog', "label" = 'Bonnes affaires', "content" ...

and the 2 update have the same condition
WHERE "siteid" LIKE '1.%' AND "id" = 8

here the first second update will overwrite the first update

**Comment by aimeos** [comment]
You've changed type "name" to "short description" so no name in French is available any more. Thus, the category label ("Hot deals") is used

**Comment by lembarek** [comment]
is there a way to change the name and the short description  to french?

**Comment by aimeos** [comment]
Add a second text item

**Comment by lembarek** [comment]
Thanks
