### ISSUE TITLE
Error running migration

### ISSUE THREAD

**Issue by williamokano** [aimeos/aimeos-laravel#51]
![essaporranaofunciona](https://cloud.githubusercontent.com/assets/5909442/16604944/dfb6f94e-4300-11e6-804d-e2aec9d4c914.png)
Hi, I tried to install aimeos from a Laravel fresh install.

I followed all the steps in the instructions but when I ran ```php artisan migrate``` of the last step I got the following error
```
[Illuminate\Database\QueryException]                                                                                                                        
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "users" add column "salutation" varchar not null) 
```

Is that a bug on the installation?

**Comment by aimeos** [comment]
Can you give us a bit more information about your environment?
Laravel version, MySQL version, PHP version, etc?

**Comment by williamokano** [comment]
Laravel 5.2.29
I'm running mariaDB but not sure which version is.

Windows with xampp latest php 7.0.4

I tried with SQLite here and I got the same problem (Linux mint rosa php
5.5.9 SQLite laravel 5.2.29)

Em qua, 6 de jul de 2016 02:57, Aimeos <notifications@github.com> escreveu:

**Comment by williamokano** [comment]
Tried again on a linux machine with the following configuration

apache 2.4
php 5.5.9
laravel 5.2.29
mysql server 5.6

And the installation ran smooth!

**Comment by aimeos** [comment]
Would be quite interesting for us what MariaDB version you are using. It seems like there's a difference to MySQL

**Comment by aimeos** [comment]
We've added default values in the migrations to fix the problem with MariaDB. Can you please try again to install Aimeos in your WAMP/MariaDB environement? You have to use `"aimeos/aimeos-laravel": "dev-master"` to get the latest code.

**Comment by williamokano** [comment]
Yes I can, I'll do this tonight. Sorry for late reply.

Thanks.

**Comment by aimeos** [comment]
Any news on this issue?
