### ISSUE TITLE
I can not remove some caracterisitcs

### ISSUE THREAD

**Issue by lembarek** [aimeos/aimeos-laravel#510]
**Environment**
1. Version dev-master
2. Operating system :linux

**Describe the bug**
I can not remove some caracterisitque 

**To Reproduce**
when  I go to a product
and  go to characteristics
and remove some and save
the characteristic return

https://github.com/user-attachments/assets/f85a84ec-3ccd-48e8-a5ca-5a599b5a8d05

**Comment by lembarek** [comment]
for now the problem happen only for the Type=Interval

**Comment by aimeos** [comment]
You have to un-check the subscription intervals in the "Subscription" tab instead.
