### ISSUE TITLE
Unable to find product "XXX" shown in admin log

### ISSUE THREAD

**Issue by yy-sw1tch-yy** [aimeos/aimeos-laravel#512]
**Environment**
1. Version (~2021.07)
2. Operating system (Mac)

**Describe the bug**
Admin log unable to find product "Product-A-Code", but after the index/rebuild is run, the "Product-A-Code" can be found in mshop_index_text url.

**Question**
1. What does the error mean? And why it happens?
2. What does index/rebuild actually do?

**Additional context**
We do schedule to run index/rebuild everyday, but just want to know what and why it happens.

**Comment by aimeos** [comment]
Can you post the stack trace from in the Log panel?
