### ISSUE TITLE
How to add table prefix

### ISSUE THREAD

**Issue by shijunti19** [aimeos/aimeos-laravel#516]
How to add table prefix

```
config\shop.php
  'resource' => [
        'db' => [
 
            'prefix'              => config('database.connections.' . config('database.default', 'mysql') . '.prefix', 'dgg_'),
```
prefix Not working 
![image](https://github.com/user-attachments/assets/a0f8a532-f245-4d4f-9c19-ebfce119c255)
I hope it's dgg_users

**Comment by aimeos** [comment]
Sorry, table prefixes are not supported but you can use a different database for each data doman like customers/users, products, etc.:
https://aimeos.org/docs/latest/laravel/optimize/#databases

**Comment by shijunti19** [comment]
@aimeos How can we solve the problem of using the same prefix for all these years, and then we can resolve the conflict ourselves.
I think prefixes are a necessary feature
双语对照
笔记

**Comment by aimeos** [comment]
They where only necessary in the old days when databases were costly.
If your users table is named differently, you can extend from the \Aimeos\MShop\Customer\Manager\Laravel class and overwrite the `table()` method to return your own table name instead
