### ISSUE TITLE
Installation failed: command fails `php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by OussemosCh** [aimeos/aimeos-laravel#52]
When I run this Command 

`php artisan aimeos:setup --option=setup/default/demo:1` 

I get this error 

`[Aimeos\MW\Setup\Exception] Not a DBAL connection`

PS: the database is working cuz when i run migration it work

**Comment by aimeos** [comment]
Seems like a mix of aimeos-laravel and aimeos-core that doesn't play together due to the new stable release today. Can you add a require `"aimeos/aimeos-core": "2016.04.*"` to your composer.json and run a `composer update` afterwards? This should fix the problem for now.

**Comment by OussemosCh** [comment]
i get this error now 

![image](https://cloud.githubusercontent.com/assets/9042895/16673603/ed3e8dd8-44af-11e6-97c8-abe4dea75088.png)

**Comment by aimeos** [comment]
Please make sure you've followed the installation guide step by step:
https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by aouliet** [comment]
Make sure to add this require `"aimeos/aimeos-laravel": "~2016.10",`
