### ISSUE TITLE
Aimeos Demo

### ISSUE THREAD

**Issue by wassimhattab** [aimeos/aimeos-laravel#53]
Hello if i had installed aimeos Laravel Demo could i disable the color and length option if i don't want to use clothes like the demo and keep the demo working correctly with adding to cart and checkout?

**Comment by aimeos** [comment]
Sure, if your products doesn't use them, you can remove these attributes without limiting functionality

**Comment by wassimhattab** [comment]
ok it worked.. if i want to change in frontend design is it possible or no?

**Comment by aimeos** [comment]
You can overwrite any template you want. Please have a look into the documentation:
https://aimeos.org/docs/Developers#HTML_Frontend

**Comment by wassimhattab** [comment]
Okay thank you
