### ISSUE TITLE
Aimeos Attribute

### ISSUE THREAD

**Issue by wassimhattab** [aimeos/aimeos-laravel#54]
Hello, I downloaded the aimeos demo and working on it,
I'm trying to add new products with new images ,colors, width and length but the colors , width and length are not showing on the frontend.
![aimeos2](https://cloud.githubusercontent.com/assets/20112008/16762849/000b8308-482f-11e6-91a5-d3d7e15ae79f.png)
![aimeos3](https://cloud.githubusercontent.com/assets/20112008/16762854/05639a66-482f-11e6-934d-60b8ece3c117.png)

**Comment by aimeos** [comment]
Please use the Aimeos forum (https://aimeos.org/help/) for user related questions
