### ISSUE TITLE
Do eloquent models exist for the Aimeos shop tables?

### ISSUE THREAD

**Issue by Jossnaz** [aimeos/aimeos-laravel#55]
Do eloquent models exist for the Aimeos shop tables? best would be along some simple examples of how to use it.

I give an example:

get all products from a group (catalog) label, specified by string.

and all of that, in the eloquent way.

Because right now I started writing all the models. MshopCatalog, MshopCatalogList, MshopProduct, MshopProductList etc. Now if that already exists I don't have to figure it out myself.

Another question:

While solving the above scenario i asked myself, even if those models do not exist, is there maybe code that describes and solves exactly those problems already? so i at least can copy the idea from there / get inspired. It took me a while which ID now was the one that corresponds to the product. This is time wasted, if it is written somewhere already as code that would explain it to me quicker.

**Comment by aimeos** [comment]
We don't use Eloquent models because they are Laravel specific and Aimeos is available for a whole bunch of frameworks and applications. Please use our managers to create, retrieve, save and delete items: https://aimeos.org/docs/Developers/Library/Managing_items

**Comment by Jossnaz** [comment]
i understand well that the aimeos core things are built using your own way. But now, this is the laravel port. Maybe someone has written this already? because it is actually quite nice working with the active records in my opinion.


I was at the docs page and was looking for something that explains the managers, i somehow overlooked it. It is a bit vague the wording "managing items and content" but maybe it is my ignorance.

while the link sheds some light, I still feel a bit swimming in the dark. Now I have found out there is a table `mshop_index_catalog` that is actually the table that I felt was missing thanks to a link to the source code of the private `$searchConfig` variables in some file. 
it's... you parameterized everything. Now it is quite difficult to read the code because things are handed as strings, evaluated. Now this is not necessarily a bad thing, it's just hard to start. And there is nothing that really helps me to get started and tells me the very basic things each, every single developer, is likely gonna use.


So, what functions are we as developers supposed to use?

Let's do an example. I want to get all products of a given category ID. This has been done obviously already by you before I now try to do it. I reverse engineered myself from the demo list view of a category.

```

ff-laravel/ext/ai-controller-frontend/controller/frontend/src/Controller/Frontend/Catalog/Standard.php 

	/**
	 * Returns the index filter for the given category ID.
	 *
	 * @param integer $catid ID of the category to get the product list from
	 * @param string|null $sort Sortation of the product list like "name", "code", "price" and "position", null for no sortation
	 * @param string $direction Sort direction of the product list ("+", "-")
	 * @param integer $start Position in the list of found products where to begin retrieving the items
	 * @param integer $size Number of products that should be returned
	 * @param string $listtype Type of the product list, e.g. default, promotion, etc.
	 * @return \Aimeos\MW\Criteria\Iface Criteria object containing the conditions for searching
	 * @since 2015.08
	 */
	public function createIndexFilterCategory( $catid, $sort = null, $direction = '+', $start = 0, $size = 100, $listtype = 'default' )


```

probably that's what we are supposed to use? there is a `@since` attached to the docs there, so I guess yes? is there other common places to use the searchConfigs?
seems like all joins are done mainly in:

`ff-laravel/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Catalog/Standard.php`

that is all subfolders of the `ff-laravel/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/`, right?

**Comment by aimeos** [comment]
Yes, the frontend controllers should be your main source for retrieving items or working with the basket if you want to extend the HTML client. They are small but powerful enough to get most of the things done you will need.

The managers in the layer below are more important for low level access like for import/export or if you need to get something special. Then, you have to look into the search configs of the managers you are using to see what you can use in the criteria objects to filter the result set.

**Comment by aimeos** [comment]
There's a new article about the software stack. Maybe it helps you to understand how Aimeos is organized: https://aimeos.org/docs/Developers/Software_stack

**Comment by ClaryPollack** [comment]
Hello. First of all, @aimeos thank you for an amazing product! I just heard of Laravel a few weeks ago and have almost completed my first e-commerce website with ease. And it loads extremely quickly!

My question echos those of @Jossnaz . Your links to the documentation didn't really address the question (other than the fact that we can't really use Eloquent). Some time has passed since the original post so I'm hopeful that someone has come up with a solution. My real issue is that the urls for the category pages are difficult to configure. Everything else has been a breeze so far so please let me know if anyone knows how to retrieve URL suffixes on the category pages by the label variable only, and not catid, etc.

Have a good day. Cheers.

**Comment by aimeos** [comment]
Hi Clary. The Laravel router is still buggy when using optional URL attributes and Taylor won't fix it because then his simplification for building REST URLs will fail :-(

This is what's done automatically:
route: /{product} : resource=product, id=1 -> /product/1

When we use it in Aimeos:
route: /{resource}/{?f_catid} : resource=catalog, f_catid=1 -> /catalog/1 (OK)
route: /{resource}/{?f_catid} : resource=catalog, f_attr[]=10 -> /catalog/10 (failure, correct would be /catalog?f_attr[]=10)

**Comment by ClaryPollack** [comment]
@aimeos thank you for the quick reply. I totally understand and it makes sense why Taylor wouldn't want to interfere with anything that could disturb the REST URLs.

Will play around with it a bit more and, if I can't make it function exactly as I would like, no problem: the speed and other features more than make up for the URL issues :)

Cheers,
Clary

**Comment by Jossnaz** [comment]
what is the current workaround for this? the router issue with aimeos

**Comment by aimeos** [comment]
The only known workaround is to create a new page and route for category based product listings only which has no optional parameters for f_name and f_catid. You have to replace the Aimeos catalog tree template and use the new route there.

**Comment by aimeos** [comment]
That's the client fetching the data, the template is https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/catalog/filter/tree-body-standard.php. The tree partial used there is also in the same directory
