### ISSUE TITLE
Redirect to login after login

### ISSUE THREAD

**Issue by ArnauMe** [aimeos/aimeos-laravel#57]
Hello, 

this is more an ignorance by my side issue than a package's issue, but i'm a little lost and i would appreciate any help. 
Before i only used laravel's basic auth, and i didn't have to edit anything whatsoever to make it work, but now i want to try your ecommerce package and i really have no clue what do i have to do after the 'make:auth' command. 
I followed you installation instructions, no errors so far, i could test the installation , all good. 
But after making the laravel auth, i'm stuck. 
When i attempt to login with the supposed admin user i created, i get redirected to the login page again, even if i try to point to /admin again as you mention in your documentation. 
I also tried to change $redirectTo = '/admin' just to see what would happen, but i get the same result (although it first redirects to /admin, but then to /login again). 

Any tips/guides for anyone who never touched anything about authentification nor guards ? I don't know what i should do to have admin and users.

If you need any code i'll post it, but as i said i haven't edited anything that wasn't in your installation guide.

I'm using Laravel 5.2.

Thank you very much.

**Comment by aimeos** [comment]
Did you've created an admin or editor user on the command line (./artisan aimeos:account ...) like described in the guide?

**Comment by ArnauMe** [comment]
Yes i did, --admin account

**Comment by ArnauMe** [comment]
Can i look for any clues myself? in the database, any laravel service provider / controller etc. ?
I'm really interested in using this but i seem to fail... to be honest laravel documentation in authentication is not really clear to me , specially interacting with this pachage.

Thanks

**Comment by ArnauMe** [comment]
I still don't know why, but i tried again in a clean laravel project, and it worked (i did it in a clean installation aswell before). 

I guess you can close this

Thanks.

**Comment by pagliaj** [comment]
Same problem. Did you every find out why? I have this same problem with multiple clean installs.

**Comment by ArnauMe** [comment]
No, i just assumed i did something wrong the first time, i'm sorry.
