### ISSUE TITLE
Correct type hinting for code completion of your functions

### ISSUE THREAD

**Issue by Jossnaz** [aimeos/aimeos-laravel#58]
i've seen it now in several places and it forces me to manually define what interface is available each time.

this would work with phpstorm see here http://stackoverflow.com/a/1763425/533426 :

```
     * @return \Aimeos\MShop\Common\Item\Iface[] some more text
     */
    public function getRefItems( $domain = null, $type = null, $listtype = null );
```

your current implementation does not work:

```
 * @return array List of items implementing \Aimeos\MShop\Common\Item\Iface
     */
    public function getRefItems( $domain = null, $type = null, $listtype = null );
```

you could just move the definition, and add [] and all phpstorm users will be happy (it is a very common editor as you can see by the amount of views on stackoverflow)

**Comment by aimeos** [comment]
Aimeos is Open Source, so feel free to change the annotations as you need and create a PR

**Comment by Jossnaz** [comment]
hmm to create a PR, i create a fork or the master, then I install aimeos somehow with composer using my fork? then I run the aimeos setup . Sorry, if i am honest with you, i haven't done it before. I have worked a lot with git but I don't know how I can create a PR of files that I can test actually locally. E.g. fork, install locally, test, push to git, then create PR. I am not sure what the process is

**Comment by aimeos** [comment]
Create your own fork on GitHub (located top right), execute "git clone <fork url>", make your changes, "git commit ." and "git push". Back on GitHub in your own fork there will be a button "Create pull request". Done :-)

**Comment by Jossnaz** [comment]
the thing is, i want to test my changes and see them in a running application before i commit them, right? after i make git clone, how do I properly test it? i replace some files in my aimeos installation? yes i know, docs do not need to be tested... but you know, in case i ever want to make a proper PR

**Comment by aimeos** [comment]
You can link to your cloned repo from the ./ext/ directory for example

**Comment by herbie-dev** [comment]
![backet](https://user-images.githubusercontent.com/63893107/79781311-dff1dd80-836f-11ea-8e56-4e5d382266be.JPG)
