### ISSUE TITLE
"English" pops up as a part of billing/delivery address

### ISSUE THREAD

**Issue by arthurtarasov** [aimeos/aimeos-laravel#59]
I'm not sure if this qualifies as a bug, but my customers seem to think it is. When a customer is about to confirm her order, she is shown `mywebsite.com/checkout/summary` page. On that page, her address appears as:

> Billing address
> Ms Jane Doe
> Central Avenue 10
> Best City 12345
> Canada
> **English**
> janedoe@email.com

The problem here is the word `English` that I highlighted in bold above. It pops out of nowhere and I cannot figure out how to remove it from a billing address. It freaks people out because they think that their purchase is going to England. The customer appears to have no control over that word, which becomes a part of the billing address, which in turn has just been filled in by a customer. Is there a way for me to quick fix this and remove the "English" word? 

I think it should not appear as a part of the address by default or the customer should have some control over it, if it is necessary in some cases. Not to mention, if my dispatcher puts it on the mail, it will confuse the mailman up to the point that the package may bounce back.

**Comment by aimeos** [comment]
You can change the address format as you like and also remove details like the chosen language:
https://github.com/aimeos/ai-client-html/blob/master/client/html/templates/common/summary/address-body-default.php#L36

Here's the documentation how to overwrite translations locally:
https://aimeos.org/docs/Laravel/Overwrite_translations

**Comment by arthurtarasov** [comment]
Many thanks!
