### ISSUE TITLE
php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by sheldonkotyk** [aimeos/aimeos-laravel#6]
hecking "text/list/type" type data                                 OK
Processing product demo data                                          removed
Processing catalog demo data                                          removed
Processing coupon demo data                                           removed
Processing customer demo data

  [MW_DB_Exception]
  Executing statement "
  			SELECT DISTINCT lvu."id", lvu."name" as "label", lvu."name" as "code",
  				lvu."company", lvu."vatid", lvu."salutation", lvu."title",
  				lvu."firstname", lvu."lastname", lvu."address1",
  				lvu."address2", lvu."address3", lvu."postal", lvu."city",
  				lvu."state", lvu."countryid", lvu."langid",
  				lvu."telephone", lvu."email", lvu."telefax", lvu."website",
  				lvu."birthday", lvu."status", lvu."vdate", lvu."password",
  				lvu."created_at" AS "ctime", lvu."updated_at" AS "mtime", lvu."editor"
  			FROM "users" AS lvu

  			WHERE ( lvu."name" LIKE 'demo-%' )

  			LIMIT 100 OFFSET 0
  		" failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.company' in 'field list'

**Comment by sheldonkotyk** [comment]
Using Laravel 5.1.x

**Comment by aimeos** [comment]
Please execute ```php artisan migrate``` before. Then, the necessary columns have been created.

**Comment by sheldonkotyk** [comment]
Nothing to migrate.

Still doesn't work.

**Comment by aimeos** [comment]
Can you execute a ```php artisan vendor:publish``` first? Seems like the database migration haven't been copied to the Laravel directory.

**Comment by aimeos** [comment]
Did that fix your problem?

**Comment by sheldonkotyk** [comment]
works now. :)
