### ISSUE TITLE
Error running migration to setup demo:

### ISSUE THREAD

**Issue by londoh** [aimeos/aimeos-laravel#60]
`$ php artisan aimeos:setup --option=setup/default/demo:1`
everything proceeds normally to here:

```
...
Creating admin tables                                                 
  Using schema from cache.php                                         
    Checking table "madmin_cache":                                    OK
    Checking table "madmin_cache_tag":                                
```
then this:
```
[Aimeos\MW\DB\Exception]                                                                                                                                                       
  Executing statement "ALTER TABLE madmin_cache_tag ADD CONSTRAINT fk_macac_tid FOREIGN KEY (tid, tsiteid) REFERENCES madmin_cache (id, siteid) ON UPDATE CASCADE ON DELETE CAS  
  CADE" failed: An exception occurred while executing 'ALTER TABLE madmin_cache_tag ADD CONSTRAINT fk_macac_tid FOREIGN KEY (tid, tsiteid) REFERENCES madmin_cache (id, siteid)  
   ON UPDATE CASCADE ON DELETE CASCADE':                                                                                                                                         
  SQLSTATE[HY000]: General error: 1005 Can't create table `aimeos`.`#sql-1d87_520` (errno: 150 "Foreign key constraint is incorrectly formed") 
```
laravel 5.2 
php 7.0.8 
apache 2.4.6 
and mariadb
```
$ mysql -V
mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for Linux (x86_64) using readline 5.1
```

Please let me know if you have solution, otherwise I'll have a look into it later or tomorrow and report back if I can figure out why.

regards

l.

**Comment by londoh** [comment]
this is possibly my error: i grabbed the 2016-07 branch
but then I read the readme ;-) and noticed it said 2016-04 
so i tried again and its worked ok

tnx

l.

**Comment by aimeos** [comment]
Version 2016.07 is the latest stable branch
Seems like a MariaDB specific problem and it may relate to the foreign key constraint using two columns. Which version of MariaDB are you using?

**Comment by londoh** [comment]
re 2016.07 - yea I saw after I reinstalled.
I also wondered if it might be a mariadb specific issue
But the funny thing I dropped the db and started over and the second time it completed, no probs.

mariadb ver is as per first post: 10.1.16 = latest I think

**Comment by aimeos** [comment]
Strange. It's hard to track if it doesn't occur again ...
