### ISSUE TITLE
Can't add first user

### ISSUE THREAD

**Issue by bruno-rodrigues** [aimeos/aimeos-laravel#62]
When i run  `php artisan aimeos:account --admin admin@mail.com` I get the following error.

```
Add "admin" group to user "admin@mail.com" for sites
- default

                                                      
  [Aimeos\MShop\Exception]                            
  No item found for conditions: Array                 
  (                                                   
      [customer.lists.type.code] => default           
      [customer.lists.type.domain] => customer/group  
  )                     
```                                                                    
Tried with 2016.04 and 2016.07 versions.
Thank you!

**Comment by aimeos** [comment]
Your database doesn't seem to be set up properly. Did you've executed `php artisan aimeos:setup`?

**Comment by bruno-rodrigues** [comment]
Output from my `history` command:

```
 9024  composer update
 9025  php artisan vendor:publish
 9026  art migrate
 9027  art aimeos:setup --option=setup/default/demo:1
 9028  art aimeos:cache
 9029  art cache:clear
```

**Comment by aimeos** [comment]
Which database are you using?
Can you have a look if the `mshop_customer_list_type` table contains an record with 'domain' => 'customer/group' and 'code' => 'default'?

**Comment by bruno-rodrigues** [comment]
`mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64) using  EditLine wrapper`.

The table `mshop_customer_list_type` has 0 rows.

**Comment by aimeos** [comment]
Have there been any errors during `php artisan aimeos:setup`?

**Comment by bruno-rodrigues** [comment]
Nope, I'll restart the installation process from scratch now. I'll give feedback here soon. Thanks for your attention.

**Comment by bruno-rodrigues** [comment]
RE-did all the process as the github page teaches and:

```
Add "admin" group to user "admin@mail.com" for sites
- default


  [Aimeos\MShop\Exception]                            
  No item found for conditions: Array                 
  (                                                   
      [customer.lists.type.code] => default           
      [customer.lists.type.domain] => customer/group  
  )   
```              

happened again :(

**Comment by aimeos** [comment]
Which operating system are you using?
Can you please execute `php artisan aimeos:setup --option=setup/default/demo:1 1>setup.log 2>setup.err` again and post the content of the created "setup" files?

**Comment by bruno-rodrigues** [comment]
MacOS with vagrant (ubuntu)

setup.log: http://pastebin.com/JQsTSdMi
setup.err: <empty>

I've done this installation yesterday for the first time and now it won't work :(

**Comment by bruno-rodrigues** [comment]
After running the command again I've got:

```
 php artisan aimeos:account --admin admin@mail.com

 Password:
 > 

Add "admin" group to user "admin@mail.com" for sites
- default
```

It worked.

Here is my history since reinstallation: 
```
 9067  rm -rf marchio-ecommerce
 9068  ls
 9069  git clone git@bitbucket.org:xxx/xxx.git
 9070  composer install
 9071  php artisan key:generate
 9072  mv .env.example .env
 9073  vim .env
 9074  php artisan key:generate
 9075  composer update
 9076  php artisan vendor:publish
 9077  art migrate
 9078  !
 9079  php artisan aimeos:setup --option=setup/default/demo:1
 9080  php artisan aimeos:cache
 9081  php artisan aimeos:account --admin addr1@mail.com
 9082  php artisan make:auth
 9083  php artisan aimeos:account --admin addr1@mail.com
 9084  php artisan aimeos:setup --option=setup/default/demo:1 1>setup.log 2>setup.err
 9085  ll
 9086  ls
 9087  cat setup.log | pbcopy
 9088  cat setup.err | pbcopy
 9089  tail setup.err
 9090  php artisan --version
 9091  php artisan aimeos:account --admin addr2@mail.com
 9092  php artisan aimeos:account --admin addr1@mail.com
```

I still don't know what I was doing wrong... 
Thank you for your attention! Have an awesome day!

**Comment by aimeos** [comment]
I'm not sure but the PHP process might have died unexpectedly the first time. When you run the setup command the second time, the missing entries have been added:
```
Checking "customer/lists/type" type data                            5/5
```

**Comment by bruno-rodrigues** [comment]
;) Thank you.. 
Can I just commit the changes since laravel installation and deploy it to my server or should I re-run all the steps in the server?

**Comment by aimeos** [comment]
You can develop locally and copy everything to your server later, including the complete database

**Comment by bruno-rodrigues** [comment]
Nice, thank you for your time and awesome support ;)

**Comment by tectiv3** [comment]
I have the same issue:
`php artisan aimeos:account --admin admin@shop.local
 Password:
 >
Add "admin" group to user "admin@shop.local" for sites
- default
  [Aimeos\MShop\Exception]
  No item found for conditions: Array
  (
      [customer.lists.type.code] => default
      [customer.lists.type.domain] => customer/group
  )
`
Run `php artisan aimeos:setup --option=setup/default/demo:1` again and after that admin account was added successfully.
