### ISSUE TITLE
Translation to pt-br

### ISSUE THREAD

**Issue by bruno-rodrigues** [aimeos/aimeos-laravel#63]
Hi.

I am using aimeos-laravel package and I'd like to contribute with a translation to pt-BR.
I do have an account at [transifex](https://www.transifex.com/aimeos/aimeos-core/dashboard/) and i've subscribed as a translator.

How can I integrate the translation in my local environment when i finish translating it via transifex?
This is not clear in the [docs](https://aimeos.org/community/translate/).

Thank you!

**Comment by aimeos** [comment]
You can do a `tx pull` in the aimeos-core and extensions but it's easier to tell us when you've finished your translations. We will than pull them and add them to the git repository and you can simply do a `composer update`

**Comment by bruno-rodrigues** [comment]
Nice, i am already translating it ;). I'll keep this thread opened to keep you updated, ok?

**Comment by bruno-rodrigues** [comment]
https://www.transifex.com/aimeos/aimeos-core/language/pt_BR/

**Comment by aimeos** [comment]
Great job! :-)

We've updated the translations in dev-master so you can already use it when changing to this branch

**Comment by bruno-rodrigues** [comment]
Thank you guys! 
How should I proceed when I "eventually" find some bugs in my translation?

**Comment by aimeos** [comment]
Fix it in transifex, we will update the translations regularly. If you need to overwrite a translation immediately, you can do this by configuration

**Comment by bruno-rodrigues** [comment]
Awesome! Thank you for your time and attention!
