### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column

### ISSUE THREAD

**Issue by Mylo-92** [aimeos/aimeos-laravel#64]
Good Day,

I have the following error: ```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.name' in 'field list'```when running the command: ```php artisan aimeos:setup --option=setup/default/demo:1```. Despite running ```php artisan vendor:publish``` first.

Any help will be greatly appreciated.

Kind Regards,

**Comment by aimeos** [comment]
You forgot to execute `php artisan migrate` between `php artisan vendor:publish` and `php artisan aimeos:setup --option=setup/default/demo:1` like described in the installation guide:
https://github.com/aimeos/aimeos-laravel#installation-or-update

**Comment by Mylo-92** [comment]
running that step as so: ```php artisan vendor:publish && php artisan migrate &&  php artisan aimeos:setup --option=setup/default/demo:1 && php artisan aimeos:cache ``` same error occurs.

**composer.json snippets**
```
...
"aimeos/aimeos-laravel": "~2016.04"
    },

  "post-update-cmd": [
            "php artisan vendor:publish --tag=public --force",
            "php artisan vendor:publish",
            "php artisan migrate",
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
```

**Comment by aimeos** [comment]
Can you have a deeper look why `php artisan migrate` doesn't do the required steps in your case?
Are the two Aimeos migration scripts executed at all? Can you post the output of that command?

**Comment by Mylo-92** [comment]
I am not too sure how I can provide a deeper look,  but here goes:

**Log**
- SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lvu.name' in 'field list' in /Applications/MAMP/htdocs/Elietech_v2.0.0/vendor/aimeos/aimeos-core/lib/mwlib/src/MW/DB/Statement/DBAL/Simple.php:88
Stack trace:
#0 /Applications/MAMP/htdocs/Elietech_v2.0.0/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(778): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /Applications/MAMP/htdocs/Elietech_v2.0.0/ext/ai-laravel/lib/custom/src/MShop/Customer/Manager/Laravel.php(471): Aimeos\MShop\Common\Manager\Base->searchItemsBase(Object(Aimeos\MW\DB\Connection\DBAL), Object(Aimeos\MW\Criteria\SQL), 'mshop/customer/...', 'mshop/customer/...', Array, NULL, 3)
```
**Terminal**
```
composer update
    1/1:	http://packagist.org/p/provider-latest$74a1c750eeddae9bb13a5bc285dfeaeafc72fcc54c5bf36d56dd76b11b44ef6a.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing composer/installers (v1.1.0)
    Loading from cache

  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing doctrine/cache (v1.6.0)
    Loading from cache

  - Installing doctrine/common (v2.6.1)
    Loading from cache

  - Installing doctrine/dbal (v2.5.4)
    Loading from cache

  - Installing aimeos/aimeos-core (2016.07.3)
    Loading from cache

  - Installing aimeos/ai-controller-frontend (2016.07.3)
    Loading from cache

  - Installing aimeos/ai-controller-jobs (2016.07.3)
    Loading from cache

  - Installing aimeos/ai-client-html (2016.07.3)
    Loading from cache

  - Installing aimeos/ai-admin-jsonadm (2016.07.2)
    Loading from cache

  - Installing aimeos/ai-admin-jqadm (2016.07.3)
    Loading from cache

  - Installing aimeos/ai-admin-extadm (2016.07.2)
    Loading from cache

  - Installing zendframework/zend-diactoros (1.3.5)
    Loading from cache

  - Installing aimeos/ai-laravel (2016.07.2)
    Loading from cache

  - Installing aimeos/ai-gettext (2016.07.2)
    Loading from cache

  - Installing aimeos/ai-swiftmailer (2016.07.2)
    Loading from cache

  - Installing aimeos/aimeos-laravel (2016.07.2)
    Loading from cache

aimeos/aimeos-core suggests installing apigen/apigen (Required for generating the API documentation)
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "AimeosUsersTable" was found in both "$baseDir . '/database/migrations/2015_03_06_000000_aimeos_users_table.php" and "/Applications/MAMP/htdocs/Elietech_v2.0.0/vendor/aimeos/aimeos-laravel/src/database/migrations/2015_03_06_000000_aimeos_users_table.php", the first will be used.
Warning: Ambiguous class resolution, "AimeosUsersLabel" was found in both "$baseDir . '/database/migrations/2015_08_10_000000_aimeos_users_label.php" and "/Applications/MAMP/htdocs/Elietech_v2.0.0/vendor/aimeos/aimeos-laravel/src/database/migrations/2015_08_10_000000_aimeos_users_label.php", the first will be used.
> php artisan vendor:publish --tag=public --force
Nothing to publish for tag [public].
> php artisan vendor:publish

Copied Directory [/vendor/uxweb/sweet-alert/src/views] To [/resources/views/vendor/sweet]
Copied Directory [/vendor/spatie/laravel-paginateroute/resources/lang] To [/resources/lang/vendor/paginateroute]
Copied Directory [/vendor/rtconner/laravel-tagging/migrations] To [/database/migrations]
Copied Directory [/vendor/yajra/laravel-datatables-oracle/src/resources/views] To [/resources/views/vendor/datatables]
Publishing complete for tag []!
> php artisan migrate
Nothing to migrate.
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
```

**running migrate:rollback**
```
Rolled back: 2016_08_12_012844_create_activity_log_table
Rolled back: 2016_08_12_004524_create_media_table
Rolled back: 2016_08_11_215506_entrust_setup_tables
Rolled back: 2015_08_10_000000_aimeos_users_label
Rolled back: 2015_03_06_000000_aimeos_users_table
Rolled back: 2014_10_12_100000_create_password_resets_table
Rolled back: 2014_10_12_000000_create_users_table
Rolled back: 2014_01_07_073615_create_tags_table
Rolled back: 2014_01_07_073615_create_tagged_table
Migrated: 2014_01_07_073615_create_tagged_table
Migrated: 2014_01_07_073615_create_tags_table
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_03_06_000000_aimeos_users_table
Migrated: 2015_08_10_000000_aimeos_users_label
Migrated: 2016_08_11_215506_entrust_setup_tables
Migrated: 2016_08_12_004524_create_media_table
Migrated: 2016_08_12_012844_create_activity_log_table
```

**Comment by aimeos** [comment]
The migrations are (in principle) OK. Which Laravel version are you using?

It seems that the `name` column is missing in the `users` table which is a standard column normally created by Laravel. Can you drop your database and start from scratch? The `2014_10_12_000000_create_users_table` migration task should create the `users` table first including the `name` column.

**Comment by Mylo-92** [comment]
Using Laravel version : 5.2.43, yeah dropping and resetting the database seems to have resolved the issue. However, I also made sure it was the first package pulled in by composer. Nonetheless, when I try to visit the route :```/admin``` or rather, in my case: ```http://localhost/xxx/public/admin``` which redirects to: ```http://localhost/xxx/public/login```, since I am not authenticated. Moving on, once authenticated: ```http://localhost/xxx/public/jqadm/search/dashboard?lang=en&site=default``` which results in a: ```HttpException in Handler.php line 107:This action is unauthorized```. Does this require me to setup my own e.g user-role-permissions structure via acl lists/gates/policies?

**Comment by aimeos** [comment]
Aimeos uses the default Laravel authentication infrastructure including the Laravel Auth trait and I'm unsure how Entrust plays together with Laravel Auth.

**Comment by Mylo-92** [comment]
Ok let's for get that for a second, it's easy and well implemented,anyway...should this route: ```http://localhost/xxx/public/jqadm/search/dashboard?lang=en&site=default``` result in **HttpException in Handler.php line 107:This action is unauthorized** on initial setup? Or should I setup user-role-permissions via laravel's acl/policy object try and plugin entrust for it to work?

Regards,

**Comment by aimeos** [comment]
If you setup the Aimeos Laravel package like described in the readme, authentication should work as expected including the admin interface. But make sure that the public directory is the document root!

**Comment by robschuh** [comment]
Hello guys, I have exactly the same error.
```
Warning: Ambiguous class resolution, "AimeosUsersTable" was found in both "$baseDir . '/database/migrations/2015_03_06_000000_aimeos_users_table.php" and "/var/www/html/site/vendor/aimeos/aimeos-laravel/src/database/migrations/2015_03_06_000000_aimeos_users_table.php", the first will be used.
Warning: Ambiguous class resolution, "AimeosUsersLabel" was found in both "$baseDir . '/database/migrations/2015_08_10_000000_aimeos_users_label.php" and "/var/www/html/site/vendor/aimeos/aimeos-laravel/src/database/migrations/2015_08_10_000000_aimeos_users_label.php", the first will be used.
```

I follow step by step the GitHub repo instructions https://github.com/aimeos/aimeos-laravel#setup
I am using the last Laravel version 5.3, maybe this is the problem?. Cheers!

**Comment by aimeos** [comment]
The warnings are not problematic. The migration tasks are referenced twice in composer because otherwise, they may not be available the first time.

We don't have much experience with Laravel 5.3 yet besides that the unittests are working fine.

What it your problem? Is the authentication not working?
