### ISSUE TITLE
Price codes

### ISSUE THREAD

**Issue by bruno-rodrigues** [aimeos/aimeos-laravel#65]
Hello again,

I am trying to change the price format to R$ 99,00.

```
 'i18n' => array(
        'pt' => array(
            'client/code' => array(
                'price:default' => array('%2$s %1$s')
            )
        )
    ),
```
Adding this to config/shop changed the price to R$ 99.00 (with dot) in the /list and in /detail.
In the basket the price is still formated as 99.00 R$.

How can I change the price in mini-basket and basket pages? How can I change the decimal separator to comma instead of dot?

Have a nice day!

**Comment by aimeos** [comment]
You can change the number format with these configurations:
- client/html/common/format/seperatorDecimal
- client/html/common/format/seperator1000

**Comment by bruno-rodrigues** [comment]
Thank you.
And what about the currency symbol position in basket?

**Comment by aimeos** [comment]
That is depending on the translation you've changed. Please keep in mind that the content of the mini basket is cached in the session of the user/browser, so you will only see changes there if you e.g. add a product.

**Comment by bruno-rodrigues** [comment]
> Please keep in mind that the content of the mini basket is cached in the session of the user/browser, so you will only see changes there if you e.g. add a product.

Even if I am setting the the cache manager to 'None'?

```
'client' => array(
		'html' => array(
			'common' => array(
				'content' => array(
					// 'baseurl' => '/',
				),
				'template' => array(
					// 'baseurl' => 'packages/aimeos/shop/elegance',
				),
                'format' => array(
                    'separatorDecimal' => ',',
                    'separator1000' => '.'
                )
			),
		),
	),
```

Makes no difference in any price. :(

Changing `Base/View.php` works, but I know that I should not update core files...
```
$sepDec = $config->get( 'client/html/common/format/seperatorDecimal', ',' );
$sep1000 = $config->get( 'client/html/common/format/seperator1000', '.' );
```

**Comment by bruno-rodrigues** [comment]
Just figured out that I was writing `separator` instead of `seperator` even PHPStorm is saying that there is a typo in word `seperator`. But this problem is now solved. 

I just need to find out how to fix currency symbol in basket page.

**Comment by aimeos** [comment]
Indeed, the setting contains a typo and is wrongly spelled. We can't change that at the moment because we need to keep it for backward compatibility. We will fix it in the first major version next year.

**Comment by aimeos** [comment]
Regarding translation: You need to change the translation in Transifex to "%2$s %1$s" for all prices related strings, so the currency symbol is first

**Comment by bruno-rodrigues** [comment]
Ohhh NOW I see ;D. Thank you again!!!

**Comment by bruno-rodrigues** [comment]
Just fixed it in Transifex, please add the changes to new commit on dev-master branch ;)

**Comment by aimeos** [comment]
done
