### ISSUE TITLE
Add payment gateway

### ISSUE THREAD

**Issue by bruno-rodrigues** [aimeos/aimeos-laravel#67]
Hi,

I need to add [Pagseguro](http://pagseguro.uol.com.br) and "Pay in physical store" as the only payment options.

I've read a LOT on aimeos docs, but the process to add a new payment isn't crystal clear to me.

I've already add the contents of the downloaded .zip file created by extension builder but I really don't know what are the next steps. Can you give me a hint on this?

Btw, I am very satisfied with your fast and awesome support for newcomers! :D

**Comment by aimeos** [comment]
Thanks :-)

You need to add the Aimeos aimeos/ai-payments extension to your composer.json file and the Omnipay driver: https://github.com/abdala/omnipay-pagseguro

If you need more information, please open a topic in the Aimeos forum.
