### ISSUE TITLE
Error Output: cp: cannot stat ‘ext

### ISSUE THREAD

**Issue by knoonrx** [aimeos/aimeos-laravel#7]
cp -r ext/*/client/extjs/deploy/* public/packages/aimeos/shop/client/extjs/deploy/
cp: cannot stat ‘ext/*/client/extjs/deploy/*’: No such file or directory
Script cp -r ext/*/client/extjs/deploy/* public/packages/aimeos/shop/client/extjs/deploy/ handling the post-update-cmd event returned with an error

                                                                                          
  [RuntimeException]                                                                      
  Error Output: cp: cannot stat ‘ext/*/client/extjs/deploy/*’: No such file or directory

**Comment by aimeos** [comment]
Sorry, the "copy" line doesn't work if no extensions are installed. Please remove the line from your composer.json file and try again. Then it should work.

**Comment by knoonrx** [comment]
Thank you it's work now
