### ISSUE TITLE
DoExpressCheckoutPayment is not being sent to Paypal

### ISSUE THREAD

**Issue by arthurtarasov** [aimeos/aimeos-laravel#70]
Hello, 
I am trying to set up PayPal Express service for my Aimeos Laravel store. I ran into an issue when transactions fail on PayPal's website with an error:

> This transaction is invalid. Please return to the recipient's website to complete your transaction using their regular checkout flow.

I contacted PayPal's support and they told me the 2nd API request (DoExpressCheckoutPayment) was not happening. Here is a full response I received from PayPal's support:

> Hi ******,
>  
> Looking at the server log again, I can see that your application sent the 1st API request that sets up the payment. (SetExpressCheckoutRequest)
>  
> Generally at this point the buyer is redirected to a PayPal login page, where they either log in to approve the payment, or choose to pay with a credit card if they don't have a PayPal account.
>  
> In either event the buyer would click a Pay, or Continue button and a 2nd API request is sent to PayPal to complete the payment. The 2nd API request is not happening. (DoExpressCheckoutPayment)
>  
> I've looked at the setup instructions for Express Checkout in your application and it seems pretty straight forward. Based on their documentation you've done everything you are supposed to do, and correctly, because I can now see your communication with the server.
>  
> You should contact the application vendor at this point to find out why the final payment request is not being sent.
>  
> Respectfully,
>  
> ******
>  
> PayPal Merchant Technical Services

The PayPal URL I am using in settings is:
`https://www.paypal.com/webscr?cmd=_express-checkout&useraction=commit&token=tokenValue`
and the endpoint:
`https://api-3t.paypal.com/nvp`

I have no idea whether this is an error on my side or some sort of a bug. I am hoping it is the former. Please advise me on the matter.

Kindly,
Arthur

**Comment by aimeos** [comment]
It there something in the Aimeos madmin_log table that is related to PayPal or the payment?

**Comment by arthurtarasov** [comment]
Nope, it does not create any log entries when this error occurs

**Comment by aimeos** [comment]
OK, then you should add some `error_log()` statements to the code and see what's executed or not and why this happens.

**Comment by arthurtarasov** [comment]
I figured it out. The problem was that my PayPal URL was wrong. This is what it should be for a live website:

`https://www.paypal.com/webscr&cmd=_express-checkout&useraction=commit&token=%1$s`

I copied it from the default value of `paypalexpress.PaypalUrl` from 
`..myprojectfolder\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Service\Provider\Payment\PayPalExpress.php`

Leaving the field empty didn't work either.

**Comment by aimeos** [comment]
Leaving the field empty results in an empty value instead of the default value. If you remove `paypalexpress.PaypalUrl` completely, the default URL will be used.
