### ISSUE TITLE
how to login aimeos backend 

### ISSUE THREAD

**Issue by phper01** [aimeos/aimeos-laravel#71]
for this document: request  xxx/list  is true ,but xxx/admin isn't show dashboard,only a admin/index.blade.php .could i do it?  thanks

**Comment by nos3** [comment]
Did you follow the setup guide for /admin?
https://github.com/aimeos/aimeos-laravel#admin

**Comment by aimeos** [comment]
https://github.com/aimeos/aimeos-laravel#admin
