### ISSUE TITLE
Question: No item found for conditions: Array... when setting up admin

### ISSUE THREAD

**Issue by DanJFletcher** [aimeos/aimeos-laravel#73]
I'm on the last steps of set up.

In Laravel 5.2 I ran `php artisan make:auth` according to the documentation.

I then ran `php artisan aimeos:account test@example.com --admin`

I enter a password, and get the message 
```
Add "admin" group to user "test@example.com" for sites
- default
```

And then I get this error in my command line:
```
 [Aimeos\MShop\Exception]                            
  No item found for conditions: Array                 
  (                                                   
      [customer.lists.type.code] => default           
      [customer.lists.type.domain] => customer/group  
  )
```                                                
If I try visiting `index.php/admin` I'm redirected to the default login view set from `make:auth` and I can log in as the test user, however I don't have access to the admin dashboard. I'm just a regular user.

I'm at a loss because I just don't know how to interpret the error.

Thanks in advance for any help or direction.

**Comment by aimeos** [comment]
Can you rerun `./artisan aimeos:setup`?
There seems to be a type record missing

**Comment by DanJFletcher** [comment]
Yep that did it - thank you!

**Comment by huseyinerbayat** [comment]
an error, after run command "./artisan aimeos:setup"
![error](https://cloud.githubusercontent.com/assets/9267964/18567118/6771b4ce-7b9f-11e6-9f06-261cb2d1e496.png)

[Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

**Comment by aimeos** [comment]
Can you try the dev-master branch? I think there's already a fix for this problem included.

**Comment by meletisf** [comment]
I faced this error and that's how i solved it:
Firstly, Aimeos tries to fetch the current site locale based on the domain name you are currently using. If you serve using artisan than it will work just fine but when you deploy it using a domain it brakes down because it cannot recognise your domain.

Just open the database using your favourite edit and in the table `_locale_site` replace `default` with your domain both in `code` and `label`

**Comment by aimeos** [comment]
@meletisf You can also change the site code/label in the Configuration > Settings panel of the Aimeos admin backend.

**Comment by meletisf** [comment]
@aimeos in my case the admin panel was inaccessible too and there was no way to update the values using the UI.
