### ISSUE TITLE
Aimeos Frontend siteid Problem

### ISSUE THREAD

**Issue by wassimhattab** [aimeos/aimeos-laravel#74]
Hello,
i'm facing a problem using aimeos in the frontent becuas its by default siteid 1, and he cannot buy things from different siteid.
I created a new site other than the default one and i add new products to it.
I fixed in the frontend to show all the items from different siteid, but when i add a product from diferent siteid than 1 i got this error message 'Adding product with ID "#id" is not allowed'

how can i fix this problem and let the user to add to basket items from different siteid?

**Comment by aimeos** [comment]
"Not allowed" means that the product is not in a category

**Comment by wassimhattab** [comment]
And how can i change the default siteid in the frontend because when i order many items from different siteid they all enter in the order database as siteid 1 and the other admin for the different store wont be able to see the order

**Comment by aimeos** [comment]
The standard Aimeos core code can't distribute the order to the different sites which the products come from. You can add a new page in the simplified admin interface which shows only the ordered products from the default site for the current site.
As alternative, the Aimeos company (https://aimeos.com) has an extension for market places as far as I know. Maybe this is what you are looking for.

If you create backend users with `./artisan aimeos:account --editor me@localhost` they only have access to their own site.
