### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by massivebrains** [aimeos/aimeos-laravel#75]
After successfully installing the package. pointing my browser to localhost:8000/list generates this exception as illustrated below
![issues](https://cloud.githubusercontent.com/assets/12751582/19604766/97289c7a-97ae-11e6-8dc2-8a56fa9b1b21.png)

What am i doing wrong?

**Comment by GalinaBublik** [comment]
Hello. Update aimeos  to 2016.10.3 version - my conposer.json http://take.ms/ASqJo.
Cleared cache.
But still have this error(

**Comment by aimeos** [comment]
Please use `"aimeos/aimeos-laravel": "~2016.10"` and not a fixed version.
Is the status in the `mshop_locale` table also "1"?
Can you post your exception?

**Comment by GalinaBublik** [comment]
i fixed this issue - copied data from backup - half of database was empty.
I setup laravel, then sleeping owl admin, add roles, then aimeos.
after  php artisan aimeos:setup --option=setup/default/demo:1
"[Aimeos\MW\DB\Exception]
  Executing statement "ALTER TABLE madmin_cache_tag ADD CONSTRAINT fk_macac_tid_tsid FOREIGN KEY (tid, tsiteid) REFERENCES madmin_cache (id, siteid) ON UPDATE CASCADE
  ON DELETE CASCADE" failed: An exception occurred while executing 'ALTER TABLE madmin_cache_tag ADD CONSTRAINT fk_macac_tid_tsid FOREIGN KEY (tid, tsiteid) REFERENCES
   madmin_cache (id, siteid) ON UPDATE CASCADE ON DELETE CASCADE':
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("laravel"."#sql-ea8_144", CONSTRAINT "fk_maca
  c_tid_tsid" FOREIGN KEY ("tid", "tsiteid") REFERENCES "madmin_cache" ("id", "siteid") ON DELETE CASCADE ON UPDATE CASCADE)"
```

**Comment by aimeos** [comment]
Can you do the setup the other way round? Install Laravel, than Aimeos, check if Aimeos works correctly and then sleeping owl admin?

**Comment by GalinaBublik** [comment]
Yes, doing it now
