### ISSUE TITLE
sql issue

### ISSUE THREAD

**Issue by SnehalSatardekar** [aimeos/aimeos-laravel#76]
while installing aimeos and running "php artisan aimeos:setup --option=setup/default/demo:1" command I am getting below issue:

Executing statement "SET NAMES 'utf8'" failed: An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user

I am using postgresql data.

Please revert me on this.

Waiting for the response

**Comment by aimeos** [comment]
For PostgreSQL, you need to reset the specific statements in the resource configuration that are required for MySQL:
```
'resource' => array(
	'db' => array(
		// ...
		'stmt' => array(),
		// ...
	),
),
```

**Comment by aimeos** [comment]
Also make sure that your .env file contains the correct database settings

**Comment by SnehalSatardekar** [comment]
i have changed shop.php with 'stmt' => array() and sone changes in .env also

still getting following error,
[Aimeos\MW\DB\Exception]                                                                                                                    
  Executing statement "SET NAMES 'utf8'" failed: An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user '<postgres_user>'@'<postgres_host>' (using password: YES)

**Comment by aimeos** [comment]
Can you post your `./config/shop.php` (without passwords)?

**Comment by SnehalSatardekar** [comment]
<?php

return array(

	'routes' => array(
        'login' => array(),
        'admin' => array('middleware' => array('auth')),
        'account' => array('middleware' => array('auth')),
        'default' => array(),
        'confirm' => array(),
        'update' => array(),
    ),

	'page' => array(
		// 'account-index' => array( 'account/profile','account/history','account/favorite','account/watch','basket/mini','catalog/session' ),
		// 'basket-index' => array( 'basket/standard','basket/related' ),
		// 'catalog-count' => array( 'catalog/count' ),
		// 'catalog-detail' => array( 'basket/mini','catalog/stage','catalog/detail','catalog/session' ),
		// 'catalog-list' => array( 'basket/mini','catalog/filter','catalog/stage','catalog/lists' ),
		// 'catalog-stock' => array( 'catalog/stock' ),
		// 'catalog-suggest' => array( 'catalog/suggest' ),
		// 'checkout-confirm' => array( 'checkout/confirm' ),
		// 'checkout-index' => array( 'checkout/standard' ),
		// 'checkout-update' => array( 'checkout/update'),
	),

	'resource' => array(
		'db' => array(
			// 'adapter' => env('DB_CONNECTION', 'mysql'),
			// 'host' => env('DB_HOST', 'localhost'),
			// 'port' => env('DB_PORT', ''),
			// 'socket' => '',
			// 'database' => env('DB_DATABASE', 'laravel'),
			// 'username' => env('DB_USERNAME', 'root'),
			// 'password' => env('DB_PASSWORD', ''),
			'adapter' => 'pgsql',
			'host' => 'xxxxxx',
			'database' => 'xxxxxxxxx',
			'username' => 'xxxxxxx',
			'password' => 'xxxxxxx',
			'stmt' => array(),
		),
	),


	'admin' => array(),

	'client' => array(
		'html' => array(
			'common' => array(
				'content' => array(
					// 'baseurl' => '/',
				),
				'template' => array(
					// 'baseurl' => 'packages/aimeos/shop/themes/elegance',
				),
			),
		),
	),

	'controller' => array(
	),

	'i18n' => array(
	),

	'madmin' => array(
	),

	'mshop' => array(
	),


	'frontend' => array(
		'admin' => array(),
		'client' => array(),
		'controller' => array(),
		'i18n' => array(),
		'madmin' => array(),
		'mshop' => array(),
	),

	'backend' => array(
		'admin' => array(),
		'client' => array(),
		'controller' => array(),
		'i18n' => array(),
		'madmin' => array(),
		'mshop' => array(),
	),
);

**Comment by aimeos** [comment]
The used array_replace_recursive() which combines two config files causes the problem here.
If you use `'stmt' => null` instead of `'stmt' => array()`, the "stmt" configuration is gone.

**Comment by aimeos** [comment]
You also have to reset the configuration for the index manager:
```
	'mshop' => array(
		'index' => array(
			'manager' => array(
				'name' => 'PgSQL',
				'attribute' => null,
				'catalog' => null,
				'price' => null,
				'text' => array(
					'name' => 'PgSQL',
				),
			),
		),
	),
```

**Comment by SnehalSatardekar** [comment]
getting this error now

[Aimeos\MW\DB\Exception]                                                                                                                    
  Executing statement "                                                                                                                       
  			SELECT mcatli."id" AS "catalog.lists.id", mcatli."parentid" AS "catalog.lists.parentid",                                                 
  				mcatli."siteid" AS "catalog.lists.siteid", mcatli."typeid" AS "catalog.lists.typeid",                                                   
  				mcatli."domain" AS "catalog.lists.domain", mcatli."refid" AS "catalog.lists.refid",                                                     
  				mcatli."start" AS "catalog.lists.datestart", mcatli."end" AS "catalog.lists.dateend",                                                   
  				mcatli."config" AS "catalog.lists.config", mcatli."pos" AS "catalog.lists.position",                                                    
  				mcatli."status" AS "catalog.lists.status", mcatli."mtime" AS "catalog.lists.mtime",                                                     
  				mcatli."editor" AS "catalog.lists.editor", mcatli."ctime" AS "catalog.lists.ctime"                                                      
  			FROM "mshop_catalog_list" AS mcatli                                                                                                      
  			                                                                                                                                         
  			WHERE ( mcatli."siteid" IN (1) AND ( mcatli."refid" IN ('1','4','5') AND mcatli."domain" = 'product' AND ( mcatli."status" = 1 AND ( mc  
  atli."start" <= '2016-10-25 11:19:00' OR mcatli."start" IS NULL ) AND ( mcatli."end" >= '2016-10-25 11:19:00' OR mcatli."end" IS NULL ) )   
  ) )                                                                                                                                         
  			GROUP BY mcatli."id", mcatli."parentid", mcatli."siteid", mcatli."typeid",                                                               
  				mcatli."domain", mcatli."refid", mcatli."start", mcatli."end",                                                                          
  				mcatli."config", mcatli."pos", mcatli."status", mcatli."mtime",                                                                         
  				mcatli."editor", mcatli."ctime"                                                                                                         
  			                                                                                                                                         
  			LIMIT 2147483647 OFFSET 0                                                                                                                
  		" failed: An exception occurred while executing '                                                                                         
  			SELECT mcatli."id" AS "catalog.lists.id", mcatli."parentid" AS "catalog.lists.parentid",                                                 
  				mcatli."siteid" AS "catalog.lists.siteid", mcatli."typeid" AS "catalog.lists.typeid",                                                   
  				mcatli."domain" AS "catalog.lists.domain", mcatli."refid" AS "catalog.lists.refid",                                                     
  				mcatli."start" AS "catalog.lists.datestart", mcatli."end" AS "catalog.lists.dateend",                                                   
  				mcatli."config" AS "catalog.lists.config", mcatli."pos" AS "catalog.lists.position",                                                    
  				mcatli."status" AS "catalog.lists.status", mcatli."mtime" AS "catalog.lists.mtime",                                                     
  				mcatli."editor" AS "catalog.lists.editor", mcatli."ctime" AS "catalog.lists.ctime"                                                      
  			FROM "mshop_catalog_list" AS mcatli                                                                                                      
  			                                                                                                                                         
  			WHERE ( mcatli."siteid" IN (1) AND ( mcatli."refid" IN ('1','4','5') AND mcatli."domain" = 'product' AND ( mcatli."status" = 1 AND ( mc  
  atli."start" <= '2016-10-25 11:19:00' OR mcatli."start" IS NULL ) AND ( mcatli."end" >= '2016-10-25 11:19:00' OR mcatli."end" IS NULL ) )   
  ) )                                                                                                                                         
  			GROUP BY mcatli."id", mcatli."parentid", mcatli."siteid", mcatli."typeid",                                                               
  				mcatli."domain", mcatli."refid", mcatli."start", mcatli."end",                                                                          
  				mcatli."config", mcatli."pos", mcatli."status", mcatli."mtime",                                                                         
  				mcatli."editor", mcatli."ctime"                                                                                                         
  			                                                                                                                                         
  			LIMIT 2147483647 OFFSET 0                                                                                                                
  		':                                                                                                                                        
  SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block

**Comment by aimeos** [comment]
Can you restart from an empty database and make sure that the index manager configuration is set like described? Did that happen when you execute `./artisan aimeos:setup`?

**Comment by aimeos** [comment]
Any news on this?

**Comment by Tidro** [comment]
edit shop.php, database.php to 'stmt' => null,
got same eror and when execute ./artisan aimeos:setup

**Comment by aimeos** [comment]
What's the error you've got? Can you post the SQL error message and the stack strace?

**Comment by Tidro** [comment]
[Aimeos\MW\DB\Exception]
  Executing statement "
                        SELECT mcatli."id" AS "catalog.lists.id", mcatli."parentid" AS "catalog.
  lists.parentid",
                                mcatli."siteid" AS "catalog.lists.siteid", mcatli."typeid" AS "catalog.
  lists.typeid",
                                mcatli."domain" AS "catalog.lists.domain", mcatli."refid" AS "catalog.l
  ists.refid",
                                mcatli."start" AS "catalog.lists.datestart", mcatli."end" AS "catalog.l
  ists.dateend",
                                mcatli."config" AS "catalog.lists.config", mcatli."pos" AS "catalog.lis
  ts.position",
                                mcatli."status" AS "catalog.lists.status", mcatli."mtime" AS "catalog.l
  ists.mtime",
                                mcatli."editor" AS "catalog.lists.editor", mcatli."ctime" AS "catalog.l
  ists.ctime"
                        FROM "mshop_catalog_list" AS mcatli                     
                                                                                
                        WHERE ( mcatli."siteid" IN (15) AND ( mcatli."refid" IN ('25','28','29')
   AND mcatli."domain" = 'product' AND ( mcatli."status" = 1 AND ( mcatli."st
  art" <= '2016-12-01 10:19:00' OR mcatli."start" IS NULL ) AND ( mcatli."end
  " >= '2016-12-01 10:19:00' OR mcatli."end" IS NULL ) ) ) )
                        GROUP BY mcatli."id", mcatli."parentid", mcatli."siteid", mcatli."typeid
  ",
                                mcatli."domain", mcatli."refid", mcatli."start", mcatli."end",
                                mcatli."config", mcatli."pos", mcatli."status", mcatli."mtime",
                                mcatli."editor", mcatli."ctime"                 
                                                                                
                        LIMIT 2147483647 OFFSET 0                               
                " failed: An exception occurred while executing '               
                        SELECT mcatli."id" AS "catalog.lists.id", mcatli."parentid" AS "catalog.
  lists.parentid",
                                mcatli."siteid" AS "catalog.lists.siteid", mcatli."typeid" AS "catalog.
  lists.typeid",
                                mcatli."domain" AS "catalog.lists.domain", mcatli."refid" AS "catalog.l
  ists.refid",
                                mcatli."start" AS "catalog.lists.datestart", mcatli."end" AS "catalog.l
  ists.dateend",
                                mcatli."config" AS "catalog.lists.config", mcatli."pos" AS "catalog.lis
  ts.position",
                                mcatli."status" AS "catalog.lists.status", mcatli."mtime" AS "catalog.l
  ists.mtime",
                                mcatli."editor" AS "catalog.lists.editor", mcatli."ctime" AS "catalog.l
  ists.ctime"
                        FROM "mshop_catalog_list" AS mcatli                     
                                                                                
                        WHERE ( mcatli."siteid" IN (15) AND ( mcatli."refid" IN ('25','28','29')
   AND mcatli."domain" = 'product' AND ( mcatli."status" = 1 AND ( mcatli."st
  art" <= '2016-12-01 10:19:00' OR mcatli."start" IS NULL ) AND ( mcatli."end
  " >= '2016-12-01 10:19:00' OR mcatli."end" IS NULL ) ) ) )
                        GROUP BY mcatli."id", mcatli."parentid", mcatli."siteid", mcatli."typeid
  ",
                                mcatli."domain", mcatli."refid", mcatli."start", mcatli."end",
                                mcatli."config", mcatli."pos", mcatli."status", mcatli."mtime",
                                mcatli."editor", mcatli."ctime"                 
                                                                                
                        LIMIT 2147483647 OFFSET 0                               
                ':                                                              
  SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction i
  s aborted, commands ignored until end of transaction block

**Comment by Tidro** [comment]
execute without data is ok.

>php artisan vendor:publish
>php artisan migrate
>./artisan aimeos:setup
>php artisan aimeos:cache

**Comment by Tidro** [comment]
try to create category in admin (expert mode) got this
Executing statement "
SELECT mcatli."id" AS "catalog.lists.id", mcatli."parentid" AS "catalog.lists.parentid",
mcatli."siteid" AS "catalog.lists.siteid", mcatli."typeid" AS "catalog.lists.typeid",
mcatli."domain" AS "catalog.lists.domain", mcatli."refid" AS "catalog.lists.refid",
mcatli."start" AS "catalog.lists.datestart", mcatli."end" AS "catalog.lists.dateend",
mcatli."config" AS "catalog.lists.config", mcatli."pos" AS "catalog.lists.position",
mcatli."status" AS "catalog.lists.status", mcatli."mtime" AS "catalog.lists.mtime",
mcatli."editor" AS "catalog.lists.editor", mcatli."ctime" AS "catalog.lists.ctime"
FROM "mshop_catalog_list" AS mcatli

WHERE ( mcatli."siteid" IN (1) AND ( mcatli."refid" IN ('1','2') AND mcatli."domain" = 'product' AND ( mcatli."status" = 1 AND ( mcatli."start" <= '2016-12-01 11:00:00' OR mcatli."start" IS NULL ) AND ( mcatli."end" >= '2016-12-01 11:00:00' OR mcatli."end" IS NULL ) ) ) )
GROUP BY mcatli."id", mcatli."parentid", mcatli."siteid", mcatli."typeid",
mcatli."domain", mcatli."refid", mcatli."start", mcatli."end",
mcatli."config", mcatli."pos", mcatli."status", mcatli."mtime",
mcatli."editor", mcatli."ctime" 

LIMIT 2147483647 OFFSET 0
" failed: An exception occurred while executing '
SELECT mcatli."id" AS "catalog.lists.id", mcatli."parentid" AS "catalog.lists.parentid",
mcatli."siteid" AS "catalog.lists.siteid", mcatli."typeid" AS "catalog.lists.typeid",
mcatli."domain" AS "catalog.lists.domain", mcatli."refid" AS "catalog.lists.refid",
mcatli."start" AS "catalog.lists.datestart", mcatli."end" AS "catalog.lists.dateend",
mcatli."config" AS "catalog.lists.config", mcatli."pos" AS "catalog.lists.position",
mcatli."status" AS "catalog.lists.status", mcatli."mtime" AS "catalog.lists.mtime",
mcatli."editor" AS "catalog.lists.editor", mcatli."ctime" AS "catalog.lists.ctime"
FROM "mshop_catalog_list" AS mcatli

WHERE ( mcatli."siteid" IN (1) AND ( mcatli."refid" IN ('1','2') AND mcatli."domain" = 'product' AND ( mcatli."status" = 1 AND ( mcatli."start" <= '2016-12-01 11:00:00' OR mcatli."start" IS NULL ) AND ( mcatli."end" >= '2016-12-01 11:00:00' OR mcatli."end" IS NULL ) ) ) )
GROUP BY mcatli."id", mcatli."parentid", mcatli."siteid", mcatli."typeid",
mcatli."domain", mcatli."refid", mcatli."start", mcatli."end",
mcatli."config", mcatli."pos", mcatli."status", mcatli."mtime",
mcatli."editor", mcatli."ctime" 

LIMIT 2147483647 OFFSET 0
':

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

**Comment by aimeos** [comment]
Can you execute this statement in the psql console by hand and remove parts of the statement until it works so we can see where it fails?

The PostgreSQL 9.5.5 installed by Ubuntu 16.04 seems to work fine.

**Comment by Tidro** [comment]
i forgot to uninstall PostgreSQL 9.3 before install 9.6.1, i will reinstall system now

**Comment by aimeos** [comment]
Only PostgreSQL >= 9.5 is supported. Versions before don't support ON CONFLICT DO NOTHING required during index rebuild

**Comment by Tidro** [comment]
it was PostgreSQL 9.3 error.
Tested with ubuntu 14.04 php7.0 PostgreSQL 9.6.1 using this fix https://github.com/aimeos/aimeos-laravel/issues/76#issuecomment-264121182

**Comment by aimeos** [comment]
Documented in https://aimeos.org/docs/Developers/Library/Database_support
