### ISSUE TITLE
Composer Issue

### ISSUE THREAD

**Issue by bobper** [aimeos/aimeos-laravel#77]
Hi 
Os : Windows 10
Server  : Localhost with Xamp server 
Framework : Laravel ( Ok) 
I edit my composer File then i Run composer Update : 

[32mLoading composer repositories with package information[39m
[30;43mThe "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: An attempt was made to access a socket in a way forbidden by its access permissions.
[39;49m
[30;43mhttps://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date[39;49m
[32mUpdating dependencies (including require-dev)[39m

[37;41m                                                                                                               [39;49m
[37;41m  [Composer\Downloader\TransportException]                                                                     [39;49m
[37;41m  The "http://packagist.org/p/aimeos/aimeos-laravel%24f501b31eadf0ee4e4dd81ae08f395e91b35e0b71bb97133d9b4f2f9  [39;49m
[37;41m  102cad345.json" file could not be downloaded: failed to open stream: An attempt was made to access a socket  [39;49m
[37;41m   in a way forbidden by its access permissions.                                                               [39;49m
[37;41m                                                                                                               [39;49m

[32mupdate [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [[39m[32m<packages>[39m[32m]...[39

**Comment by aimeos** [comment]
Seems like a temporary issue on packagist.org. Running `composer update` on a Laravel 5.3 test installation has worked fine. Can you run `composer update` again please?
