### ISSUE TITLE
Is there an easy way to disable unused modules in the application to make it suitable for a simple application ?

### ISSUE THREAD

**Issue by Hazemwd** [aimeos/aimeos-laravel#78]
I'm trying to use this package for a simple e-commerce application which contains only categories and products, prices, offers, no payment included, ability to upload an attachment while ordering an item.

I find this package is a bit complex to use for the application I described above, so how can I disable unused modules in this package to improve the performance ?

Thanks

**Comment by aimeos** [comment]
Performance shouldn't be a problem at all if you've read https://aimeos.org/docs/Laravel/Optimize_performance

If you don't need certain components, you can remove the others from your templates (resources/views/vendor/shop/) and disable them in the config file:
https://github.com/aimeos/aimeos-laravel/blob/master/src/config/shop.php#L14

To remove unneeded steps from the checkout, please read these articles:
https://aimeos.org/docs/Configuration/Core/client/html#Checkout

**Comment by Hazemwd** [comment]
Great!
This enhanced the performance!
I'm exploring the rest, but I'm just wondering why can't I add a product category from the simple view mode ?
I hope I could add products and categories from the simple view as these are the most common activities taken by the admins.

**Comment by aimeos** [comment]
We are working on a panel for managing categories in the simple admin interface. Probably the next major version will contain one.
