### ISSUE TITLE
Files for styling page is all over the place

### ISSUE THREAD

**Issue by manfordbenjamin** [aimeos/aimeos-laravel#79]
Please make it easier. I can barely find and alter the navigation bar!

**Comment by aimeos** [comment]
The navigation bar is in the app.blade.php file you've created during setup. This is a Laravel convention which we can't make easier. What we've already done is to radically simplify the Aimeos templates in the dev-master branch: https://github.com/aimeos/ai-client-html/tree/master/client/html/templates

**Comment by manfordbenjamin** [comment]
Right but in there I want to modify the partial included in this block

```
<div class="navbar-right">
   @yield('aimeos_head')
</div>
```

**Comment by aimeos** [comment]
This depends on the page you are:
https://github.com/aimeos/aimeos-laravel/tree/master/src/views/catalog

What do you want to change exactly?

**Comment by manfordbenjamin** [comment]
I want to add another list with a condition that displays the name of the user that's currently logged in. 

```
@if (Auth::guest())
    <li><a href="{{ route('login') }}">Login</a></li>
    <li><a href="{{ route('register') }}">Register</a></li>
@else
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            {{ Auth::user()->name }} <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="{{ url('/logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                    Logout
                </a>
                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
    </li>
@endif
```

**Comment by aimeos** [comment]
Simply add this inside the "navbar" section of your app.blade.php template you've created for your application

**Comment by manfordbenjamin** [comment]
Thanks but I didn't work. The list displays with bullet points beneath the cart. How are you rendering the cart if I may ask?

**Comment by aimeos** [comment]
It depends where you add your code and on your CSS styling

**Comment by manfordbenjamin** [comment]
Alright. Will try that and get back to you
