### ISSUE TITLE
Installation Problem in Composer Update

### ISSUE THREAD

**Issue by QadeerAhmad19** [aimeos/aimeos-laravel#82]
Hi there i have issue while installing aimeos on local laravel 5 repo.i just added 
"aimeos/aimeos-laravel": "~2016.04" in composer.json but i show 
i need solution..any help.
Waiting for relpy...
![2016-12-19_2313](https://cloud.githubusercontent.com/assets/24417874/21323802/ecef783e-c640-11e6-8a5f-3edb73c5a62c.png)

**Comment by aimeos** [comment]
You need at least Laravel 5.1.11 for Aimeos as this is the first version that supports authentication.

**Comment by QadeerAhmad19** [comment]
yeah you are right..
But when upgraded laravel 5 to 5.1 there is still issues...
 [ErrorException]
  file_put_contents(C:\xampp\htdocs\fitkitstech\portal/bootstrap/cache/services.json): failed to open stream: No such file or directory

**Comment by aimeos** [comment]
That's a Laravel issue. Maybe the experts in the Laravel forums know what's the problem
