### ISSUE TITLE
After /list show exception

### ISSUE THREAD

**Issue by QadeerAhmad19** [aimeos/aimeos-laravel#83]
Invalid locale "1"
Some solution..?

**Comment by aimeos** [comment]
Which Laravel and Aimeos versions do you use?

**Comment by QadeerAhmad19** [comment]
I am using laravel 5.1 and Aimeos 2016:10 or :04  i used both ...

**Comment by aimeos** [comment]
Seems like your route contain a (maybe optional) parameter that is interpreted as Aimeos site. Optional parameter handling in Laravel is still buggy and leads to such exceptions.
