### ISSUE TITLE
image upload failed

### ISSUE THREAD

**Issue by aouliet** [aimeos/aimeos-laravel#84]
hi !
I can't add image to new product using an admin account.
> Could not upload file, please contact your administrator.

**Comment by aimeos** [comment]
Please make sure that the `public/packages/aimeos/shop/` directory and its subdirectories are writable by the web server. You may find more information about the problem in the `madmin_log` table.

**Comment by aouliet** [comment]
Still the same error, public/packages/aimeos/shop/ directory and its subdirectories are writable , and there is no mention of this error in madmin_log

**Comment by aimeos** [comment]
Can you please open the browser console (network tab) and post the response from the server for this request?

**Comment by mgwebgroup** [comment]
I have the same issue. Using aimeos symfony edition v2010.10. The browser log shows requested image URL as: "http://127.0.0.1:8000/.preview/9/8/980dd8c75777df8ebf5fb24f6c182c04.jpg". 
There is a "dot" at the beginning of the image path, seems would be the cause for this error. How to get rid of it?

**Comment by developerpratika** [comment]
i am getting this error
`{"error":{"code":-1,"message":"Couldn't delete file \"\""},"status":"failure"}`

**Comment by aimeos** [comment]
You are getting this error in the expert mode? Which version do you use?

**Comment by developerpratika** [comment]
yes 
i am using  "aimeos/aimeos-laravel": "2017.01.*"

**Comment by aimeos** [comment]
Fixed by https://github.com/aimeos/aimeos-core/commit/02237c0886012a19bcd19e7fb5feb1d83ba73436
