### ISSUE TITLE
Can Aimeos be used as a backend for native IOS and Android Apps?

### ISSUE THREAD

**Issue by arjun2503** [aimeos/aimeos-laravel#85]
Hey Guys

I am trying to figure out this framework for my upcoming android and ios apps. I was looking for a robust backend which can fetch me products, cart and create orders through REST  @APIs.

**Comment by aimeos** [comment]
Aimeos already has a JSON REST API for administration purpose and we are currently working on a design for the REST API for the frontend. We expect it to be available in the 2017.04 release. We are happy for any suggestions, so you can make sure it will fit your needs by contributing your expertise :-)

**Comment by aimeos** [comment]
Branch 2017.03 contains the new JSON REST API for the frontend. Catalog part is included, checkout part will follow

**Comment by aimeos** [comment]
The full Aimeos JSON REST API is available since version 2017.04 and documented here:
https://aimeos.org/docs/Developers/Client/JSONAPI
