### ISSUE TITLE
Sourcing products from members

### ISSUE THREAD

**Issue by bryceray1121** [aimeos/aimeos-laravel#86]
I'm trying to evaluate if aimeos would be suitable for running a store in which all products belong to individual users, in a similar way to the way etsy works.  From what I can tell this would require massive customization, can you confirm my evaluation?

**Comment by aimeos** [comment]
How does Etsy work resp. what are your key requirements?

If you want to create a market place, that's already possible and other developers have used Aimeos already for that purpose. Nevertheless, there will always be customizations necessary but Aimeos is designed to make that point possible easier than other packages.
