### ISSUE TITLE
WOW! > Custom Payment Gateway??

### ISSUE THREAD

**Issue by wyklif** [aimeos/aimeos-laravel#87]
I just Stumbled Across your package and all i can say is WOW!! but also is there a way for me to add a custom payment gateway? thanks

**Comment by aimeos** [comment]
Sure! The preferred way is to install the ai-payments extension and create an Omnipay driver if none for the payment gateway exists yet (https://github.com/thephpleague/omnipay). Alternatively, if you need a more sophisticated interface, you can implement an Aimeos payment service provider: https://aimeos.org/docs/Developers/Library/Service

**Comment by wyklif** [comment]
Thanks. in any case of issues can i feel free to revisit this issue? closing it for now

**Comment by aimeos** [comment]
You can also have a look into the forum and post there: https://aimeos.org/help/

**Comment by karneaud** [comment]
Just to hijack this post for a bit. i created a custom gateway using Omnipay library but for a previous laravel frameowkr. Is this all that is needed or do I now need to adjust it for Aimeos?

**Comment by aimeos** [comment]
As long as you've implemented your Omnipay driver according to the Omnipay specs (which are a bit lax in some areas), it should work with Aimeos too. Maybe you have to adapt a few minor things to make it totally compliant.
