### ISSUE TITLE
php artisan aimeos:setup and aimeos:cache failed

### ISSUE THREAD

**Issue by phil1996s** [aimeos/aimeos-laravel#88]
Hey everybody,

the php artisan commands "php artisan aimeos:setup"  and "php artisan aimeos:cache" failed.

This is the failure message:
  [Aimeos\MW\DB\Exception]                                                     
  Executing statement "SET NAMES 'utf8'" failed: An exception occured in driv  
  er: SQLSTATE[HY000] [2002] Connection refused  

The other commands work very well.

**Comment by aimeos** [comment]
Seems like your database credentials are not correct. Please check in your .env file or if they are correct there, try to add them directly to your config/shop.php file. The .env system isn't always reliable.

**Comment by publicarray** [comment]
I've got the same issue using sqlite and laravel 5.4
```
                                                                               
  [Aimeos\MW\DB\Exception]                                                     
  Executing statement "SET NAMES 'utf8'" failed: An exception occurred while   
  executing 'SET NAMES 'utf8'':                                                
  SQLSTATE[HY000]: General error: 1 near "SET": syntax error                   
```

A normal `php artisan migrate` works fine

**Comment by publicarray** [comment]
Using Postgress I get 
```
[Aimeos\MW\DB\Exception]                                                     
  Executing statement "SET SESSION sql_mode='ANSI'" failed: An exception occu  
  rred while executing 'SET SESSION sql_mode='ANSI'':                          
  SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration par  
  ameter "sql_mode"                                                            
```
