### ISSUE TITLE
php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by amine8ghandi8amine** [aimeos/aimeos-laravel#89]
Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size

**Comment by aimeos** [comment]
MySQL default value for the "sort_buffer_size" setting is way to low in the latest version. Add this to your `my.cnf` and restart your MySQL daemon:
```
sort_buffer_size        = 1M
```
