### ISSUE TITLE
Remove default routes after adding override routes

### ISSUE THREAD

**Issue by CyberiaResurrection** [aimeos/aimeos-laravel#9]
How do I get rid of the stock routes after defining my own in a way that will persist between upgrades?

**Comment by aimeos** [comment]
Laravel doesn't support unsetting routes AFAIK but you can reconfigure the original route. In the config/shop.php you can e.g. configure the route prefixes, middleware, etc. in the "routes" section: https://aimeos.org/docs/Laravel/Custom_routes

**Comment by CyberiaResurrection** [comment]
I've done that and set custom routes in app/Http/routes.php - sorry if I wasn't too clear.  How do I get rid of the default ones that shipped with the package?

Eg, I've set things up under shop/, so at moment I have both
shop/list  (custom route I set up)
AND
list  (which is shipped by default)

How do I get rid of plain list?

**Comment by aimeos** [comment]
The routes are registered in the Laravel service provider and you can't remove routes in favor of your own: https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/ShopServiceProvider.php#L55

To achieve what you want you should configure the "/shop" prefix for the existing routes and remove your own ones. Adding a prefix for the routes can be done in the config/shop.php file:
```
'routes' => array(
    'default' => array('prefix' => 'shop'),
    ...
),
```

**Comment by CyberiaResurrection** [comment]
Thanks for your understanding while I was busy making a fool of myself.
