### ISSUE TITLE
Laravel 5.4 ShopServiceProvider error

### ISSUE THREAD

**Issue by noriega9807** [aimeos/aimeos-laravel#90]
There's an error when adding the provider `Aimeos\Shop\ShopServiceProvider::class,`
I installed aimeos on a new laravel project and tried using `"aimeos/aimeos-laravel": "~2016.10"` and `"aimeos/aimeos-laravel": "~2017.01"`.
This is the error:
```php
FatalErrorException in ShopServiceProvider.php line 112: Call to undefined method Illuminate\Foundation\Application::share()
```

**Comment by aimeos** [comment]
Laravel 5.4 is now supported in the latest dev-master branch and the readme has been updated.
You can follow/like us on Github/Twitter/Facebook to get the latest news.
