### ISSUE TITLE
media files are not uploading

### ISSUE THREAD

**Issue by developerpratika** [aimeos/aimeos-laravel#92]
i am using 
`"aimeos/aimeos-laravel": "2017.01.2"`
now every thing is fine only image are not uploading
it displaying error message
`{"error":{"code":-1,"message":"Couldn't delete file \"\""},"status":"failure"} `

**Comment by aimeos** [comment]
The bug has been fixed in the core and a new release has been tagged (2017.01.4). After executing `composer update`, it should work as expected.

Thank you for your help to localize the problem!

**Comment by developerpratika** [comment]
on 
`$ composer update`
Loading composer repositories with package information
Updating dependencies (including require-dev)

> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package aimeos/aimeos-laravel 2017.01.4 exists as aimeos/aimeos-laravel[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.x-dev, 1.1.0, 1.1.1, 1.1.x-dev, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.x-dev, 2016.01.1, 2016.01.2, 2016.01.3, 2016.01.4, 2016.01.5, 2016.01.x-dev, 2016.03.1, 2016.03.2, 2016.03.3, 2016.03.x-dev, 2016.04.1, 2016.04.2, 2016.04.3, 2016.04.x-dev, 2016.07.1, 2016.07.2, 2016.07.3, 2016.07.x-dev, 2016.10.1, 2016.10.2, 2016.10.3, 2016.10.x-dev, 2017.01.1, 2017.01.2, 2017.01.x-dev, dev-master] but these are rejected by your constraint.

**on Composer update it displaying following error**

**Comment by aimeos** [comment]
It's version 2017.01.4 of aimeos-core. You will get it automatically if you use aimeos/aimeos-laravel ~2017.01

**Comment by developerpratika** [comment]
ok now it is working thanks bro
