### ISSUE TITLE
Not able install the application

### ISSUE THREAD

**Issue by vignesh-subash** [aimeos/aimeos-laravel#93]
Cloned the app into the folder, Added the "aimeos/aimeos-laravel": "~2017.01", in composer.json file. when i run composer install and through the following error.
![issue-1](https://cloud.githubusercontent.com/assets/13498070/22507378/58281b88-e8ab-11e6-8dfb-e6f5edb4ad58.PNG)

 i tired all the available options like changing into ~2017.01.1, ~2017.01.2. when i change the  "aimeos/aimeos-laravel": "~2017.01" into "aimeos/aimeos-laravel": "dev-master" and aimeos file into "dev-master" its installing but unable to find 
![issue-2](https://cloud.githubusercontent.com/assets/13498070/22507523/f67c14e2-e8ab-11e6-94c9-b5126fad3560.PNG)

This is how the Composer.json file look like when i clone the file
![issue-3](https://cloud.githubusercontent.com/assets/13498070/22507586/31de29da-e8ac-11e6-99a5-cc03e5af13c8.PNG)

**Comment by aimeos** [comment]
You have to create a Laravel application first:
https://laravel.com/docs/5.4#installing-laravel

**Comment by vignesh-subash** [comment]
Thanks for the help.
