### ISSUE TITLE
Admin Login Issue

### ISSUE THREAD

**Issue by Abhiram3** [aimeos/aimeos-laravel#94]
Tried to login as an admin, but the view is being restricted as shown in the figure. 

![screenshot 318](https://cloud.githubusercontent.com/assets/12019238/22534704/f4fa8dfe-e91b-11e6-91c3-e64ba62b8738.png)

/admin url is getting redirected to /login. And after a successful login with admin credentials the above error is coming and for the normal accounts the home page is being displayed.

**Comment by aimeos** [comment]
Which Laravel and Aimeos version do you use?

**Comment by Abhiram3** [comment]
Laravel 5.2
Aimeos dev-master

**Comment by vignesh-subash** [comment]
Try using `"aimeos/aimeos-laravel": "~2017.01"`. this will work.

**Comment by aimeos** [comment]
The documentation for that combination (2017.x/dev-master and Laravel 5.1/5.2) was wrong, the `$class` argument in the `AuthServiceProvider.php` is required:
```php
public function boot(GateContract $gate)
{
	// Keep the lines before

	$gate->define('admin', function($user, $class, $roles) {
		return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );
	});
}
```
The readme has been updated.

**Comment by Abhiram3** [comment]
It worked! Thanks a lot.
