### ISSUE TITLE
After install no database migration files

### ISSUE THREAD

**Issue by Sytze-Koster** [aimeos/aimeos-laravel#95]
After a composer install I cannot migrate database, There ar no migration files.

**Comment by vignesh-subash** [comment]
what was the error are you getting in because at first i am also unable to migrate database. i changed few codes and now i had migrated the database. Depends upon your error type only we can help you out.

**Comment by Sytze-Koster** [comment]
Ah check, i found it, it is SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size. So i need to upscale the memory

**Comment by vignesh-subash** [comment]
If you fixed the problem then close the issue. :)

**Comment by Sytze-Koster** [comment]
I cannot find a way to increase the memory size or where to find the file

**Comment by aimeos** [comment]
Please have a look here:
https://github.com/aimeos/aimeos-laravel/issues/89

**Comment by vignesh-subash** [comment]
You can always find the file in your control panel. Mysql->config->"my.ini". in this "my.ini" file you have change the  > sort_buffer_size        = 1M

**Comment by Sytze-Koster** [comment]
Yes solution found. Just login to MySql and the type SET GLOBAL sort_buffer_size = 1024 * 1024 * 4;
