### ISSUE TITLE
Error in php artisan vendor:publish

### ISSUE THREAD

**Issue by valluminarias** [aimeos/aimeos-laravel#96]
Hello,

I followed the installation steps correctly, but I after adding the Aimeos provider
```
    return array(

        'providers' => array(

            ...

            Aimeos\Shop\ShopServiceProvider::class,

        ),

    );
```
and executing 
``
php artisan vendor:publish
``
I got an error
```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Foundation\Application::share()
``

**Comment by valluminarias** [comment]
Don't worry. I have figured it out. It seems that your docs is not updated. I just changed the version number to `~2017.01` and it worked. But in your docs is `~2016.10`, which triggered the error in `php artisan vendor:publish`.

**Comment by aimeos** [comment]
Yes, Laravel 5.4 ist only supported by 2017.x. We will update the docs in the Wiki, the readme at Github is correct
