### ISSUE TITLE
Trying the setup on laradock env getting 1038 error, how to fix?

### ISSUE THREAD

**Issue by naretini** [aimeos/aimeos-laravel#99]
Executing:
`php artisan aimeos:setup --option=setup/default/demo:1`

I got a error:

>  SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, cons
>   ider increasing server sort buffer size

Tried to add on my.cnf  for MySQL continer the following line:

`sort_buffer_size=256K
`

but problem persists

Any hint?

Thanks

**Comment by aimeos** [comment]
The value is too low. You need at least `sort_buffer_size=1M`

**Comment by InigoWD** [comment]
Within my config/database.php file, I have set 

`        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
            'options' => array(
                            'sort_buffer_size' => '1M'
                        )
        ],`

However, I am still getting the same error.

**Comment by aimeos** [comment]
Wrong file. Please reread this section carefully: https://github.com/aimeos/aimeos-laravel#important-notice

**Comment by InigoWD** [comment]
Thanks. From that page:

> Add that line to your MySQL my.cnf configuration file and restart the MySQL daemon:

`sort_buffer_size=1M`

Sorry if this is straying beyond the bounds of this issue, but how am I supposed to do this using Homestead? Do I need to SSH into the Vagrant box after it has been created and manually edit that file? If that is the case then:

a) I don't know how to do this using Gitbash and Windows 10. Any advice or pointers greatly appreciated! :)
b) I'm amazed that there isn't a way to specify this in the box creation process. Is this really the only way to do it? And why doesn't the method I used above work (specifying an 'options' array in the config/database.php file) which someone suggested after I raised the issue [here](url=http://stackoverflow.com/questions/42434397/where-to-configure-mysql-settings-such-as-sort-buffer-size-with-laravels-home/42434710?noredirect=1#comment72015448_42434710)

Thank you for your patience, and apologies for the barrage of questions, but there is scant information out there on this subject and I will soon have to consider giving up and not using this package as I have simply wasted far too much time on this now.

**Comment by aimeos** [comment]
Yes, you have to SSH into the Homestead box, change add/change the line in `/etc/my.cnf`, `/etc/mysql/mysql.conf.d/mysqld.cnf` or similar with `sudo nano <filename>` and restart the MySQL daemon (usually by `sudo service mysql-server restart`).

Can't answer your questions in b), so please ask in the laravel forums resp. the Homestead maintainer.

**Comment by InigoWD** [comment]
Awesome. Now working. Many thanks!

In case it helps anyone, the service on my Homestead box is actually just named 'mysql', therefore the correct command was actually

`sudo service mysql restart`
